w3c/csswg-drafts

css-grid/Overview.bs

In the first step, items are locked to a row, so the algorithm should
define how to determine the column-start instead of the row-start.

[css-grid] Fix typo in the grid item placement algorithm

---

css-images-4/Overview.bs

As resolved during the 'cursor' discussions, mandate support for PNG and SVG in <image>.

[css-images-4] Mandate support for PNG and SVG in <image>

---

css-text-decor-4/Overview.bs
css-text-decor-4/Overview.html

Putting this in Level 4, since we agreed L3 wasn't the right place.

[css-text-decor-4] Add trailing-spaces to text-decoration-skip

---

css-page-floats/Overview.bs

After Shinyu's comments ( https://lists.w3.org/Archives/Public/www-style/2015May/0233.html ) and explanations of usage of line-right/left by fantasai at CSSWG F2F.

[css-page-floats] map left/right to line-left/right for inline elements and clarify position of anchor

---

css-align/Overview.bs

Grid items might fill more than one grid cell, hence alignment container must be the grid area they are located in, instead of single grid cell.

Alignment container for justify-self and justify-items In Grid Layout must be the grid area instead of the grid cell.

---

css-containment/Overview.bs

Fix layout containment to work better with Regions and other fragmenting things.
Discussion in this mail thread:
https://lists.w3.org/Archives/Public/www-style/2015Jul/0078.html

[css-containment] Fix layout containment and fragmentainer interaction

---

css-grid/Overview.bs

Two fixes of the example in the `grid-auto-flow` section of the spec:
1. Markup correction — making IDs unique
2. Updating the CSS to match the example rendering (without adding `dense`, the departments block will render in the last row, not in the first, at least by my understanding and the current Blink experimental implementation: http://codepen.io/SelenIT/pen/JdmKMK)

Minor fixes of the example for `grid-auto-flow` section

---

css-ui/Overview.bs

This removes some redundancies in the stylesheet given in "Appendix D. Default style sheet additions for HTML" of CSS Basic User Interface Module Level 3.
(Note to self: Additionally, the `white-space: nowrap` in the first section just ends up getting overridden for `button` and `textarea`, but that will be a matter for a separate issue.)

[css-ui] Avoid unnecessary redundancy in HTML default stylesheet

---

css-ui/Overview.bs

Per https://html.spec.whatwg.org/multipage/rendering.html#hidden-elements :
> ```css
> input[type=hidden i] { display none ! important; }
> ```

[css-ui] Add !important to input[type=hidden] portion of default stylesheet to align with HTML

---

css-ui/Overview.bs

Stop defining a `white-space` on `button` and `textarea`, only to immediately override it with a different value.
See:
* https://github.com/w3c/csswg-drafts/blob/cb0c4d3eb1c8b7095591e20549d89708fbc15e14/css-ui/Overview.bs#L1636-L1640
* https://github.com/w3c/csswg-drafts/blob/cb0c4d3eb1c8b7095591e20549d89708fbc15e14/css-ui/Overview.bs#L1664-L1667

[css-ui] Avoid unnecessary cascading in default HTML stylesheet

---

css-round-display/Overview.bs

Further details at: https://lists.w3.org/Archives/Public/www-style/2015Oct/0163.html

Quite a few misc fixes plus rephrasing 2 paragraphs

---

cssom-view/Overview.bs

* Add "center" to ScrollLogicalPosition.
* Add inline dictionary member to ScrollIntoViewOptions.
Ref. https://www.w3.org/Bugs/Public/show_bug.cgi?id=17152
Ref. https://lists.w3.org/Archives/Public/www-style/2015Dec/0050.html

[cssom-view] Add more positioning control to scrollIntoView

---

css-device-adapt/Overview.bs

Assuming I'm interpreting this correctly, the intention is that at most 1 of the branches in https://drafts.csswg.org/css-device-adapt/#resolve-width will execute. If so, I suggest tweaking the phrasing to clarify this. Thus, naive translations of the algorithm from spec-ese into actual code would result in better code (`if...else if` rather than `if...if`; there's no need to check for the 2nd case if the 1st case was true).

[css-device-adapt] Trivial clarification of "Resolve width value" algo

---

selectors/Overview.bs

https://lists.w3.org/Archives/Public/www-style/2016Jan/0166.html shows that it’s easy to miss.
How does this look, @tabatkins?

Point out case-insensitivity of i in [foo=bar i]

---

cssom-view/Overview.bs

I see no obvious reason not to link these.

[cssom-view] Link mentions of "beginning edges" term

---

css-grid/Overview.bs

The `grid-template` shorthand property has been removed from the spec, but two references to it remained. Also, this change was not reflected in the 'Changes' section. Shouldn't we fix this?

Removal of the rests of 'grid-template' references

---

css-scroll-snap/Overview.bs

@fantasai I think this was just overlooked in the rebranding, right?

[css-scroll-snap] 'snap window' -> 'snapport'

---

css-flexbox/Overview.bs

'width' is not an animation type and quoting width like this links to the width property.

[css-flexbox] Fix animation type of 'flex-basis'

---

css-sizing/Overview.bs

This addresses the multicol part of w3c/csswg-drafts#163.

Take column gaps into account for multicol intrinsic sizing

---

css-cascade-3/Overview.bs
css-cascade/Overview.bs

Simple typo fix. Added the missing verb "is"

[css-cascade] typo. Fixes #154

---

cssom-view/Overview.bs

My attempt to fix https://github.com/w3c/csswg-drafts/issues/159.
@tabatkins , could you review this?
> Return the nearest ancestor <a>unclosed node</a> element of the element
"unclosed node element of the element" can be acceptable?

[cssom-view] Fix #159. Do not leak a closed node via offsetParent

---

css-position/Overview.bs
css-position/Overview.html

Correct some spelling errors/typos:
"coresponding" -> "corresponding"
"marins" -> "margins"
"containement" -> "containment"

[css-position] typo/spelling corrections

---

mediaqueries/Overview.bs

This fixes a mistake introduced in https://github.com/w3c/csswg-drafts/commit/2f37630466463a8653832584ad3c80fd6f2e01be
Not only can you not have `or` and `and` at the same level, but `not` is handled the same as well, and also needs extra parentheses.

[mediaqueries-4] Can't have 'not', 'and' and 'or' at the same level

---

css-text/Overview.bs

This is my first PR, so please review carefully before merging!
Sebastian

[css-text-3] Bikeshed improvements related to property values

---

mediaqueries/Overview.bs

Corresponding change in css-color:
436e62df84e04f42c546b49b8ca00d94889e9a26
WG decision:
https://lists.w3.org/Archives/Public/www-style/2016Jun/0021.html
---
Ref. https://twitter.com/svgeesus/status/749901587720658944 @svgeesus

[mediaqueries] Change p3 to dci-p3 per WG decision

---

css-font-loading/Overview.bs

[css-font-loading] Fix typo in WebIDL

---

css-color/Overview.bs
css-color/conversions.js
mediaqueries/Overview.bs

Ref. https://github.com/w3c/csswg-drafts/commit/b7e9438393033fad1e390f41a4558cb735b3507c#commitcomment-18147194
---
My text editor also trimmed trailing whitespace.
@grorg @svgeesus @tabatkins

[css-color][mediaqueries] Editorial: use space in "Rec. 2020"

---

css-display/Overview.bs

This threw me off when investigating [this Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=25291) as search wasn't finding a definition for "inline-list-item".

Fix typo in definition of inline-list-item

---

css-device-adapt/Overview.bs

Addresses #326 
Intro reworded to discuss more of the "why" -- why current default behavior exists and why authors would want to opt-out.  Added 2 scenarios -- one for fully responsive using <meta> viewport and one partially responsive using @viewport and @media.  The examples use the current syntax for now, if/when syntax changes are made they can be updated at that time.

[css-device-adapt] Adds motivating scenarios and rewording of intro

---

css-animations/Overview.bs

Right now the CSS Animations spec has a straggling bullet in its "At Risk" section -- it says:
> The following features are at-risk, and may be dropped during the CR period:
> * the pseudoElement property of the AnimationEvent interface
> * 
>
> “At-risk” is a W3C Process term-of-art, [...]
From local testing with Bikeshed, I've confirmed that the stray bullet is caused by the blank line after "At Risk". If I delete that blank line (as in this pull request), the stray bullet goes away.

Drop blank line, to fix straggling "At Risk" bullet

---

cssom-view/Overview.bs

[The previous attempt ](https://github.com/w3c/csswg-drafts/pull/169)to update offsetParent to fix #159 was incomplete:
when the real offsetParent in the closed shadow tree has
'position:fixed', offsetParent should return null, instead
of continue searching for unclosed ancestor.

[cssom-view] Fix #159 update offsetParent spec for Shadow DOM

---

css-fonts-4/Overview.bs

Currently the text below https://drafts.csswg.org/static/css-fonts-4/#document-conventions is set to π% which is interesting, but particularly hard to read

[css-fonts-4] Fix small font size

---

css-grid/Overview.bs

The grid shorthand syntax was changed in commit 5fde09cd,
but the example was not updated by that time.

[css-grid] Update grid shorthand example to the new syntax

---

css-align/Overview.bs

This fixes a minor spelling typo that was introduced in f5d582671f7fd3ff935e45c0675aca9f52e23483

Fix typo: s/interpretead/interpreted/

---

cssom/Overview.bs

[cssom] Make MediaList.item return serialization.

---

cssom/Overview.bs

A media query list can contain no media query at all, so "the list of one or more media queries" is incorrect.

Fix wording in parsing a media query list

---

css-values/Overview.bs

Make the spec match reality, as most (all?) high-dpi screen devices
currently also anchor on pixel unit, and not any physical unit.
Closes https://github.com/w3c/csswg-drafts/issues/708

Change anchor for high-dpi devices to pixel

---

css-device-adapt/Overview.bs

Ports the note warning/note recently added to
https://w3c.github.io/html/document-metadata.html#the-meta-element about
not suppressing/limiting user's ability to zoom, and the note that UAs
can ignore these directives anyway.
Closes https://github.com/w3c/csswg-drafts/issues/704

Port HTML note on zoom/accessibility

---

css-position/Overview.bs

This fixes some minor spelling mistakes, duplicated phrases and singular/plural grammatical nitpicks in the css-position spec. It also removes a dummy "example" section that appears to have been left over from the bikeshed template.
As a side comment, I found some parts of the spec difficult to read/comprehend properly. I have some ideas of improvements that can be made, but given that css-position is a new draft spec, I wasn't sure how far through the writing process it was.
What's the etiquette here? Create separate pull requests with suggested changes, or just raise an issue or two? (Or leave it be until the spec is further advanced?)

[css-position] Fix some minor typos and grammatical issues

---

mediaqueries/Overview.bs

Related to the discussion in https://github.com/w3c/csswg-drafts/issues/690 this is an initial expansion/change to the current advice given for `pointer`/`hover`/`any-pointer`/`any-hover`.
[edit: copying the relevant description from the individual commits here, for completeness]
* Change "rare" to "all available": "rare" is a loaded term, unnecessarily implying (without much foundation) the likelihood/frequency that a user may use inputs deemed "not primary" by the OS/UA. In addition, as `any-*` also include the pointer that is deemed primary, the "rare" moniker is even more inappropriate, as by definition the "primary" is not "rare".
* Reword the note about pointer/hover vs any-*: Change the emphasis of the note, away from making the `any-*` features sound like a nice-to-have, and more …

[mediaqueries-4] expand/change emphasis of advice for use of pointer/hover/any-pointer/any-hover 

---

css-logical-props/Overview.bs

(fixes #691)
r? @fantasai @heycam @kojiishi

Remove text-orientation references from css-logical-props 

---

mediaqueries/Overview.bs

- expands the table https://drafts.csswg.org/mediaqueries/#mf-interaction to include an example of `pointer:none`, swaps "stylus-based screen" to "stylus digitizer" (preferred/common term), adds distinction between basic and advanced stylus (the latter does support hover)
- adds an introductory paragraph in the main "Interaction Media Features" section that introduces the concept of primary/all input mechanisms
- based on the conversation in https://github.com/w3c/csswg-drafts/issues/690#issuecomment-260941888, add a (non normative) note hinting at ways in which UAs can potentially determine what is and isn't primary (based on @frivoal's explanation to me in that thread about what the expectation for UAs seems to be...this makes it a bit more explicit)
both these changes should be …

[mediaqueries-4] add example of 'pointer: none' to table, add note about how UA could determine "primary" input

---

css-fonts-4/Overview.bs

I was randomly looking at the spec source of CSS fonts level 4 and found this out:
- Loading Typescript JavaScript was failing because it wasn't from a secure source
- Boilerplate styles aren't needed to display https://drafts.csswg.org/css-fonts-4/ properly
- The script adding a "touch" class to the document isn't needed

[css-fonts-4] Remove redundant boilerplate styles and scripts

---

css-align/Overview.bs

css-align section 4.2 currently [says](https://drafts.csswg.org/css-align/#valdef-justify-content-baseline):
> `baseline`
> [...] The fallback alignment for `baseline` is `start`.
> 
> `last-baseline`
> [... ]The fallback alignment for `baseline` is `end`.
Those "fallback alignment" sentences are contradictory (they say opposite things about the fallback alignment for `baseline`).
The latter one clearly means to be talking about `last-baseline`, not `baseline`. Here's a pull request to fix that typo.

[css-align] fix typo: s/baseline/last-baseline/

---

css-transforms-2/Overview.bs

We link to the definition of transformable-element from css-transforms-1

[css-transforms-2] Transform properties apply to transformable elements

---

css-flexbox/Overview.bs

Fixes #671. In the [old version](https://hg.csswg.org/drafts/rev/25641c92d33f) this case was specified, but dropped while changing from a table to a paragraph.
r? @dbaron

[css-flexbox] Clarify implied minimum size definition

---

selectors/Overview.bs

Adds support for `:focusring`, related discussion here: https://lists.w3.org/Archives/Public/www-style/2016Mar/0250.html
`:focusring` only matches an element if the element is currently focused and a focus ring or other indicator should be drawn for that element. This is extremely useful for accessibility.
As @tabatkins explained on the mailing list:
> The main benefit of such a thing is that, today, if the default UA focus ring style does not work well with your site's theme, you're kinda screwed. You can manually write a :focus rule, but you can't predict when an element would have a focus ring drawn; you'll unfortunately start drawing focus rings when the user mouse-clicks a button. Using :focus-ring instead does the right thing automatically, triggering your styles only when the UA …

Add :focusring selector

---

css-transforms-2/Overview.bs

The individual transform properties create a containing block, just
like the transform property does.
fixes #582

[css-transforms-2] Transform properties create containing block

---

css-fonts-4/Overview.bs

Just fixing a typo I noticed when reading this section of the spec - capitalizing a word at the start of a sentence.
(The next sentence starts with the same term & it's capitalized there, so this isn't an always-lowercase-term or anything like that.)

Fix typo (capitalization at start of sentence)

---

css-text/Overview.bs

It doesn't seem to me there is any reason we need to distinguish between "line feed" and the other two types of "segment break", so I suppose this is probably a typo, which could be misleading.

Change "line feed" to "segment break" in 4.1.2

---

css-values/Overview.bs

Resolution in https://lists.w3.org/Archives/Public/www-style/2016Aug/0009.html

[css-values] Add the ''lh'' and ''rlh'' units

---

cssom/Overview.bs

For the following declarations:
```css
div {
background: green;
background-image: none !important;
}
```
the current spec should return something for `getPropertyValue('background')`, but all browsers (even Servo) agree on that this should return nothing because the importance of its longhands differ.
This PR fixes this issue.
It can alternatively be fixed in "serialize a CSS value" algorithm. Given that the other callsite of this algorithm with a list (which is "serialize a CSS declaration block") already handles important flag itself, I guess it is better being put in `getPropertyValue` rather than "serialize a CSS value".

[cssom] Don't serialize shorthand if importance differs

---

mediaqueries/Overview.bs

Adds more explicit clarification about the possibly non-intuitive way in
which `any-pointer:none`/`any-hover:none` work.
Splits out the initial mention (that "ALL pointing devices need to
match") into its own line, and provides two sets of notes/examples that
clarify scenarios where this may not be completely obvious.
Additionally, this explicitly highlights the situation that currently
cannot be detected: having more than one pointing device where at least
one is non-hover-capable (as touched on in
https://github.com/w3c/csswg-drafts/issues/737#issuecomment-269348418 )

[mediaqueries-4] More explicit clarification for when any-* 'none' evaluates to true

---

css-transforms-2/Overview.bs

When 'translate', 'rotate' or 'scale' are animating or transitioning, and
the from value or to value (but not both) is none, the value none is
replaced by the equivalent identity value (0px for translate, 0deg for
rotate, 1 for scale).
resolves #968

[css-transforms-2] Individual transform properties animate with none

---

css-color/Overview.bs

This is a proposal to resolve the lack of a generally usable definition for how colors, and in particular `currentcolor` are turned into computed values, used values, inherited...
This should help address #741, #480, and #867 (and maybe other issues I am not aware of).
If we agree on the concept, we should probably try to backport the relevant subset of this to css-colors-3. I can do this as an update to this PR or as a separate one, as the WG / editors prefer.
I have for now left undefined (and marked as an issue) the computed values of the functions that are not yet implemented. We should have that discussion as well, but it need not delay the introduction of the general concept and anchoring terminology.
For the functions that are implemented, the definition I provided is based on my …

Resolving colors

---

css-grid/Overview.bs
css-grid/images/gutters-gaps.svg

Example for grid-gap section demonstrating difference between grid-gap and visible gutter.
Re: Issue 452 https://github.com/w3c/csswg-drafts/issues/452

Added example to grid-gap section

---

mediaqueries/Overview.bs

Closes https://github.com/w3c/csswg-drafts/issues/984

[mediaqueries-4] Add note about min-/max- shortcoming vs proper range context

---

css-color/Overview.bs

Per [discussion in the mailing list](https://lists.w3.org/Archives/Public/www-style/2016Mar/0431.html).

[css-color] Add note for relationship between color property and color glyphs

---

cssom-view/Overview.bs

[cssom-view] Return real values for colorDepth and pixelDepth (closes #993)

---

css-position/Overview.bs

Before this change, https://drafts.csswg.org/css-position-3/#def-cb shows a stray list item (just an empty "3." in an ordered list).  This comes from two back-to-back `<li>` tags.  My change just removes one of these redundant `<li>` tags.

Delete stray <li> from containing block definition

---

mediaqueries/Overview.bs

Closes https://github.com/w3c/csswg-drafts/issues/967

[mediaqueries-4] make explicit that `pointer`, `hover`, `any-pointer`, `any-hover` relate only to pointing devices

---

cssom-view/Overview.bs
cssom/Overview.bs

See https://github.com/whatwg/html/pull/2476
Also change the behavior for left=foo to act as if left=0 to align
with the behavior of at least WebKit and Chromium.

[cssom-view] Move tokenizing of window.open's features arg to HTML

---

cssom-view/Overview.bs

See https://github.com/whatwg/html/pull/2476#issuecomment-290339738
---
This is on top of https://github.com/w3c/csswg-drafts/pull/1138

[cssom-view] Make window.open's features use Web-exposed screen area 

---

css-values/Overview.bs

Another option would be to allow any calc-value again, and let the prose that follows disambiguate like we do for the * products.

Fix #1241 by adding a number-calc microgrammar

---

css-contain/Overview.bs
css-display/Overview.bs
css-multicol/Overview.bs

Moves a terminology definition from css-contain to css-display so that it can be reused more broadly, and reuse it in multicol to solve #1071

[css-multicol][css-display][css-contain] Becomes a formatting context

---

css-animations-2/Overview.bs
css-animations/Overview.bs
css-color/Overview.bs
css-conditional/Overview.bs
css-counter-styles/Overview.bs
css-font-loading/Overview.bs
css-fonts/Fonts.html
css-fonts/Fonts.src.html
css-fonts/Overview-wip.bs
css-module-bikeshed/Overview.bs
css-pseudo/Overview.bs
css-regions/Overview.bs
css-regions/region-styling.txt
css-transitions-2/Overview.bs
css-transitions/Overview.bs
cssom-view/Overview.bs
cssom/Overview.bs
mediaqueries/Overview.bs

`CSSOMString` is an IDL `typedef` of either `USVString` or `DOMString`, chosen by implementations.
CSSWG resolution: https://github.com/w3c/csswg-drafts/issues/1217#issuecomment-295053842. Fixes #1217.
Each replaced occurrence is one of:
* CSS syntax
* A name (for example a property name) that also occurs in CSS syntax
* `Stylesheet::type`, which is always `text/css`.
* <s>`Stylesheet::title`, which is set from the eponymous HTML content attribute of [`<style>`](https://html.spec.whatwg.org/multipage/semantics.html#attr-style-title) and [`<link>`](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-title) elements.</s>

[cssom][all] Add CSSOMString and replace DOMString usage with it

---

mediaqueries/Overview.bs

Minor copy change to clarify what `hover:none` refers to. Uses the
"primary pointing device" wording now used consistently in the
Interaction Media Features section

[mediaqueries-4] Clarify hover:none refers to primary pointing device

---

css-counter-styles/Overview.bs

… in all contexts, not just `@counter-style` rules.
Fix #1295.

[css-counter-styles] Exclude 'none' from <counter-style-name>

---

css-color/Overview.bs

To disambiguate the '@color-profile/src' descriptor.

[css-color] Bikeshed fix

---

css-content/Overview.bs

Fix and simplify syntaxes, see #663 for details

[css-content] Fix syntaxes according to CSS Values and Units grammar

---

css-display/Overview.bs

[Flex layout](https://drafts.csswg.org/css-display-3/#valdef-display-flex) is missing from the title of its section:
> [§ 2.2. Inner Display Layout Models: the flow, flow-root, table, grid, and ruby keywords](https://drafts.csswg.org/css-display-3/#inner-model)
It should be
> [§ 2.2. Inner Display Layout Models: the flow, flow-root, table, **flex**, grid, and ruby keywords](https://drafts.csswg.org/css-display-3/#inner-model)

[css-display] Missing 'flex' in section title

---

cssom/Overview.bs

https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-_dashed_attribute
```WebIDL
partial interface CSSStyleDeclaration {
[CEReactions, TreatNullAs=EmptyString] attribute CSSOMString _dashed_attribute;
};
```
This IDL snippet does not have `extract` class attached and thus collected on IDL index, whereas other _camel_cased_attribute and _webkit_cased_attribute examples are not collected.

[cssom-1] Add missing extract class on dashed_attribute example

---

css-conditional/Overview.bs
cssom/Overview.bs

Fixes #851.
---
cc @Manishearth

[cssom][css-conditional] Merge IDL definitions for CSSMediaRule

---

css-color/Overview.bs

In https://drafts.csswg.org/css-color/#rgb-functions:
> Also for legacy reasons, an rgba() function also exists, with an identical grammar and behavior to rgb().

[css-color] Link to rgb() instead of its *a() alias

---

css-namespaces/Overview.bs

It was removed in https://github.com/w3c/csswg-drafts/commit/23f06fe37e7185bd44e8408cd533b2f5110ad586, presumably accidentally.
It includes a normative statements that was missing for the ED:
> In CSS Namespaces a namespace name consisting of the empty string is taken to represent the null namespace or lack of a namespace.

[css-namespaces] Restore Terminology section

---

cssom/Overview.bs

This PR adds serialization steps of CSSMediaRule and CSSFontFaceRule. I reverse-engineered the grammars and came up with these steps.
Serialization of these rules are also implemented with this approach in servo: https://github.com/servo/servo/pull/14238
cc @Manishearth

[cssom] Specify serialization of CSSMediaRule and CSSFontFaceRule

---

css-display/Overview.bs

CSS Display defines "replaced element" in the same spec, so there is no need to link CSS2.

[css-display] Link "replaced element" to CSS Display instead of CSS2

---

css-align/Overview.bs

Currently, Firefox wraps the word "Authoritarianism" in the Example 1, making it hard to understand the difference between unsafe and safe centering. Setting `white-space:nowrap` to it makes it more clear.

[css-align] Fixes Example 1 behavior in Firefox

---

css-transforms/Overview.bs

* Update /TR link
* Fix CSS 2.1 reference
* More autolinks

[css-transforms] Editorial fixes

---

cssom-view/Overview.bs

Fixes #1538.
---
I think this is already tested by http://w3c-test.org/cssom-view/scrollingElement.html

[cssom-view] Check computed value for overflow-x/y in potentially scrollable

---

css2/visudet.src

In section CSS2 10.3.2, there are a series of paragraphs that start out "If 'height' and 'width' ..." with both properties linkified.  One of them neglects to linkify 'height'. This pull request fixes that.

[css2] Linkify a mention of the 'height' property

---

css-display/Overview.bs

The 'Changes' section still stated that `display:contents` on replaced elements etc. computed to `inline`, although the spec has been updated with more detailed rules for such elements with `display:none` as a general rule. This PR aims to fix it.

[css-display] Fix the 'Changes' section

---

css-fonts-4/Overview.bs

@litherum fixes made prior to fpwd, for https://github.com/w3c/csswg-drafts/issues/1585

some bikeshed link disambiguation and validity fixes; add TR link

---

css-box/Overview.html

There's en error in example 12.
`margin-bottom: 2em 0 1em 0`

[css-box] fix ex.12 'margin-bottom' -> 'margin'

---

css-align/Overview.bs

[css-align] Fix reference to unexisting justify-items: auto.

---

css-flexbox/Overview.bs
css-grid/Overview.bs

Removes the [now redundant](https://github.com/w3c/csswg-drafts/commit/52ebb10453232307562a4e2c69e82565da9fd39b) exclusion of `column-*` properties from applying to flex and grid containers.
Sebastian

[css-flexbox][css-grid] Removed redundant exclusion of column-* properties from applying to flex and grid containers

---

css-backgrounds/Overview.html
css-backgrounds/Overview.src.html

There is no reasons for `border-image-width` to differ from other `border-image-*` properties. I suppose "internal" was missed by accident when [splitting `border-image` into multiple properties](https://github.com/w3c/csswg-drafts/commit/eb4c769e78568e37b8fad92f99d6ebd49f484371)

[css-background] Add missed "internal" into "applies to" for <'border-image-width'>

---

css-values/Overview.bs

Adding 'cap' unit to the 'Font-relative lengths' section heading, to solve #1126

Adding 'cap' unit to the section heading

---

css-transitions/Overview.bs

Clarify that the after-change style does not include updates to CSS Animations

---

selectors/Overview.bs

Scoped style was removed from WHATWG HTML. See whatwg/html#552.

[selectors] Remove scoped <style> element

---

css-text/Overview.bs

Line break break all

---

mediaqueries-5/Overview.bs

Discussed at recent F2F meeting, and in CSS Issue #443

MQ5 User Prefs: prefers-reduced-transparency

---

css-transforms-2/Overview.bs

The shorthand defined by CSS Motion Path is named
'offset', not 'motion'.
https://drafts.fxtf.org/motion-1/#propdef-offset
The 'Current Transformation Matrix' no longer refers
to the obsolete name 'motion'.

[css-transforms-2] Refer to offset, not motion

---

css-align/Overview.bs

We refer to the longhands for the initial value and computed
value of 'gap'.
The longhands row-gap and column-gap apply to 'multi-column elements,
flex containers, grid containers', and the gap shorthand now applies
to these same elements, instead of only 'grid containers'.
resolves #1784

[css-align] gap now consistent with longhands

---

cssom-view/Overview.bs

This aligns with the behavior of Gecko/WebKit/Chromium; EdgeHTML
treats explicit undefined like false.
Fixes #1367.
Tests: https://github.com/w3c/web-platform-tests/issues/6253

[cssom-view] Change scrollIntoView(undefined) to be like true

---

css-grid/Overview.bs

'grid-template-columns' and 'grid-template-rows', are animatable,
as simple lists of length, percentage, or calc.
https://drafts.csswg.org/css-grid/#propdef-grid-template-columns
Thus the shorthands 'grid' and 'grid-template'
https://drafts.csswg.org/css-grid/#propdef-grid
https://drafts.csswg.org/css-grid/#propdef-grid-template
can also animate.
resolves #1794

[css-grid] grid and grid-template are animatable

---

css-animations/Overview.bs
css-conditional/Overview.bs
css-font-loading/Overview.bs
css-regions/Overview.bs
cssom-view/Overview.bs
cssom/Overview.bs
mediaqueries-5/Overview.bs

This is necessary for https://github.com/heycam/webidl/issues/365.
---
cc @annevk @tobie

[css-animations][css-conditional][css-font-loading][cssom-view][cssom][mediaqueries] IDL: Use [Exposed] consistently

---

css-flexbox/Overview.bs

This fixes a typo in @fantasai's commit https://github.com/w3c/csswg-drafts/commit/1ddd3039929a92d20a63dd3ae5cbc6996b7fa702
(Without this typo-fix, a bunch of this paragraph ends up being incorrectly italicized.)

Fix typo (<var> wanted to be </var)

---

css-syntax/Overview.bs

@tabatkins I think this falls out of the change made earlier — there are no paths to "consume an escaped code point" which are not preceded by the check, so EOF is not possible at this juncture now.

Related to #1821, the change to "check if two code points are a valid escape" makes part of "consume an escaped code point" unreachable.

---

css-break/Overview.bs

According to tabatkins/bikeshed#1042, `<i>` autolinks will be removed in the future.

[css-break] Remove <i> autolinks

---

mediaqueries-5/Overview.bs
mediaqueries/Overview.bs

* Javascript -> JavaScript
* Remove superfulous "]"

[mediaqueries] Editorial fixes

---

css-values-3/Overview.bs
css-values/Overview.bs

"The unit 'Q' is very common in Japanese typesetting"
https://lists.w3.org/Archives/Public/www-style/2013Nov/0302.html
http://tosche.net/2013/10/font-size-in-the-metric-system_e.html

[css-values] Use upper case for Q unit

---

css-pseudo-4/Overview.bs
css-text-decor-3/Overview.bs
css-text-decor-4/Overview.bs

This pull requests is an attempt to solve https://github.com/w3c/csswg-drafts/issues/1828, based on what I think we were converging towards in during the [conf call](https://github.com/w3c/csswg-drafts/issues/1828#issuecomment-334319887).
A possible variant of this would be to add the two new values to `text-decoration-style` instead of `text-decoration-line`. Arguably, if UAs wanted to allow it, `text-decoration: overline spelling-error` is slightly more likely to be a meaningful combination than `text-decoration: solid spelling-error`.
However, neither are motivated by real use cases, and the syntax I chose in this PR means the feature can be activated with just `text-decoration: spelling-error` or `text-decoration-line: spelling-error`, rather than having to specify `text-decoration: …

Spelling & grammar markers

---

mediaqueries-4/Overview.bs

A follow-up to https://github.com/w3c/csswg-drafts/pull/1083 that further expands the example to also include use of high-precision values (while we wait for browsers to support range context queries)

[mediaqueries-4] Expand example for min-/max- shortcoming vs proper range context

---

css-values-3/Overview.bs
css-values-4/Overview.bs

Add note that CSS values such as 1Q and 1Hz serialize as lower case.
Note requested in teleconference
https://lists.w3.org/Archives/Public/www-style/2017Oct/0025.html

[css-values] Values serialize as lower case

---

css-break-3/Overview.bs

[css-break-3] Clarify the definition of widows and orphans

---

css-overflow-3/Overview.bs

Shepherd uses L4 for the unleveled URL.

[css-overflow-3] Fix ED link

---

selectors-4/Overview.bs

[selectors-4] Rename :focus-ring to :focus-visible

---

css-fonts-3/Fonts.html
css-fonts-3/Fonts.src.html
css-fonts-3/Overview-wip.bs
css-fonts-3/Overview.html
css-fonts-4/Overview.bs

Replaced "users agents" with "user agents"

[css-fonts] user agents, not users agents

---

css-color-4/Overview.bs

`#787` (`#778877`) is represented in HWB as `hwb(120deg, 47%, 47%)` and next transformations not right for this color too.

[css-color-4] Fix typo

---

selectors-4/Overview.bs

CSS Selectors 4 previously allowed >> as an alternative
for whitespace. This has been removed.
resolves #641

[selectors] Single form for descendant combinator

---

css-values-4/Overview.bs

As far as I can tell, this bit of text is redundant with the (now improved, thanks to #2115) the last paragraph of https://drafts.csswg.org/css-values-4/#font-relative-lengths
Sending this as a PR rather than making a direct fix, in case I missed something and there's actually a good reason to be explicit here.

[css-values-4] Remove redundant text

---

css-color-4/Overview.bs

Uses the `color-mod()` function name consistently in order to avoid confusion with the `color()` function.
Resolves #868

[css-color-4] consistently name color-mod()

---

css-color-4/Overview.bs

Correct the `blend()` adjuster calculation so that a base color does not change when a specified color is 0% blended in.
This will consequently correct `tint()` and `shade()` adjusters, as they rely on the behavior of `blend()`.
Resolves #2195

[css-color-4] correct blend() adjuster calculation

---

css-tables-3/Overview.bs

[css-tables-3] Editorial fixes

---

css-color-4/Overview.bs

This corrects an example of `gray()` in the spec that is using a percentage (`50%`), while the syntax for `gray()` should only use a number (`50`).
https://github.com/w3c/csswg-drafts/pull/2231/files
The correct syntax is:
```
gray() = gray( <number>  [ / <alpha-value> ]? )
```
This is clarified in the description of its arguments:
> The first argument specifies the shade of gray, equal to the **CIE Lightness**...
And it is further clarified directly below the description:
> In other words, `gray(a / b)` is equal to `lab(a 0 0 / b)`.

[css-color-4] correct gray() example

---

css-grid-1/Overview.bs

Before: 
>...UAs should attempt to minimize *distortation* of the grid container with respect to unfragmented flow.
After 
>...UAs should attempt to minimize *distortion* of the grid container with respect to unfragmented flow.

[css-grid-1] Fix Typo (Distortation)

---

selectors-4/Overview.bs

It's true that `:nth-child(n)`/`:nth-last-child(n)` have been added in Level 3, but `of S` syntax is Level 4 addition. I believe they should be marked as Level 3/4, like the `:not()` selector (also introduced in Level 3, but extended in Level 4 with the ability to contain selector lists).

[selectors-4] :nth-*-child(n of S) selectors should be Level 3/4

---

css-fonts-3/Fonts.html
css-fonts-3/Fonts.src.html
css-fonts-3/Overview.html
css-fonts-4/Overview.bs

After #1127, `<number>` was mistakenly changed to `<integer>` in Fonts 4. Revert this commit. Also change the links for `<integer>` to point to Values 3, as CSS 2.1 does not define the `<integer>` type.

[css-fonts] Fix references to <integer> and <number> types

---

css-values-3/Overview.bs
css-values-4/Overview.bs

The definition of attr() used CSS 2.1 tokens (e.g. NUMBER) to describe parsing instead of CSS Syntax tokens (e.g. <number-token>). Update the text to use the tokens described in CSS Syntax.

Use CSS Syntax tokens for attr()

---

cssom-1/Overview.bs

This mostly follows how [`DOMTokenList`](https://dom.spec.whatwg.org/#interface-domtokenlist) works in the DOM spec, which has a similar situation that having a live object reflecting an attribute.
This should fix #1559.

[cssom-1] Ensure inline style and corresponding declaration block ates each other properly

---

cssom-1/Overview.bs

This change removes all the "terminate these steps" and "terminate this algorithm" from this spec. They are either removed due to redundancy (already following a "return" or "throw") or replaced with "return".

[cssom-1] Remove or replace "terminate ..."

---

css-contain-1/Overview.bs
css-regions-1/Overview.bs

As discussed in https://github.com/w3c/csswg-drafts/issues/1872#issuecomment-365686723, this PR moves the effect of containment on regions from the containment spec to the regions spec.
@astearns I vouch for the css-contain part of this patch. Can you review (and hopefully approve, then merge) the css-regions part?

Move effects of containment on regions from [css-contain-1] to [css-regions-1]

---

css-align-3/Overview.bs

Before this fix, the spec text says "...provide this functionality for multi-column flex, and grid layout" (with links to these three distinct layout specs).  Clearly there's a comma missing between "multi-column" and "flex".
Link to this spec section, for reference: https://drafts.csswg.org/css-align/#gaps

Add missing comma between "multi-column" & "flex"

---

css2/tables.html

"A is B" can mean both "A = B" and "B = A". It usually means the former; but in this case it's the latter, and that's confusing.

Explicitly specify what gets set to what with MCW

---

css-counter-styles-3/Overview.bs
css-device-adapt-1/Overview.bs
css-fonts-4/Overview.bs

CSSFontFaceRule, CSSViewportRule, CSSCounterStyleRule are now
explicitly exposed to Window.
The other CSSRule interfaces defined in csswg-drafts are
already exposed to Window.
resolves #2342

CSSFontFaceRule etc. exposed to Window

---

css-animations-2/Overview.bs
css-pseudo-4/Overview.bs
css-regions-1/Overview.bs
css-transitions-1/Overview.bs

From #2342:
WebIDL now defines that interfaces include the Exposed extended attribute even in the case where it is only exposed to Window.
The following interfaces previously omitted the Exposed extended attribute:
NamedFlow, NamedFlowMap,
CSSPseudoElement, CSSPseudoElementList,
CSSKeyframeEffectReadOnly,
TransitionEvent

Add [Exposed=Window] to interfaces

---

selectors-4/Overview.bs

The DOM methods are querySelector and querySelectorAll,
not query and queryAll.
resolves #2360

[selectors] querySelectorAll not queryAll

---

css-lists-3/Overview.bs

The functions `counter()` and `counters()` were badly specified, using
`<ident>` for the counter names, even though `counter-increment` and friends
will only accept `<custom-ident>` for those names.

Use `<custom-ident>` consistently for counter names

---

css-display-3/Overview.bs

Applet is no longer part of the HTML spec.

[css-display] Remove references to <applet>.

---

css-multicol-1/Overview.bs

The grammar rules are now
- column-rule-style: < line-style >
- column-rule-width: < line-width >
instead of
- column-rule-style: <‘border-style’>
- column-rule-width: <‘border-width’>
- border-style: < line-style >{1,4}
- border-width: < line-width >{1,4}
resolves #2379

[css-multicol] Refer to line-style,line-width

---

selectors-4/Overview.bs

See https://github.com/w3c/csswg-drafts/issues/2346.
Note: I don't know how to add contributor information as described at https://github.com/w3c/csswg-drafts/blob/master/CONTRIBUTING.md.

Fix Selectors, Level 4 typos.

---

css-fonts-4/Overview.bs

See https://github.com/w3c/i18n-drafts/issues/125 for an example.

[css-fonts-4] Larger font size can also have a11y implications

---

css-text-decor-4/Overview.bs

This PR updates the L4 spec, along with some formatting changes to the section (in separate commits, for the ease of review).

[css-text-decor-4] Skip punctuation for emphasis marks

---

cssom-1/Overview.bs
cssom-view-1/Overview.bs

WebIDL recently introduced dedicated syntax for mixins [1]. This
replaces the existing [NoInterfaceObject] and "implements" syntax with
"interface mixin" and "includes" in the appropriate places.
This fixes #1931, #1932 issues.
Test: https://github.com/w3c/web-platform-tests/pull/8772
[1] https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920

Use Web IDL's new-ish interface mixins concept

---

web-animations-1/Overview.bs

This fixes #2065 and #2068. It also fixes #2055.
Summary of changes:
* Replaced `AnimationEffectReadOnly` with `AnimationEffect`.
* Replaced the timing member of `AnimationEffectReadOnly` with the `getTiming()` and `updateTiming()` methods on `AnimationEffect`.
* Removed the `AnimationEffectTimingReadOnly` and `AnimationEffectTiming` interfaces.
* Renamed the `AnimationEffectTimingProperties` dictionary to `EffectTiming`.
* Renamed the `ComputedTimingProperties` dictionary to `ComputedEffectTiming`.
* Introduced the `OptionalEffectTiming` dictionary for use with the `updateTiming()` method.
* Removed `KeyframeEffectReadOnly`, leaving only `KeyframeEffect`.
The relevant parts of the new IDL look something like:
```webidl
[Exposed=Window]
interface AnimationEffect {
EffectTiming …
```

[web-animations-1] Replace *ReadOnly interfaces and timing objects

---

css-font-loading-3/Overview.bs

Missing comma-separate in Extended Attribute list of FontFaceSource

[css-font-loading] Fix invalid WebIDL syntax

---

css-transforms-2/Overview.bs

* Change the title to match spec shortname and the title of L1;
* Change the "Level" metadata to 2.

[css-transforms-2] Typo fix

---

mediaqueries-4/Overview.bs

Based on https://www.smashingmagazine.com/2018/02/media-queries-responsive-design-2018/, and in particular based on the article's note
> "I’d suggest that you should take great care in using these, as making a user switch from their primary pointing device is likely to result in a poor user experience."
I think the fact that relying purely on `pointer` and `hover` can also be just as bad has been missed out by having the note where it is. Moving it right to the start (and strenghtening the suggestion) would probably help in making sure authors don't get too complacent about relying just on whatever the browser/device determines to be the primary pointer input, as ignoring any alternative inputs would conversely force users to only use the primary input even if they don't want to, for …

[mediaqueries-4] Move 'pointer'/'hover' note, reword "can potentially" to "should strongly consider"

---

cssom-1/Overview.bs

Now that the HTML spec exports the definition of CORS-same-origin, the term should be linked correctly and no longer needs to be ignored. Fixes #823.

[cssom] Remove CORS-same-origin from ignored terms

---

css-transforms-2/Overview.bs

rotateZ(angle) is a 3d transform equivalent to the 2d transform
rotate(angle).
The spec previously said they are "the same", which is inaccurate
as 3d transforms can have additional side-effects in UAs.
resolves #2520

[css-transforms] 2D and 3D rotation are distinct

---

cssom-1/Overview.bs

See individual commits for reference.

[cssom] Fix #2403 and #2149

---

cssom-1/Overview.bs

[cssom] Have property setters append new declaration rather than set in place

---

cssom-1/Overview.bs

Also remove a bunch of ignored terms, as either these are no longer present or they since resolve properly.

Add links for media query terms in CSSOM

---

css-scoping-1/Overview.bs

This was discussed at
https://github.com/w3c/csswg-drafts/issues/640
Blink has implemented this behind the flag, but it looks never used.
https://www.chromestatus.com/metrics/feature/timeline/popularity/1691

Remove `>>>` combinator from the css-scoping spec.

---

css-ui-3/Overview.bs
css-ui-4/Overview.bs

outline-width only permits one line-width, not two or three or four.
resolves #2535

[css-ui] outline-width refers to line-width

---

css-align-3/Overview.bs
css-flexbox-1/Overview.bs
css-grid-1/Overview.bs
css-transforms-2/Overview.bs
cssom-view-1/Overview.bs

Make sure that various specs correctly invoke either
"overflow is not visible" or "is a scroll container" since these two are
no longer equivalent.
This change is meant to be editorial prior to the introduction of 'overflow: clip', and to avoid the introduction of 'overflow:clip' to have undesirable normative effects.
----
This PR does not bother with maintained specs like css-box.

Deal with overflow:clip

---

cssom-1/Overview.bs

See individual commits for reference.

Fix #1548.

---

css-fonts-3/Fonts.src.html

A missing semicolon causes IDL parser error.

[css-fonts-3] Add semicolon after CSSFontFaceRule

---

css-text-3/Overview.bs

There's no ZJW class in UAX 14. I guess @frivoal means the ZWJ (Zero Width Joiner) class.

[css-text-3] Typo fix

---

css-fonts-4/Overview.bs

Use "prop" to be consistent with other property sections. (`font-variant-emoji` is a property, not a descriptor.)

[css-fonts-4] Fix ID for the font-variant-emoji section

---

css-display-3/Overview.bs

For consistency with the other syntax definitions.

[css-display] Add space before semicolon

---

css-animations-1/Overview.bs

As per the web-idl spec, float should only be used if there is a specific
reason, as double much more closely matches the ECMAScript Number
type. In the case of AnimationEvent's 'elapsedTime' member there does
not appear to be such a reason.
Furthermore, switching to double allows the elapsedTime to reach higher
values without overflowing. A rough calculation (with some assumptions
and possible errors) suggests that this change will raise the celing
from ~4.5 hours to years.

[css-animations] Change an AnimationEvent member from float to double

---

css2/cover.html
css2/cover.src
css2/syndata.html
css2/syndata.src
css2/tables.html
css2/tables.src
css2/visudet.html
css2/visudet.src
css2/visuren.html
css2/visuren.src

[CSS2] Reapply most editorial changes not by Bert

---

css-text-3/Overview.bs

[css-text-3] Spaces don't hang when break-spaces is specified

---

css-fonts-4/Overview.bs

Previous Web IDL update (https://github.com/w3c/csswg-drafts/commit/146c023e7b8b218874fd82d9b52b354f116aeffa) only fixed the first syntax error reported by Reffy.
A few other semi-colons were still missing. Also, the spec used the `MapClass` extended attribute, which no longer exists in Web IDL. The `CSSFontFeatureValuesMap` interface now uses a [maplike declaration](https://heycam.github.io/webidl/#idl-maplike).

[css-fonts-4] Fix Web IDL syntax

---

css-transforms-2/Overview.bs

Similar to #2711. You really need to go through the 4 columns.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1459403

[css-transforms-2] Fix scale application in matrix recomposition algorithm.

---

css-transforms-2/Overview.bs

You need to apply translation in all the columns.
I found this while hunting a transform recomposition bug in the new Gecko style
engine, which implemented this spec to the letter.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1459403

[css-transforms-2] Fix translation in matrix recomposition algorithm.

---

css-text-3/Overview.bs

[css-text-3] overflow-wrap:break-word affects intrinsic sizing

---

selectors-4/Overview.bs

Change "header element" to "heading element". "Heading" is intended here, since it is referring to HTML heading elements above, and "heading" is also used in a prior description (line 1271).

Fix typo: "header element" to "heading element"

---

css-animations-1/Overview.bs

`GlobalEventHandlers` is now defined as a `mixin` per https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers. Update the partial interface's definition to indicate that it is a `mixin`.

[css-animations] Change definition of GlobalEventHandlers to mixin

---

css-contain-1/Overview.bs

'counter-increment' and 'content' property names are now working links.
resolves #2800

[css-contain] property names linkified

---

css-env-1/Overview.bs

Define CSS safe area inset variables as part of #2629

[css-env-1] Define safe area inset variables #2629

---

css-shapes-2/Overview.bs

css-shapes-2 refers to css-shapes-1 for shape-margin.
css-shapes-2 (like css-shapes-1) refers to css-masking-1 for 'nonzero'
and 'evenodd'.

[css-shapes] Refer css-shapes-1 for shape-margin

---

mediaqueries-5/Overview.bs

This is a proposal to add the ability to detect the display environment.
We've heard from several authors that they want to use a different style for an immersive display and they currently can't do that without invoking script.
With this simple media feature they can adjust their pages for an AR and VR display.
Hopefully this PR can start a good discussion!

Added the first proposal for a 'environment-blending' keyword.

---

css-round-display-1/Overview.bs

The CSS Borders spec (CSS3-BORDER) is obsolete.
We now have CSS Backgrounds and Borders (CSS3BG).

[css-round-display] Refer to Backgrounds & Borders

---

css-text-3/Overview.bs

[css-text-3] Move break-spaces from overflow-wrap to white-space

---

css-grid-1/Overview.bs
css-inline-3/Overview.bs

The Grid and Inline modules now link to css-align-3 for alignment baseline,
avoiding a link error as svg2-draft also defines alignment baseline.
No change needed for flexbox as it already linked to css-align-3.

Link to css-align-3 for alignment baseline

---

css-text-decor-4/Overview.bs

css-text-decor-4 refers to fill-stroke-3 (not svg2) for fill and stroke.

[css-text-decor] fill-stroke-3 for fill, stroke

---

css-writing-modes-3/Overview.bs
css-writing-modes-4/Overview.bs

The recent change to make direction, unicode-bidi and writing-mode
not animatable is now listed in Changes, and copied across to
writing-modes-4.

[css-writing-modes] not animatable in Changes

---

css-writing-modes-4/Overview.bs

css-writing-modes-4 refers to css-break-3 (not url) for the definition
of fragment.

[css-writing-modes] Use css-break-3 for fragment

---

css-contain-1/Overview.bs
css-contain-1/issues-2018-cr.html
css-contain-1/issues-2018-cr.txt

[css-contain] layout containment causes stacking contexts

---

css-align-3/Overview.bs

There's a missing single quote here, which means this one instance of  align-self/stretch gets quoted directly in the spec, with broken linkification around it. Here's the affected section if you're curious:
https://drafts.csswg.org/css-align/#baseline-content-alignment
And here's a screenshot (good for 14 days):
https://screenshots.firefox.com/V5tvNjkCu5juNkoF/drafts.csswg.org
Looks like we're just missing a single quote here. This pull request adds the missing single-quote to fix it.
Copy the above line into the Title and replace with the relevant details. Fill in any additional details here. See https://github.com/w3c/csswg-drafts/blob/master/CONTRIBUTING.md …

[css-align] Add 2nd single-quote around 'align-self/stretch'

---

css-transforms-1/Overview.bs
css-transforms-2/Overview.bs

Add a new definition "containing block for all descendants" and specify
that values other than 'none' on 'transform', 'transform-style',
'perspective' will cause an element to establish a containg block for
all descendants.

[css-transform] Define "containing block for all descendants"

---

web-animations-1/Overview.bs

This fixes #3000.
r? @graouts @stephenmcgruer @flackr

[web-animations] Use 'auto' for unspecified keyframe-specific composite operations

---

css-grid-1/Overview.bs

The custom-ident for line name cannot be 'auto'.
Resolved in
https://github.com/w3c/csswg-drafts/issues/2856#issuecomment-411476346
fixes #2856

[css-grid] Exclude 'auto' from line name

---

css-syntax-3/Overview.bs

Adds missing `(\)` after `U+005C REVERSE SOLIDUS`

[css-syntax-3] Missing character after Unicode name

---

css-scrollbars-1/Overview.bs

Add `none` value for `scrollbar-width` given we may be dropping `<length>`.

[css-scrollbars-1] Add scrollbar-width: none

---

cssom-view-1/Overview.bs

This PR fixes https://github.com/w3c/csswg-drafts/issues/2146.
It removes instant from the IDL.

[cssom-view] Removed instant mention

---

selectors-4/Overview.bs

@tabatkins Following up on #2481, trying to more clearly explain the intent of this pseudo-class and provide better author and UA guidance.
Thanks to @patrickhlauke and @AmeliaBR for inspiration for the second example (not sure how to credit you in the spec).
cc @robdodson @bkardell

Explain :focus-visible intent, add examples and UA guidance

---

css-scrollbars-1/Overview.bs

I think the main point of having thin scrollbars is to give content more room when the space is already tight, so it is probably better using the concept of "scrollbar gutter" for this value, which is also clearer when overlay scrollbar / auto-expand scrollbar involves.
Also when the scrollbar is already fully overlay (e.g. on macOS when trackpad is used, or on Android), I believe there is no point to create an even thinner scrollbar, so the value probably shouldn't use a "must".

[css-scrollbars-1] Loosen requirement for scrollbar-width:thin

---

css-scrollbars-1/Overview.bs

[css-scrollbar] Merge scrollbar color properties into one

---

css-text-3/Overview.bs

[css-text-3] Make sure control characters really are visible #1990

---

css-text-3/Overview.bs

[css-text-3] treat lone cr as any control character #855

---

css-scrollbars-1/Overview.bs

[css-scrollbar] Add text for contrast concern of scrollbar colors

---

css-backgrounds-3/Overview.bs
css-break-3/Overview.bs
css-contain-1/Overview.bs
css-exclusions-1/Overview.bs
css-page-3/Overview.bs
css-regions-1/Overview.bs
css-shapes-1/Overview.bs
css-shapes-2/Overview.bs
css-ui-3/Overview.bs
css-ui-4/Overview.bs

Update refs to the box model

---

css-align-3/Overview.bs

The production rules for self-position and content-position
previously ended with `| flex-end;`
The semicolon is not needed.

[css-align] flex-end without semicolon

---

css-contain-1/Overview.bs

Adding the bikeshed wpt info for tests in the wpt test suite.
@tabatkins I think I'm doing this right, but I don't understand if this is safe to merge. If I understand correctly, any test added to wpt that isn't referenced here will generate a fatal error, and block the spec from being auto-regenerated on http://drafts.csswg.org/, which seems bad.
Generating a warning is totally useful, but I fatal error seems a problem. Am I misunderstanding something?

[css-contain-1] Add bikeshed wpt info

---

web-animations-1/Overview.bs

[web-animations-1] Calculate the play state using an animation's effective playback rate

---

css-content-3/Overview.bs

In `attr()`, `<type-or-unit>` is space-separated, instead of comma-separated, with `<attr-name>`.

[css-content-3] Typo fix

---

css-transforms-2/Overview.bs

This occurs in the following code:
```
if (product == 1.0)
quaternionDst = quaternionA
return
theta = acos(dot)
w = sin(t * theta) * 1 / sqrt(1 - product * product)
```
If `product` is -1.0 we'll end up doing division by zero when we
calculate `w`.
WebKit works around this by inverting the angle (effectively doing the
same thing as taking the absolute value):
https://github.com/WebKit/webkit/blob/425f9748af04b2c7e235cf3ff9396eecc23c0af5/Source/WebCore/platform/graphics/transforms/TransformationMatrix.cpp#L542-L548
Chromium takes the absolute value like this patch does:
https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/transforms/transformation_matrix.cc?l=762&rcl=cd5181ecb173efdef4163f066c27bd136fca01d5

[css-transforms-2] Fix the check for product == 1.0 to include the case when product is -1

---

cssom-view-1/Overview.bs

Given that usage of these attributes are high and that they are implemented in Chrome, WebKit, and Edge, standardization seems like the best option for `screenLeft` and `screenTop`. Add them into the spec as simple aliases of `screenX` and `screenY`.
Fixes #1091.

[cssom-view] Add window.screenLeft and window.screenTop as aliases

---

css-print/Overview.bs

It erroneously used `css-mobile` instead of `css-print`.

[css-print] correct Bikeshed Shortname variable

---

css-transforms-1/Overview.bs

[css-transforms-1] Specify the "pad, interpolate prefix, then smoosh" interpolation behavior

---

css-animations-1/Overview.bs
css-transitions-1/Overview.bs

...and thus should only be extended by `partial interface mixin`s.

[css-transitions-1] [css-animations-1] GlobalEventHandlers is a mixin

---

css-sizing-4/Overview.bs

"tall" and "high" refer to the same dimension so it doesn't really make sense.

[css-sizing-4] Typo: s/as tall as it is high/as tall as it is wide/

---

css-images-3/Overview.bs

The deprecated image-rendering value 'optimizeQuality' has the same behavior as 'smooth'.
resolves https://github.com/w3c/csswg-drafts/issues/3283

[css-images] optimizeQuality behaves like smooth

---

css-transforms-2/Overview.bs

[css-transforms-2] Permit piecewise rotation interpolation when 0deg angle is present #3236
This change makes rotations like `rotateX(45deg)` and `rotateY(0deg)` compatible for simple interpolation without triggering matrix interpolation. Any 0deg rotation can interpolate cleanly with any other rotation.

[css-transforms-2] Permit piecewise rotation interpolation when 0deg angle is present #3236

---

css-fonts-4/Overview.bs
css-text-3/Overview.bs

[css-text-3] Disentangle content language and writing system

---

css-values-4/Overview.bs

The example ''calc(20px + 0%)'' is serialized as
''calc(0% + 20px)'', according to the serialize a summation rules
https://drafts.csswg.org/css-values/#math-function-serialize-a-summation
i.e. Sort the terms in the following order:
1. The number, if present
2. The percentage, if present
3. The dimensions, ordered by their units <a>ASCII case-insensitive</a> alphabetically
4. The ''min()'' and ''max()'' functions,
in the order they appeared in the original expression.

[css-values] Serialize % before px in calc example

---

css-regions-1/Overview.bs

CSS-wide keywords such as `inherit` do not need to be included
in the grammar for a specific property such as `flow-from`.

[css-regions] Skip inherit in flow-from grammar

---

css-counter-styles-3/Overview.bs
css-gcpm-3/Overview.bs
css-gcpm-4/Overview.bs
css-shapes-1/Overview.bs
css-shapes-2/Overview.bs

Remove Bugzilla in the metadata section for specs return "**Zarro Boogs found.**"
The remaining ones are:
* [css-animations-1](https://github.com/w3c/csswg-drafts/blob/70e11db3dcc0fda5cc0ee89be5bd347477d565c2/css-animations-1/Overview.bs#L34) and [css-animations-2](https://github.com/w3c/csswg-drafts/blob/70e11db3dcc0fda5cc0ee89be5bd347477d565c2/css-animations-2/Overview.bs#L46)
* [css-device-adapt-1](https://github.com/w3c/csswg-drafts/blob/70e11db3dcc0fda5cc0ee89be5bd347477d565c2/css-device-adapt-1/Overview.bs#L17)
* [css-exclusions-1](https://github.com/w3c/csswg-drafts/blob/70e11db3dcc0fda5cc0ee89be5bd347477d565c2/css-exclusions-1/Overview.bs#L15)
* [css-regions-1](https://github.com/w3c/csswg-drafts/blob/70e11db3dcc0fda5cc0ee89be5bd347477d565c2/css-regions-1/Overview.bs#L15)
* …

Reduce references to Bugzilla

---

css-text-3/Overview.bs
resize-observer-1/Overview.bs

[resize-observer-1] Update algorithms with new boxes
A large pull request, algorithm redo touched everything.
The main work was modifying algorithms to work with multiple boxes. This work should be complete. I assumed RO is only observing 1 box at a time, as discussed in #3329.
Minor work included:
- fixing some of the spec bugs that were opened by domenic in the old repo.
- switching from contentRect to borderBoxSize in examples, no need to showcase old API.
One last large [remaining problem](https://github.com/WICG/ResizeObserver/issues/46) is ResizeObservation. It should not be an idl interface, but a bag of slots and algorithms. I'll do this next week. 
I am not very proficient with bikeshed, especially references and slots. There is probably a lot of room for cleanup by an expert.

[resize-observer-1] Update algorithms with new boxes

---

mediaqueries-3/Overview.html
mediaqueries-3/Overview.src.html

Not that it's observable I think, since there are no defined media features with non-ascii characters, but...

[mediaqueries-3] Mention ASCII case-insensitivity, not only case-insensitivity.

---

css-shadow-parts-1/Overview.bs

The [algorithm for parsing part mappings](https://drafts.csswg.org/css-shadow-parts/#parsing-mapping) states that a colon (`:`) is expected between idents.
As noted in the [fix for the explainer doc](https://github.com/fergald/docs/pull/2), the missing colon in the example is probably an oversight after the syntax change.

[css-shadow-parts-1] Add missing colon to part forwarding example

---

css-fonts-3/Fonts.html
css-fonts-3/Fonts.src.html
css-fonts-3/Overview-wip.bs
css-fonts-3/Overview.html
css-fonts-4/Overview.bs

A non-default value for letter-spacing should disable all
optional ligatures, not just common ligatures. Defer to css-text for
optional ligature definition.
Test that letter-spacing disables discretionary ligatures in particular at
https://chromium-review.googlesource.com/c/chromium/src/+/1294874

[css-fonts-3][css-fonts-4] letter-spacing disables optional ligatures. #2644

---

css-text-3/Overview.bs

This sentence is a leftover form where break-spaces was defined as a
value of overflow-wrap, and no longer makes sense now that it has been
moved to the white-space property
cc @fantasai 
Note: I did not update the DoC or the Change section in this patch, so that needs to be done after merging.

[css-text] Remove stray text

---

web-animations-1/Overview.bs

[web-animations-1] Make the definition of "is current" reflect the associated animation's playback rate

---

css-text-3/Overview.bs
css-text-3/test-coverage.html

@fantasai this PR corrects a sentence which I find somewhat confusing / misleading.
Correcting it to what I believe is the "obvious" correct meaning, but asking you for review in case I am more confused than I thought.

[css-text-3] Clarify confusing sentence

---

css-logical-1/Overview.bs

https://github.com/w3c/csswg-drafts/commit/8dbce74efa894eb8c7183440bd312316cb1ce449#diff-d7d080704a1157585de808649f930ae7 did this change for `caption-side`, `text-align` and `resize`, but forgot about `float, clear`.

[css-logical-1] s/as specified/specified keyword

---

css-pseudo-4/Overview.bs

Fixes a typo in [this paragraph](https://www.w3.org/TR/css-pseudo-4/#intro).

[css-pseudo-4] Fix typo

---

cssom-1/Overview.bs

Matching https://dom.spec.whatwg.org/#mixin-documentorshadowroot.

[cssom] Treat DocumentOrShadowRoot as an interface mixin

---

css-pseudo-4/Overview.bs

[css-pseudo-4] Rename the values of CSSPseudoElement.type to match the corresponding pseudo-elements

---

css-variables-1/Overview.bs

https://drafts.csswg.org/css-variables/#using-variables
Opened because of&nbsp;@tabatkins’s comment in&nbsp;https://github.com/w3c/csswg-drafts/pull/3475#issuecomment-451526826.
review?(@tabatkins, @zcorpan)

refactor(css‑variables): Simplify `var()` function syntax definition

---

css-writing-modes-4/Overview.bs

Fix typo: Closing tag missing character '>'

---

css-ui-4/Overview.bs

This text used to say "may not be"; and at some point, "may not" was replaced
with "is not", and the word "be" was left in accidentally.

Fix typo (s/is not be/is not/)

---

css-shapes-1/Overview.bs

An ellipse may have an x-radius and y-radius, or neither.
resolves #3609

Address typo in ellipse() syntax

---

css-overflow-3/Overview.bs

Treating it as ''line-height: 0'' should handle that.
This is slightly different from the resolution taken in #2905, but this should be equally safe with regards to relayout, while still allowing text alignment and especially justification to work fine.

[css-overflow-3] Inserting the block ellipsis should not cause relayouts

---

css-nesting/Overview.bs

This adds css-nesting as a draft, taken from https://github.com/tabatkins/specs as `css-nesting/index.bs` and moved here as `css-nesting/Overview.bs`.
From [#2701](https://github.com/w3c/csswg-drafts/issues/2701#issuecomment-402392212):
> The Working Group just discussed css nesting, and agreed to the following:
> RESOLVED: add css-nesting as an ED, Tab Atkins as editor, file issues until ppl are overall kinda happy with what it's like before we consider FPWD
**This is original work by @tabatkins and should be reviewed by @tabatkins before being considered to merge.**
- I renamed the bikeshed document from `index.bs` to `Overview.bs` to match other specs in this repository.
- I updated the top-most `metadata` section to match other specs, as well. This attempt may have included mistakes. …

Add CSS Nesting

---

css-nesting-1/Overview.bs

Fixes a couple of typos and grammatical errors like:
```diff
-	editting
+	editing
-	Nesting allow
+	Nesting allows
-	some people find the nesting difficult to visually distinguish
+	some people find the nesting challenging to distinguish visually
```
Looking forward, peace! ✌️

🐛 FIX: Typos & Grammar

---

cssom-view-1/Overview.bs

...so that it can be called in other contexts, by other specs (like this one: https://github.com/whatwg/html/pull/3774/commits/7bd134ec67472303d06700686be5d37d45ada048#diff-36cd38f49b9afa08222c0dc9ebfe35ebR28619)

[cssom-view-1] Name the algorithm for determining devicePixelRatio

---

css-regions-1/Overview.bs

The actual `mixin` keyword was overlooked in https://github.com/w3c/csswg-drafts/pull/3643.

[css-regions-1] Convert Region to a mixin (reprise)

---

css-scroll-snap-1/Overview.bs

As per https://github.com/w3c/csswg-drafts/issues/3752
All other scrollbar operations are listed in the examples. Seems odd to not include the arrows.

[css-scroll-snap-1] Include scroll arrows in "intended direction" examples. #3752

---

css-values-4/Overview.bs

Related to #2331 and commit b8935e7df14ed544c51a991cf10f15bf077eb603
The only normative change (from Tab's commit) is that `atan2()`
is changed to support values with dimensions (so long as both dimensions are the same).
I don't see any implementation reason not to allow it;
they type checking rules are the same as `hypot`
(except that the types cancel out, so don't affect the final type of the function).
Most other corrections should be obvious in the diff.
I changed the note about atan2 because it used terminology
based on a y-axis-up coordinate system
and CSS/SVG uses a y-axis-down system.
I changed the notes about simplifying at computed value time
to refer to _calculations_ instead of _math functions_,
because some complex nested functions cannot be simplified early.
(E.g., …

[css-values-4] Clean up trig function definitions

---

css-ruby-1/Overview.bs

Also integrated changes from previous publications.

[css-ruby-1] Update Changes section

---

css-conditional-3/Overview.bs

There are multiple interoperable implementations of it.

[css-conditional-3] @supports is not at risk.

---

css-text-decor-4/Overview.bs

It looks like 70e40c9315bf8d478ddecf0da5e5af3ddacbc509 introduced the `text-decoration-skip-ink` property, but kept the example from the previous `text-decoration-skip` one.

[css-text-decor-4] typo in text-decoration-skip-ink property name

---

css-conditional-3/Overview.bs
css-conditional-4/Overview.bs

Depends on #3773.
Closes #3207.

[css-conditional] Define @supports selector function.

---

css-images-4/Overview.bs

Closes #1334
I'm pretty sure this was the only change required. Not sure why I didn't make a PR at the time I filed the issue, but I guess I was busy…

[css-images-4] Fix gradient color stop syntax

---

selectors-4/Overview.bs

- Removed `:drop()` from the at-risk feature list since removed from the spec
- Added `s` to `Ignored Vars`. Not sure its needed
- Added `s` to `<attr-modifier>` syntax

[selectors-4] Fixes according latest changes

---

css-rhythm-1/Overview.bs

line-height-step is a length, so the initial
value is '0px', not '0'.
WPT: https://github.com/web-platform-tests/wpt/pull/13572

[css-rhythm] line-height-step initial value

---

web-animations-1/Overview.bs

[web-animations-1] Define animation replacing behavior

---

css-contain-1/Overview.bs

Display keywords 'none' 'contents' and 'table-cell' now
appear as links.
resolves #3889

[css-contain] Add links to display keywords

---

css-backgrounds-4/Overview.bs

In CSS Backgrounds and Borders Level 3, the initial value
of background-position is '0% 0%'.
In Level 4, the initial value of background-position-x and
background-position-y is '0%' and '0%', not 'left' and 'left'.

[css-backgrounds] Initial background-position-x/y

---

cssom-1/Overview.bs

[cssom] Define legacy CSSStyleSheet methods as implemented in Blink.

---

css-backgrounds-4/Overview.bs

The entries in background-position-x and background-position-y
may not be empty.
We use the exclamation point (!) modifier to indicate that
a keyword or length-percentage (or both) must be present,
they cannot both be omitted.

[css-backgrounds] list entries not empty

---

css-images-4/Overview.bs

Closes #428
Because current Web IDL spec [allows namespaces to include readonly attributes](https://heycam.github.io/webidl/#idl-namespaces).
Also `Map` is replaced to `any` because AFAIK there is no valid way to represent ES map object in IDL.

[css-images-4] Uncomment IDL attribtue

---

web-animations-1/Overview.bs

[web-animations-1] Add advice about not using indefinitely filling animations

---

css-gcpm-4/Overview.bs

Avoids bikeshed failure:
FATAL ERROR: Couldn't find 'LATINREQ' in bibliography data.
Also use https for github link.

[[css-gcpm-4] Fix reference to dpub-latinreq

---

cssom-1/Overview.bs

https://drafts.csswg.org/cssom-1/#the-cssstyledeclaration-interface
`[TreatNullAs=EmptyString]` should stick to IDL types instead of arguments. cc @gsnedders

[cssom] Move TreatNullAs to the correct position

---

resize-observer-1/Overview.bs

Just fixing some typos.
This commit replaces 'specificBox' with 'observedBox' in several places (which is the actual defined term for this concept in the spec).  This also fixes one mention of "bounding-box" which really meant to say "border-box".

[resize-observer-1] Fix some observedBox terminology issues

---

css-regions-1/Overview.bs

Avoid the bikeshed warning:
The biblio refs [[css-break-3]] and [[CSS3-BREAK]] are both aliases of the same base reference [[css-break-3]]. Please choose one name and use it consistently.

[css-regions] Consistent references to CSS3-BREAK

---

css-inline-3/Overview.bs
css-scroll-anchoring-1/Overview.bs

Select the css-box-3 definition of 'content area',
not the description in css-exclusions-1.
Avoid bikeshed message:
Multiple possible 'content area' dfn refs.

[css-inline] [css-scroll-anchoring] content area

---

css-ui-4/Overview.bs

Fixes #3551
Tests: https://github.com/web-platform-tests/wpt/pull/14996
cc @MatsPalmgren @tkent-google

[css-ui] appearance: menulist-button is different from auto

---

css-scroll-snap-1/Overview.bs

Discussed in #1084 and
https://drafts.csswg.org/css-scroll-snap-1/#changes-20161020

[css-scroll-snap] scroll-padding is not negative.

---

css-fonts-4/Overview.bs

Replaces font-size prefix keywords -webkit-xxx-large and -konq-xxx-large.
Similar to <font size="7">
resolves #3907
WPTs to be added by implementations, e.g.
https://crbug.com/966249

[css-fonts] Add font-size: xxx-large

---

css-nav-1/explainer.md

This fixes a few typos and rewords one bit that I noticed while reviewing w3ctag/design-reviews#287.

[css-nav-1] Fix a few typos and reword one bit that's unclear.

---

css-values-4/Overview.bs

Avoid bikeshed error report:
FATAL ERROR: Line 3251 isn't indented enough (needs 1 indent) to be valid Markdown:
Fix reference to `<<calc-value>>`

[css-values] fix indentation

---

css-cascade-3/Overview.bs
css-cascade-4/Overview.bs
css-fonts-4/Overview.bs
css-page-3/Overview.bs

Link to css-values definition of ex units
instead of css-inline-3 leading-trim keyword ex.
(Specs already link to css-values for em.)
css-cascade-3 links to mediaqueries-4 instead
of css-cascade-4 for media-query.

Link to CSS Values definition of ex units

---

css-values-3/Overview.bs

List of tests bikeshed-added with <wpt> into Overview.bs are 
absolute-length-units-001.html
angle-units-001.html
angle-units-002.html
angle-units-003.html
angle-units-004.html
angle-units-005.html
attr-color-invalid-cast.html
attr-color-invalid-fallback.html
attr-color-valid.html
attr-invalid-type-001.html
attr-invalid-type-002.html
attr-invalid-type-008.html
attr-length-invalid-cast.html
attr-length-invalid-fallback.html
attr-length-valid-zero-nofallback.html
attr-length-valid-zero.html
attr-length-valid.html
attr-px-invalid-cast.html
attr-px-invalid-fallback.html
attr-px-valid.html
calc-angle-values.html
calc-background-position-002.html
calc-in-calc.html	
calc-in-counter-001.xhtml
calc-in-media-queries-001.html
calc-in-media-queries-002.html
calc-invalid-range-clamping.html …

[css-values-3] Bikeshed-added 34 links to tests in Overview.bs

---

css-values-3/Overview.bs

List of 38 additional tests bikeshed-added into csswg-drafts/css-values-3/Overview.bs are
initial-background-color.html
regions-resizing-003.html
regions-resizing-007.html
regions-resizing-009.html
shape-outside-circle-002.html
shape-outside-circle-004.html
shape-outside-circle-010.html
shape-outside-circle-011.html
shape-outside-ellipse-002.html
shape-outside-ellipse-004.html
shape-outside-ellipse-010.html
shape-outside-ellipse-011.html
shape-outside-inset-003.html
shape-outside-inset-008.html
shape-outside-inset-009.html
shape-outside-polygon-004.html
shape-outside-polygon-006.html
transforms-support-calc.html
transition-delay-001.html
transition-duration-001.html
unset-value-storage.html
vh-calc-support-pct.html
vh-calc-support.html
vh-em-inherit.html
vh-inherit.html …

[css-values-3] Bikeshed-added 38 more links to tests in Overview.bs

---

css-ui-4/Overview.bs

The 'button-bevel' value is removed in Chromium 75:
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/ldH_uIfk_QE/Ua0bGyLIAwAJ
Tests: https://github.com/web-platform-tests/wpt/pull/14980
---
cc @tkent-google @MatsPalmgren

[css-ui] appearance: Remove 'button-bevel'

---

css-values-4/Overview.bs

List of 22 tests bikeshed-added into csswg-drafts/css-values-4/Overview.bs are
calc-integer.html
calc-nesting-002.html
calc-positive-fraction-001.html
calc-rgb-percent-001.html
calc-serialization-002.html
calc-serialization.html
calc-z-index-fractions-001.html
getComputedStyle-border-radius-001.html
getComputedStyle-border-radius-003.html
ic-unit-001.html
ic-unit-002.html
ic-unit-003.html
ic-unit-004.html
ic-unit-008.html
ic-unit-009.html
ic-unit-010.html
ic-unit-011.html
ic-unit-012.html
lh-rlh-on-root-001.html
lh-unit-001.html
lh-unit-002.html
rgba-011.html

[css-values-4] Bikeshed-added 22 links to tests

---

css-values-3/Overview.bs

Fix typos in recent changed parts

[css-values-3] Fix typos

---

css-multicol-1/Overview.bs

https://github.com/w3c/csswg-drafts/issues/1072
Given the fiddliness of this I have opened a PR. I'm just looking at this first part now, with regard to the inclusion of the new model plus the naming we discussed. If we can get this right I'll go through the spec looking for any naming problems that fall out of it. I'll address the parts that deal with spanners specifically separately. I wanted to sort all these anonymous boxes first.
1. I think we essentially add an extra container (2 in @frivoal's writeup in the issue) when we do this, I've attempted to write that in. We end up with multiple multicol rows in the case of pagination (these contain the box 1 in @frivoal's writeup) and spanners. In future we might then add the concept or rows being created in the block dimension by height …

[css-multicol] Pass at incorporating the new model plus clarification in the issue re naming

---

css-grid-2/Overview.bs
css-sizing-4/Overview.bs

css-grid-2 refers to css-align-3 column-gap (and row-gap).
css-sizing-4 refers to css-align-3 column-gap (and css-multicol-1 column-count).

[css-grid] [css-sizing] links to column-gap

---

css-transforms-1/Overview.bs

Simplify syntaxes for `matrix()`, `translate()`, `scale()` and `skew()`

[css-transforms-1] Simplify transform function syntaxes

---

css-round-display-1/Overview.bs

'shape-inside' property was postponed in level 1 and now resides in level 2.

[css-round-display] Refer to css-shapes-2

---

css-scrollbars-1/Overview.bs

Link to the scrollbar-color and scrollbar-width
definitions of auto.
Avoid bikeshed warning:
Multiple possible 'maybe' local refs for 'auto'.

[css-scrollbars] links to auto keyword

---

css-values-3/Overview.bs

links added to the following tests:
css/CSS2/values/units-008.xht
css/CSS2/values/numbers-units-016.xht
css/css-values/absolute_length_units.html
css/CSS2/values/units-001.xht
css/CSS2/values/units-006.xht
css/CSS2/values/units-008.xht
css/CSS2/values/units-009.xht

Added links of 7 tests in css-values-3/Overview.bs

---

css-values-3/Overview.bs

Links to the following 6 tests added into css-values-**3**/Overview.bs:
calc-ch-ex-lang.html
calc-in-color-001.html
calc-in-font-feature-settings.html
calc-rem-lang.html
calc-rounding-001.html
ex-calc-expression-001.html

Added links to 6 tests in css-values-3/Overview.bs

---

css-conditional-3/Overview.bs

Tests submitted to WPT:
https://github.com/web-platform-tests/wpt/pull/17276

[css-conditional-3] Remove duplicate interface #3528

---

css-animations-1/Overview.bs

Replace the old phrasing
Animatable: no
with the new phrasing
Animation type: not animatable

[css-animations] animation-delay is not animatable

---

css-text-3/Overview.bs

Separate the notion of hanging in general, from it's specific
application to hanging-punctuation, and provide reusable anchor
terminology that distinguishes unconditional hanging from “allowed” hanging.
Also, be explicit about the effects on intrinsic sizes.
Note: there are open issues and pending edits on how preserved
white-space at the end of a line is supposed to hang. This edit does not
solve these, and keeps the current behavior as it is. By making the
definitions of hanging reusable, it is a useful step towards solving
these as well.

[css-text] Clarifications on "hanging"

---

css-text-3/Overview.bs

Closes #3879
@fantasai: Requesting review primarily to bikeshed the new anchor term introduced to refer to Unicode Category Zs less U+0020 and U+00A0 (but other comments welcome as well, of course).

[css-text-3] Hanging/collapsing of fixed-width spaces

---

css-fonts-4/Overview.bs

Each string in font-variation-settings is
paired with a single number.

[css-fonts] font-variation-settings

---

css-values-4/Overview.bs

Use minus sign instead of hyphen.
Use increasing order for tan, improving consistency
as we use increasing order for sin and cos.

[css-values] sin and cos can reach -1

---

css-tables-3/Overview.bs

bikeshed didn't give the definition the ② ③ links when the
references were done with a href.

[css-tables-3] Editorial: Fix constrainedness references

---

css-tables-3/Overview.bs

[css-tables-3] Remove vestiages of min-width percents from #607
WG resolved to ignore percent min-width for column widths in #607 but
not everything was removed.

[css-tables-3] Remove vestiges of min-width percents

---

css-writing-modes-3/Overview.bs
css-writing-modes-4/Overview.bs

'writing-mode' and 'direction' are propagated up from the body element.
This affects the root element in addition to the ICB and viewport,
but only for used values, not for computed values.
The same propagation is optionally allowed for 'text-orientation'.
Closes #3066

[css-writing-modes] Clarify how propagation from body works

---

css-shapes-1/Overview.bs

shape-image-threshold now accepts any alpha-value, just like
opacity. (An alpha-value is a number or percentage, that
serializes as a number.)
resolves #4102

[css-shapes] shape-image-threshold accepts percent

---

css-values-3/Overview.bs
css-values-4/Overview.bs

- Replaced `text-shadow` for `box-shadow` since `text-shadow` has no `inset` component
- Removed unnecessary grouping ([`<shadow>` definition](https://drafts.csswg.org/css-backgrounds/#typedef-shadow))
According to spec, the order of terms should be `none | [ <color>? && <length>{2,4} && inset? ]#`. However, left it as is since it's not a big deal.

[css-values-3][css-values-4] Fix example in Property Value Examples

---

css-counter-styles-3/Overview.bs

In current form of `counter-style` syntax, `symbols()` is not a reference for the type:
```
<counter-style> = <counter-style-name> | symbols();
```
This change fix that.

[css-counter-styles-3] Fix <counter-style> syntax to refer to <symbols()> instead of defining it

---

css-overflow-3/Overview.bs

Resolution: https://github.com/w3c/csswg-drafts/issues/3779#issuecomment-481762912

[css-overflow-3] #3779 Do not propagate overflow from boxless elements.

---

css-scroll-snap-1/Overview.bs

Move `auto` keyword in the beginning like in any other syntaxes of the spec.

[css-scroll-snap-1] Make <'scroll-padding'> syntax uniform with others

---

css-color-4/Overview.bs

Preserves language around system colors from css-color-3; moves undeprecated values from the appendix, leaving behind those which are still deprecated.

[css-color-4] Add new set of CSS system colors (addresses #3804)

---

css-egg-1/Overview.bs
css-shapes-1/Overview.bs

Use ''closest-side'' syntax so the keyword is formatted as CSS syntax.
Use link-defaults to prevent definitions in css-images-3 or motion-1 from
being chosen by bikeshed.
Use `<a href="#closest-side">` to link to the definition in CSS Shapes.
Note:
If basic shapes including the closest-side keyword were defined inside a
property such as shape-outside, we could use the
''shape-outide/closest-side'' bikeshed syntax.

[css-shapes] link to closest-side definition

---

css-exclusions-1/Overview.bs

We now link to the `float` and `wrap-through` definitions
of 'none', as appropriate.
Avoid bikeshed warning:
Ambiguous for-less link for 'none'

[css-exclusions] Link to definitions of 'none'

---

css-inline-3/Overview.bs

line-height must be normal or a number or a length-percentage.
It cannot be a number followed by a length-percentage.
This brings the definition of line-height into consistency with CSS 2.
https://www.w3.org/TR/CSS2/visudet.html#propdef-line-height

[css-inline] line-height cannot have two values

---

css-transforms-2/Overview.bs

[css-transforms-2] Use reference-box for translate property. 

---

css-transitions-1/Overview.bs

Required after heycam/webidl#750. (Found from web-platform-tests/wpt#18382)

[css-transition-1] Add dictionary default value

---

cssom-view-1/Overview.bs

Required after heycam/webidl#750. (Found from web-platform-tests/wpt#18382)

[cssom-view-1] Add dictionary default values

---

web-animations-1/Overview.bs

Required after heycam/webidl#750. (Found from web-platform-tests/wpt#18382)

[web-animations-1] Add dictionary default values

---

css-animations-1/Overview.bs

Required after heycam/webidl#750. (Found from web-platform-tests/wpt#18382)

[css-animation-1] Add default dictionary value

---

web-animations-2/Overview.bs

That's a single spec that define a title via `<h1>`. Now it defined as in any other spec

[web-animations-2] Define a title as in other specs

---

css-overflow-3/Overview.bs

That's a single spec where order of CSS class goes in that ways. It would be great to keep consistent order of classes in such cases.

[css-overflow-3] Change class order in markup as in other specs

---

css-tables-3/Overview.bs

Removed symbols even not visible on GitHub's diff view.
The diff from GitHub Desktop client:

[css-tables-3] Remove invisible symbols in <'border-spacing'> syntax definition

---

css-tables-3/Overview.bs

Revert "[css-tables-3] Remove invisible symbols in <'border-spacing'> syntax definition"

---

css-animations-1/Overview.bs
css-backgrounds-4/Overview.bs
css-fonts-4/Overview.bs

- a multiplier should stick to a term
- `#` multiplier should go before `{N,M}`

[css-animations-1][css-backgrounds-4][css-fonts-4] Fix multiplier usage in propdef/descdef

---

css-animations-2/Overview.bs
css-logical-1/Overview.bs
css-overflow-3/Overview.bs
css-writing-modes-3/Overview.bs
css-writing-modes-4/Overview.bs

With this patch there will be the following list of values for `Inherited`:
- yes
- no
- no (but see prose)
- no (but see prose, above)
- n/a
Not sure we need to left `n/a`, but not sure about replacement

Uniform `Inherited` values across specs

---

css-overflow-4/Overview.bs

Correct spelling of `id="scollbar-gutter-property"`

---

css-text-3/Overview.bs

Linkify and use non ambiguous terminology for "white space", "spaces",
and related terminology throughout normative prose.
Closes #4267

[css-text-3] Disambiguate "space"

---

css-text-3/Overview.bs

[css-text-3] Hang trailing collapsible other space separators instead of removing them

---

web-animations-1/Overview.bs
web-animations-2/Overview.bs

This PR moves the `iterationComposite` concept from the level 1 spec to the level 2 spec, as motivated in https://github.com/w3c/csswg-drafts/issues/4300

[web-animations-1][web-animations-2] Move iterationComposite to web-animations-2

---

web-animations-1/Overview.bs
web-animations-2/Overview.bs

Closes https://github.com/w3c/csswg-drafts/issues/4299

[web-animations-1][web-animations-2] Move mutable timelines to web-animations-2

---

css-nav-1/Overview.bs

The search origin will be updated only when the old focus target is completely off-screen after the scrolling.
(Note: If the old focus target is partially in the view after scrolling, the search origin won't be changed)
Related issue: https://github.com/w3c/csswg-drafts/issues/3392

[css-nav-1] Update the search origin after scrolling

---

css-nav-1/Overview.bs

Hide the description related to css property (`spatial-navigation-action`) from the processing model by option

[css-nav-1] Simplify the description of processing model

---

css-nav-1/Overview.bs

Consider the focusable element which fully overlaps with another focusable element.
Detailed changes are as below:
1. Add another condition to the definition of 'inside area'
* To consider the focusable element which fully overlaps with search origin as a candidate for enabling the focus to move there.
2. Make the difference the way to select 'insider' depending on whether the search origin is a spatial navigation container or not
* If the search origin is a container, consider the partially visible focusables as the insider.
* Else (if the search origin is the general element), consider only the fully overlapped focusables as the insider.
* NOTE: The partially overlapped focusable isn't included in the set of insider.
3. Modify the way to select candidates among visible focusable …

[css-nav-1] Fix the unreachability for a focusable element inside the search origin

---

css-nav-1/Overview.bs

* Add the step for using `inside` attribute of `option` argument
* Modify that the `candidates` are assigned after assigning the `container`.
* Add an example about the result of spatialNavigationSearch API using `inside` attribute
Close #3743

[css-nav-1] Modify spatialNavigationSearch API with `inside` attribute

---

web-animations-1/Overview.bs

To align with other list-list properties, box-shadow
addition/accumulation is changed to be defined as concatenation for
addition (previously component-wise addition) and component-wise
addition for accumulation (previously unspec'd).
Fixes https://github.com/w3c/csswg-drafts/issues/4330

[web-animations-1] Fix box-shadow addition/accumulation

---

css-values-4/Overview.bs

#94 has made a resolution that certain `calc()` mixing both lengths and percentages MUST be treated as `auto` instead of MAY. Updating spec accordingly.
Relevant WPT are updated in https://chromium-review.googlesource.com/c/chromium/src/+/1832619.

[css-values] Change MAY into MUST regarding calc() on table

---

css-values-4/Overview.bs

- Added missed chars in example definition, since it should be as original defined
- Remove doubling `<` and `>` around "pairing", since it renders odd

[css-values-4] Fix typos in comma-separated-list multiplier notes

---

cssom-view-1/Overview.bs

Fixes #4407.
Tests: https://github.com/web-platform-tests/wpt/pull/18390
---
@annevk are some of the terms here not exported in DOM but should be?

[cssom-view] Update {add,remove}Listener() to hook into DOM correctly

---

cssom-1/Overview.bs

> To serialize a URL means to create a string represented by "url(", followed by the serialization of the URL as a string, followed by ")".
> 
> To serialize a LOCAL means to create a string represented by "local(", followed by the serialization of the URL as a string, followed by ")".
`s/URL/LOCAL/` in that last line. Looks like it was copied from the rule above and incompletely replaced.

[cssom] Fix a typo in #serialize-a-local

---

web-animations-1/Overview.bs

Code health: This allows for much easier navigation in editors with live outline view.

[web-animations-1] reformat all headings to markdown style

---

css-font-loading-3/Overview.bs

Add clarification on 'find the matching font faces' algorithm regarding an empty text string

[css-font-loading-3] Add clarification on 'find the matching font faces' algorithm regarding an empty text string

---

css-size-adjust-1/Overview.bs

Like other sizing properties, text-size-adjust does not
accept negative values.

[css-size-adjust] text-size-adjust is non-negative

---

css-syntax-3/Overview.bs

when consuming a token, the first instruction for PLUS SIGN, HYPHEN-MINUS, and FULL STOP are all the same, but the PLUS SIGN instructions are missing a comma.
visit: https://www.w3.org/TR/css-syntax-3/#consume-comment
search the page for:
```
If the input stream starts with a number, reconsume the current input code point, consume a numeric token and return it. 
```
there is only 1 instance.
search the page for:
```
If the input stream starts with a number, reconsume the current input code point, consume a numeric token, and return it.
```
there are 2 instances.
i think all 3 versions should match.

[css-syntax] make "plus sign" match other 2 items

---

css-grid-1/Overview.bs

Fixes #4313.
I added the changes into "Minor Changes", but the change has no effect in practice, not sure if this means it should be in "Clarifications" instead.

[css-grid-1] Initialize growth limits of flexible tracks to infinity. #4313

---

css-backgrounds-4/Overview.bs

Computed length-percentage values for background-position longhands
is now specified using the same terminology as for other properties.

[css-backgrounds] computed background-position-*

---

css-color-4/Overview.bs

No change to the actual content, just align the end of the HTML comments. Currently, only the first 2 are aligned, despite having different lengths; the alternative would be to not align any of the comment ends, to be consistent with a single space before `*/`

[css-color-4] Align color example comments

---

resize-observer-1/Overview.bs

Minutes: https://github.com/w3c/csswg-drafts/issues/3554#issuecomment-540086408
Authors need a way to get the content box size in integral physical pixels. This allows for the correct sizing of the backing store of a canvas to match the snapped CSS size and prevents moire patterns that arise when the sizes are mismatched. 
Currently authors could use devicePixelRatio and rounding in order to approximate this, but due to implementation differences in pixel snapping, can still get the wrong answer. Additionally, this can be affected by position changes which authors cannot currently hook into in a reasonable manner.

Add support for device-pixel-content-box-size #3554 

---

resize-observer-1/Overview.bs

Minutes: https://github.com/w3c/csswg-drafts/issues/3673#issuecomment-467221565
The working group resolution was to have the ResizeObserverEntry box size properties return sequences instead of a single value, to better support fragments. This change modifies the idl accordingly and adds some explanation of why this is, and updates algorithms/references to the properties to be aware of the sequence

[resize-observer-1] ResizeObserverEntry properties future proofing for fragment support #3673

---

css-transforms-2/Overview.bs
css-transforms-2/examples/3d-intersection.html

This changes the 3d rendering model to be closer to the old TR (and blink/gecko's implementation), where transform-style:preserve-3d is what establishes/extends a rendering context, rather than flat.
It also makes transform-style:preserve use parent elements instead of containing blocks (or stacking contexts) to resolve handling of overflow:hidden (which is neither).

[css-transforms-2] Revert to the TR rendering model, where transform-style:preserve-3d establishes the 3d rendering context. #1950

---

resize-observer-1/Overview.bs

Link to minutes: https://github.com/w3c/csswg-drafts/issues/3946#issuecomment-550567232
The ResizeObserverEntry constructor should not be exposed to JavaScript. However, it is still useful to have around as a concept for the `broadcast active observations` algorithm

[resize-observer-1] Remove JavaScript constructor for ResizeObserverEntry #3946

---

css-counter-styles-3/Overview.bs

Change `cjk-earthly-branch` and `cjk-heavenly-stem` from `alphabetic` to `fixed`, per https://www.w3.org/2019/12/06-clreq-minutes.html#x03
Fix #2096.

[css-counter-styles-3] Change cjk-earthly-branch and cjk-heavenly-stem

---

css-scroll-anchoring-1/Overview.bs

Chromium has, since launch of the scroll anchoring feature, had a suppression trigger when
scroll offset becomes zero. We should just add it to the spec.
One reason to do so is that scroll offset zero is a conceptual stable point that can be observed by the user, and therefore should be maintained. It is also common to trigger feature such as pull-to-refresh based on zero scroll offset.
A third reason is web compatibility. An example bug related to this in which Firefox currently differs from Chromiu is [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1022615). Others were found during the pre-launch testing of scroll anchoring for Chromium.

[scroll-anchoring-1] Add a scroll anchoring suppression trigger for zero scroll offset

---

css-scroll-anchoring-1/Overview.bs

[scroll-anchoring-1] Allow anchor nodes to be any non-atomic inline box

---

resize-observer-1/Overview.bs

This IDL is non-normative and is excluded by class="exclude":
https://github.com/tidoust/reffy/blob/d886aca8457f85bd7c89c9daf855d27def0d635d/src/cli/extract-webidl.js#L148

[resize-observer] exclude ResizeObservation IDL from Reffy

---

css-scroll-anchoring-1/Overview.bs

Reverts w3c/csswg-drafts#4681
I don't think we want this after all. On change of overflow-anchor, a layout has not actually occurred, and we just need to re-compute the anchor, not suppress the whole action for the next
layout.
css/css-scroll-anchoring/subtree-exclusion.html is such a case, that would break otherwise.

Revert "[scroll-anchor-1] Add scroll-anchor suppression trigger for overflow-anchor"

---

mediaqueries-5/Overview.bs

Content pulled from discussion within #2370

[css-mediaqueries] Add 'prefers-reduced-data' (addresses #2370)

---

css-animations-2/Overview.bs
css-transitions-2/Overview.bs
web-animations-1/Overview.bs

Fixup of #4437 addressing #4301.
* Add pseudoElement option to KeyframeEffect constructor body
* Fix #4502 adding catch-all pseudo-element case to composite order
* Fix #4586 adding error handling to KeyframeEffect.pseudoElement
* Fix #4701 making note of case when property values cannot be calculated

[web-animations-1] Resolve remaining issues missed in pseudo-element change.

---

selectors-4/Overview.bs

Remove the notion of the Live and Snapshot Profiles and mark `:has()` as "at risk" and "optional", according [to the resolution](https://github.com/w3c/csswg-drafts/issues/3925#issuecomment-492724267) to #3925 (https://lists.w3.org/Archives/Public/www-style/2019May/0008.html)

[selectors-4] Mark :has() as at risk and optional, remove profile (solves #3925)

---

css-color-5/Overview.bs

[css-color-5] Change examples to commaless form
See https://drafts.csswg.org/css-color-4/#changes-from-20160705:
> Describe previous, comma-using color syntaxes as "legacy"; change examples to commaless form

[css-color-5] change examples to comma-less form

---

selectors-4/Overview.bs

[selectors-4] Add the `:defined` pseudo-class as discussed in #2258. 
The original definition has been moved verbatim from the html spec and a note and examples added. PR to remove the [definition from the html spec from WHATWG](https://github.com/whatwg/html/pull/4433).
A test for this definition has previously been submitted: https://github.com/ewilligers/web-platform-tests/commit/92a561a3121a1831214a7b9f47931904ae3df5e7
Worked on with @zcorpan and @isaacdurazo.

[selectors-4] Add :defined pseudo-class

---

css-fonts-4/Overview.bs

The properties were removed in https://github.com/w3c/csswg-drafts/commit/ebca02f2de74aadd45f675ed794cd686a2852d87.

[css-fonts-4] Clean up `font-min-size` and `font-max-size`

---

scroll-animations-1/Overview.bs

Removed fill from ScrollTimeline in favor of returning Infinity values for before start and after end states of the timeline.
Also fixed edit link by correcting shortname. 
Related Issues:
https://github.com/w3c/csswg-drafts/issues/2066 (Discussion for change)
https://github.com/w3c/csswg-drafts/issues/4347 (Solved by this change)

[scroll-animations-1] Removed fill from ScrollTimeline

---

css-scroll-snap-1/Overview.bs

The [scrollport](https://www.w3.org/TR/css-overflow-3/#scrollport) refers to the visual viewport. Add clarification that the scroll-padding property is relative to the layout viewport when the scroll container is the root scroller.
Fixes #4393.

[css-scroll-snap] Clarify scroll-padding scrollport (#4393)

---

css-color-adjust-1/Overview.bs

This addresses issue #3855.
The resolution was to no longer adjust colors for SVG `<text>` elements in forced colors mode by default.

[css-color-adjust-1] Don't force colors on SVG text by default #3855

---

css-text-3/Overview.bs

Just a minor update, it seems to me like the word "element" is missing from the sentence:
> [...] the rules for determining the content language of an HTML are defined in [...]

[css-text-3] Adding missing word "element"

---

css-scrollbars-1/Overview.bs

Both to visually differentiate them from surrounding text and to make them actual links once rendered/processed.
Loosely related to #3315

[css-scrollbars-1] Make mentions of properties/values actual references #3315

---

css-gcpm-3/Overview.bs

There was a mismatch between the markup and the CSS in example 14. There is still ongoing discussion of this example in #3524

[css-gcpm-3] fix CSS errors in example 14

---

css-gcpm-3/Overview.bs

This addresses #3524 by adding break-before properties to examples 13 and 14, thus triggering the creation of page groups.

[css-gcpm-3] add break-before properties to examples 13 and 14 per #3524

---

resize-observer-1/Overview.bs

w3c/csswg-drafts#4683
Previous change to add support for per-fragment box sizes used invalid webidl, namely that attributes of sequence<T> are disallowed so that authors can never be confused about the liveness of the returned value.
Switch these to FrozenArray instead.

[resize-observer-1] attributes cannot be sequence<T> #4683

---

css-animations-2/Overview.bs

css-animations-2 makes clear that returning web-animations objects may
require pending style changes but we also test that reading animation
state also requires pending style flushing.
For example:
https://github.com/web-platform-tests/wpt/blob/master/css/css-animations/CSSAnimation-playState.tentative.html#L43

[css-animations-2] Document attributes of web animations can require pending style changes

---

web-animations-1/Overview.bs

Since `TypeError` is not a valid DOMException error name, change it to `SyntaxError` (the code for this kind of type error).

[web-animations-1] Fix invalid error code for KeyfameEffect.pseudoElement

---

css-values-3/Overview.bs
css-values-4/Overview.bs

Add editorial note to resolve #3696 by noting that for HTML docs, base is mutable.
See also [discussion in tag review of json-ld](https://github.com/w3ctag/design-reviews/issues/312)

[css-values] resolve #3696

---

css-transforms-1/Overview.bs

`wsp*` is already a prefix of `comma-wsp` and thus is useless here
Non-substantive change

[css-transforms-1] Fix typo and simplify transforms syntax

---

css2/about.html
css2/about.src
css2/aural.html
css2/aural.src
css2/cascade.src
css2/conform.html
css2/conform.src
css2/cover.html
css2/generate.src
css2/intro.html
css2/intro.src
css2/media.html
css2/media.src
css2/refs.html
css2/refs.src
css2/sample.html
css2/sample.src
css2/selector.html
css2/selector.src
css2/syndata.html
css2/syndata.src
css2/visuren.html
css2/visuren.src

Fixes #4837 (renaming refs to match what specref knows about, with the exception of `[[CSS20]]`) and a couple of other minor issues.

[CSS2] bunch of reference changes

---

.github/ISSUE_TEMPLATE

Add some more guidance for new contributors, who might not understand what the spec shortnames are.

[meta] Update ISSUE_TEMPLATE to explain spec shortnames

---

mediaqueries-4/Overview.bs

As resolved in issue #4471 I have added in:
```
video-color-gamut
video-dynamic-range
video-width
video-height
video-resolution
dynamic-range
```
And a brief description of the issue along with normative text of when to answer differently between a single or bi-plane scenario.
Specific to dynamic-range we placed a general definition there and are interested in thoughts since standard & high may fluctuate over time but I'd expect the spec text too as well.

Adding of video-* properties and dynamic-range to handle bi-plane scenarios

---

css-ruby-1/Overview.bs

A series of commits (best reviewed one by one) to clean up the spec, get rid of bikeshed errors, get consistent source code formatting, and other editorial tweaks to make it easy to work with.
Contains no normative change.

Ruby cleanup

---

css-page-3/Overview.bs

Per the resolution in #4491, here's proposed text to define page-orientation.
I stuck with the name "rotate-left" and "rotate-right" from the resolution, and chose "upright" as the initial value, following 'text-orientation', per @fantasai's suggestion in the later issue comment.
I decided not to copy 'text-orientation' more fully, because the values there don't seem to reasonably apply to this situation.  I also didn't copy 'image-orientation' at all; its values seemed clumsier, and in general it's probably not important to match with a deprecated property. ^_^

[css-page] Add page-orientation descriptor. Fixes #4491.

---

scroll-animations-1/Overview.bs

Make improvements to CSS syntax based on previous CSSWG discussions. 
This addresses issue #4338 .
Introduce @timeline at-rule. The rule is used to specify parameters for scroll timeline (but can later
be used for regular timelines as well).
The animation-timeline property would select the appropriate at-rule based on its name.
I have also added language to allow existing `animation-name` property to be used for this as well. This will improve ergonomics IMO. But I can drop this part and have it as a separate PR if there is concern.
This addresses  #4336 
Use shorter names for properties:
- startScrollOffset -> start
- endScrollOffset -> end
- scrollSource -> source (optional)
Minor changes to avoid bikeshed WARNING:
- disambiguate reference to rAF
- Reference layout cycle

[scroll-animations] Update scroll timeline css syntax and properties (#4338, #4336)

---

css-color-4/Overview.bs

It said:
color(display-p3 0.43313, 0.50108, 0.37950);
That should have been:
color(display-p3 0.43313 0.50108 0.37950);

Fix typo in color() syntax example

---

css-color-4/Overview.bs

A previous reformat introduced an error.

[css-color-4] Fix rec2020 white chromaticity.

---

cssom-1/Overview.bs

[cssom] CSSStyleDeclaration.cssText should return the empty string for computed style.

---

cssom-1/Overview.bs

Closes #1316. #4947 for the ordering issue.

[cssom] Include custom properties in getComputedStyle().

---

web-animations-1/Overview.bs

Initializing start time of scroll animations to zero is required to have animation effect progress in sync with the timeline progress.
Changes made:
* Removed responding to a newly inactive timeline section (#2080).
* Updated playing/pausing animation procedures to initialize start time to zero for finite timelines. This makes animation current time equal to scroll timeline current time or unresolved if the timeline is inactive.
* Updated pausing animation procedure to execute animation pending pause task when inactive timeline becomes active. This makes ready time resolved at the time of the execution and, as a result, produces resolved hold_time.
* Updated definition of idle play state to include check for unresolved start time. This is required so
playing animations attached to …

[web-animations-1] Initialize start time of scroll animations to zero (#2075)

---

css-ruby-1/Overview.bs

[css-ruby] size and position empty rbc/rtc

---

css-backgrounds-3/Overview.bs
css-box-3/Overview.bs
css-box-4/Overview.bs
css-logical-1/Overview.bs

This updates the definitions of the various margin/border/padding properties to clarify that they do not apply to ruby base containers nor to ruby annotation containers, as resolved in https://github.com/w3c/csswg-drafts/issues/4937#issuecomment-614153466
For css-box-3 and css-backgrounds-3, this is marked at risk, since they are more mature than css-ruby and may need to move along the REC track before it does.
For css-logical, there's no need to be explicit, and thus no need to mark at-risk: tying the applicability of the logical longhands to that of the physical ones deals with it without introducing tight coupling.

[css-box][css-backgrounds][css-logical] Applicability of M/B/P on ruby

---

cssom-1/Overview.bs

[TreatNullAs=EmptyString] → [LegacyNullToEmptyString], per https://github.com/heycam/webidl/pull/870.
---
This should not be merged until that PR is merged, and then given a day to reach the link databases.

[cssom-1] Follow Web IDL extended attribute changes

---

css-pseudo-4/Overview.bs

active-selection-063.html
grammar-error-001.html
selection-text-shadow-006-manual.html
selection-text-shadow-016.html
spelling-error-001.html
spelling-error-002-manual.html
spelling-error-003-manual.html
textpath-selection-011.html

[css-pseudo-4] Edited links to 8 tests in Overview.bs

---

css-values-3/Overview.bs

The following 4 tests are no longer in the repository. So, I removed the links about them in the Overview.bs file:
FATAL ERROR: Couldn't find WPT test 'css/css-values/ch-unit-013.html'
FATAL ERROR: Couldn't find WPT test 'css/css-values/ch-unit-014.html'
FATAL ERROR: Couldn't find WPT test 'css/css-values/ch-unit-015.html'
FATAL ERROR: Couldn't find WPT test 'css/css-values/ch-unit-018.html'
FATAL ERROR: Couldn't find WPT test 'css/css-values/vh-support-atviewport.html'
See
https://github.com/w3c/csswg-drafts/issues/4766#issuecomment-585405189
for, about the vh-support-atviewport.html test

[css-values-3] Removed links to 4 inexistent tests

---

css2/Makefile

(will merge this fairly quickly in the absence of objections)
@plinss I'm assuming moving the built spec to `dist` would necessitate co-ordinating with you? or would adding something using mod_rewrite to the .htaccess file suffice? it would be quite nice to have all the built artefacts in a single directory of their own!

[CSS2] Move more intermediate build products into build/

---

css-text-decor-4/Overview.bs

Given that there is not a single canonical algorithm for determining the boundaries of script runs in arbitrary text, and given that some implementor want to retain the freedom to make adjustments based on user feedback, I don't think we can or should currently specify precise, normative requirements for how `text-decoration-skip-ink` behaves down to the level of every individual character.
However, the spec could usefully include a (non-normative) note to offer guidance to implementors. Here is some proposed text for consideration by the editors.

Add note re scripts to text-decoration-skip-ink

---

web-animations-1/Overview.bs

Fixes #5013 
The options dictionary in `Element.animate` now has an optional nullable timeline
member. This allows timeline to be set via that method in addition to Animation
constructor.
Here are some examples of how this may be used:
```
// Create animation with a null timeline.
div.animate({color: 'red' }, { duration: 1000, timeline: null});
```
```
// Create a scroll-linked animation.
div.animate({color: 'red' }, { duration: 1000, timeline: new ScrollTimeline()});
```

[web-animations-1] Add timeline to animate() options (#5013)

---

css-scroll-anchoring-1/Overview.bs

The PR adds scroll anchoring priority candidates which would be used before the DOM order children are considered as scroll anchors.
#5018

[css-scroll-anchoring-1] Add priority candidates for scroll anchor selection #5018

---

resize-observer-1/Overview.bs

Change the box size calculation algorithm for svg elements when observed box is "device-pixel-content-box" to return the bounding box in integral device pixels.
See [#5014](https://github.com/w3c/csswg-drafts/issues/5014)

[resize-observer-1] device-pixel-content-box should be in integral device pixels for SVG #5014

---

css-pseudo-4/Overview.bs

[css-pseudo-4] 
Added `<wpt>` links to
cascade-highlight-001.html
cascade-highlight-002.html
cascade-highlight-004.html
highlight-z-index-001.html
highlight-z-index-002.html
tests and edited CSS2.1§E.2 link

Bikeshed-added 5 tests and improved 1 inter-spec link

---

mediaqueries-4/Overview.bs

This is an attempt to rewrite the section of media-queries that defines and uses brightness and contrast ratio.
I think this makes the intent clearer, removes ambiguities, while keeping the details of the implementation up to user agents as intended.
This corresponds to the "For section 6.6 …" bullet point of https://github.com/w3c/csswg-drafts/pull/4678#issuecomment-610725135.
Review from @svgeesus, @gregwhitworth, @vi-dot-cpp, or @gregwfreedman very much appreciated.

Editorial rewrite of HDR text

---

web-animations-1/Overview.bs

[web-animations-1] There is no `iterationCount` property but there is an `iterations` property. Fix some non-normative text to use the correct property name. This addresses issue #5096.

[web-animations-1] Non-normative mention of "iterationCount" instead of "iterations"

---

css-tables-3/debug.log

It was presumably a mistake to add this file to the repository.
The following may be useful to a reviewer:
$ git log -p master -- css-tables-3/debug.log
commit 3ebc8f4adc79064ec074aa1bbb90978eb0d863ae
Author: François REMY <email>
Date:   Tue Jun 20 16:02:35 2017 -0700
Fix #1025 (colgroup's widths only apply on its columns if their width is auto)
diff --git a/css-tables-3/debug.log b/css-tables-3/debug.log
new file mode 100644
index 000000000..5ae48beca
--- /dev/null
+++ b/css-tables-3/debug.log
@@ -0,0 +1,2 @@
+[0224/101633:ERROR:tcp_listen_socket.cc(76)] Could not bind socket to 127.0.0.1:6004
+[0224/101633:ERROR:node_debugger.cc(86)] Cannot start debugger server

[css-tables-3] Remove file "debug.log"

---

css-speech-1/Overview.bs

[css-speech] fix the level and ED/TR links

---

web-animations-1/Overview.bs

#4842 is missing updates required to handle reverse() API and re-playing finished animations:
- If scroll animation is reversed and start time is set as part of play animation procedure, pending playback rate needs to be applied to ensure correct current time calculation while the animation is in pending state.
- When re-playing finished scroll animation hold_time needs to be set to unresolved to ensure start_time stays resolved.

[web-animations-1] Fixed play animation procedure for scroll animations  (#2075)

---

css-contain-1/Overview.bs
css-contain-2/Overview.bs
css-overflow-3/Overview.bs

Follow-up / rephrasing of #4934. See https://github.com/w3c/csswg-drafts/issues/4934#issuecomment-635800118 for rationale.

[css-overflow][css-contain] define and use overflow clip edge

---

css-speech-1/Overview.bs

Since the `speech` media type has now also been deprecated (see https://github.com/w3c/csswg-drafts/issues/1751#event-3381393863), this clarifies that the CSS properties defined for CSS Speech Module apply to all media types, and that they cannot be scoped in the way that was described

[css-speech-1] Rephrase background information about media types

---

scroll-animations-1/Overview.bs
scroll-animations-1/img/example-element-based.svg

Add basic definition for Element-based offsets
Major changes:
* Introduce concept of "scroll timeline offset" that can be container-based (existing concept) and element-based (new concept).
* Add IDL for the new offset type and use it.
* Define the process for each offset type to be resolved into an effective scroll offset.
* Update current time calculation to resolve offsets and use the effective values.
* Add basic diagram to show the behavior visually for a simple example
Minor changes:
* Rewrap lines to fit in 80 chars
* Trim end-of-line whitespace
* Clarify some definitions
TODO (as follow ups):
- Define threshold for element-based offset.
- Add css syntax for element-based offsets.
- Add more examples

[scroll-animations-1] Add Element-based offset (#4337)

---

css-animations-2/Overview.bs
scroll-animations-1/Overview.bs
web-animations-1/Overview.bs

Move `animation-timeline` property definition from scroll-animations into css-animations-2.
Similarly move changes to `animation` shorthand.
As part of this move, for now we drop the logic to reuse animation-name value for animation-timeline. I was not sure if it is clear enough and wanted to keep this PR simple.
I think that is something we can come back to later. For now I left a note/issue in the spec that explains the improvement in ergonomics that it can provide.

[scroll-animations] Move animation-timeline to css-animations-2 (#5159)

---

scroll-animations-1/Overview.bs
scroll-animations-1/img/example-element-based-threshold.svg
scroll-animations-1/img/example-element-based.svg

Add threshold to element-based offset.
This builds on top of PR #5124. Though I have not found out a good way to have one PR depend on another in-flight PR yet.

[scroll-animations-1] Add threshold to element based (#5124)

---

css-contain-2/Overview.bs

This changes "woudln't" to "wouldn't" in an example.

[css-contain-2] Fix one letter typo

---

css-inline-3/Overview.bs

Closes #3411
See issue for discussion/reasoning & differences from SVG 1.
Bikeshed error that needs fixing:
the “current text position” definition from SVG text
is not being exported in a way that Bikeshed is picking up,
even with hints about which spec to look for it in.
(@TabAtkins, can I fix this here, or do I need to add some attributes to the SVG spec?)
Changes should be copied over to css-inline-4 after review.

[css-inline-3] Extend “applies to” for SVG text

---

scroll-animations-1/Overview.bs

This seems like an oversight from https://github.com/w3c/csswg-drafts/pull/5124 ?

[scroll-animations-1] Update ScrollTimeline.start/end types

---

biblio.ref

This update adjusts the URLs of the entries for CSS Backgrounds and Borders Module Level 4 and CSS Pagination Templates Module Level 3, so that they target the final document directly; and refreshes the list of authors for CSS Backgrounds and Borders Module Level 4.

[biblio.ref] Update URLs of css-backgrounds-4 and css-page-template-1

---

scroll-animations-1/Overview.bs

For now, that is.
Fixes #5167.

[scroll-animations] Ignore @scroll-timeline rules in shadow trees

---

css-inline-3/Overview.bs
css-writing-modes-3/Overview.bs
css-writing-modes-4/Overview.bs

The rendering in the example shows the Gurmukhi character ji (ਜੀ)
but the source code had "ji" in latin alphabet, which would not result
in the expected rendering. This commit makes the source match the
rendering.
See https://en.wikipedia.org/wiki/Gurmukhi
and https://r12a.github.io/pickers/gurmukhi/

[css-writing-modes] Fix source to match rendering in example

---

scroll-animations-1/Overview.bs
web-animations-1/Overview.bs

I added section describing how scroll timeline phase is calculated. Inclusive end exception that was removed in a previous PR has been added back in through the phase calculation (an explanatory note for the exception has been included). 
I also reformatted the section for calculating current time to match the new phase calculation formatting.

[scroll-animations-1][web-animations-1] Added phase calculation for ScrollTimeline #4325

---

css-color-adjust-1/Overview.bs

This addresses issues #4916 and #4917.
This change removes the `background-image` special-casing for input controls and adds logic to revert non-URL background images in Forced Colors Mode.

[css-color-adjust-1] Revert non-URL background images in Forced Colors Mode

---

scroll-animations-1/Overview.bs

Fixing #5202 and #5211 
Changes:
- Fix IDL to make source nullable.
- In CSS source will accept 'auto' and 'none' with none
mapping to null.
- In JS, we now map missing 'source' to document scrolling element
(i.e., auto behavior) and explicitly null 'source' to null.
- Correctly check null source when calculating offsets.
Other minor cleanups.

[scroll-animations] let source be explicitly nullable (#5202, #5211)

---

scroll-animations-1/Overview.bs

Add css syntax to for element-based offsets. Fixes #4337.
The element-based syntax is simply applied when the value starts with  `selector(#id)` with the following characteristics: 
- `<<id-selector>>` is required and is expected to be the first value.
- both edge and threshold are optional can can be provided in any order.
I followed some of the ideas mentioned by @tabatkins in #4348 to to get to a more ergonomic  css function syntax.  In particular there is no comma and the optional params can be in any order. Note that unlike  #4348 we are not adding a function syntax.

[scroll-animations] Add css syntax for element-based offset 

---

scroll-animations-1/Overview.bs

Use appropriate CSSTypedOM instead of DOMStrings in the API. Fixes #5213.
Changes:
- For offsets use `CSSNumericValue` or `CSSKeywordish` instead of DOMString
- When setting the offset, the grammars for these values is check to ensure only the valid subset can be set.
- When computing effective scroll offset check the offset actual type and interpret it accordingly
- Update examples to showcase the API and add noted to clarify the usage.

[scroll-animations-1] Use CSSTypedOM instead of strings (#5213)

---

web-animations-1/Overview.bs

When it comes to the term "computed value", the spec is currently
very confused. It appears to be making several references to
"the" computed value (as in [1]), when in reality the intention is
(I believe) to apply the *process* that calculates the computed
value ([1]) to the value specified (locally) in the keyframe. This
process is not described in a reusable way anywhere (I think), so I've
added the algorithm "compute a property value" for this. I'm using
the term "property value", since it's already extensively used in this
spec. Possibly it would be more suited for css-cascade, but I'm
proposing it for this spec until we need it somewhere else.
In general I want to maintain a clear distinction between when we
mean the actual computed value [1], and when we mean some value that
has …

[web-animations-1] Specify how to compute property values

---

css2/Overview.bs

This avoids referencing the obsolete RFC2616.
Should we be marking this section as informative? It doesn't seem to have any conformance criteria beyond what RFC2318 itself gives. I guess we could have something such as "When encoding a style sheet as a message entity [[!RFC2015]] or an HTTP message [[!RFC7231]], an author must use the text/css media type. When a UA receives a message entity or an HTTP message with a media type of text/css, it must process it as a CSS style sheet."?

[CSS2] simplify reference to RFC2318

---

css-color-5/Overview.bs

This makes a few adjustments to the definitions of hue interpolation
types to follow up on the discussions in #4735.
First, it adjusts the pseudo-code so that for 'shorter' and 'longer',
angles that differ by 180 degrees will always go in the decreasing
direction, as described in
https://github.com/w3c/csswg-drafts/issues/4735#issuecomment-650254063
Second, it adjusts the set notation to match the pseudo-code.  (They
were not matching even prior to this change.)  The set notation
previously seemed to assume that there were absolute-value functions
present that were not actually there.  However, given the asymmetry of
always going in the decreasing direction, it's more correct to write it
without absolute values.

[css-color-5] Adjustments to edge cases and set notation for hue interpolation types

---

css-namespaces-3/Overview.bs

[css-namespaces-3] This replaces the CSS 2.1 syntax used to define the `@namespace` rule by the newer [CSS Syntax 3](https://drafts.csswg.org/css-syntax-3/) rules used in other specs.

Defined @namespace using CSS syntax (fixes #649)

---

css-fonts-4/Overview.bs

This echoes what's already described in prose in the notes: https://drafts.csswg.org/css-fonts-4/#font-weight-numeric-values
The reason why I'd like this change is that I'm working on a fuzz testing tool that uses these grammars to generate valid CSS, via https://github.com/mdn/data/ -- see https://github.com/mdn/data/pull/420

[css-fonts-4] Add range specifying that font-weight-absolute must be >= 1 and <= 1000

---

css-animations-2/Overview.bs
web-animations-1/Overview.bs

In css-animations-2, instead of generating keyframes resembling
computed keyframes, generate specified keyframes. Computing the
keyframes at keyframe-creation-time creates too many questions
regarding when/how property values inside the keyframes are computed.
We can instead rely on the existing process for calculating computed
keyframes, and apply that process at the time getKeyframes is called.
This means that var() references (and dependencies in general, such
as 'em' units) remain until computed-keyframe-time.
This isn't a problem for shorthand expansion at keyframe-creation-time:
if there's a var() in a shorthand, it expands using the "pending
substitution value" [1] for its longhands.
We can continue to resolve logical properties to physical at keyframe-
creation-time as well, …

[css + web-animations] Handle getKeyframes for CSSAnimations

---

css-syntax-3/Overview.bs

This changes various sentences in the css-syntax in order to improve the readability of the specification.
- This fixes a grammatical error in 1 description. (f32266a1a)
- This improves consistency in 2 descriptions by changing non-possessives to possessives. (f32266a1a, 6ca6cc82d)
- This improves consistency in 1 description by changing a specific article to a non-specific article. (3adc0363a)
- This improves terminology by linking a cross-referenced term in 4 descriptions. (306eaf0c2)
---
The “**_Consume a simple block_**” section reads (with emphasis added):
> Create a simple block with its associated token set to the current input token and **with a value with is** initially an empty list.
The second half of this sentence has a typo where it reads “_with a value with is_”, while the …

[css-syntax-3] Improvements to grammar, possessives, perspectives, and links

---

css-variables-1/Overview.bs

Animatable:no would suggest that custom properties are not processed
at all if they appear in keyframes. Use 'discrete' animation type
instead.

[css-variables] Use discrete animation type

---

css-syntax-3/Overview.bs

This updates the label of a reference to the **identifier-start code point** definition in the CSS Syntax specification.
The **identifier code point** definition contains a potentially mislabeled [reference to a “_**name-start** code point_”](https://drafts.csswg.org/date/2020-07-22T16:50:27/css-syntax-3/#identifier-code-point):
> **identifier code point**
> A name-start code point, a digit, or U+002D HYPHEN-MINUS (-).
In that definition, “_name-start code point_” links to the **identifier code point** definition.
I believe it should be relabeled to “_identifier-start code point_”:
> **identifier code point**
> An identifier-start code point, a digit, or U+002D HYPHEN-MINUS (-).

[css-syntax-3] Reference identifier-start instead of name-start

---

css-values-4/Overview.bs

I found a small mistake in [the Combination of `<integer>`](https://www.w3.org/TR/css-values-4/#combine-integers) section, where Addition of `<number>` is mistakenly defined instead of` <integer>`.
This PR fixes it.

[css-values-4] Fix <<number>> to <<integer>> in Combination of <integer> section

---

web-animations-1/Overview.bs
web-animations-2/Overview.bs

Related issue: https://github.com/w3c/csswg-drafts/issues/5401
This change moves mutable timelines back to web-animations-1. The procedure for setting the timeline was already in web-animations-1; however, the mutability of the timeline was moved to v2 of the spec. We are now close to supporting mutable timelines across browsers (albeit behind feature flags).

[web-animations-1][web-animations-2] Move mutable timeline back to web-animations-1

---

css-fonts-3/Fonts.src.html
css-fonts-3/Overview-wip.bs

I was arguing with our tech writer whether it should be "a @​font-face" (silent '@') or "a**n** @​font-face" (pronounced '@'). The spec was inconsistent, but generally favored "a**n** @​font-face". I have changed the remaining occurrences to "an".

[css-fonts-3] Consistent article "an" for `@font-face`

---

css-cascade-3/Overview.bs
css-cascade-4/Overview.bs

This change also modifies the mention of @charset as an example of an at-rule with restrictions on its relative ordering to replace it with@namespace, since @charset is no longer considered an at-rule.

[css-cascade] Clarify how @import behaves with invalid rules  #5313

---

css-contain-2/Overview.bs

When a new content-visibility: auto element is added, the check to determine
its visibility needs to occur in the same frame to avoid a flash of blank content.
This PR adds a clarification to this effect.

[css-contain-2] Specify that the first content-visibility: auto visibility check happens immediately

---

cssom-1/Overview.bs

Either the word "integer" was missing from most of these steps, or it was accidentally added in one step. ~~This patch assumes the former.~~

[cssom-1] Improve accuracy of <color> serialization

---

css-flexbox-1/Overview.bs

https://github.com/w3c/csswg-drafts/blob/e2399816bd8f945d62d914597737d3e251ffc9a9/css-flexbox-1/Overview.bs#L976
The spec refers to https://drafts.csswg.org/css-flexbox/#specified-size-suggestion
But currently it's linking to https://drafts.csswg.org/css-images-3/#specified-size

[css-flexbox-1] Typo: s/specified size/specified size suggestion/

---

css-fonts-4/Overview.bs

Following the [resolution](https://github.com/w3c/csswg-drafts/issues/4792#issuecomment-693528301), this patch adds the following @font-face descriptors to CSS Fonts Level 4:
- `ascent-override: normal | <percentage>`
- `descent-override: normal | <percentage>`
- `line-gap-override: normal | <percentage>`

Add @font-face descriptors for overriding font metrics

---

cssom-1/Overview.bs

closes #5513 as per resolution from the minutes there documenting reality of what is shipping.
Previously MathML elements didn't specify IDL, but now they do and are widely shipping - Lots of tests in https://wpt.fyi/results/mathml/relations?label=experimental&label=master&aligned make use of this.

https://wpt.fyi/results/mathml/relations?label=experimental&label=master&aligned

---

css-display-3/Overview.bs

I think this link to the definition of inline block would be helpful because inline blocks are not defined [in the glossary](https://drafts.csswg.org/css-display/#glossary) with the other box types.  Inline blocks are instead only defined as an alias to inline boxes [here in the generated box table](https://drafts.csswg.org/css-display/#inline-block), which one might miss when reading the paragraph in this diff.

[css-display-3] Link to definition of inline block

---

css-color-adjust-1/Overview.bs

Per resolution: https://github.com/w3c/csswg-drafts/issues/3846#issuecomment-648923121.
Add a reference to the HTML specification from the specification of the color-scheme property.
HTML pull request: https://github.com/whatwg/html/pull/5938

[css-color-adjust-1] Move color-scheme meta to HTML #3846

---

css-font-loading-3/Overview.bs

[css-font-loading-3] Add override attributes to FontFace interface following resolution in https://github.com/w3c/csswg-drafts/issues/4792#issuecomment-693528301

[css-font-loading-3] Add override attributes to FontFace interface following resolution in #4792

---

mediaqueries-5/Overview.bs

This editorial reorganization of the text is intended to make the
overlap between forced-colors:active and prefers-contrast:forced
more readily understandable: one being the syntax that the CSS Working
Group finds more desirable, the other being retained for compatibility
with content issued against an earlier draft (see #3856).
Prior to this refactoring, the definition of this mode was also spread
between the two media features, causing confusion. This commits
consolidates the whole thing in one place.
Related to #5433

Refactoring of the forced-colors and prefers-contrast media feature

---

css-cascade-3/Overview.bs

Editorial proposal to follow up on https://github.com/w3c/csswg-drafts/issues/1861#issuecomment-691751716, leaving that issue closed because this is tangential to the main point of that issue.

[css-cascade] Editorial: clarify "does not apply"

---

css-grid-2/Overview.bs

[css-grid-2] Editorial: Corrected `subgid` to `subgrid` keyword.
This fixes #5579

Editorial: Replaced 'subgid' by 'subgrid'

---

css-nesting-1/Overview.bs

Added examples with nested `:is` and `:not` and an invalid example. Publishing draft PR, will be adding to it over the next week or so.

[css-nesting] additional examples

---

css-egg-1/Overview.bs

[css-egg-1] Add the `adafish` unit and the `performance` media query
This was first proposed by @toji in https://twitter.com/Tojiro/status/1317298532630499329 , and has rapidly gained the support of the community (me).
cc @AdaRoseCannon
r? @tabatkins  @frivoal

[css-egg-1] Add the `adafish` unit and the `performance` media query

---

css-nesting-1/Overview.bs

[css-nesting-1] 
This PR adds a section on nesting conditionals and provides a small set of examples to get the conversation started.
**Example**
```css
.foo {
display: grid;
@media (orientation: landscape) {
& { 
grid-auto-flow: column; 
}
}
}
/* equivalent to */
.foo { display: grid; }
@media (orientation: landscape) {
.foo { 
grid-auto-flow: column; 
}
}
```
fixes https://github.com/tabatkins/specs/issues/56

[css-nesting-1] initial idea for nested conditionals

---

web-animations-1/Overview.bs
web-animations-2/Overview.bs

https://github.com/w3c/csswg-drafts/issues/5422
Adds the following steps:
* When transitioning to a scroll timeline, start time is updated to synchronize current time with the scroll position.
* When transitioning from a scroll timeline to a document timeline, current time is preserved.

[web-animations-2] Add steps for transitioning to/from a scroll timeline.

---

css-conditional-3/Overview.bs

"after a conditional group rules" is internally inconsistent.

[css-conditional-3] Fix plurality

---

css-scoping-1/Overview.bs

This takes the liberty of also applying the related resolution to `:host-context`, although that's not mentioned in the issue.
Resolves #2158

[css-scoping-1] Let :host/:host-context/::slotted take a single compound

---

scroll-animations-1/Overview.bs

Follow-up to #5263, which specifies that a "missing" source shall
result in using the Document's scrollingElement, but if we give
source a default value of null, it can never be missing.

[scroll-animations-1] Remove default vaule for ScrollTimelineOptions.source

---

css-contain-2/Overview.bs

This is not meant to change the expected behavior, however the original text was not very clearly phrased, hence this rewrite.
This is an attempt to solve #4931, along the lines of the so-called option α of https://github.com/w3c/csswg-drafts/issues/4931#issuecomment-704676915. It is currently written against level 2, but to be back ported to the L1 REC if we like it.
The diff is reasonably hard to read, so for ease of review, here's the resulting new section 3.1: http://files.florian.rivoal.net/css-contain-2/Overview.html#containment-size
Also note the commented out line in the source, which would allow us to let other specs opt into excluding some properties from the *sizing as if empty* phase, in order to do the so-called option β of …

[css-contain-2] Clarify how sizing containment works

---

css-scroll-anchoring-1/Overview.bs

This reduces the scope of the focused area priority candidate to only the elements that permit text entry. Notably, this excludes typical buttons and anchor tags
Also small fix-up to active match to reference the spec.

[css-scroll-anchoring-1] Reduce the scope of focused element

---

resize-observer-1/Overview.bs

This PR makes some small improvements to the example code in the [Resize Observer](https://drafts.csswg.org/resize-observer-1/) introduction:
* Fix spelling
* Reword comment
* Replace var with let
* Code formatting consistency (semicolons, quotes, whitespace)

[resize-observer-1] Improve example code

---

css-color-4/Overview.bs

[css-color-4] Add missing / to close span for ButtonBorder so that the swatch doesn't include the description text.

[css-color-4] Add missing / to close span for ButtonBorder

---

mediaqueries-5/Overview.bs

Non-substantive edit.
In an advisement section on `prefers-contrast`, concerning "forced"...
> This does not necessarily indicates a preference for more contrast.
"indicates" should be "indicate"

[mediaqueries-5] Fix grammar typo in advisment for prefers-contrast:forced 

---

css-cascade-5/Overview.bs

Currently the spec links to the Media Capture and Streams instead of the HTML definition of the audio element

[css-cascade-5] Fix link to audio element

---

css-font-loading-3/Overview.bs

This fixes #5744 by removing the exception-throwing step in the algorithm (that nobody has implemented), and adjusting the related note to reflect this.

[css-font-loading] Remove step 3 from FontFaceSet.check()

---

css-scroll-anchoring-1/Overview.bs

Rationale:
1. This is consistent with all other CSS drafts
2. This saves a redirect

[css-scroll-anchoring-1] Add trailing slash to ED URL

---

css-pseudo-4/Overview.bs

[css-pseudo] Add text for the ::file-selector-button pseudo-element.

---

css-syntax-3/Overview.bs

The CSS Syntax 3 module was missing the links to the CSSOM 1 spec., so I've added them.
Sebastian

[css-syntax-3] Editorial: Linked to CSSOM

---

css-shapes-2/Overview.bs

Add a draw() shape syntax, which accepts shape-segments equivalent to SVG path segments.
Fixes #5674

[css-shapes-2] Add a shape() syntax, which accepts shape-segments equivalent to SVG path

---

css-animations-1/Overview.bs

I was documenting this over at MDN and spotted that the information for `select` in findRule mentioned the "rule to be deleted", I think this should be "found".

[css-animations-1] Updating typo in CSSKeyframesRule.findRule

---

css-color-4/Overview.bs

I noticed a few typos in the example uses of lab(), lch() and color(lab ...) as I was reading through spec.

[css-color-4] Fix typos in examples of lab(), lch() and color(lab ...)

---

css-images-4/Overview.bs

Just two small typo fixes to prose in https://drafts.csswg.org/css-images-4/#image-set-notation

[css-images-4] Fix typos (s/tho/though/, s/It/If/)

---

css-2020/Overview.bs

Since [css-transforms-1] has been a CR since 2019 and is already listed in the Official Definition, it seems unreasonable to keep it among the pre-CR excections in the 2020 snapshot. I assume this is an editorial fix.

[css-2020] Remove css-transforms-1 from pre-CR exclusions

---

selectors-4/Overview.bs

Mergeable when <https://github.com/whatwg/html/pull/6269> merges, and not before.

[selectors-4][editorial] Remove mention of <link> being a :link match

---

css-pseudo-4/Overview.bs

Bikeshed-added links to:
active-selection-001-manual.html
active-selection-002-manual.html
active-selection-004-manual.html
active-selection-011.html
active-selection-012.html
active-selection-014.html
active-selection-016.html
active-selection-018.html
active-selection-021.html
active-selection-025.html
active-selection-027.html
active-selection-031.html
active-selection-041.html
active-selection-043.html
active-selection-045.html
active-selection-051.html
active-selection-052.html
active-selection-053.html
active-selection-054.html
active-selection-056.html
active-selection-057.html
grammar-error-002-manual.html
grammar-error-003-manual.html
highlight-painting-order.html
selection-contenteditable-011.html
selection-input-011.html
selection-intercharacter-011.html …

Bikeshed-added links to 32 tests

---

scroll-animations-1/Overview.bs

Described specification for ScrollTimeline.scrollOffsets API.

[scroll-animations-1] Support for multiple scroll offsets #4912

---

css-grid-3/Overview.bs

Generates out to an invalid anchor value with a double `##`

[css-grid-3] Remove hash from ID

---

css-fonts-4/Overview.bs

Caused it to be output as an HTML element in Bikeshed

[css-fonts-4] Escpape string placeholder

---

css-rhythm-1/Overview.bs

Maybe more of a Bikeshed issue, but was outputing as `<img U0003Cblockquote src="images/line-grid-center.svg" style="height: 300px">` before

[css-rhythm-1] Collapse img for Bikeshed

---

css-flexbox-1/Overview.bs

- Double TBODY
- Spacing causing extra P tag

[css-flexbox-1] Bikeshed errors

---

css-gcpm-3/2009-06-10.html
css-gcpm-3/2009-06-10.src.html
css-writing-modes-3/Overview.bs
css-writing-modes-4/Overview.bs

Could go a few ways as possessive or singular then plural, but I think these are duplicates

typo: Double word elements

---

css-flexbox-1/Overview.bs

The IDs now have language postfixes like `axis-mapping-table-en`, and there is no rowspan value of 8.
This choked up the HTML validator, but that might be a bug there

[css-flexbox-1] Drop styles with no matching ID

---

css-grid-1/Overview.bs

I would specify the height property in example 8 of the Grid Areas chapter for `#grid`. This makes it easy to see the differences between `align-self: start;` and `align-self: end;` for newcomers in that example. Otherwise, it's may not so clear how `align-self: start;` and `align-self: end;` styles work if you try to run this snippet.
[3.3. Grid Areas](https://www.w3.org/TR/css-grid-1/#grid-area-concept)
What do you think?

[css-grid-1] Specify height in example 8 for #grid

---

selectors-4/Overview.bs

[selectors-4] Remove example related to :focus:not(:focus-visible) (#4278)
:focus:not(:focus-visible) is a workaround due to some implementations
not following the spec (not using :focus-visible in the default UA style sheet).
Apart that this is no longer needed as implementations have been updated,
this kind of workarounds shouldn't be in the spec as they're confusing.
Fixes #4278

[selectors-4] Remove example related to :focus:not(:focus-visible) (#4278)

---

css-fonts-4/Overview.bs

- Drop old summary attribute from table
- Trailing paragraphs in OLs
- Nested links

[css-fonts-4] HTML validation from Bikeshed

---

css-transforms-2/Overview.bs

Allow percentages inside the scale functions,
and the scale property.
resolves #3399

[css-transforms] scale function and property %

---

css-rhythm-1/Overview.bs

HTML validation flagging use of figcaption inside of DIVs, so converted them all to actual figure/figcaption. Used height/width attributes instead of styles on the images at the same time.

[css-rhythm-1] figure/figcaption conversion

---

css-highlight-api-1/Overview.bs

The name HighlightRegistry makes more sense for this concept - a place with Highlight objects are registered. It also follows prior art established by CustomElementRegistry.
Closes #5760

[css-highlight-api-1] Rename HighlightsRegister to HighlightRegistry

---

css-grid-1/Overview.bs
css-grid-1/images/grid-order-page.svg
css-grid-2/Overview.bs
css-grid-2/images/grid-order-page.svg

Use `main` as a more suitable element in example 9.
Changes:
- Tweak the SVG image
- Use the `main` element in example 9 for _CSS Grid Layout Module Level
1_ and _CSS Grid Layout Module Level 2_
Before:
After:

[css-grid-1][css-grid-2] Replace article to main

---

css-variables-1/Overview.bs

[css-variables-1] Custom props that are IACVT become guaranteed-invalid

---

css-exclusions-1/Overview.bs

HTML validation flagged the bad `width` values on some DIV based figures. Moved that to `style` and conveted them to figure/figcaption elements

[css-exclusions-1] figure/figcaption and widths

---

css-grid-1/Overview.bs
css-grid-2/Overview.bs

Use the body element because it has used as a grid container in the
example above:
```
body { display: grid;
grid: "h h h"
"a b c"
"f f f";
grid-template-columns: auto 1fr 20%; }
article { grid-area: b; min-width: 12em;     }
nav     { grid-area: a; /* auto min-width */ }
aside   { grid-area: c; min-width: 12em;     }
```
This change makes these examples much more clear.

[css-grid-1][css-grid-2] Use `body` in example 9

---

css-fonts-4/Overview.bs

This change makes the CSS Fonts spec reference the “create a potential-CORS request” algorithm from the HTML spec.
Otherwise, without this change, the CSS Fonts spec references “potentially CORS-enabled fetch”, which is an obsolete algorithm that no longer exists either in the Fetch spec nor in HTML.
---
Related: https://github.com/whatwg/html/pull/6265

[css-fonts-4] Use “create a potential-CORS request”

---

css-color-4/Overview.bs

Currently, it is phrased as if interpolating in any other color space is an exception to Lab. If we're going to be referencing this for `color-mix()` and the like, it needs to be more generic wrt to interpolation space.

[css-color-4] Rephrase interpolation to be more generic wrt to interpolation spac

---

css-tables-3/Overview.bs

This addresses the syntax issue raised in #4275 (which got merged then reverted because `<>` have to be doubled in practice). The goal of the update is to make the definition compliant with the [Value Definition Syntax](https://www.w3.org/TR/css-values-4/#value-defs).

[css-tables-3] Drop zero-width spaces in border-spacing dfn

---

css-highlight-api-1/Overview.bs

[css-highlight-api] Remove redundant add method from HighlightRegistry interface
Since HighlightRegistry is setlike, it gets its add method from the setlike interface. This method just needs to be implemented with some special rules, as defined in the highlight-api spec. We need not define an explicit add method on HighlightRegistry - this is redundant and confusing to read.

[css-highlight-api] Remove redundant add method from HighlightRegistry interface

---

css-ui-4/Overview.bs

Use :focus-visible instead of :focus in the explanation about when UAs paint outlines.

[css-ui] Use :focus-visible instead of :focus

---

css-overflow-3/Overview.bs

Point it to css-ui-3 spec instead of CSS2.

[css-overflow] Update link to outline properties

---

css-highlight-api-1/Overview.bs

[css-highlight-api] Custom highlight overlays should stack below native highlight overlays

---

css-highlight-api-1/Overview.bs

[css-highlight-api] Add comment about the default numerical priority for custom highlights.
[css-highlight-api] Highlight priority attribute should be long instead of double.
[css-highlight-api] Remove text for resolved highlight priority issues.
Resolves #4591 #4592 #4593

[css-highlight-api] Misc highlight priority fixes based on recent resolutions

---

css-transforms-2/Overview.bs

While the premise of #2124 was that this was not already defined, I
believe this is already the straightforward result of the definition in
cssom-1.  Thus this adds a note rather than additional normative text.
Fixes #2124.

[css-transforms-2] Add note that computed value of translate has percentages

---

css-transforms-2/Overview.bs

The group resolved in #3305 that individual transform properties do not
distinguish between values specified using 2D syntax and values
specified using 3D syntax that produce the same matrices.
Fixes the individual transforms part of #3305.
cc @BorisChiou (who isn't in the list of reviewers I can choose from) and also @smfr (who is welcome to review as well, and can let me know if he wants me to wait for his review)

[css-transforms-2] Don't maintain state for whether individual transform property values are 2D or 3D.

---

css-fonts-4/Overview.bs
css-fonts-5/Overview.bs

The prose says what to do if there are exactly 1 or exactly 2 values, but not what to do if there are more. `#` indicates that there can be more.

[css-fonts-5] Don't allow more than 2 values for the font-size @font-face descriptor

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6171

[css-fonts-4] font-stretch should serialize to a number/percentage, not a keyword

---

css-fonts-5/Overview.bs

Edits for the various metrics descriptors. Commit-by-commit review recommended. (It's not separate PRs because they build on each other. Please don't make me submit them one by one, I'll end up tangling all the branches in git...)

[css-fonts-5] Various Edits

---

css-color-5/Overview.bs

According to the Value Definition Syntax, parentheses are to be interpreted as representing their corresponding tokens. For grouping, brackets must be used:
https://drafts.csswg.org/css-values/#value-defs

[css-color-5] Fix definition of color-contrast

---

css-fonts-5/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6128.

[css-fonts-5] The font-size-adjust property is applied after the size-adjust descriptor

---

css-highlight-api-1/Overview.bs

[css-highlight-api-1] Make HighlightRegistry maplike and remove name property from Highlight.
[css-highlight-api-1] Add note recommending authors to use custom highlight names that are CSS identifiers for easier styling via CSS.
[css-highlight-api-1] Add note recommending authors to only use one name to style a highlight and add an example showcasing why using multiple names is problematic.
Resolves #5910

[css-highlight-api-1] Make HighlightRegistry maplike

---

css-grid-1/Overview.bs
css-grid-2/Overview.bs

Set the `min-height` property for the `.grid` class to make
`align-content: center;` work much more clear. `align-content: center;`
has no sense if we run example 39 as it is.
Without `min-height`
With `min-height`

[css-grid-1][css-grid-2] Set min-height for ex 39

---

css-syntax-3/Overview.bs

Fix a description of identifier in non-normative section. https://github.com/w3c/csswg-drafts/issues/5764

[css-syntax-3] Fix description of identifier

---

css-regions-1/Overview.bs

The previously defined members are implicit in the maplike declaration:
https://heycam.github.io/webidl/#es-maplike
Fixes https://github.com/w3c/csswg-drafts/issues/6014.

[css-regions-1] Use maplike declaration for NamedFlowMap

---

css-lists-3/Overview.bs

This allows HTML to define the rendering for `<ol reversed>` in terms
of a presentational hint for `counter-reset: reversed(list-item)`
or `<ol reversed start=X>` to `counter-reset: reversed(list-item) X+1`.
See https://github.com/whatwg/html/pull/4816
Fixes #4181
Fixes #4211

[css-lists] Define reversed counters with automatic initial value

---

css-regions-1/Overview.bs

As an interface mixin, Region can't be used as a type per Web IDL:
https://heycam.github.io/webidl/#idl-types
Fixes https://github.com/w3c/csswg-drafts/issues/5519.

[css-regions] Avoid the use of Region as a return type

---

css-device-adapt-1/Overview.bs

Previously the background-color set inline for the pseudocode block resulted in nearly zero contrast between the text and the background. I feel it is preferable to remove the broken inline style and potentially later add a global style to readd a subtle background to all `pre` code blocks if desired.

[css-device-adapt-1] Visual: Remove inline background-color style breaking dark theme

---

selectors-4/Overview.bs

We resolved to add these [in Toronto in June 2019](https://lists.w3.org/Archives/Public/www-style/2019Jul/0002.html).
This is a first draft; I'm sure the text could use some work before merging.
Fixes #3821.
Fixes #3933.

[selectors-4] Define a number of new pseudo-classes for matching the state of media elements.

---

web-animations-2/Overview.bs

Per WebIDL, a partial dictionary declaration cannot inherit from a base dictionary. See Note in:
https://heycam.github.io/webidl/#idl-interfaces
"Note: A partial interface definition cannot specify that the interface inherits from another interface. Inheritance must be specified on the original interface definition."
`ComputedEffectTiming`, defined in Level 1, already inherits from `EffectTiming`, so no need to formulate that again in the partial definition.

[web-animations-2] Fix WebIDL - no inherit for partial dictionary

---

web-animations-2/Overview.bs

Previous fix made WebIDL parse-able: https://github.com/w3c/csswg-drafts/pull/6267
However, the WebIDL remains invalid because `void` has now been replaced by `undefined` in WebIDL and because optional dictionary parameters with no required members need to have a default value. This update fixes these validity issues.

[web-animations-2] Make WebIDL valid

---

css-conditional-3/Overview.bs

The <general-enclosed> production now just produces "false".
See Issue #6175.

[css-conditional-3] Remove "unknown" value concept

---

css-highlight-api-1/Overview.bs

[css-highlight-api-1] Update examples
Resolves issue #6331:
- Add 'div' variable definition in Example 2.
- Indent Example 1 and 2 like the others (one tab for contents of <style> and <script>).
Resolves issue #6333:
- Define Highlights `h1` and `h2` in Example 4, update the explanation accordingly.
- Change CSS.highlights.add() into CSS.highlights.set() in Example 4.
- Change style rules from p::highlight into ::highlight.

[css-highlight-api-1] Update examples

---

css-color-4/Overview.bs

[css-color-4] change text of MarkText example to match styling

---

css-nesting-1/Overview.bs

[css-nesting-1] fixes #3748
Felt sufficient to demonstrate the result of a BEM style nesting selector, as opposed to a note specifically calling out BEM. The answer is in the examples.

[css-nesting-1] demo the result of BEM style nesting

---

css-text-decor-3/Overview.bs
css-text-decor-4/Overview.bs

The paragraph preceding the example for the text-decoration property in both CSS Text Decoration Module Level 3 and Level 4 says:
> The following example underlines unvisited links with a solid blue underline in CSS1 and CSS2 UAs and a navy dotted underline in CSS3 UAs.
However, the example uses a type selector of `link`. The `link` element is not used for hyperlinks, but instead to link their document to other resources, more typically used in the `<head>` of the document. The `a` element is used for hyperlinks. As a result, the example CSS does not do what is described.
Looking at the history, it looks like the selector was originally `:link` but the colon was mistakenly removed in b32b070, a commit which was intended to only change whitespace.
```diff
@@ -322,12 +326,13 @@ Text …
```

[css-text-decor-3] [css-text-decor-4] Fix incorrect CSS in text-decoration example

---

css-contain-3/Overview.bs

It is simpler to treat *elements* as query containers, and delay
interaction with the layout box until query-evaluation-time.
This makes it possible to answer the question "is this element a
container?" sooner, which is beneficial for implementing the feature.
It also seems to make more sense given that we're going to have
container features that don't really care about the layout box.
Also:
- Require layout containment for dimensional queries.
- Add 'block-size' as part of the computed value.

[css-contain-3] Make the query container an element, ++

---

css-lists-3/Overview.bs

[css-lists] Fix reversed counters to count how many elements increment or set the counter

---

css-ui-4/Overview.bs

A [long time ago](https://github.com/w3c/csswg-drafts/issues/2495#issuecomment-380397331) we resolved to add an `input-security : auto | none` property that only applies to `<input type=password>`. Here's a PR that does this, though not very well.
I'll write a corresponding PR for HTML's Rendering section too.

[css-ui-4] Define the ''input-security'' property. Fixes #2495.

---

cssom-1/Makefile
cssom-1/Overview.bs

[cssom-1] Merge constructable stylesheets into CSSOM (https://lists.w3.org/Archives/Public/www-style/2020Feb/0012.html)
This is a first PR to merge the [Constructable Stylesheets proposal](https://wicg.github.io/construct-stylesheets/) into the CSSOM spec. This was resolved in Feb 2020: https://lists.w3.org/Archives/Public/www-style/2020Feb/0012.html. There are several sub-resolutions there, a few of which are handled here:
- [RESOLVED: CSS() is merged into CSSOM1 (~~either @emilio or @rakina~~ @mfreed7 doing so)](https://lists.w3.org/Archives/Public/www-style/2020Feb/0012.html).
- [RESOLVED: Remove title and alternate from constructor](https://github.com/WICG/construct-stylesheets/issues/105#issuecomment-577704271).
- [RESOLVED: Add base URL constructor argument for sole purpose of …

[cssom-1] Merge constructable stylesheets into CSSOM (https://lists.w3.org/Archives/Public/www-style/2020Feb/0012.html)

---

css-nesting-1/Overview.bs

[css-nesting-1] fix the nesting example
This changes adds a missing nesting selector (`&`) to [an example in the CSS Nesting specification](https://drafts.csswg.org/css-nesting-1/#mixing).
The current example, without a nesting selector:
```css
article {
color: blue;
:where(&) { color: red; }
}
```
The fixed example, with a nesting selector:
```css
article {
color: blue;
&:where(&) { color: red; }
}
```

[css-nesting-1] fix nesting example

---

css-fonts-5/Overview.bs

switches `ex | cap | ch | ic` to `ex-height | cap-height | ch-width | ic-width | ic-height`
Possible alternative: `ex | cap | ch | ic` to `ex | cap | ch-width | ic-width | ic-height`

[css-fonts-5] absolutize axis of font-size-adjust metrics #6288

---

scroll-animations-1/Overview.bs
web-animations-2/Overview.bs

Change the implicit handling of auto duration animations to use the duration of the supplied timeline if resolved.   Scroll-timelines have an implicit timeline duration and the intrinsic iteration duration can be calculated based on this value.  Document timelines will have an unresolved timeline duration, which will translate to an intrinsic iteration duration of zero consistent with the currently specified behavior.  
If the timeline duration is resolved, effect timing is normalized based on this duration.
This pull request is a replacement for https://github.com/w3c/csswg-drafts/pull/4890.

[web-animations-2] [scroll-animations-1] Support automatic duration scroll animations

---

scroll-animations-1/Overview.bs

[scroll-animations-1] Update serialization of CSSScrollTimelineRule.
The serialization process contained stale references to 'start', 'end' and 'time-range' rule descriptors.
Removed 'time-range' and replaced 'start' and 'end' with 'scrollOffsets'.

[scroll-animations-1] Update serialization of CSSScrollTimelineRule.

---

cssom-1/Overview.bs

[cssom-1] Refactor CSSStyleSheet constructor and replaceSync to allow steps to be referenced from HTML spec
The [CSS module scripts](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md) feature is being specified in HTML using several algorithms defined in cssom-1 on the `CSSStyleSheet` interface. In the review of the CSS module scripts HTML spec PR https://github.com/whatwg/html/pull/4898, there was a [concern ](https://github.com/whatwg/html/pull/4898#discussion_r324088522) that referencing the CSSStyleSheet methods directly implies that if these methods were overridden by user script, the UA should call the user script instead.
This change pulls the steps for the `CSSStyleSheet` constructor and `replaceSynce` method into separate algorithms so that …

[cssom-1] Refactor CSSStyleSheet constructor and replaceSync to allow steps to be referenced from HTML spec

---

css-values-3/Overview.bs
css-values-4/Overview.bs

Small typo update to the absolute lengths table where I changed the equivalence in terms of inches given for points. 
Before it was 1pt = 1/72th of 1in, and I believe it should be 1pt=1/72nd of 1in. That section of the page can be found [here for css-values-3](https://www.w3.org/TR/css-values-3/#pt) and [here for css-values-4](https://www.w3.org/TR/css-values-4/#pt) page.

[css-values-3, css-values-4] Updated the equivalence for points in the absolute-lengths table #6409.

---

mediaqueries-5/Overview.bs

Add two new media feature that allow for authors to detect situations where the viewport is logically separated based on the window's configuration with respect to display features. This is designed to allow authors to target foldable devices where the viewport spans multiple displays (logical or physical). 
There are features for both the horizontal and vertical directions and are integers so that future form factors (think a tri-fold device) that do not yet exist can be explicitly detected and supported by authors.
Fixes #5621

[mediaqueries-5] Add viewport segment media features

---

css-cascade-5/Overview.bs
cssom-1/Overview.bs

[cssom-1, css-cascade-5] Add adoptedStyleSheets using [ObservableArray](https://heycam.github.io/webidl/#idl-observable-array).
Some things I need input on:
1. See [this discussion](https://github.com/WICG/construct-stylesheets/issues/118). I added a single list item to the Cascade-5 text to reference the new "final CSS style sheets" concept I added in CSSOM-1. We might (?) want to instead change the `styleSheets` property to explicitly exclude the contents of adoptedStyleSheets, and fold "final CSS style sheets" back into "document or shadow root CSS style sheets".
2.  I can't seem to get the "link magic" working between cssom-1 and css-cascade-5. I tried various permutations of `<a for=foobar>concept name</a>` but nothing seemed to please bikeshed. So I resorted to `<a href=>`. Help …

[cssom-1, css-cascade-5] Add adoptedStyleSheets using ObservableArray

---

cssom-1/Overview.bs

Not sure if this is 100% worth it but it should close #6421, and I think
it's better.

[cssom-1] Move the camel-cased-attribute definition a bit further up.

---

cssom-view-1/Overview.bs

Closes #1725 by removing the usage of incumbent settings object. I could find no evidence of such a check in the Blink, Gecko, or WebKit codebases. Indeed, such a check should not generally be necessary, as (unlike, e.g., window.close()) these methods are not accessible cross-origin.
Also includes various changes for things that have updated in other specs:
* Use "this" instead of "context object"
* Use "string is" instead of "case-sensitive"
* Use "start node" and "start offset" instead of referring to properties of Range (or now, AbstractRange)
* Link to the correct "event loop" definition
* Remove redundant anchor blocks, as these days most definitions are properly exported

[cssom-view] Remove "familiar with" check for move/resize methods

---

cssom-1/Overview.bs

The fact that we haven't given-up loading the style sheet is enough,
there's no need for a specific flag. This is what...
https://html.spec.whatwg.org/#contributes-a-script-blocking-style-sheet
... does as well.
Part of #6463

[cssom] editorial: Remove reference to non-existing flag.

---

web-animations-2/Overview.bs

[web-animations-2] Preserve animation progress when setting the timeline
When switching to a non-monotonic timeline on a paused animation, we set the hold time to the previous current time to prevent the animation from visually jumping until the animation is unpaused.
Similarly, when transition from a non-monotonic timeline to a monotonic timeline, we preserved current time to ensure smooth continuity in the animation.
This process worked well, when dealing exclusively with time-based timeline, but is not compatible with progress-based timelines. We address this by preserving previous progress in places where we previously preserved current time.  The change is compatible with time-based animations as the measured progress (current time / end time) is consistent for a time or progress …

[web-animations-2] Preserve animation progress when setting the timeline

---

css-highlight-api-1/Overview.bs

Specify that when painting a document, the associated `HighlightRegistry`'s ranges that are positioned in a different document are not painted.
Also, fix a bug: the "no longer [in a document tree](https://dom.spec.whatwg.org/#in-a-document-tree)" check excluded ranges positioned inside a shadow tree, which is probably not what we want. Using the [shadow-including root](https://dom.spec.whatwg.org/#concept-shadow-including-root) instead fixes this.
Closes #6417.

[css-highlight-api-1] Don't paint ranges positioned in a different window #6417

---

scroll-animations-1/Overview.bs

[scroll-animations-1] Fix a couple indentation bikeshed errors in spec.
The errors were as follows:
FATAL ERROR: Line 408 isn't indented enough (needs 1 indent) to be valid Markdown:
"</div>"
FATAL ERROR: Line 1058 isn't indented enough (needs 2 indents) to be valid Markdown:
"       Otherwise, the concatenation of the following:"

[scroll-animations-1] Fix indentation and spacing for bikeshed.

---

css-highlight-api-1/Overview.bs

Per resolution of #6375, specify that:
- UAs do not provide any default styles for custom highlights.
- Custom highlights inherit the styles of their originating element.
Closes #6375.

[css-highlight-api-1] Specify that custom highlights have no UA styles #6375

---

css-fonts-4/src-explainer.md

Merging explainers, compare https://github.com/w3ctag/design-reviews/issues/666#issuecomment-901188985

[css-fonts-4] format() supports explainer edits

---

cssom-1/Overview.bs

[cssom] editorial: Remove another reference to unneeded and non-existing flag.

---

css-env-1/Overview.bs

[css-env-1] Introduce environment variable indexing and viewport segment environment variables #5622
This adds the ability to index up to two dimensions via the `env()` syntax. Also adds the viewport segment variables, of which there are 6 values (viewport-segment-{width, height, top, right, bottom, left}), all of which have two dimensions representing their physical location in grid-like organization of the divided viewport.

[css-env-1] Introduce environment variable indexing and viewport segment environment variables #5622 

---

css-font-loading-3/Overview.bs

The spec says in https://drafts.csswg.org/css-font-loading-3/#document-font-face-set:
> The set entries for a document’s font source must be initially populated with all the CSS-connected FontFace objects from all of the CSS @font-face rules.
And in https://drafts.csswg.org/css-font-loading-3/#font-face-css-connection
> There is a two-way connection between [FontFace objects and @font-face rules]: any change made to a @font-face descriptor is immediately reflected in the corresponding FontFace attribute, and vice versa.
And, finally, in https://drafts.csswg.org/css-font-loading-3/#dom-fontfaceset-clear
> Remove all items from the FontFaceSet’s set entries.
It seems like `clear()` shouldn't delete CSS-connected FontFaces. This is also what Firefox and Chrome both do. I'm updating WebKit to …

[css-font-loading-3] FontFaceSet.clear() should not clear CSS-connected items

---

css-nesting-1/Overview.bs

Current example on [Nesting Conditional Rules](https://www.w3.org/TR/css-nesting-1/#conditionals) (§ 2.3) has an invalid parentless `& { ... }` rule:
```css
/* equivalent to
.foo { display: grid; }
@media (orientation: landscape) {
& {                             <--- what does & represent here?
grid-auto-flow: column;
}
}
*/
```
Updated version repositions it inside `.foo`:
```css
/* equivalent to
.foo {
display: grid;
@media (orientation: landscape) {
& {                           <--- & represents .foo
grid-auto-flow: column;
}
}
}
*/
```
Great proposal otherwise! Really excited for this one :)

[css-nesting] Fix Nesting Conditional Rules example

---

web-animations-2/Overview.bs

[web-animations-2] Fix bikeshed indentation errors.
The spec had several incorrect indents that lead to failures running bikeshed on it.

Fix bikeshed indentation errors in web-animations-2 diff spec.

---

css-font-loading-3/Overview.bs

This is for https://github.com/w3c/csswg-drafts/issues/520.
The [resolution](https://github.com/w3c/csswg-drafts/issues/520#issuecomment-387799523) is:
> RESOLVED: [add this functionality to] css-font-loading, level TBD
I added this to level 3, because level 4 doesn't exist. If the editor prefers this go in a level 4, that's no problem.
The GitHub thread hasn't come to a conclusion about what should go in the `FontFaceFeatures` interface, so I left it blank for now.

[css-font-loading] Add IDL for discovery of information about a font

---

css-font-loading-3/Overview.bs

This fixes invalid IDL syntax introduced in:
https://github.com/w3c/csswg-drafts/pull/6591
Errors were:
- Interfaces must have an `[Exposed]` extended attribute.
- `bool` does not exist in Web IDL. Correct type is `boolean`.

[css-font-loading] Fix invalid IDL

---

css-fonts-4/Overview.bs

https://drafts.csswg.org/css-fonts-4/#font-prop-desc
Remove redundant `<angle>` in the `font-style` `@font-face` descriptor. `<angle> | <angle>{1,2}` seems redundant.
It was introduced in https://github.com/w3c/csswg-drafts/pull/6162

[css-fonts-4] Remove redundant grammar

---

css-highlight-api-1/Overview.bs

Remove Issue block now that #4597 has been resolved.
Remove start/end offset clipping behavior since we resolved to just use the DOM spec's validity definition.

[css-highlights-api] StaticRange validity updates

---

css-highlight-api-1/Overview.bs

This check was removed in https://github.com/w3c/csswg-drafts/commit/7e65e3821d011e3bd29b8aca6e8bb9d5a223bca5, but it's still needed per the resolution of #6417, which was that we should not paint ranges from documents other than the one associated with the current highlight registry.
This is separate from the validity question, because a range in a different document can be valid (or it could be a live range), but we still shouldn't paint it.

[css-highlights-api] Restore check that range is in same document as the HighlightRegistry

---

css-conditional-4/Overview.bs

Define criteria for enabling @supports to distinguish support for
a set of font technologies defined in the grammar.
Addresses resolution in #6520 to add criteria for font technologies as a
first step.
Incorporates @LeaVerou 's feedback from [1]
[1] https://github.com/w3c/csswg-drafts/issues/6520#issuecomment-904703888

[css-conditional-4] Extend supports feature to express font capabilities

---

css-conditional-4/Overview.bs

We resolved to accept the proposal from <https://tabatkins.github.io/specs/css-when-else/>, not a modified version using @if. The UD uses @when for a reason; it's not a trivial edit worthy of being done without discussion.

Reset to the @when from the resolved-on proposal

---

cssom-1/Overview.bs

Fixes #6501.
Tests in https://github.com/web-platform-tests/wpt/pull/30140.

[cssom] Let getComputedStyle return an empty style for invalid pseudo-elements, and the element's style if the string doesn't begin with a colon.

---

web-animations-2/Overview.bs

[web-animations-2] Fix style in dl.switch for web-animations-2 spec.
This PR addresses two formatting glitches in the web-animations-2 spec: 1) paragraphs after a marker, and 2) indentation of bulleted lists. Both tweaks are for descendants of a dl.switch. Without the changes, a newline is inserted after a marker within the switch if the maker is followed by a paragraph.  List items within a dl.switch are outdented which causes the text to overlay the bullets.

[web-animations-2] Fix style in dl.switch for web-animations-2 spec.

---

web-animations-2/Overview.bs

Inheritance is already set in the main interface declaration, and is syntactically forbidden at the partial level.

[web-animations-2] Remove inheritance from partial interface definition

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6623.

[css-fonts] [css-device-adapt] [palettes] FONT_PALETTE_VALUES_RULE conflicts with VIEWPORT_RULE

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6626.

[css-fonts] [palettes] base-palette and override-color should have their integer values be required to be nonnegative

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6678.

[css-fonts] [palettes] base-palette should be able to reference "dark" or "light" (just like font-palette can)

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6625.

[css-fonts] [palettes] Can't get the palette name from CSSFontPaletteValuesRule

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6624.

[css-fonts] [palettes] CSSFontPaletteValuesRule's maplike doesn't make much sense

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6630.

[css-fonts] [palettes] override-color takes a list but isn't plural

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6645.

[css-fonts] [palettes] Properties in CSSFontPaletteValuesRule don't need to be mutable

---

css-color-4/Overview.bs
css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6680.

[css-fonts] Context for resolving override-color colors

---

css-transforms-2/Overview.bs

This adds the `none` argument to the `perspective()` function, equivalent to infinity.
Fixes #6488.

[css-transforms-2] Add ''perspective(none)''.

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6627.

[css-fonts] [palettes] Remove the <string> values from override-color and base-palette

---

css-color-adjust-1/Overview.bs

This allows HTML to "set" the used value of the color-scheme property,
via a meta tag.
Part of https://github.com/whatwg/html/issues/7213
Closes https://github.com/w3c/csswg-drafts/issues/6726

[css-color-adjust] Define color-scheme: normal to be hookable by HTML.

---

css-scrollbars-1/Overview.bs

This clarifies the purpose of the property, as well as how users (not authors) are ultimately in charge of this UI component.
See #6351

[css-scrollbars] Add notes and advisements to scrollbar-width

---

css-cascade-4/Overview.bs
css-color-4/Overview.bs
css-fonts-4/Overview.bs
css-images-4/Overview.bs
css-shapes-2/Overview.bs
css-syntax-3/Overview.bs
css-values-4/Overview.bs

Add a generic method to fetch style resources, and make use of it in
fonts & imports.
[css-syntax-3]: Make sure we have a location when parsing a stylesheet, as the location is necessary for parsing import rules.
[css-values-3]: Add a reusable method to fetch a style-originated
resource.
[css-cascade-4]: Formalize the import algorithm to use the new fetch
method.
[css-fonts-4]: Formalize font loading to use the new fetch method. Removed some of the font loading "guidelines" as they are now baked in to the algorithm.
[css-shapes-2]: Load css-shapes external images/SVG using fetch style resoure
See https://github.com/w3c/csswg-drafts/issues/562
Fixes #6076
Tests: https://github.com/web-platform-tests/wpt/pull/31344

[css-syntax-3][css-values-3][css-cascade-4][css-fonts-4] Formalize fetching and resource timing reporting

---

mediaqueries-4/Overview.bs

This is to make it possible for the following things to match
`<general-enclosed>`:
- `unknown()`
- `(unknown)`
- `(10px < unknown)`

[mediaqueries-4] Make <any-value> optional in <general-enclosed>, remove <ident>

---

mediaqueries-4/Overview.bs

For container queries (css-contain-3), it would be convenient to
be able to reference paren-less `<media-feature>`, since that grammar
wants to wrap the value in a function rather than plain parentheses.
As far as I can tell, `<media-feature>` is only used by `<media-in-parens>`,
so this should be safe.

[mediaqueries-4] Lift parens to <media-in-parens>

---

css-highlight-api-1/Overview.bs

Per resolution of #6498, add a `HighlightType` enum attribute to `Highlight`. This will be used to convey the semantics of the `Highlight` for accessibility tools.

[css-highlight-api-1] Add `type` enum attribute to `Highlight` #6498

---

css-highlight-api-1/Overview.bs

Per [resolution](https://github.com/w3c/csswg-drafts/issues/4597#issuecomment-905688814) in #4597, clarify that when authors uses StaticRange highlights, UAs should use the actual static ranges rather than backing them with live ranges.

[css-highlight-api-1] Clarifying that user agents must not use live ranges internally for static ranges #4597

---

css-cascade-5/Overview.bs

So that we can distinguish whether an `@import` is unlayered or in an anonymous layer.

[css-cascade-5] Make CSSImportRule.layerName nullable #6576

---

css-syntax-3/Overview.bs

Since double dash `--` is a valid identifier by the spec the `CDC-token` is breaking "round-trip" with parsing now when follows after `#`, `-`, number or `@`:
* `#-->` = `#--` (hash-token) + `>` (delim-token)
* `--->` = `---` (ident-token) + `>` (delim-token)
* `number-->` = `number--` (dimension-token) + `>` (delim-token)
* `@-->` = `@--` (at-keyword-token) + `>` (delim-token)

[css-syntax-3] Fix serialization matrix related to CDC-token

---

css-color-4/conversions.js

[css-color-4] fix typo
Current code behaves like this (which I think is a typo) :
```js
var alpha = 1;
if (alpha = 0) {
console.log('truthy')
} else {
console.log(5 / alpha);
}
> Infinity
```

[css-color-4] fix typo in conversions.js

---

css-fonts-4/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/6631.

Functions and relative lengths in palettes are evaluated within the root element's context

---

css-color-4/Overview.bs

Replace 'SelectedItemTExt' with correctly-cased 'SelectedItemText'.

[css-color-4] Fix incorrect casing in 6.2 System Colors

---

css-animations-2/Overview.bs

Keyframes should only be merged when they have matching keyframe offset, timing function _and_ composite.

[css-animations-2] Account for `animation-composition` when merging keyframes (closes #6935)

---

css-highlight-api-1/Overview.bs

Specify that repaints of highlights triggered by addition or removal of ranges, or by changes to highlight properties, should be asynchronous.
Closes #4596

[css-highlight-api-1] Specify that highlight repaints must be async

---

css-contain-3/Overview.bs

Per resolution for issues #5984 and #6711:
https://github.com/w3c/csswg-drafts/issues/5984#issuecomment-1028488562
https://github.com/w3c/csswg-drafts/issues/6711#issuecomment-1028487865
Test coverage:
https://wpt.live/css/css-contain/container-queries/pseudo-elements-001.html
https://wpt.live/css/css-contain/container-queries/pseudo-elements-002.tentative.html
https://wpt.live/css/css-contain/container-queries/pseudo-elements-003.tentative.html
https://wpt.live/css/css-contain/container-queries/container-for-shadow-dom.tentative.html

[css-contain-3] Pseudo elements and shadow DOM #5984 #6711

---

css-fonts-4/Overview.bs

Current color excluded from possible values for override-colors:
entries, see discussion in
https://github.com/w3c/csswg-drafts/issues/7010

[css-fonts-4] #7010 Remove `currentcolor` from `override-colors:` example

---

css-fonts-4/Overview.bs

Improve consistency with other parts of CSS where later declarations
override earlier ones, fixes #7026.

[css-fonts-4] Use last key/palette index in override-colors, #7026

---

css-backgrounds-4/Overview.bs

In order to get the spec. compiled again by Bikeshed, it requires the property definition tables to include an animation type.
This change adds it whereever it was missing so far. The added types are either chosen to copy pre-existing ones of the previous level or by looking at the property's syntax.
Sebastian

[css-backgrounds-4] Added missing animation types to property definitions

---

css-scroll-snap-1/Overview.bs

This is a non-substantive contribution. 
Axis is a required value, but it was not included in the sample code.
The current sample code does not work correctly, so I added it. 
https://www.w3.org/TR/css-scroll-snap-1/#re-snap
If this is a misconception, please close.

[css-scroll-snap-1] Add missing Axis to sample code

---

scroll-animations-1/Overview.bs

Otherwise it inherits the dfn type `attribute` set on the encloding `<dl>`
Not sure if the `dfn-for` should also be overridden, and if so, by what.

[scroll-animations-1]  Mark 'set the offset value' as an abstract-op

---

css-fonts-5/Overview.bs

Correct typo techn() -> tech() for font technology function.
Follow up to 102da5ae79, also fixes #6791.

[css-fonts-5] Fix typo in tech() function

---

css-contain-2/Overview.bs

[css-contain-2] Fix typo (just dropping a stray 'and') from css-contain-2.
(just an editorial typo fix; no semantic change)

[css-contain-2] Fix typo (just dropping a stray 'and') from css-contain-2

---

selectors-4/Overview.bs

This was added in #3735 but isn't mentioned yet in the changes section.

[css-selectors-4] Mention :defined in change history

---

css-shapes-2/Overview.bs

Avoids an ambiguity where the second radius and angle can both come from calc
Closes #6925

[css-shapes-2] Add the "rotate" keyword to shape()

---

css-fonts-4/Overview.bs

This uses @drott's proposed text.
Fixes https://github.com/w3c/csswg-drafts/issues/7093.

[css-fonts-4] Color fonts are not enabled by default

---

css-contain-2/Overview.bs

[css-contain-2] Fix two mispellings of "though"
This fixes two small typos and doesn't introduce any semantic changes.

[css-contain-2] Fix two mispellings of "though"

---

css-images-4/Overview.bs

The `<basic-shape-rect>` construct introduced in #7058 needs to be wrapped in another pair of `<>`, otherwise it gets interpreted as an unknown custom markup tag and property value gets rendered as: `none |`.

[css-images-4] Fix escaping in object-view-box definition

---

css-page-3/Overview.bs

The `orphans` and `widows` properties were moved to CSS Fragmentation 3. Therefore they got removed.
Fixes #1573

Removed mentioning of orphans and widows

---

css-values-4/Overview.bs

[css-values-4] Fetch now exposes 'conclude' instead of 'finalize' which works with a `fetch controller` - this clarifies that resource timing entries are mapped to a fetch rather than to a response.

[css-values] Use fetch 'conclude' instead of 'finalize'

---

cssom-view-1/Overview.bs

`bool` is `boolean` in Web IDL.

[cssom-view-1] Fix invalid "bool" IDL type

---

cssom-view-1/Overview.bs

This is a follow-up to #7162 to fix occurrences of `bool` that were missed in the previous PR.
(Sorry I missed these in the first PR. I checked the resulting IDL this time, we should be all good.)

[cssom-view-1] Fix remaining IDL instances of "bool"

---

css-syntax-3/Overview.bs

Noticed these while implementing this yesterday.

[css-syntax-3] Fix two typos in `<urange>` parsing algorithm

---

css-pseudo-4/Overview.bs

This patch makes edits for #6818:
* clarifies that color:currentColor represents the color of the next *active* layer below (q1 resolved)
* states that gCS behaves as if the given highlight is active and all other highlights are inactive (q2 resolved)
* note that q2 and the resolution deal with ‘color’ specifically, but it only makes sense to extend this to all styles returned by gCS, since other properties can depend on ‘color’ if they are set to ‘currentColor’

[css-pseudo] clarify highlight color:currentColor + gCS (closes #6818)

---

css-pseudo-4/Overview.bs
css-variables-1/Overview.bs

This patch makes edits for #6264:
* adds a section stating that custom properties are allowed on all pseudos
* explicitly clarifies that non-inherited registered customs are also inherited
One thing I’m unsure of… should we restate or refer to this near the lists of applicable properties? Especially with [the one for ::marker](https://drafts.csswg.org/css-lists/#marker-properties), which is in a separate spec, the reader could miss this if they’ve only read the section about a specific pseudo.

[css-pseudo] [css-variables] highlight pseudos and custom properties (closes #6264)

---

css-ui-4/Overview.bs

@fantasai and I gave a stab at the refactoring of https://github.com/w3c/csswg-drafts/pull/6537 we had been talking about in https://github.com/w3c/csswg-drafts/issues/3526. Goal: avoid having to talk about specific HTML elements in the CSS spec, and in particular, avoid having to have long lists of types of widgets.
Doing that was undesirable because:
* CSS, at least in theory, is not limited to HTML.
* The descriptions of each types of widgets were stubs “a button is a <a>widget</a> which must have the <a>native appearance</a> of a button”,  while the HTML spec held the actual descriptions of the rendering of various elements in its Rendering chapter.
* This created a bunch of unnecessary indirections between the two specs, making both of them longer and harder to read than necessary. …

[css-ui-4] Provide hooks for HTML to define rendering for widgets

---

css-flexbox-1/Overview.bs
css-grid-2/Overview.bs
css-ruby-1/Overview.bs

Via https://github.com/mdn/yari/pull/4656#issuecomment-1113508815
The CSS Display spec defines [possible values for the `display` property](https://drafts.csswg.org/css-display/#propdef-display). This includes `flex`, `grid`, `ruby` and associated values, whose meanings are normatively defined in CSS Flexbox, CSS Grid and CSS Ruby.
On top of meanings, the CSS Flexbox, CSS Grid and CSS Ruby specs actually redefine the values themselves through a "New Values" table. This is fully clear for humans, but a naive attempt to extract formal value definitions from CSS specs ends up with the impression that `flex`, `grid` and `ruby` are actually normatively defined twice.
This update proposes to flag the "New values" tables in CSS Flexbox, CSS Grid and CSS Ruby as "informative" so that extraction …

[css-flexbox-1] [css-grid-2] [css-ruby-1] Flag "New values" tables for display property as informative

---

css-backgrounds-3/Overview.bs

[css-backgrounds-3] Fixed a typo in section [6.1. Drop Shadows: the box-shadow property](https://www.w3.org/TR/css-backgrounds-3/#box-shadow)
The typo that needed to be changed was that in the section there was a sentence stating,  "Omitted lengths are 0; omitted colors default to the value of the color property. ". But later on in that section, it states, "Specifies the color of the shadow. If the color is absent, it defaults to currentColor. "
So I believe that instead of, "Omitted lengths are 0; omitted colors default to the value of the color property. " it should be
"Omitted lengths are 0; omitted colors default to currentColor. " as stated in the issue created.

[css-backgrounds-3] Updated omitted lengths sentence in section 6.1 (Drop Shadows: the box-shadow property) #5993

---

css-pseudo-4/Overview.bs

This patch makes edits for #6829, stating that decorations introduced by highlight pseudos are propagated through inheritance rather than through decorating boxes (the opposite of originating decorations).

[css-pseudo] no decoration propagation on highlights (closes #6829)

---

css-page-3/Overview.bs

Resulting page area was incorrect in `EXAMPLE 24`.

[css-page] Fix typo in Overview.bs

---

css-text-decor-4/Overview.bs

The current sentence could be interpreted as performing a `floor` on the actual calculated value, while it is actually rounded to the nearest integer, with a minimum value of one.
Equivalent to: `x = min(1, round(x))`
Fixes #7283

[css-text-decor-4] Clarified constraints for thickness length and percentage #7283

---

css-contain-3/Overview.bs

Current proposal to disallow 'not' and 'none' as container-names.

[css-contain-3] Exclude 'none' and 'not' from custom-ident. #7203

---

css-contain-3/Overview.bs

Use a separate definition of container-name in the @container syntax to
disallow 'none' and 'not'.

[css-contain-3] Disallow not/none for container-name in @-rule. #7203

---

css-color-5/Overview.bs

as title. one termref has additional closing bracket.

[css-color-5] possible typo (unnecessity `]`)

---

selectors-4/Overview.bs

Add a simple sentence to apply the resolution of issue #6952:
- RESOLVED: Disallow nesting :has() inside :has()
https://github.com/w3c/csswg-drafts/issues/6952#issuecomment-1143812466

[selectors-4] Disallow nesting :has() inside :has(). #6952

---

css-values-4/Overview.bs

See https://github.com/whatwg/fetch/pull/1413
Fetch now reports timing automatically if initiator is passed.

[css-values-4] Editorial: adjust to fetch refactor

---

css-fonts-3/Overview.html

Examples of different schemas and different domains are inconsistent with the given assumed URL.

[css-fonts-3] Fix the mistake that the scheme is inconsistent, and improve comments

---

css-color-5/Overview.bs

Temporary fix of #7363 until spec authors decide to further edit the value definition.

[css-color-5] Fix typo in `<rgb()>` value definition

---

css-syntax-3/Overview.bs

[css-syntax-3] Fix typo in `<an+b>` value definition

---

css-images-3/Overview.bs

Definition of `<size>` currently appears as `<size> =  |  | {2}` in the [Editor's Draft](https://drafts.csswg.org/css-images-3/#typedef-size) because autolinks to types/productions need to be wrapped in `<<foo>>` to properly generate a `<foo>` construct (and not a `<foo>` HTML tag)

[css-images-3] Fix escaping in definition of <size>

---

cssom-view-1/Overview.bs

This way other specs like IntersectionObserver can call it.
See https://github.com/w3c/IntersectionObserver/issues/55

[cssom-view] Add a "get the bounding box" algorithm for getBoundingClientRect() #5614 

---

css-animations-1/Overview.bs

Fixes https://github.com/w3c/csswg-drafts/issues/7424

[css-animations-1] Add `constructor` type on `AnimationEvent`'s definition (fix #7424)

---

cssom-view-1/Overview.bs

[cssom-view-1] Introduce VisualViewport API #6339
This PR merges the visual-viewport API from the [WICG spec](https://wicg.github.io/visual-viewport/index.html) into cssom-view-1 as agreed in https://github.com/w3c/csswg-drafts/issues/6339.
This omits the experimental `segments` extension in the WICG repo as well as the broader non-normative discussion. Some wording and flow was reworked for consistency with the cssom-view-1 spec.
Fixes #6339

[cssom-view-1] Introduce VisualViewport API #6339

---

cssom-view-1/Overview.bs

Fixes a couple of bikeshed errors in cssom-view-1:
* Missing indentation on newline in ordered list
* Duplicate definitions for "scroll completed"
* Missing definition for "scrolling box"
* Wrong type for "scrollend" links
* Missing definition for "pending scrollend event targets"

[cssom-view-1] editorial: Fix linking errors
