w3c/csswg-drafts

css-ui-4/Overview.bs
Changed “From controls” to “Form controls”
=> [css-ui-4] Fix typo

default.css
Also monospace element-attr
------
cc @tabatkins
=> More consistent monospace styling

css-round-display/Overview.bs
Further info: https://lists.w3.org/Archives/Public/www-style/2015Oct/0127.html
=> Doing the changes in the bikeshed file. 

css-size-adjust/Overview.bs, css-size-adjust/Overview.html
@dbaron, how does this sound to you?
This should resolve the following discussion:
https://lists.w3.org/Archives/Public/www-style/2016Jan/0012.html
I investigated answering the "small display" question but it grew to be more than I expected so I've just set it as an issue in this PR for now, and have raised this on www-style.
=> Specify the text-size-adjust <percentage> value

css-color/Overview.bs
Hi there,
I was reading through the new draft spec and noticed some minor spelling/grammar errors. Hope you don't mind a PR out of the blue.
=> [css-color] Fix some minor typos

cssom/Overview.bs
=> [cssom] Handle custom properties separately.

css-containment/Overview.bs
=> [css-containment] Reuse existing terminology

cssom/Overview.bs
=> [cssom] Check index for rule insertion first

css-transforms/Overview.bs, cssom/Overview.bs
=> [cssom][css-transforms] Allow other specs to specify 'resolved value'

css-line-grid/Overview.bs
~~Closes #491~~ (that was a typo)
Closes #939
=> [css-line-grid] Make the dependency on line-height-step explicit.

selectors/Overview.bs
=> Allow universal selector with no namespace

css-grid/Overview.bs
The commit is self-explaining :)
=> [css-grid] typo in example

css-grid/Overview.bs, css-grid/images/spanned-gap-align.svg, css-grid/images/spanned-gap.svg
Example 43, figures 16 and 17.
=> [css-grid] Replaced example screenshots with SVG versions

css-2015/Overview.bs, css-2017/Overview.bs
=> Typo fixes

selectors/Overview.bs
Zen Coding has been renamed to Emmet.
=> [selectors] Zen Coding -> Emmet

css-font-loading/Overview.bs
=> Don't <dfn> Promise. WebIDL already does that.

css-contain/Overview.bs
I left out classes as those are not really relevant and their choosing would be *opinionated*.
=> Replace <section> with <article> in markup example

css-grid/Overview.bs
=> [css-grid] Fix some small issues in examples

css-font-loading/Overview.bs
Fix autolinks to `ArrayBuffer`/`ArrayBufferView`.
=> [css-font-loading] Bikeshed fix

cssom/Overview.bs
For autolinks & bibliographical references.
=> [cssom] Bikeshed fix

mediaqueries-5/Overview.bs
Reinstate the content that was taken out of Level 4, and
add 'prefers-reduced-motion'.
=> Create a Media Queries 5 specification

css-inline/Overview.bs
''none'' -> ''initial-letter-wrap/none''
=> [css-inline] Bikeshed fix

css-writing-modes-3/Overview.bs
=> [css-writing-modes-3] create non-normative subsection

css-round-display/Overview.bs
Follow-up for df04a0d8d1a6b95b969d35ada4c94bd5ec0b1eea.
Context: #214 & w3c/fxtf-drafts#14.
=> [css-round-display] Remove polar positioning in Introduction

css-logical/Overview.bs
* Fix reference to CSS21
* Change introduction section to `<h2>`
=> [css-logical] Editorial fixes

cssom/Overview.bs
See https://github.com/heycam/webidl/pull/286
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=30107
=> [cssom] Update IDL for [TreatNullAs] extended attribute

css-ui/Overview.bs
=> [css-ui] Fixed a typo

css-values-3/Overview.bs, css-values/Overview.bs
=> [css-values] Fix typo: 'Q' vs. 'q' in table entry

cssom-view/Overview.bs, cssom/Overview.bs
See https://lists.w3.org/Archives/Public/www-style/2017Sep/0023.html
=> [cssom][cssom-view] Update editors

README.markdown
Part of https://github.com/w3c/csswg-drafts/issues/1844
=> Revamp (trim) the Mercurial documentation

css-line-grid/Overview.bs, css-position/Overview.bs, css-shapes/Overview.bs, css-text-decor/Overview.bs, css-transforms/Overview.bs
Address some fatal errors about aliases of the same base reference.
=> Bikeshed fixes

selectors-4/Overview.bs
I've replaced a word with more formal equivalent.
=> [selectors-4] Fix typo

css-ui-4/Overview.bs
=> [css-ui] Fix highligh typo

css-cascade-3/Overview.bs, css-counter-styles-3/Overview.bs, css-images-3/Overview.bs, css-images-4/Overview.bs, css-lists-3/Overview.bs, css-syntax-3/Overview.bs, css-writing-modes-3/Overview.bs, css-writing-modes-4/Overview.bs
Utilize the autolink shortcuts in Bikeshed.
=> Use autolink for HTML elements

web-animations-1/Overview.bs
This fixes #2059 and fixes #2073 and fixes #2226.
=> [web-animations-1] Make Animation.playbackRate setter not seek; introduce Animation.updatePlaybackRate

css-values-4/Overview.bs
Need this to use it in Typed OM spec
=> Export definition of math functions

selectors-4/Overview.bs
https://drafts.csswg.org/selectors redirects.
=> Append / to ED link

css-color-3/Overview.src.html
This pull request fixes #2089.
=> [css-color-3] Remove old note for the appearance property

css-text-3/Overview.bs
As suggested by Myles in #2003
=> [css-text-3] Simplify the behavior of the break-spaces value

css-fonts-4/Overview.bs
... instead of UA style sheets.
Background: https://github.com/w3c/csswg-drafts/pull/2436#issuecomment-372600446
=> [css-fonts-4] Users should set user style sheets

css-contain-1/Overview.bs
There are 2 effects listed below
=> [css-contain] Typo: use plural

css-grid-2/Overview.bs
The initial example was based on the two-axis model, updated it to be per-axis.
=> [css-grid-2] Updating initial example to match per-axis model

css-fonts-4/Overview.bs
See https://github.com/tidoust/reffy-reports/issues/3#issuecomment-387550183
=> Fix Web IDL syntax encountered by Reffy

css-writing-modes-3/Overview.bs, css-writing-modes-4/Overview.bs
This was hidden by mistake in commit fa9120b911.
=> [css-writing-modes] Show diagram for vertical writing mode

web-animations-1/Overview.bs
=> [web-animations-1] Make async methods on Animation return appropriate Promise objects.

css-exclusions-1/Overview.bs
In "position: fixed;" the 'fixed' keyword is from css-position-3.
=> [css-exclusions] Refer to css-position-3

css-will-change-1/Overview.bs
Discussed in Sydney 2018 F2F
https://github.com/w3c/csswg-drafts/issues/2737#issuecomment-402574750
=> [css-will-change] will-change is not animatable

css-regions-1/Overview.bs
Found while authoring https://github.com/web-platform-tests/wpt/pull/11979
=> Fix syntax error

css-writing-modes-3/Overview.bs
https://github.com/w3c/csswg-drafts/issues/2751#issuecomment-402604609
direction/writing-mode/unicode-bidi are not animatable
=> [css-writing-modes] direction etc. not animatable

cssom-view-1/Overview.bs
Fixes #1569.
(See #1569 for discussion.)
=> Define overflow directions in terms of block-end and inline-end.

css-box-3/Overview.html
=> removing accidental markup

css-scrollbars-1/Overview.bs
=> [css-scrollbar] Put some reasoning into the scope section

css-scrollbars-1/Overview.bs
=> [css-scrollbar] Add scrollbar-color: dark/light

selectors-4/Overview.bs
=> [selectors-4] Document changes since Selectors 3

css-text-3/Overview.bs
=> [css-text-3] clarify that U+3000 is not affected by word-break

css-transforms-2/Overview.bs
=> [css-transforms-2] Fix order of interpolation/addition sections

css-transforms-2/Overview.bs
=> [css-transforms-2] Fix clamping of product

css-transforms-1/Overview.bs, css-transforms-2/Overview.bs, web-animations-1/Overview.bs, web-animations-2/Overview.bs, web-animations-css-integration/Overview.src.html
Issues should be created in
https://github.com/w3c/csswg-drafts/issues
not
https://github.com/w3c/fxtf-drafts/issues
=> [css-transforms] [web-animations-1] csswg github

css-transforms-1/Overview.bs, css-transforms-2/Overview.bs, web-animations-1/Overview.bs, web-animations-2/Overview.bs, web-animations-css-integration/Overview.src.html
=> Revert "[css-transforms] [web-animations-1] csswg github"

cssom-1/Overview.bs
=> [cssom] Return CSSStyleSheet from LinkStyle

cssom-1/Overview.bs
Resolves https://github.com/w3c/csswg-drafts/issues/3311#issuecomment-438402828.
=> [cssom] Return CSSStyleSheet instead of StyleSheet

css-shadow-parts-1/Overview.bs
Add missing /TR link
https://www.w3.org/TR/css-shadow-parts-1/
=> Add TR link

css-transforms-2/Overview.bs, web-animations-1/Overview.bs, web-animations-2/Overview.bs, web-animations-css-integration/Overview.src.html
Change deliverers from FXTF to CSSWG. @birtles could you approve the web animations part please?
=> [css-transforms][web-animations] Change deliverers from FXTF to CSSWG

css-text-3/Overview.bs
[css-text-3] Clarify editorial note about line-break requirements
=> [css-text-3] Clarify editorial note about line-break requirements

web-animations-1/Overview.bs
=> [web-animations-1] Make animations with zero playback rate in before/after phase NOT be considered "current"

web-animations-1/Overview.bs
=> [web-animations-1] Fix order of steps for resolving physical vs logical properties in computed keyframes

css-pseudo-4/Overview.bs
`implements` is only for mixins.
=> [css-pseudo-4] EventTarget is not a mixin

css-backgrounds-3/issues-cr-2017.bsi, css-backgrounds-3/issues-cr-2017.html, css-flexbox-1/issues-cr-20160526.bsi, css-flexbox-1/issues-cr-20160526.html, css-multicol-1/issues-2011.html, css-multicol-1/issues-2011.txt, css-values-3/issues-cr-2016.bsi, css-values-3/issues-cr-2016.html, css2/cover.html, css2/cover.src, mediaqueries-4/issues-wd-2016-01-26.html, mediaqueries-4/issues-wd-2016-01-26.txt
See https://gsnedders.com/who-even for details.
=> Use Sam's correct name

web-animations-1/Overview.bs
=> [web-animations-1] Specify requirements on style change events

css-values-4/Overview.bs
removed an "is" - simple grammar issue, not related issue/bug
=> [css values 4] grammar fix

css-regions-1/Overview.bs
Following https://github.com/heycam/webidl/pull/433.
=> [css-regions-1] Convert Region to a mixin

css-lists-3/Overview.bs
The only normative change since the previous publication was https://github.com/w3c/csswg-drafts/commit/cb834e9ce57cf8ee44e896f3e8e2d092147b3816
=> [css-lists-3] Update Changes section

css-font-loading-3/Overview.bs
Following https://github.com/heycam/webidl/pull/433.
=> [css-font-loading-3] Convert FontFaceSource to a mixin

css-animations-2/Overview.bs, css-transitions-2/Overview.bs
=> [css-transitions-2][css-animations-2] Specify composite order for ::marker pseudo elements

css-values-4/Overview.bs
=> [css-values-4] Percentage before pixels

css-sizing-3/Overview.bs
=> [css-sizing-3] Actually define the term "intrinsic sizes"

web-animations-1/Overview.bs
=> [web-animations-1] Add parameter for fetching all animations on a subtree

cssom-1/Overview.bs
=> [cssom] Use CSS/Parse in getComputedStyle().

css-animations-1/Overview.bs, css-transitions-1/Overview.bs, css-values-3/Overview.bs
Link to easing-function instead of the defunct
timing-function.
=> [css-animations] [css-transitions] [css-values] easing

web-animations-1/Overview.bs
=> [web-animations-1] Move definition of getAnimations from Document to DocumentOrShadowRoot

css-text-decor-3/Overview.bs
This project is now available only on GitHub.
=> [css-text-decor] Update the link to Kenten Generic

css-values-3/Overview.bs
List of 67 additional tests bikeshed-added with into csswg-drafts/css-values-3/Overview.bs  are
animation-iteration-count-calc.html
calc-background-image-gradient-1.html
calc-background-linear-gradient-1.html
calc-background-position-1.html
calc-background-size-1.html
calc-border-radius-1.html
calc-height-block-1.html
calc-height-table-1.html
calc-margin-block-1.html
calc-max-height-block-1.html
calc-max-width-block-1.html
calc-max-width-block-intrinsic-1.html
calc-min-height-block-1.html
calc-min-width-block-1.html
calc-min-width-block-intrinsic-1.html
calc-offsets-absolute-bottom-1.html
calc-offsets-absolute-left-1.html
calc-offsets-absolute-right-1.html
calc-offsets-absolute-top-1.html
calc-offsets-relative-bottom-1.html
calc-offsets-relative-left-1.html …
=> [css-values-3] Bikeshed-added 67 more links to tests in Overview.bs

css-ui-4/Overview.bs
=> [css-ui] Editorial: Use "control" instead of "form control"

css-color-adjust-1/Overview.bs
=> [css-color-adjust-1] Rename color-scheme:auto to normal #3849

css-fonts-3/Fonts.html, css-fonts-3/Overview.html
=> [css-fonts-3] Fix type on onload eventHandler

cssom-1/Overview.bs
=> [cssom] Correct typos in serialization step

css-grid-1/Overview.bs
Add missing versions to fix https://lists.w3.org/Archives/Public/site-comments/2019Jun/0003.html
=> [css-grid-1] Fix Previous Versions

css-values-3/Overview.bs
Added links of these following tests into css-values-3/Overview.bs :
css/CSS2/values/numbers-units-001.xht
css/CSS2/values/numbers-units-002.xht
css/CSS2/values/numbers-units-003.xht
css/CSS2/values/numbers-units-004.xht
css/CSS2/values/numbers-units-005.xht
css/CSS2/values/numbers-units-006.xht
css/CSS2/values/numbers-units-007.xht
css/CSS2/values/numbers-units-009.xht
css/CSS2/values/numbers-units-010.xht
css/CSS2/values/numbers-units-011.xht
css/CSS2/values/numbers-units-012.xht
css/CSS2/values/numbers-units-013.xht
css/CSS2/values/numbers-units-014.xht
css/CSS2/values/numbers-units-015.xht
css/CSS2/values/numbers-units-017.xht
css/CSS2/values/numbers-units-019.xht
css/CSS2/values/units-002.xht
css/CSS2/values/units-003.xht
css/CSS2/values/units-004.xht
css/CSS2/values/units-005.xht
=> Added links to 20 tests in css-values-3/Overview.bs

css-values-4/Overview.bs
Links to the following 6 tests added into css-values-4/Overview.bs: 
calc-ch-ex-lang.html
calc-in-color-001.html
calc-in-font-feature-settings.html
calc-rem-lang.html
calc-rounding-001.html
ex-calc-expression-001.html
=> Added links to 6 tests in css-values-4/Overview.bs

cssom-view-1/Overview.bs
[cssom-view-1] Scroll element into view: height for block direction
Fixes #1515
=> [cssom-view-1] Scroll element into view: height for block direction

css-writing-modes-3/Overview.bs
=> [css-writing-modes-3] Undefine processing of spaces inside text-combine-upright for L3

css-overscroll-1/Overview.bs
Update the shortname to be the same as the directory name and the /TR shortname. Also add the link to /TR in the metadata section.
=> [css-overscroll] Update shortname and link to /TR

cssom-1/Overview.bs
It's a mixing now.
Fixes #4174
=> [cssom] Fix ElementCSSInlineStyle section.

css-contain-1/Overview.bs
=> [css-contain] Be more rigorous about box vs element

css-ui-4/Overview.bs
"to incorporates, extends, and supersedes these."
becomes
"to incorporate, extend, and supersede these."
resolves #3976
=> [css-ui-4] Remove redundant 's', three times

css-gcpm-3/Overview.bs
Fixed indentation of closing tag
=> [css-gcpm-3] Fix propdef block markup formatting

css-grid-2/Overview.bs
Added `partial` class as in other specs
=> [css-grid-2] Add missed `partial` class in markup

css-writing-modes-3/Overview.bs
=> [css-writing-modes-3] Fix typo #4293

css-transitions-2/Overview.bs, web-animations-1/Overview.bs
[css-transitions-2] Add section of transition-timing-function and getComputedTiming (issue #4288)
=> [css-transitions-2] Add section of transition-timing-function and getComputedTiming (issue #4288)

cssom-1/Overview.bs
=> [cssom] Specify the serialization of <ratio> and linkify that section.

css-overscroll-1/Overview.bs
=> [css-overscroll-1] Remove redundant colon

css-transforms-1/Overview.bs
Fix typo : Fixes https://github.com/w3c/csswg-drafts/issues/4453
=> [css-transforms] Fixes #4453

web-animations-1/Overview.bs
=> [web-animations-1] Eliminate usage of CSSPseudoElement

css-text-3/Overview.bs
=> [css-text-3] Define interaction of bidi and eol hanging spaces

resize-observer-1/Overview.bs
As discussed in https://github.com/w3c/csswg-drafts/issues/3840
=> [resize-observer] More precise wording for "Calculate depth for node"

css-ui-4/Overview.bs
Tests: already covered by css/css-ui/appearance-cssom-001.html
Part of #3024.
---
cc @tkent-google @foolip @MatsPalmgren @emilio @jwatt
=> [css-ui] Add an issue about slider-vertical & sliderthumb-vertical

css-text-4/Overview.bs
Closes https://github.com/w3c/csswg-drafts/issues/3229
https://lists.w3.org/Archives/Public/www-style/2018Nov/0006.html
> RESOLVED: Add a new text-spacing:auto value, which is not the initial value. (Issue #3229)
=> [css-text-4] Add auto value to text-spacing

css-scroll-anchoring-1/Overview.bs
This resolves issue #3494 .
A WPT test already exists for this:
https://wpt.fyi/results/css/css-scroll-anchoring/opt-out-dynamic.html
=> [scroll-anchor-1] Add scroll-anchor suppression trigger for overflow-anchor

css-scrollbars-1/Overview.bs
[css-scrollbars-1] Add suggestions (lightly edited) to resolve #3315.
=> [css-scrollbars-1] Add suggestions (lightly edited) to resolve #3315.

css-color-4/Overview.bs
Per resolution: https://github.com/w3c/csswg-drafts/issues/4608#issuecomment-578151377
=> [css-color-4] Initial value for color is CanvasText #4608.

scroll-animations-1/Overview.bs
Remove outdated trigger syntax from example
=> [scroll-animations] Remove outdated trigger syntax from example

cssom-1/Overview.bs
=> [cssom-1] clarify resolved value of 'line-height: normal'.

scroll-animations-1/Overview.bs
Adding myself (majidvp@google.com) as editor to the spec.
Also moving Stephen (smcgruer@google.com) to former editor section.
=> [scroll-animations-1] Add majidvp as editor

scroll-animations-1/Overview.bs
Add gerchiko@microsoft.com as editor.
Also made the following updates to editors metadata:
- Update to comma-separated format expected by bikeshed: https://tabatkins.github.io/bikeshed/#metadata
- Add w3cid for existing editors
- Update affiliation for birtles@
=> [scroll-animations-1] Add gerchiko@microsoft.com as editor

css-transforms-2/Overview.bs
=> fixing typo

css-inline-3/Overview.bs
https://drafts.csswg.org/css-writing-modes-3/#text-orientation
=> [css-inline-3] text-orientation: sideways-left is not a thing

web-animations-1/Overview.bs
=> [web-animations-1] Clarify that unsupported pseudo-elements are also invalid

web-animations-1/Overview.bs
=> [web-animations-1] Mark ready and finished promise rejections as handled

css-speech-1/Overview.src.html
Could not run the regenerate script so the corresponding overview.html file is not included.
Ping @fantasai who offered to help with the bikeshed conversion.
=> css-speech-1 Adds LJWatson as editor

css-text-decor-4/Overview.bs
reflect the resolution on https://github.com/w3c/csswg-drafts/issues/4277#issuecomment-588354602
=> [css-text-decor-4] update to `text-decoration-skip-ink: all` #4277

css-ruby-1/Overview.bs
=> [css-ruby] Remove incorrect language tags, include terms in original language

css-values-4/Overview.bs
=> [css-values-4] typo: s/atr/attr/

css-scroll-snap-1/Overview.bs
=> typo fo => for

web-animations-1/Overview.bs
Adding phase to Animation Timeline requires changes to multiple spec's let me know if they can be done at once in the same PR or if they need to be split into individual PR's.
I'm sure there are some places I missed that need to reference the new timeline phase. If you can think of any please comment and let me know so I can adjust the spec as needed.
=> [web-animations-1] Added phase to Animation Timeline #4325 

css-speech-1/Overview.bs
=> Corrects editor contact information

css-inline-3/Overview.bs
Here are a few typo fixes (and one markup fix).
=> [css-inline-3] A few typo fixes.

css-inline-3/Overview.bs
Use similar phrasing to express similar idea.
=> [css-inline-3] Harmonize phrasing

mediaqueries-5/Overview.bs
Adds top-level privacy note to Media Queries Level 5 per request in issue #4832
I did my best to articulate the issue and provide the current state of affairs. Thoughts?
=> [mediaqueries-5] fixes #4832

css-text-3/Overview.bs
an legacy name alias → a legacy name alias
=> [css-text-3] Typo fix

mediaqueries-5/Overview.bs
Now that Level 5 includes all of Level 4, this can be updated in the abstract also
=> [mediaqueries-5] editorial: s/Level 3/Level 4

css-images-4/Overview.bs
=> [css-images-4] Added <element()> to <image> data type

css-color-3/Overview.html
[css-spec-shortname-1] Remove stray `;`
=> Remove stray `;`

css-inline-3/Overview.bs
[css-inline-3] removed a duplicate word
=> [css-inline-3] remove duplicate word

css-values-4/Overview.bs
I found a few typos when I was reading [css-values-4](https://www.w3.org/TR/css-values-4/), and I've fixed them in this PR.
=> [values-4] Fix typos in css-values-4 draft

css-extensions-1/Overview.bs, css-nesting-1/Overview.bs, css-scoping-1/Overview.bs, css-tables-3/Overview.bs, selectors-4/deferred-for-level-5
Fixes <https://github.com/w3c/csswg-drafts/issues/5428>
=> Update mentions of `:matches(…)` to `:is(…)` or `:where(…)`

css-pseudo-4/Overview.bs
=> [css-pseudo-4] Compatibilit{iy -> y}

cssom-1/Overview.bs
Part of https://github.com/w3c/csswg-drafts/issues/4828.
=> [cssom] Define the serialization of CSSKeyframesRule and CSSKeyframesRule

cssom-1/Overview.bs
Per https://github.com/w3c/csswg-drafts/issues/5627#issuecomment-712475204
=> [cssom-1] Drop sorting and deduplication from media query serialization.

mediaqueries-5/Overview.bs
[mediaqueries-5] Per discussions at TPAC, adding myself as an editor.
=> Add myself as mediaqueries-5 editor

resize-observer-1/Overview.bs
=> [resize-observer-1] Remove ResizeObservation from IDL index

selectors-4/Overview.bs
=> [selectors-4] Make links more precise in selectors overview table

css-values-4/Overview.bs
I found this when I was reading [css-values-4](https://www.w3.org/TR/css-values-4/#combine-colors),  I think it's color here, not number.
=> [css-values-4] Fix types in css-values-4 draft

css-contain-2/Overview.bs
[css-contain-2] Make content-visibility not animatable #5708
=> [css-contain-2] Make content-visibility not animatable #5708

css-gcpm-3/Overview.bs
=> [css-gcpm-3] Simplify syntax definitions

css-color-adjust-1/Overview.bs
=> [css-color-adjust-1] possible typo

css-text-3/Overview.bs
Not sure why it's a CG-DRAFT...
/cc @fantasai
=> [css-text-3] Fix spec status

css-break-3/Overview.bs
[css-break-3]
Bikeshed-added:
css/css-break/widows-001.html
css/css-break/widows-orphans-001.html
css/css-break/widows-orphans-002.html
css/css-break/widows-orphans-003.html
css/css-break/widows-orphans-004.html
css/css-break/widows-orphans-005.html
css/css-break/widows-orphans-006.html
css/css-break/widows-orphans-007.html
css/css-break/widows-orphans-008.html
css/css-break/widows-orphans-009.html
css/css-break/widows-orphans-010.html
css/css-break/widows-orphans-011.html
css/css-break/widows-orphans-012.html
css/css-break/widows-orphans-013.html
css/css-break/widows-orphans-014.html
css/css-break/widows-orphans-015.html
css/css-break/widows-orphans-016.html
css/css-break/widows-orphans-017.html
=> Bikeshed-added 18 widows and/or orphans tests

css-break-3/Overview.bs
Bikeshed-added 
widows-orphans-018.html 
in csswg-drafts/css-break-3
=> Bikeshed-added widows-orphans-018.html in csswg-drafts/css-break-3

css-pseudo-4/Overview.bs
WPT patch: https://github.com/web-platform-tests/wpt/pull/27454
=> [css-pseudo-4] update <wpt> for #highlight-painting

css-break-3/Overview.bs
=> [css-break-3] Incorrect closing quote

css-speech-1/Overview.bs
=> [css-speach-1] Broken closing dfn element

css-page-3/Makefile, css-page-4/Makefile
looks like these were from when there was a parent Makefile, but no longer exists
=> [css-page3/4] Remove stub Makefiles

css2/Overview.bs
Tracing back a few things that generate HTML validation issues after the Bikeshed generation
=> [css2] Bikeshed HTML cleanup

css-speech-1/Overview.bs
=> [css-speach-1] Malformed DT tag

css-print/Overview.bs
Bikeshed creates duplicate title and charset elements with these
=> [css-print] Remove duplicate metadata

css-backgrounds-4/Overview.bs
Bikeshed ending up swallowing the following paragraphs into the PRE, till it hit the ending DIV
=> [css-backgrounds-4] Missing closing PRE

css-mobile/Overview.bs
Causes 2 sets of title and meta charset tags to be output
=> [css-mobile] Remove duplicate metadata

css-2015/Overview.bs, css-2017/Overview.bs
Looks like it was fixed in subsequent years already
=> [css-2015/2017] Remove extra closing DL

web-animations-1/Overview.bs
Trips up and thinks it's a sub-DL
=> [web-animations-1] DD indent for Bikeshed

web-animations-2/Overview.bs
- Nested DDs to sublists only
- DIV indented too far, so new DL not opened
=> [web-animations-2] DL nesting issues in Bikeshed

css-color-3/issues-lc-2008.html, css-gcpm-3/2009-06-10.html, css-mobile/Overview.bs, css-page-3/implementations.htm, css-template-1/new.html, css-template-1/new2.html
Legacy tag updated with find/replace
=> fix: ACRONYM to ABBR tab

css-grid-2/Overview.bs
Apply the same changes from #5968 to _CSS Grid Layout Module Level 2_
=> [css-grid-2] Specify height in example 8 for #grid

css-highlight-api-1/Overview.bs
Resolves issue [6032](https://github.com/w3c/csswg-drafts/issues/6032).
=> [css-highlight-api] Fix examples' Ranges

css-color-5/Overview.bs
=> Fixes note about 100% and 0% usage with `color-mix()`

css-fonts-5/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/6075
=> [css-fonts-5] Add size-adjust @font-face descriptor

css-transforms-2/Overview.bs
As discussed at the start of the March 24 teleconference, adding myself as an editor.
=> [css-transforms-2] Add myself as a co-editor.

css-cascade-5/Overview.bs
possible fixes for new in level 5. (also would like to ask this readings are correct)
(found during, but not related to an i18n review on css-cascase-4/5)
=> [css-cascade-5] possible typo

css-fonts-4/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/6190.
=> [css-fonts-4] font-optical-sizing interacts with font-size-adjust

css-nesting-1/Overview.bs
Fix an example of what a specific nesting would be equivalent to in css.
=> [css-nesting-1] Fix css example in nesting draft https://drafts.csswg.org/css-nesting-1/

css-color-4/Overview.bs
=> Typo: issue with 'isse'

css-values-3/implementation-report.html
Important:
**There are notes about tests and Issues at the bottom of the source code of the file**
=> Created implementation report for css-values-3

css-align-3/Overview.bs
Swap wrong left/right figure references
=> [css-align-3] fix figure description

css-color-4/Overview.bs
Related to f1e9daa830dbbed021d599e5adb3f0343e16fc56 (remove `lab` from `color()`)
=> [css-color-4] Use lab() in example

selectors-4/Overview.bs
This should not land until https://github.com/whatwg/html/pull/6603 lands in HTML.
=> [selectors-4] Match HTML's use of certain terms defined in it.

cssom-1/Overview.bs
=> [cssom] Fix xml-stylesheet link.

css-logical-1/Overview.bs
Signed-off-by: Jens Oliver Meiert <jens@meiert.com>
=> [css-logical] Made headings more consistent (re: #6492)

css-nesting-1/Overview.bs
Can be merged after the publication of FPWD.
=> [css-nesting] Link to /TR

css-scoping-2/Overview.bs
=> [css-scoping-2][editorial] Fix typo: it's -> its

css-cascade-5/Overview.bs
The code example was missing a comma. This PR fixes it.
=> [css-cascade-5] Add Missing Comma

css-fonts-4/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/6633.
=> [css-fonts] [palettes] font-palette cannot be expanded in the future

css-fonts-4/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/6622.
=> [css-fonts] [palettes] Remove the none value from font-palette

web-animations-2/Overview.bs
The web-animations-1 editors went through an update and it seems that web-animations-2 should follow along.
=> [web-animations-2] Update editors

css-cascade-4/Overview.bs
I added myself to the contributor list of `[css-cascade-4]` as per https://github.com/w3c/csswg-drafts/pull/6715#issuecomment-963751277
I also contributed to the following, but they don't have a general acknowledgement section so not sure how to do that:
- `[css-images-4]`
- `[css-shapes-2]`
- `[css-color-4]`
- `[css-fonts-4]`
=> [css-cascade-4] Add myself to contributor list

css-values-4/Overview.bs, cssom-1/Overview.bs
Closes https://github.com/w3c/csswg-drafts/issues/6883
=> [css-values-4][cssom-1] Editorial: alignm with fetch algorithm rename

css-color-5/Overview.bs
=> Choropleth is a more common spelling

selectors-4/Overview.bs
The intent was to make the direction more readable and remove ambiguity.
=> [selectors-4] Added the word "for"

selectors-4/Overview.bs
Propose removing "simply" as it is not inclusive language.
=> [selectors-4] Remove the word "simply"

css-pseudo-4/Overview.bs
This patch makes some trivial changes to improve readability.
=> [css-pseudo] non-substantive prose tweaks

css-backgrounds-4/Overview.bs
As of the [resolutions of February, 3rd](https://lists.w3.org/Archives/Public/www-style/2022Feb/0001.html), I've added myself as co-editor of CSS Backgrounds 4.
Sebastian
=> [css-backgrounds-4] Added myself as editor

css-fonts-4/palette-explainer.md
As I am filing a FYI tag review, adding an explainer for font-palette.
=> Add explainer for CSS-fonts-4 `font-palette`

web-animations-1/Overview.bs
=> [web-animations-1] Fix play an animation procedure

css-conditional-3/Overview.bs
As per https://github.com/w3c/csswg-drafts/issues/6819.
=> [css-conditional] Make conditionText readonly.

css-ui-4/Overview.bs
=> [css-ui] Remove Animation Origin for 'appearance' disabling

css-contain-3/Overview.bs
=> [css-contain-3] Allow duplicate container names. #7181

css-animations-1/Overview.bs, css-transitions-1/Overview.bs
=> [css-animations-1][css-transitions-1] Associate event definitions with their EventHandler container

css-values-4/Overview.bs
Fixiing a small mistake in previous patch
=> Editorial: [css-values-4] initiator -> initiator type

web-animations-2/Overview.bs
[web-animations-2] Fix styling.
Addresses a few styling inconsistencies with web-animations-1, namely:
* Informational blocks
* Programming interface
=> [web-animations-2] Fix styling.

css-contain-2/Overview.bs
https://github.com/w3c/csswg-drafts/issues/7384
=> [css-contain-2] Add ContentVisibilityAutoStateChanged event (issue #7384)

css-animations-2/Overview.bs
`animation-name` and name of `@keyframe` didn't match
=> [css-animation-2] typo

scroll-animations-1/Overview.bs
=> [scroll-animations-1] Remove <custom-ident> from scroll() notation

css-contain-2/Overview.bs
[css-contain-2] Update 'Update the Rendering' step number
=> [css-contain-2] Update 'Update the Rendering' step number

css-fonts-4/Overview.bs, css-writing-modes-3/Overview.bs
I corrected a few mistakes such as `the these` (instead of `these`).
=> Fix mistakes

css-grid-2/Overview.bs
Fix a simple spelling mistake.
=> [css-grid-2] Fix simple spelling mistake

css-shared-element-transitions-1/Overview.bs
[css-shared-element-transitions-1] Add more non-normative text in the SET spec
=> [css-shared-element-transitions-1] Add more non-normative text in the SET spec

resize-observer-1/Overview.bs
As per suggestion in https://github.com/whatwg/html/pull/8348.
=> [resize-observer] Tweak naming to include "resize" on algorithm / etc names.

resize-observer-1/Overview.bs
This is now upstream.
Fixes #4824
=> [resize-observer] Remove HTML monkey patch.

bin/build-index.py
For the GH Pages deployment, this change generates a timestamps.json file that maps each shortname in the repo to a timestamp representing the time for the most recent commit of corresponding Bikeshed source file for that shortname — enabling any downstream users/consumers of the deployed GH Pages specs to have accurate last-committed data for all sources.
I have immediate use for this timestamp data for the https://html-now.github.io/ dashboard and can imagine that others might end up having good use for the timestamp data as well.
=> [gh-pages] Generate timestamps.json file w/ git timestamps for sources

css-nesting-1/proposals.md
[css-nesting] Added my preference to the table
=> [css-nesting] Syntax preference feedback

css-nesting-1/proposals.md
=> [css-nesting-1] Syntax preference feedback

css-sizing-3/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/7206#issuecomment-1218336931
=> [css-sizing-3] Add note to clarify indefiniteness of intrinsic size keywords

css-view-transitions-1/Overview.bs
Spec edits for the following issues:
- https://github.com/w3c/csswg-drafts/issues/7812
- https://github.com/w3c/csswg-drafts/issues/7784
- https://github.com/w3c/csswg-drafts/issues/7813
- https://github.com/w3c/csswg-drafts/issues/7560
=> [css-view-transitions-1] Update spec from resolved issues

scroll-animations-1/Overview.bs
This PR adds a `>` that is missing.
=> [scroll-animations-1] Fix link to type

selectors-4/Overview.bs
Fix typo: pseudo-eleent → pseudo-element
Non-substantive contributions
For simple spelling, grammar, or markup fixes unrelated to the substance of a specification, issuing a pull request without a corresponding issue is acceptable.
=> Fix typo: pseudo-eleent → pseudo-element

css-color-4/Overview.bs
[css-color-4] Fix grammar in #convert-destpolar
=> [css-color-4] Fix grammar in #convert-destpolar

css-text-4/Overview.bs
This pull request was made with respect to issue #7301
=> Replaced <length-percentages> by <length-percentage> referencing to issue #7301

css-overflow-3/Overview.bs
Addresses #8194 #7303 #7237 and does some additional editorial cleanup.
=> Define scroll terminology

selectors-4/Overview.bs
Makes at-risk features list consistent with the Changes section according to the resolution of #8168
=> [selectors-4] Remove at-risk status from :has() and :read-write

css-view-transitions-1/Overview.bs
This was reviewed in https://github.com/jakearchibald/csswg-drafts/pull/3
=> [css-view-transitions-1] Rearrange algorithms

css-text-3/Overview.bs
As per https://github.com/w3c/csswg-drafts/issues/8279
=> [css-text-3] Strengthen language about conformant use of text-transform

css-animations-2/Overview.bs
This change fixes typos in the Changes section and adds links to the defined properties and interface.
Sebastian
=> [css-animations-2] Fixed Changes section and added links

scroll-animations-1/Overview.bs
=> [scroll-animations-1] Add entry-crossing and exit-crossing timeline ranges

css-rhythm-1/Overview.bs
=> [css-rhythm-1] Remove duplicate animation type fields

css-conditional-5/Overview.bs
=> [css-conditional-5] Fix dfn of "<font-format>"

scroll-animations-1/Overview.bs
Fixes #8644. Full questionnaire answers added in #8645
=> [scroll-animations-1] Add privacy and security considerations sections.

css-text-4/Overview.bs
This PR added the Unicode General Category for nonspacing marks.
=> [css-text-4] Add Unicode Category for nonspacing marks

css-cascade-6/Overview.bs
=> [css-cascade-6] Make CSSScopeRule.start/end optional

css-cascade-6/Overview.bs
=> [css-cascade-6] Remove strong scoping proximity

css-cascade-6/Overview.bs
=> [scroll-animations] Clarify proximity with nested @scope rules

css-animations-2/Overview.bs
This aims to fix #8507 and #8487 as well as make the section more correct overall and easier to read, understand, and reference.
=> Rewrite Keyframe Processing

css-text-3/Overview.bs, css-text-4/Overview.bs
Change U+201D RIGHT DOUBLE QUOTATION MARK to U+201C LEFT DOUBLE QUOTATION MARK.
=> [css-text] Editorial fix

cssom-1/Overview.bs
=> [cssom] Allow CSSImportRule.styleSheet to be null.

css-anchor-position-1/Overview.bs
=> [css-anchor-1] Change anchor-scroll's initial value to default

css-ui-4/Overview.bs
=> [css-ui] Remove slider-horizontal, square-button, push-button from <compat-auto>

css-view-transitions-1/Overview.bs
Comments and explanations in the commit messages... feel free to ask me for explanations if there's anything here that isn't self-evident.
=> Editorial (first pass)

cssom-1/Overview.bs
=> [cssom] Don't handle CSSViewportRule since it's no longer a thing.

web-animations-1/Overview.bs
* Apply semantic line breaks throughout https://rhodesmill.org/brandon/2012/one-sentence-per-line/
* Fix indentation
* Fix/update markup
* Fix punctuation (commas, etc.)
* Live: https://fantasai.inkedblade.net/style/specs/web-animations-1/Overview
* Diff: https://services.w3.org/htmldiff?doc1=&doc2=https%3A%2F%2Ffantasai.inkedblade.net%2Fstyle%2Fspecs%2Fweb-animations-1%2FOverview
=> [web-animations-1][editorial] Reformat

css-color-5/Overview.bs
Reverts w3c/csswg-drafts#8631 as requested https://github.com/w3c/csswg-drafts/issues/8609#issuecomment-1490858163
=> Revert "[css-color-5] fix mention of powerless components"

css-values-4/Overview.bs
=> [css-values-4] Fix numeric type of acos/asin/atan/atan2

css-backgrounds-4/Overview.bs, css-borders-4/Overview.bs
Updated and corrected the Changes sections of CSS Backgrounds 4 and CSS Borders 4 and added issues for the missing features mentioned in those sections.
Sebastian
=> [css-backgrounds-4][css-borders-4][editorial] Added proper Changes sections

css-borders-4/Overview.bs
@Loirooriol provided a lot of good feedback lately, so he deserves to be mentioned in the Acknowledgements section.
Sebastian
=> [css-borders-4] Added Oriol Brufau to acknowledgements

css-anchor-position-1/Overview.bs
Proposed spec text for the `align/justify-self: anchor-center;` value discussed in #8979.
=> [css-anchor-position-1] Add justify/align-self:anchor-center value. #8979

css-transitions-2/Overview.bs
=> [css-transitions-2] Fix mismatched closing tag

scroll-animations-1/Overview.bs
=> [scroll-animations-1] Add view-timeline-inset to shorthand

css-ruby-1/Overview.bs
- Add language tags
- Change U+3000 to U+0020 in English
=> [css-ruby] Editorial fixes

web-animations-2/Overview.bs
Fix typo and formatting glitches with switch.
=> [web-animations-2] Cleanup of markup formatting.

css-anchor-position-1/Overview.bs
For #8837 
Following resolution https://github.com/w3c/csswg-drafts/issues/8837#issuecomment-1690145010
=> [css-anchor-position-1] Make anchor-name a list

cssom-1/Overview.bs
=> [cssom-1] Throw explicit SyntaxError DOMException

css-fonts-4/Overview.bs
=> [css-fonts-4] Define production for <family-name>

css-gcpm-3/Overview.bs
=> [css-gcpm-3] Fix refs to element() and running()

css-text-4/Overview.bs
See https://github.com/w3c/webref/blob/ba9ca967febd9816653d4a97133a870da92178c7/ed/css/css-text-4.json#L556 and https://speced.github.io/bikeshed/#autolink-wrappers.
=> [css-text-4] Fix property value range annotation

css-fonts-4/Overview.bs
=> [css-fonts-4] Define src with <font-src-list>

css-ui-4/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/7542
=> [css-ui-4] Add 'field-sizing' property

css-grid-3/Overview.bs
[css-grid-3][masonry] Add Brandon Stewart as an editor to Masonry Spec
=> [css-grid-3][masonry] Add Brandon Stewart as an editor to Masonry Spec

css-counter-styles-3/Overview.bs
https://github.com/w3c/csswg-drafts/issues/8636#issuecomment-1591665495
https://lists.w3.org/Archives/Public/www-style/2023Jun/0003.html
=> [css-counter-styles] Require i18n's Ready-Made Counter Styles #8636

css-shapes-2/Overview.bs
=> [css-shapes-2] Make shape-padding consistent with shape-margin

css-view-transitions-1/Overview.bs
As per resolution
Closes #9616
=> [css-view-transitions-1] Add a note about why view-transition-name is animatable

web-animations-2/Overview.bs
Fix reference to outdated spec at the same time
=> [web-animations-2] Use auto-links for canvas

css-page-3/Overview.bs
=> [css-page-3][editorial] Fixed grammatical mistake

css-color-4/Overview.bs
This fixes the issues I outlined in https://github.com/w3c/csswg-drafts/commit/7148b31cbc862faba3c1e6f6dcd481d2a06d47b7.
Sebastian
=> [css-color-4] Fixed a few issues regarding hue interpolation

mediaqueries-5/Overview.bs
Change it to an author suggestion. Closes #9674. cc @emilio
=> [mediaqueries-5] Remove inverted-colors UA rule (fixes #9674)

css-view-transitions-1/Overview.bs
=> Fix merge error from previous commit

css-fonts-4/Overview.bs
=> [css-fonts-4] Fix markup #9969

css-color-4/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/8311#issuecomment-1919596811.
> I agree that a production rule needs to be added.
=> [css-color-4] Add production rule for <opacity-value>

css-text-4/Overview.bs
Minor change.
(Would be open to prepare additional corrections, e.g., to ensure consistency in headings case and some such.)
=> [css-text] Add missing space

css-viewport/Overview.bs
=> Add clarification that viewport properties are not divided by CSS zoom

css-viewport/Overview.bs, cssom-view-1/Overview.bs
=> [cssom-viewport] Add specification for `currentCSSZoom`

css-scrollbars-1/Overview.bs
@frivoal I think you meant to say paint here?
=> chore: typo in css-scrollbars

css-view-transitions-1/Overview.bs
Closes https://github.com/w3c/csswg-drafts/issues/10101.
=> [css-view-transitions-1] Apply resolutions for hidden document state

css-view-transitions-2/Overview.bs
=> [css-view-transitions-2] Update remaining instances of "type" to "types"

css-nesting-1/Overview.bs
=> [css-nesting-1] Fix typo

cssom-view-1/Overview.bs
=> [cssom-view] Fix offsetParent to refer to effective zoom as a stopping point

css-view-transitions-2/Overview.bs
Applies suggestions from https://github.com/w3c/csswg-drafts/issues/10283.
=> [css-view-transitions-2] Updates for horizontal review

css-viewport/Overview.bs
=> [css-viewport] Add clarification that path() contents are zoomed

css-conditional-5/font-tech-format-explainer.md
=> [css-conditional-5] Remove redundant “to”

css-nesting-1/Overview.bs, css-syntax-3/Overview.bs, cssom-1/Overview.bs
=> [css-nesting] Retire @nest, introduce the 'nested declarations rule'

css-color-5/Overview.bs
=> [css-color-5][editorial] Fix serialization form of mixed colors (#10415)

css-viewport/Overview.bs
[css-viewport] Fix bikeshed errors so the spec can be generated.
=> [css-viewport] Fix bikeshed errors so the spec can be generated.

css-grid-3/Overview.bs
Remove masonry-auto-flow based on the resolution here: https://github.com/w3c/csswg-drafts/issues/10231
=> [css-grid-3] Remove masonry-auto-flow

css-fonts-4/Overview.bs
Remove trailing backticks in syntax.
=> [css-fonts-4][editorial] Typos

mediaqueries-5/Overview.bs
Per resolution at https://github.com/w3c/csswg-drafts/issues/6517#issuecomment-2220975121 this adds me as a co-editor of the Media Queries Level 5 spec.
=> [mediaqueries-5] Add myself (Luke Warlow) as co-editor.

bin/requirements.txt
Casual find after Snyk complained about this in my csswg-drafts fork. Filing PR after [brief chat](https://github.com/j9t/csswg-drafts/pull/1#issuecomment-2265045632) with @tabatkins.
----
The following vulnerabilities are fixed by pinning transitive dependencies:
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-5798483
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-6057353
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-6091621
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-6091622
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-6091623
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-6209406
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-6209407
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-6645291
- https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-6808823
- https://snyk.io/vuln/SNYK-PYTHON-CERTIFI-5805047
- …
=> [css-?] Update bin/requirements.txt to reduce vulnerabilities

css-conditional-5/scroll_state_explainer.md, css-conditional-6/scroll_state_explainer.md
Container queries now moved to css-conditional.
=> [css-conditional-5] Update references and resolution to add scroll-state() to explainer

css-conditional-5/Overview.bs
Adjusted out-of-date example. Editorial change.
=> [css-conditional-5] There is no container-type:style

css-variables-1/Overview.bs
=> [css-variables-1] Fix typo in css-variables-1/Overview.bs

css-images-4/Overview.bs
=> [css-images-4][editorial] Use radial- rather than rg-

css-anchor-position-1/Overview.bs
For typographical happiness :D
=> “3x3” → “3×3”

css-pseudo-4/Overview.bs
Context:
https://github.com/w3c/csswg-drafts/issues/10440#issuecomment-2357498781
=> [css-pseudo-4] Fix grammer for ::picker

css-nesting-1/Overview.bs
Fix typo in example.
Fixes #9283
=> [css-nesting-1] Fix exponential explosion example

cssom-1/Overview.bs
=> [cssom] Don't serialize empty rules (@media)

css-ui-4/Overview.bs
Fix animmations -> animations typo
- Typo on line 1247.
- Fixes #11132
=> [css-ui-4] Fix animmations -> animations typo

css-position-3/Overview.bs
=> [css-position] Fix obsolete references to `inset-area`

css-position-4/Overview.bs
[css-position-4] Small wording tweak to match the relevant section in the [HTML spec](https://html.spec.whatwg.org/#update-the-rendering) so it's easier to search for.
=> [css-position-4] small wording update

css-overflow-5/carousel-explainer.md
Adds an explainer which talks through the problem space being solved and the high level details of the solution.
=> [css-overflow-5] Add an explainer for carousel CSS features.

css-anchor-position-1/Overview.bs
No associated issue, this is very minor, but I _think_ this is what was intended?
=> [css-anchor] Minor editorial

selectors-4/Overview.bs
This is as resolved in #8637.
Fixes #8637.
=> [selectors-4] Add :popover-open pseudo-class.

css-2024/Overview.bs
This change adds a new section "Reliable Candidate Recommendations" including the specs Media Quries 4, CSS Scroll Snap 1, CSS Scrollbars 1, and CSS Grid 1 and 2.
This was resolved in https://github.com/w3c/csswg-drafts/issues/9770#issuecomment-2474321674.
Sebastian
=> [css-2024] Added new section "Reliable Candidate Recommendations"

css-images-3/Overview.bs
It's "a natural thing", not "an natural thing"
=> [css-images-3] Fix some a/an related typos

css-grid-1/Overview.bs
=> [css-grid-1] Gloss in-flow/out-of-flow jargon

css-env-1/Overview.bs
This PR specifies the `safe-area-max-inset-*` envvars.
Fixes #11019.
=> [css-env-1] Spec safe-area-max-inset-* envvars

css-color-5/Overview.bs, css-easing-2/Overview.bs
=> [css-color-5] Fix markup

css-borders-4/Overview.bs
No need for /, and can have 1-4 values.
=> [css-borders-4] Clean up 'corner-shape' shorthand

web-animations-2/Overview.bs
=> Removed bad syntax adding defaults to interface attributes + any instead of dictionaries as attribute types

selectors-4/Overview.bs
This PR makes a few minor terminology changes to the Partitioned :visited links algorithm footnote.
=> [selectors-4] Terminology edits to the :visited footnote #11151

css-forms-1/Overview.bs
[css-forms-1] Define `::color-swatch` pseudo element
See #11837
=> [css-forms-1] Define `::color-swatch` pseudo element

css-forms-1/Overview.bs
Previously input buttons didn't get all the styles of buttons.
=> [css-forms-1] Add input buttons to selectors for buttons

css-counter-styles-3/Overview.bs
Follow up of https://github.com/w3c/csswg-drafts/pull/11883#issuecomment-2711456259.
=> [css-counter-styles-3] Explicitly tell when the counter style is not defined

web-animations-2/Overview.bs
Fixed some errors and warnings from bikeshed
=> [web-animations-2] Editorial: fixed some bikeshed errors and warnings

css-forms-1/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/11893
=> [css-forms-1] Add textual inputs to pseudo elements table

css-color-hdr-1/Overview.bs
=> [css-color-hdr-1] Remove duplicate productions

cssom-1/Overview.bs
Exactly what it says on the tin.
This is non-substantive.
=> [cssom-1] Fix typo in Overview.bs

css-view-transitions-2/Overview.bs
=> [css-view-transitions-2] `view-transition-name: auto` with ID should only match other IDs

css-view-transitions-2/Overview.bs
=> [css-view-transitions-2] Fix typo

cssom-1/Overview.bs
This should be non-substantive.
=> [cssom-1] Fix typo

css-view-transitions-1/Overview.bs
=> [css-view-transition-1] Fix typos

selectors-3/Overview.html
=> [selectors-3] Fix typo

css-forms-1/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/11837
=> [css-forms-1] Remove inline issue regarding color-swatch name

css-forms-1/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/9830
=> [css-forms-1] Add slider- prefix to slider pseudo-element names

css-multicol-2/column-wrap-explainer/explainer.md
[css-multicol-2] Column-wrap explainer
TAG wants it here, rather than in a personal repo.
See https://github.com/w3ctag/design-reviews/issues/1073#issuecomment-2812600843
Previously added here: https://github.com/mstensho/column-wrap
=> [css-multicol-2] Column-wrap explainer

css-gaps-1/Overview.bs
Add a trailing slash to the ED to avoid a redirect
=> add trailing slash to ED

css-sizing-4/responsive-iframes-explainer.md
=> [css-sizing-4] Create responsive-iframes-explainer.md

css-conditional-5/Overview.bs
Resolution:
https://github.com/w3c/csswg-drafts/issues/10982#issuecomment-2898572289
=> [css-conditional-5] Explicitly allow tree counting functions #10982

pointer-animations-1/Overview.bs
Beginning to draft the first ED of `pointer-animations-1`.
This spec has interrelations with `scroll-animations`/`css-animations`/`web-animations` hence:
/cc @flackr @fantasai @bramus @birtles 
Also FYI @noamr @kizu @astearns
=> Initial editor's draft of pointer-animations-1

css-borders-4/Overview.bs
Resolution:
https://github.com/w3c/csswg-drafts/issues/12194#issuecomment-2917026075
Closes #12194
=> [css-borders-4] Add a general note about outline bordering and corner-shape

css-animations-2/Overview.bs
No text changes, fixes some linking.
=> [css-animations-2] Fix bikeshed errors

css-borders-4/Overview.bs
"super-ellipse()" -> "superellipse()"
=> [css-borders-4] Typo

css-align-3/Overview.bs
There was this little whitespace hanging around. I think we can remove it.
=> [css-align-3] Remove additional whitespace

css-2025/Overview.bs
=> [css-2025] Added URL modifiers to Safe to Release pre-CR Exceptions

css-view-transitions-2/Overview.bs
[css-view-transitions-2] add activeViewTransition definition
Closes #12407
=> [css-view-transitions-2] add activeViewTransition definition

css-conditional-4/Overview.bs
=> [css-conditional-4][editorial] Fixed examples

css-2025/Overview.bs
Related resolutions:
- https://github.com/w3c/csswg-drafts/issues/12702#issuecomment-3249667615
- https://github.com/w3c/csswg-drafts/issues/12692#issuecomment-3249673391
- https://github.com/w3c/csswg-drafts/issues/12694#issuecomment-3249713181
=> [css-2025] Added CSS Cascade 5, CSS Color Adjust 1, and CSS Conditional 4 to Reliable CRs

cssom-view-1/Overview.bs
I added all the Web Platform Tests that currently cover the features in CSSOM View 1.
Sebastian
=> [cssom-view-1][editorial] Added WPTs

css-fonts-4/Overview.bs
=> [css-fonts] Add notes for system-ui #3658

css-link-params-1/Overview.bs
Just correcting a little error
=> [css-link-params-1] Use dashed ident in example
