w3c/csswg-drafts

- css-values-3/Overview.bs
"This unquoted syntax ~is~ cannot accept a <url-modifier> argument ..."
> [css-values-3] Fix minor typo

- css-color-4/Overview.bs
Working my way through the spec top-to-bottom as a new reader, so, I notice these things...
* Split out conceptual definitions from syntactic definitions, pulling the former up into the main section intro.
* Define “color function” properly as a term.
*  Give an actual overview of all the color syntaxes in the intro, so readers have a map of what's coming.
* Push legacy syntax into its own subsection.
* Factor `<alpha-value>` into its own section, rather than as a paragraph of the rgb() section.
* Shift non-normative text about hue angles into a note.
> Editorial Refactor of <color> Definition Section

- web-animations-2/Overview.bs
[web-animations-2]: Cleanup all build warnings in prep for transition to editor's draft.  As before and after phases for timelines have been deprecated, these are also removed as part of the cleanup.
> [web-animations-2] Clean build warnings and remove obsolete hold phase

- mediaqueries-4/Overview.bs
- mediaqueries-5/Overview.bs
This fixes the grouping in the `<general-enclosed>` production so that
both sides of the | are grouped with [].
It also applies that fix and the prior fix in #6799 to mediaqueries-5.
> Fix grouping in <general-enclosed> and apply earlier fixes to mediaqueries-5.

- selectors-4/Overview.bs
All of the things talked about in [the subsections of 14.4](https://www.w3.org/TR/selectors/#typed-child-index) ('this section') are pseudo-classes, not pseudo-elements.
(Unless I'm misunderstanding or missing something, which is entirely possible!)
> [css-selectors-4] Fix typo in selectors

- cssom-view-1/Overview.bs
The `resize` and `scroll` event definitions need to be completed to account for the newly introduced `VisualViewport` target.
This update also adjusts the firing phrasing related to `VisualViewport` for consistency with the rest of the spec (other alignments are covered in #7466) and fixes a typo.
> [cssom-view-1] Fix dfns for events that target VisualViewport

- cssom-view-1/Overview.bs
Also, fix interface of the event in the summary table to be MediaQueryListEvent
> [cssom-view-1] Align phrasing for change event firing with DOM spec

- resize-observer-1/Overview.bs
This PR incorporates [this resolution](https://github.com/w3c/csswg-drafts/issues/4032#issuecomment-510137495) on the interactions between SVG and ResizeObserver into the spec:
> RESOLVED: svg elements generating css layout boxes are included as part of resize observer and resize observer rectangles with a definition of `svg:root, *:not(svg|*) > svg, svg|foreignObject > svg { /* SVG elements with CSS layout box */}
I wonder if this resolution is still intended to be included in the spec. This PR can be closed if not. Thanks!
> [resize-observer-1] Include SVG elements that generate CSS layout boxes #4032

- mediaqueries-4/Overview.bs
- mediaqueries-5/Overview.bs
This text is based on that in [Cascade 4](https://www.w3.org/TR/css-cascade-4/#filtering).
(Maybe this isn't editorial, maybe it's a correction that does not add new features, given we don't seem to have interop here, but at least to me the intent of this text seems clear and unambiguous?)
> [Editorial] Clarify what "disallowed" values are

- css-color-4/Overview.bs
I suspect typos in example 4 and example 26.
> Tipo about lime

- css-cascade-5/Overview.bs
The `<<layer-name>>` in the `layer()` function in the `@import` syntax cannot be omitted.
```
@import [ <<url>> | <<string>> ]
[ layer | layer(<<layer-name>>) ]?
<<import-condition>> ;
```
This means that the following example is wrong, `()` should be removed.
```css
@import url("override.css") layer();
```
> [css-cascade-5] fix example syntax error for `@import layer;`

- css-fonts-4/Overview.bs
It isn't actually marked as a proper Bikeshed 'term,' so there will be no broken links.
> [css-fonts-4] Rename "system font fallback" to "installed font fallback" to avoid confusion with the system font

- css-display-3/Overview.bs
This text in the Introduction:
> the most commonly used type is the the Dom
The extra 'the' was removed
> [css-display-3] Fix a minor typo in the introduction #7652

- css-color-4/conversions.js
This matches the behavior of the other color conversions and avoids returning `NaN` if `val < -Et2`, which I assume was not the intention.
> [css-color] Use absolute value in lin_ProPhoto

- css-contain-3/Overview.bs
- Add containerName, containerQuery.
- Reorganize syntax so that conditionText and containerQuery both map
to productions which make sense.
#7033
> [css-contain-3] Improve CSSContainerRule

- css-text-3/Overview.bs
- css-text-4/Overview.bs
Fix a small grammar issue by removing an extra "is" that shouldn't be there, and have better/more consistent wording by switching around parts of a sentence, which makes it easier to read and makes it consistent with the way it's written elsewhere in the spec.
> [css-text-3][css-text-4] Fix grammar and have better/more consistent wording in § 4.1.2

- css-fonts-4/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/7683.
> [css-fonts-4] Group font-variant sub-property symbols

- scroll-animations-1/Overview.bs
Addresses remaining points in https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1175722383
> [scroll-animations-1] Define named view timeline phases and their usage. #7044

- css-conditional-5/font-tech-format-explainer.md
Preparation for Blink Intent-to-ship.
> [css-conditional-5] Add explainer for `font-tech()`,`font-format()` Conditionals Syntax

- scroll-animations-1/Overview.bs
> [scroll-animations-1] Fix formal syntax of animation-delay-(start|end)

- css-images-4/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/7803.
> [css-images-4] Fix format() typo in image-set()

- css-grid-2/Overview.bs
Looked like dust on the screen, but then it scrolled with the text.
> [css-grid-2] Remove U+0323 COMBINING DOT BELOW

- css-color-4/hslToRgb.js
- css-color-4/hwbToRgb.js
- css-color-4/rgbToHsl.js
- css-color-4/rgbToHwb.js
This adds JSDoc comments to the color conversion functions of css-color-4, in order to indicate the expected and returned value ranges.
> [css-color-4] Add JSDoc comments to color example functions

- bin/templates/redirect.html.j2
In the https://w3c.github.io/csswg-drafts/ mirror, if you append a spec's shortname without a level to the URL (https://w3c.github.io/csswg-drafts/css-grid, for example), you land on a page that redirects you to the current work of that spec. However, if you add a fragment to the URL, that fragment goes away in the redirect. This is an issue for MDN, for example.
The fragment goes away because currently redirects happen with meta refresh. This change uses `<noscript>` to make sure such redirects keep working when scripting is disabled, and then does a JS-based redirect that does preserve the fragment.
> Fix the auto-builder redirect pages to maintain the URL fragment

- css-overflow-3/Overview.bs
Some (hopefully helpful) grammatical fixes after some initial reading.
> [css-overflow-3] Fix simple grammatical error.

- css-highlight-api-1/Overview.bs
#6665 rewrote #default-styles to align ::highlight() inheritance and paired defaults with the other highlight pseudos. The term “default highlight colors” was renamed to “paired default highlight colors” before merging, but I forgot to rename it in the highlight API spec. This patch fixes that.
> [css-highlight-api] fix paired defaults terminology

- css-view-transitions-1/Overview.bs
[css-view-transitions-1] Rename shared element transition -> view transition
> Rename shared element transition -> view transition

- css-view-transitions-1/Overview.bs
[css-spec-shortname-1] Pending transform operations before IntersectionObserver
Input from the DOM to generate styles for pseudo-elements should happen after ResizeObserver but before IntersectionObserver.
> Pending transform operations before IntersectionObserver

- css-view-transitions-1/Overview.bs
[css-view-transitions-1] Clarify outgoing capture timing for view transition.
> Clarify outgoing capture timing for view transition

- css-pseudo-4/Overview.bs
This patch makes edits for #7101, adding ‘text-underline-position’, ‘text-underline-offset’, ~~and ‘text-emphasis-color’~~ to the list of those applicable to highlight pseudos.
> [css-pseudo] allow underline-related properties on highlights (closes #7101)

- css-viewport/Overview.bs
[css-viewport-1] Add 'interactive-widgets' to viewport meta
This describes the proposed `interactive-widgets` property of the viewport meta tag for describing the expected behavior when a virtual-keyboard-like widget is shown.
> [css-viewport-1] Add 'interactive-widgets' to viewport meta

- css-fonts-4/Overview.bs
Removed font-variant descriptor example.
Changes from the March 15 2018 CSS Fonts 3 Candidate Recommendation ‘font-variant’ descriptor moved to CSS Fonts 4 due to lack of implementations  
And then…
17.5. Changes from the 20 September 2018 Working Draft Remove font-variant @font-face descriptor per WG resolution  
All references have been removed, other than this example.
> Remove font-variant descriptor example

- cssom-1/Overview.bs
The CSS Animations specification says that keyframe names that are CSS wide values, or "default", or "none", should be treated as strings when serialized.
This patch also adds a missing " { " output step.
This is already partially covered by the WPT css/cssom/CSSKeyframesRule.html.
> [cssom] CSSKeyframesRule name serialization should sometimes be escaped

- css-nesting-1/proposals.md
Added my preferences to the table. (second attempt - hope I don't overwrite another line this time)
> [css-nesting] Syntax preference feedback

- .github/workflows/build-specs.yml
This change causes the GH Pages build to do a full clone rather than a shallow clone. This is necessary in order to get the correct timestamps for all sources (see https://github.com/w3c/csswg-drafts/pull/7898).
Otherwise, without this change, git doesn’t report accurate timestamps for any sources; instead it reports the same timestamp for all of them — which is apparently whatever the current time is when git creates the (shallow) clone.
> [gh-pages] Do full clone rather than shallow clone

- css-cascade-5/Overview.bs
There is no `setPropertyValue()` method, change to `setProperty()`
> [cascade-5] Fix CSSOM example in legacy alias name

- css-view-transitions-1/Overview.bs
I corrected a few warnings and added issues for the rest.
> [css-view-transitions-1] Fix warnings, add issues for currently unfixable warnings

- css-view-transitions-1/Overview.bs
Rename everything based on resolution at https://github.com/w3c/csswg-drafts/issues/7960. This also includes a tentative rename for page-transition-image-wrapper to keep the spec consistent.
> [css-view-transitions-1] Rename all CSS properties and associated concepts

- css-view-transitions-1/Overview.bs
Fixes #8000. 
As well as formatting, I:
- Fixed a bunch of links
- Used "old" and "new" consistently for the images
- Used "name" or "transition-name" consistently rather than "tag"
There aren't any normative changes.
> [css-view-transitions-1] The big reformat

- selectors-4/Overview.bs
Wasn't clear whether the resolution mapped both `:lang()` and `:lang("")` or just `:lang("")` ...
> [selectors-4] Make empty language strings match untagged elements. #6915

- css-view-transitions-1/Overview.bs
Applies resolutions from following issues:
- https://github.com/w3c/csswg-drafts/issues/7956
- https://github.com/w3c/csswg-drafts/issues/7874
- https://github.com/w3c/csswg-drafts/issues/7812
> [css-view-transitions-1] Update spec for resolved issues.

- css-nesting-1/Overview.bs
@tabatkins @argyleink 
`@layer` already defines how nesting multiple `@layer` rules works.
In that case sub layers are created.
```css
@layer foo {
@layer bar {
}
}
/* equivalent to */
@layer foo.bar {}
```
> [css-nesting] fix `@layer` example

- css-animations-1/Overview.bs
> [css-animations-1] Define indexed property getter for CSSKeyframesRule

- web-animations-1/Overview.bs
[web-animations-1] Maintain start time when changing playback rate for non-monotonic animations
Animations associated with non-monotonic timelines typically anchor to the start of their associated timeline. Setting the playback rate currently would change that by explicitly setting the current time after changing the playback rate which implicitly changes the start time. This would result in the animation getting out of sync with the timeline range. This fixes #2075.
> [web-animations-1] Maintain start time when changing playback rate for non-monotonic animations

- web-animations-1/Overview.bs
> [web-animations-1] Factor out relevant animation definitions

- web-animations-1/Overview.bs
[web-animations-1] Animations are current if associated with non-increasing timelines.
If an animation is associated with a non-monotically increasing timeline it may become active in the future. As such it should still be considered current (the same as an animation which may play in the future). This fixes #8053.
> [web-animations-1] Animations are current if associated with non-increasing timelines.

- css-animations-2/Overview.bs
Enclosing `<` and `>` characters cannot be omitted when referencing a `type` definition.
> [css-animations-2] Fix value references to "<single-animation-timeline>"

- css-easing-2/Overview.bs
Enclosing `<` and `>` characters cannot be omitted when referencing a `type` definition.
> [css-easing-2] Typo: Fix reference to "<easing-function>"

- css-backgrounds-4/Overview.bs
- css-backgrounds-4/style.css
Like in CSS Color 4, this adds previews for the colors in the example related to the `stripes()` function.
This was requested in https://github.com/w3c/csswg-drafts/issues/8172#issuecomment-1335791336.
> [css-backgrounds-4] Added previews for colors

- scroll-animations-1/Overview.bs
[scroll-animations-1] Make scroll-timeline and scroll-timeline-name support multiple timelines fixing #7657
> [scroll-animations-1] Make scroll-timeline and scroll-timeline-name support multiple timelines fixing #7657

- scroll-animations-1/Overview.bs
https://github.com/w3c/csswg-drafts/issues/7587
> [scroll-animations-1] Define view() notation #7587

- css-overflow-3/Overview.bs
> [css-overflow-3] Fix typo in example 6 #8190

- selectors-4/Overview.bs
What the title says. See #8168 for the reasoning.
Fixes #8168
> [selectors-4] Added `:blank` to at-risk list and removed `:read-write` and `:has()` from it

- css-link-params/Overview.bs
In order to get picked up by the spec. processor, the index.bs file was renamed to Overview.bs.
Sebastian
> [css-link-params] Renamed index.bs to Overview.bs

- css-animations-2/Overview.bs
This syntactically integrates the scroll() and view() functions into animation-timeline.
It also defines the named timeline search to look for scroll and view progress timelines before searching at-rule timelines. (This seemed the most reasonable way to integrate the search, but open to other ideas...)
> [css-animations-2] Integrate scroll animations into animation-timeline #7579

- cssom-view-1/Overview.bs
[cssom-view-1] Extend 'scroll into view' steps to Ranges
Generalizes The `scroll an element into view` algorithm to work also work for a Range as well as an Element. This is trivial as the only use of Element is to call `getBoundingClientRect` which Range also defines.
Additionally exports this algorithm for use in https://github.com/whatwg/html/issues/8282.
Nit: also fixes erroneous reference to a non-existent `box` variable where `scrolling box` was intended.
> [cssom-view-1] Extend 'scroll into view' steps to Ranges

- css2/Overview.bs
The `data-dfn-for` attribute incorrectly referenced the non-existing `border-bottom-right` property, instead of `border-bottom-width` (this attribute's value is typically used to generate the index at the end of the spec).
> [css2] Fix reference to border-bottom-width

- css-position-3/Overview.bs
The term "absolute positioning containing block" (APCB) previously linked to a usage of the term, rather than its definition. Instead, with this change, it now links to the description of when an APCB is established. This should remove some confusion.
This confusion is partially discussed in [#5332](https://github.com/w3c/csswg-drafts/issues/5332), where the term "fixed positioning containing block" (FPCB) is also discussed. Since there is no normative description of anything that establishes an FPCB (only a vague note), an equivalent change cannot be made for FPCB without some larger changes.
> [css-position-3] Move definition of "absolute positioning containing block"

- css-text-4/Overview.bs
This pull request makes several changes in response to https://github.com/w3c/csswg-drafts/issues/6950:
- Adds `ideograph-alpha` and `ideograph-numeric` to the initial value, `normal`.
- Adds a UA stylesheet rule to disable `text-spacing` in `pre`, `code`, and `tt` to preserve their monospace behavior.
- Specifies that non-zero margin/border/padding inhibits autospacing.
- Clarifies that intervening characters such as spaces also inhibit autospacing.
- Defines the interscript autospace to be 1/8 of the ideographic advance (`0.125ic`), which is the smallest amount in the common-use range. The primary justification for using 1/8 instead of 1/6 or 1/4 is that, since we're trying to make this the default, it minimizes the layout impact on existing pages. (Note that Antenna House uses a 1/4 …
> [css-text-4] interscript text-spacing as default

- css-color-6/Overview.bs
One `]` character was missing.
> [css-color-6] Fix typo in contrast-color() syntax

- css-view-transitions-1/Overview.bs
Animations targeting pseudo-elements are considered active, for the purpose of finishing the transition, if they are in running or paused state. See resolution here for details: https://github.com/w3c/csswg-drafts/issues/7785#issuecomment-1269115123.
"paused" was incorrectly changed to idle in the following commit: https://github.com/w3c/csswg-drafts/commit/5151ae80775a862c0edb5ebb35653bc47a55f906.
This change fixes that.
> [css-view-transitions-1] Fix play state tracking for animations

- css-view-transitions-1/Overview.bs
This attempts to define how pseudos are built and ordered. It also defines the view-transition-name of the pseudos.
Fixes #8113.
> [css-view-transitions-1] Define pseudo-nesting and naming

- css-color-6/Overview.bs
Prose says keyword is `wcag2`, not `wcag`.
> [css-color-6] Fix typo in wcag2 keyword

- css-view-transitions-1/Overview.bs
Bikeshed changed databases, and we ended up with a couple of new warnings/errors.
There's still one remaining new error:
```
LINE ~371: Spec-section autolink tried to link to non-existent 'css-viewport' spec:
[[css-viewport#interactive-widget-section]]
```
I don't think this is our fault, I think it's something missing from the database (cc @tabatkins)
> [css-view-transitions-1] Fix refs

- web-animations-1/Overview.bs
[css-animations-1] Export 'pending animation event queue'
Export this definition for [use in css-view-transitions-1](https://www.w3.org/TR/css-view-transitions-1/#:~:text=pending%20animation%20event%20queue)
> [css-animations-1] Export 'pending animation event queue'

- css-anchor-1/Overview.bs
Spec update to change `popup` references to `popover` to align with the renaming of the Popover API.
> [css-anchor-1] Change Popup references to Popover

- css-grid-1/Overview.bs
- css-grid-2/Overview.bs
Without the 'grid-template-rows' prefix this link points at 'auto' in the context of the grid item placement properties, but like its neighbors it is actually meant to refer to the track sizing function.
> [css-grid-1][css-grid-2][editorial] Fix 'auto' sizing function link in layout-algorithm

- cssom-view-1/Overview.bs
This reverts commit b270d9091a211f67aec9e7740dde1de845181e8e.
Also clarifies that the algorithm covers `behavior: "instant"` so that no one will retry removing it.
Closes #7773
> [cssom-view-1] Restore `scrollTo({ behavior: "instant" }`

- css-view-transitions-1/Overview.bs
[css-view-transitions-1] Remove fixed issue about linking to unexported terms
These terms were exported in #8325 so we can remove the issue now.
> [css-view-transitions-1] Remove fixed issue about linking to unexported terms

- css-view-transitions-1/Overview.bs
Added some developer documentation to the APIs.
> [css-view-transitions-1] Adding DOM intro sections

- css-images-4/Overview.bs
Fixes #7986.
The current syntax makes the color stop list optional, which is obviously unexpected.
This PR also aligns CSS Images 4 with CSS Images 3 regarding `<size>` renamed to `<rg-size>` (resolving a conflict with `<ray()>`) and `<ending-shape>` renamed to `<rg-ending-shape>` (for consistency, I guess).
I am not sure if `a? b? || c` is different than `[a? b?]! || c` so I prefered the first option for simplicity.
> [css-images-4] Fix basic syntax of gradients

- web-animations-1/Overview.bs
[A code example](https://w3c.github.io/csswg-drafts/web-animations-1/#example-515a2006) calls `Animation.finished()` with a callback function. [`Animation.finished`](https://w3c.github.io/csswg-drafts/web-animations-1/#dom-animation-finished) is a promise and not callable. This PR changes the code example to use `Animation.finished.then()`, not `Animation.finished()`.
> [web-animations-1] fix code example by handling `Animation.finished` with `.then()`

- css-values-5/Overview.bs
Correct link to the `css-values-4` acknowledgments section is https://www.w3.org/TR/css-values-4/#acknowledgments
> [css-values-5] Fix acknowledgments link

- css-text-4/Overview.bs
Remove the unnecessary verb 'is' in line 5934.
https://drafts.csswg.org/css-text-4/#text-wrap:~:text=The%20wrap%20value-,is,-will%20typically%20map
> [css-text-4] Fix a grammar issue in line 5934 - https://drafts.csswg.org/css-text-4/#text-wrap

- css-backgrounds-3/Overview.bs
- css-tables-3/Overview.bs
- css-ui-3/Overview.bs
- css-ui-4/Overview.bs
This set of changes is the result of auditing all specification
Overview.bs other than CSS2 and css-overflow-* for correct handling of
overflow:clip, since many specifications have historically referenced
concepts like "overflow values other than visible".
It is related to #6212, but doesn't actually fix it, because it's really
only a bug in CSS2.
> Audit specifications for correct handling of overflow:clip.

- scroll-animations-1/Overview.bs
- web-animations-2/Overview.bs
[web-animations-2][scroll-animations-1] Update timeline currentTime
Timeline current time should be a percentage for progress-based animations.
> [web-animations-2][scroll-animations-1] Update timeline currentTime

- css-color-5/Overview.bs
CSS grammar parsers do not like it when there is a space after the opening `<`.
This update also uses the autolink wrapper syntax to create links between the references `<custom-color-space>` references and its definition. That is also more consistent with the rest of the production rules in that block.
> [css-color-5] Fix "custom-color-space" grammar, add autolinks

- css-animations-2/Overview.bs
> [css-animations-2] Define animation-timeline with animation type

- css-transitions-1/Overview.bs
> [css-transitions-1] Define `transition` with animation type

- css-module/Overview.bs
> [css-module] Replace "Animatable" by "Animation Type"

- css-multicol-1/Overview.bs
> [css-multicol-1] Define `column-count` with animation type

- css-cascade-6/Overview.bs
> [css-cascade-6] Remove selector scoping notation

- css-cascade-6/Overview.bs
The grammar allowed this, but the prose did not.
> [css-cascade-6] Support limits for implicit scopes

- css-conditional-values-1/Overview.bs
- css-easing-1/Overview.bs
- css-easing-2/Overview.bs
- css-egg-1/Overview.bs
Editorial change replacing explicit optional groups with implicitly optional commas, ie. `... [ , ... ]?` with `... , ...?`.
I would appreciate this change because parsing against these two syntaxes with the CSS parser I am using, produces two different results (ie. `List(..., optionalList(comma, ...))` vs. `List(..., comma, ...)`), and the second is easier to handle.
I searched for all occurrences with `/\[\s*,.+\]\s*\?/`. I did not replace the result found in the value definition of [`copy-into`](https://drafts.csswg.org/css-gcpm-4/#propdef-copy-into) (CSS GCPM 4, not ready for implementation): the whole alternation can be omitted, which seems to be a bug.
> **Name:** `copy-into`
> **Value**: `none | [ [ <custom-ident> <content-level>] [, <custom-ident> <content-level>]* ]?`
It should …
> [various] Replace optional group with implicitly optional comma

- css-values-4/Overview.bs
Non-substantive contribution for grammar
> [css-values-4] Section 6.1: Removed the word "unit" to avoid confusion

- css-view-transitions-1/Overview.bs
In the current spec, this will cause three unhandled rejections:
```js
const transition = document.startViewTransition(() => {
doesNotExist();
});
```
As it will cause `transition.updateCallbackDone`, `transition.ready`, and `transition.finished` to reject with the same error.
This PR _always_ marks `transition.finished` as handled, as it only ever rejects for the same reason as  `transition.updateCallbackDone`. It marks `transition.ready` as handled if it's rejected with the same reason as `transition.updateCallbackDone`.
> [css-view-transitions-1] Fix some promise timing, and avoid duplicate unhandled rejections

- css-sizing-3/Overview.bs
> [css-sizing-3] Define min|max-width|height with animation type

- css-overflow-3/Overview.bs
> [css-overflow-3] Define `scroll-behavior` with animation type

- css-round-display-1/Overview.bs
> [css-round-display-1] Define `shape-inside` with animation type

- scroll-animations-1/Overview.bs
> [scroll-animations-1] Define `animation-range-start|end` with animation type

- css-overflow-4/Overview.bs
Restricted the syntaxes of `line-clamp` and `-webkit-line-clamp` to positive integers.
Fixes #8409.
> [css-overflow-4] Added limits to `line-clamp` and `-webkit-line-clamp` syntax

- css-text-4/Overview.bs
Series of commits for properly integrating the L3 'white-space' shorthand and L4 longhand definitions in CSS Text Level 4.
> [css-text-4] 'white-space' and longhand integration

- css-nav-1/Overview.bs
Adds `Animation Type: not animatable` to all property definitions. According to [Web Animations 1](https://drafts.csswg.org/web-animations-1/#animating-properties), they would be otherwise considered as animatable:
> Unless otherwise specified, all CSS properties are **animatable**.
> [css-nav-1] Define properties with animation type

- css-display-3/Overview.bs
Only one hyphen in `display-listitem`.
> [css-display-3] Typo: fix reference to "<display-listitem>"

- css-grid-1/Overview.bs
- css-grid-2/Overview.bs
- css-shapes-1/Overview.bs
- css-speech-1/Overview.bs
Add range notation to some productions used to define a track list.
This change assumes that out of range values are invalid (they are in Chrome/Firefox). This is not explicitly defined in prose, as it is often the case in other specs that use range notation.
**EDIT:**
After searching for `non-negative` in all specs, I added a non-negative range notation for:
- `zoom`, `min-zoom`, `max-zoom`, in CSS Device Adapt
- `<track-size>`, `<track-breadth>`, `<inflexible-breadth>`, `<fixed-breadth>`, in CSS Grid 1-2
- `shape-margin` in CSS Shapes
- `pause-before`, `pause-after`, `rest-before`, `rest-after`, `voice-rate`, in CSS Speech
I ignored `min-width` and `max-width` (descriptors for `@viewport`) in CSS Device Adapt because there is a note about removing them.
> [css-device-adapt][css-grid][css-shapes][css-speech] Add range notation

- css-backgrounds-3/Overview.bs
- css-backgrounds-4/Overview.bs
- css-box-3/Overview.bs
- css-box-4/Overview.bs
- css-logical-1/Overview.bs
- css-overflow-3/Overview.bs
- css-overflow-4/Overview.bs
- css-overscroll-1/Overview.bs
- css-position-3/Overview.bs
- css-scroll-snap-1/Overview.bs
- css-sizing-3/Overview.bs
- css-sizing-4/Overview.bs
See #2822.
For convenience, below is a list of the updated property definition tables grouped by spec and logical property group.
I guess an issue should be created in Bikeshed repo for auto-linking [`Logical property group`](https://drafts.csswg.org/css-logical-1/#logical-property-group).
- CSS Backgrounds 3
- border-color
- border-bottom-color
- border-top-color
- border-left-color
- border-right-color
- border-style
- border-bottom-style
- border-left-style
- border-right-style
- border-top-style
- border-radius
- border-bottom-left-radius
- border-bottom-right-radius
- border-top-left-radius
- border-top-right-radius
- border-width
- border-bottom-width
- border-left-width
- border-right-width
- border-top-width
- CSS Backgrounds 3, CSS Backgrounds 4
- border-color
- …
> [meta] Add "Logical property group" propdef table field

- css2/Overview.bs
The `@media` at-rule was defined twice, first time in the heading and second time in the prose without the `@` prefix. Both were flagged as "exported". This update replaces the second one with a reference to the first to avoid the duplication (and avoid the creation of an at-rule without the `@` prefix).
> [css2] Drop duplicated dfn of `@media` at-rule

- css-fonts-4/Overview.bs
- css-images-4/Overview.bs
- css-values-4/Overview.bs
Added a few URL modifiers to enable request parameters:
3 modifiers that correspond to `link` attributes:
- [`crossorigin`](https://html.spec.whatwg.org/#attr-link-crossorigin)
- [`referrerpolicy`](https://html.spec.whatwg.org/#attr-link-referrerpolicy)
- [`integrity`](https://html.spec.whatwg.org/#attr-link-integrity)
This enables CORS requests for CSS images, credentialed requests for fonts, and fine-tuning using integrity etc.
Example:
`url("https://..." crossorigin(anonymous) integrity("shaX--something") referrerpolicy(same-origin))`
See #1603
> [css-values-4][css-images-4][css-fonts-4] URL request modifiers

- css-view-transitions-1/Overview.bs
Most of this diff is indenting.
The actual change is giving each of the new pseudos their own heading, so they appear in the TOC, making navigating the spec easier.
> [view-transitions-1] Give defined pseudos their own heading, so they appear in TOC

- scroll-animations-1/Overview.bs
> [scroll-animations-1] source is updated upon request and in sync with currentTime

- css-backgrounds-4/Overview.bs
This change adds the different longhand properties for the `box-shadow` property to the CSS Backgrounds and Borders Module Level 4. This is one part of #4431.
The definition of the `box-shadow` property was taken from [level 3 of the specification](https://drafts.csswg.org/css-backgrounds-3/#box-shadow). Then the different longhand properties were created by splitting the syntax and value descriptions of the `box-shadow` property. Some additional descriptions were added and all the properties placed in a new section "Drop Shadows".
> [css-backgrounds-4] Added box-shadow-* longhand properties

- scroll-animations-1/Overview.bs
Fixes #8227.
This PR replaces #8390 which was created from the wrong branch.
> [scroll-animations-1] Add self keyword

- mediaqueries-4/Overview.bs
As Firefox has shipped it and Chromium is about to ship, I propose to remove "at-risk" for the '@media/update' media feature.
> [css-mediaqueries-4] Remove "at-risk" for the '@media/update' media feature

- css-view-transitions-1/Overview.bs
We removed "DOM" from the API, since it isn't usually referenced in API naming, but left it in a couple of non-API places.
> [view-transitions-1] Remove DOM references

- css-text-4/Overview.bs
Fixes `<'white-space-collapse'> || <'text-wrap'> || <'text-space-trim'>` generated without enclosing quotes:
https://drafts.csswg.org/css-text-4/#propdef-white-space
> [css-text-4] Fix refs to property productions

- css-animations-1/Overview.bs
- css-animations-2/Overview.bs
`<time>` in the value definition of `animation-duration` has a numeric range but `animation` is defined with its own `<time>` production that is missing the same range.
> [css-animations] Add missing numeric range

- css-images-4/Overview.bs
This changes the interpolation of `stripes()` values to look at each pair of thicknesses instead of disallowing mixing values completely.
This fixes #8163.
Sebastian
> [css-images-4] Fixed interpolation of `stripes()` with different types

- css-color-5/Overview.bs
I noticed some typo's in the examples for `color-mix()`.
Doesn't include any substantive changes.
> [css-color-5] fix typo's in `color-mix` examples

- scroll-animations-1/EXPLAINER.md
The scroll-animations-1 explainer had gotten fairly out of date after the most recent declarative rethinking and subsequent rewrite of the spec. This brings the concepts and examples in the explainer up to date, though further refinement could be done to focus more on the CSS side of things.
> [scroll-animations-1] Update explainer to use new API and concepts.

- scroll-animations-1/EXPLAINER.md
This adds answers to all of the W3C TAG [self-review questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/) [questions](https://www.w3.org/TR/security-privacy-questionnaire/#questions) to the explainer.
> [scroll-animations-1] Add W3C security and privacy questionnaire answers to explainer

- css-color-5/Overview.bs
see : https://github.com/w3c/csswg-drafts/issues/8609
https://drafts.csswg.org/css-color-4/#specifying-lab-lch
> If the chroma of an LCH color is 0%, the hue component is [powerless](https://drafts.csswg.org/css-color-4/#powerless-color-component). If the lightness of an LCH color (after clamping) is 0%, or 100%, both the hue and chroma components are powerless.
https://drafts.csswg.org/css-color-4/#specifying-oklab-oklch
> If the chroma of an Oklch color is 0% or 0, the hue component is [powerless](https://drafts.csswg.org/css-color-4/#powerless-color-component). If the lightness of an Oklch color is 0% or 0, or 100% or 1.0, both the hue and chroma components are powerless.
> [css-color-5] fix mention of powerless components

- css-overflow-3/Overview.bs
Fixes ref to `<'overflow-block'>`.
https://drafts.csswg.org/css-overflow-3/#propdef-overflow
> [css-overflow-3] Fix ref to property production

- css-highlight-api-1/Overview.bs
> [css-highlight-api-1] Add i18n warning about placement of range endpoints in text

- scroll-animations-1/Overview.bs
See [proposal](https://github.com/w3c/csswg-drafts/issues/7748#issuecomment-1306097703), [WebIDL draft](https://github.com/w3c/csswg-drafts/issues/7748#issuecomment-1307381553), and [CSSWG resolution](https://github.com/w3c/csswg-drafts/issues/7748#issuecomment-1325424372).
Note that with the given syntax, it's not possible to ask for `auto` via the TypedOM version of the API. We could do that also, but we'd have to add some validation steps to make sure the keyword is in fact `auto`. (That said, this _is_ the initial value; it could just be omitted.)
> [scroll-animations-1] Add inset option to ViewTimeline constructor #7748

- css-align-3/Overview.bs
> [css-align-3] When assuming orthogonal writing mode for baseline alignment, choose based on 'direction'. #7775

- css-view-transitions-1/Overview.bs
Fixes #7797
Reviewed in https://github.com/jakearchibald/csswg-drafts/pull/4
> [css-view-transitions-1] Direct pointer events to document element while rendering is suppressed

- css-contain-3/Overview.bs
Per resolution in #8127, style() queries can query properties without a value which evaluates to true if the computed value is different from the initial value for that property.
> [css-contain-3] Support boolean context style() queries #8127

- scroll-animations-1/Overview.bs
> [scroll-animations-1] Clarify how range positions are determined with sticky offsets.

- css-animations-1/Overview.bs
- css-animations-2/Overview.bs
- css-display-4/Overview.bs
> [css-animations-1] Animations are only canceled if base and computed display are none.

- scroll-animations-1/Overview.bs
> [scroll-animations-1] Describe scroll/view-timeline-attachment

- scroll-animations-1/EXPLAINER.md
This adds sections explaining the addition of automatically fitting an auto duration to a scroll timeline or view timeline and the introduction of a ranges section to explain animation ranges.
> [scroll-animations-1] Add auto duration and animation ranges to explainer

- scroll-animations-1/Overview.bs
> [scroll-animations-1] Add note about horizontal and vertical axis still using logical direction

- scroll-animations-1/Overview.bs
I think there's more to consider here, but this at least aligns us with the most recent resolution in #8201.
> [scroll-animations-1] Use options dictionary for getCurrentTime() #8201

- cssom-1/Overview.bs
Added a `supportsText` attribute to `CSSImportRule` to allow access to supports conditions declared in `@import` rules. Closes #8710.
> [cssom-1] Add CSSImportRule supportsText attribute

- css-images-3/Overview.bs
- css-images-4/Overview.bs
This PR adds an explicit value definition of `<repeating-*-gradient>`, similarly as in https://github.com/w3c/csswg-drafts/commit/8a7728f0fd26cd4c849a18f1e000a85e975f2adf for `hsla()` and `rgba()` (#8231).
> [css-images] Add basic syntax of repeating gradient types

- css-contain-3/Overview.bs
Remove the recently added grammar part for style-feature that was inaccurate.
Do not accept invalid declarations or unsupported property names as a style-feature. The effect of that is that we do not need to store invalid declarations, but merely fall back to parse the style() query with the invalid declaration as a general-enclosed, which will evaluate to unknown.
> [css-contain-3] Tweak the spec for style() queries #8127

- css-images-3/Overview.bs
- css-images-4/Overview.bs
`<repeating-*-gradient>` are both defined as types and functions. Hopefully they are correctly defined (as functions) now.
https://github.com/w3c/webref/blob/main/ed/css/css-images-4.json#L191
https://github.com/w3c/webref/blob/main/ed/css/css-images-4.json#L224
> [css-images] Fix duplicate repeating gradient definitions

- css-color-5/Overview.bs
- scroll-animations-1/Overview.bs
> [scroll-animations-1] Also rerun style/layout for changed timeline ranges

- index.html
See https://github.com/mdn/content/issues/26613. The change made in https://github.com/w3c/csswg-drafts/commit/52077ef broke all links to CSS specs in all MDN CSS articles. This is an attempt to get all those links unbroken temporarily until we can find a better fix.
> Temporary fix for w3c.github.io redirect breakage

- css-scroll-snap-2/Overview.bs
scroll-start-target is a shorthand. This change specifies its related shorthands.
> [scroll-snap-2] Add scroll-start-target longhand details

- css-view-transitions-1/Overview.bs
Ink-overflow is an implementation detail, and up to the UA to apply. object-view-box doesn't directly affect the ink-overflow rect. Replaced mentioned of `ink-overflow rect` with `border box`, and added note about how ink-overflow plays into this.
Also, texture size constraints should not affect the observed natural size of the captured image. Instead, implementations
should capture at least the visible part of the element (downscaled if they must).
See [resolution 1](https://github.com/w3c/csswg-drafts/issues/8597#issuecomment-1488952275) and [resolution 2](https://github.com/w3c/csswg-drafts/issues/8561#issuecomment-1470414852).
Closes #8561 
Closes #8597
> [css-view-transitions-1] Clarify that observable image size refers to the border-box, and observed natural size is not affected by hw constraints

- css-scroll-snap-2/Overview.bs
This was marked as UD, however, all of the features have been discussed. Previous resolutions:
`scroll-start` and `scroll-start-target`: https://github.com/w3c/csswg-drafts/issues/6986#issuecomment-1028503857
`:snapped`, `snapChanged` and `snapChanging` and creation of css-scroll-snap-2 ED: https://github.com/w3c/csswg-drafts/issues/6985#issuecomment-1049029573
Discussion of original PR in #8766.
> [css-scroll-snap-2] Mark as ED

- css-view-transitions-1/Overview.bs
Skip fragmented elements when preparing transition, and add note about looking at this again in the future.
See [resolution](https://github.com/w3c/csswg-drafts/issues/8339#issuecomment-1470268830).
Closes #8339
> [css-view-transitions-1] Fragmented elements don't participate in view transitions.

- css-view-transitions-1/Overview.bs
[css-view-transitions-1] Rename snapshot-root to snapshot containing block and determine that the snapshot CB is an absolute/fixed positioning containing block for its descendants.
Based on [this resolution](https://github.com/w3c/csswg-drafts/issues/8505#issuecomment-1505587046).
Closes #8505
> [css-view-transitions-1] Rename snapshot-root to snapshot containing block

- css-view-transitions-1/Overview.bs
- css-viewport/Overview.bs
Use explicit properties in the struct for old element styles, and export interactive-widgets
> [css-view-transitions-1][css-viewport] Resolve a few missing types

- scroll-animations-1/Overview.bs
> [scroll-animations-1] Rename physical axes to x/y

- css-scroll-snap-2/Overview.bs
This PR adds a `Logical property group` field to physical/logical `scroll-start-*` longhands, as required by [this resolution](https://github.com/w3c/csswg-drafts/issues/2822#issuecomment-722050788).
I know CSS Scroll Snap 2 is unofficial and this change is not important at this point, but it seems listed in `w3c/browser-specs`, which means it is deemed relevant for the Web Platform, and `w3c/reffy` extracts its definitions, which means some implementations/tools may start implementing it.
> [css-scroll-snap-2] Define logical property group of scroll-start-*

- scroll-animations-1/Overview.bs
Alternative to https://github.com/w3c/csswg-drafts/pull/8902
> [scroll-animations-1] Replace timeline-attachment with timeline-scope #7759

- css-view-transitions-1/Overview.bs
> [css-view-transitions-1] Consolidate global UA style rules #8891

- css-view-transitions-1/Overview.bs
This patch splits apart the Concepts section which was a collection of random ideas and consolidates the various parts with related content.
It might be easier to review commit by commit.
> Reorganize Concepts in View Transitions spec

- css-view-transitions-1/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/8917 The revised definition looks less formal, but afaict it actually hooks up more properly.
THIS PATCH BUILDS ON https://github.com/w3c/csswg-drafts/pull/8918 in order to avoid merge conflicts, and therefore incorporates that entire PR. See last commit for this change.
> [css-view-transitions-1] Clarify stacking context model #8917

- css-view-transitions-1/Overview.bs
This change fixes the following issues inlined into the spec:
* The link for "paint order" doesn’t seem right. Is there a more canonical definition?
The DOM order of `::view-transition-group` pseudo-elements needs to match the paint order of the corresponding DOM elements. This is why elements are traversed in paint order when adding them to named elements. The definition of paint order used here is correct.
* Isolation and the dynamic setting of blending is only necessary...
This was resolved in https://github.com/w3c/csswg-drafts/issues/7814.
* Refactor this so the algorithm takes a set of elements that will be captured...
This was a problem because there was no way to refer to an element participating in a transition. Presence of view-transition-name was not enough. Now there's a bool …
> [css-view-transitions-1] Resolve open issues.

- css-view-transitions-1/Overview.bs
It's probably easiest to review commit by commit. This PR does three things:
* Renames “transition suppressing rendering” to “rendering suppression for view transitions” which is longer but more understandable and also more clearly a noun. Another option might be “transition rendering suppression”... I'm not entirely sure of the nuance we're going for, but “transition suppressing rendering” definitely feels awkward.
* Renames “show view-transition root pseudo-element” to “show view transition tree”; because (afaict) fundamentally this is about displaying the entire tree, not just the root of it
* Makes a bunch of minor fixes to prepositions and markup
This PR builds on top of https://github.com/w3c/csswg-drafts/pull/8954
> [css-view-transitions-1] Algorithms Section: various minor editorial fixes

- css-syntax-3/Overview.bs
In the “filter code points” step of the “Preprocessing the input stream” section at https://drafts.csswg.org/css-syntax/#css-filter-code-points, this change adds a non-normative Note to clarify that the only way to produce a surrogate code point in CSS content is by directly assigning a `DOMString` with one in it via an OM operation.
> [css-syntax-3] Note: surrogate can only be produced by OM operation

- web-animations-1/Overview.bs
Going through the spec and cleaning up things that tripped me up...
Might be easier to review by commit.
Some of the commit messages have detailed explanations, hope that helps...
> [web-animations-1] Improvements to term definitions and cross-linking

- css-transitions-2/Overview.bs
[css-transitions-2] Add spec for @starting-style #8174
> [css-transitions-2] Add spec for @starting-style #8174

- css-view-transitions-1/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/8924
> Use keyframes to specify plus-lighter blending for cross-fades

- css-animations-2/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/6530
> [css-animations-2] Make animation-duration:auto resolve to 0s for legacy compat #6530

- css-color-5/Overview.bs
Fixed two typo's in the list of changes of `css-color-5`
> [css-color-5] fix typo

- css-pseudo-4/Overview.bs
This adds the missin word "styled" to the examples.
Fixes #9023
> [css-pseudo-4][editorial] Fixed typo in example

- css-backgrounds-4/Overview.bs
- css-box-3/block-layout.bs
- css-color-hdr/Overview.bs
- css-module/Overview.bs
- css-writing-modes-3/Overview.bs
- css-writing-modes-4/Overview.bs
[css-backgrounds-4][css-box-3][css-color-hdr][css-module][css-writing-modes-3][css-writing-modes-4] Convert remaining "Animatable" lines to "Animation type" lines.
See #72.
> Convert remaining Animatable lines to Animation type lines.

- css-pseudo-4/Overview.bs
After #9024, the line breaks were a bit off, which this change corrects.
> [css-pseudo-4][editorial] Fixed formatting in example 2

- css-images-3/Overview.bs
w3c/csswg-drafts@c03b2ea changed `<color-stop> = <color> <length-percentage>?` to `<linear-color-stop> = <color> && <length-percentage>?`
I believe the `&&` was a mistake, since `<length-percentage> <color>` doesn't seem to be valid?
Note: This also affects [css-images-4], which uses the same definition.
> [css-images-3] remove && from <linear-color-stop> syntax

- css-anchor-position-1/Overview.bs
I am writing an HTML spec PR to define the anchor attribute, which sets the implicit anchor element. That PR doesn't have any references to or integrations with the popover attribute, and I got feedback that the implicit anchor element seems popover-specific due to the example: https://github.com/whatwg/html/pull/9144#discussion_r1244592176
This PR changes the example to talk about the anchor attribute rather than the popover API. I'm not sure if the popover API is supposed to set an implicit anchor element... maybe @xiaochengh knows?
> [css-anchor-position-1] Change implicit anchor element example

- css-anchor-position-1/Overview.bs
For #8913
Allows `::before`, `::after` and `::backdrop` to use originating element's implicit anchor element
@tabatkins  PTAL
> [css-anchor-position-1] Add implicit anchors to pseudo elements

- css-anchor-position-1/Overview.bs
Fixes #8675
As discussed, there's no need to expose `anchor-scroll` as a separate property and provide opt-out. So we turn it into a internal detail of computing the snapshotted scroll offset.
> [css-anchor-position-1] Hide `anchor-scroll` as an internal detail

- css-anchor-position-1/Overview.bs
> [css-anchor-position-1] Apply only allowed properties when applying fallback style

- css-view-transitions-1/Overview.bs
- Separated view transition activation to own algorithm, to prepare for cross-doc
- Clarifying that new elements are invisible during the transition
- Changed type of image from ImageData to 2D-bitmap
- Fixed a few broken refs
See #8958
> [css-view-transitions-1] A few clarifications and nits

- css-syntax-3/Overview.bs
Spotted some typos while reading the spec so here's a fix.
> [css-syntax-3] Fix typos in parser entry points section

- css-contain-2/Overview.bs
[css-contain-2] Define proximity to the viewport
This doesn't have a resolution per se (and likely needs one), but the resolution in https://github.com/w3c/csswg-drafts/issues/8542#issuecomment-1542482803 led to the following PR https://github.com/whatwg/html/pull/9312. That PR references proximity to the viewport, since that's a needed part of the algorithm. However, it wasn't clear where to define those terms and it seems like css-contain-2 is the right spot
Also, not sure if this is better suited for css-contain-3 instead.
> [css-contain-2] Define proximity to the viewport

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
This lays the foundations for cross-document view transitions.
Specifically:
- The opt-in
- The reveal event
See https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md
> [css-view-transitions-1][css-view-transitions-2] Initial draft for cross-document view transitions

- css-view-transitions-1/Overview.bs
The monkey patches have been integrated into the HTML spec.
See e.g. https://html.spec.whatwg.org/#perform-pending-transition-operations
> [css-view-transitions-1] Remove HTML monkey patches

- css-anchor-position-1/Overview.bs
This makes a few edits from proofreading the document.  In particular:
* add a sub-list to make it clearer what condition an "Otherwise" is referring to,
* use correct bikeshed shorthand for a syntax item in a comment in an example so that it shows up, and
* change two places that invoke a defined algorithm to use wording that makes it clearer that they're invoking an algorithm.
> [css-anchor-position-1] Edits from proofreading.

- css-view-transitions-2/Overview.bs
- Add wording in security about 3p CSS
- Fire reveal event before rAF, inside update the rendering
Closes #8889 (see [resolution](https://github.com/w3c/csswg-drafts/issues/8889#issuecomment-1640752547))
See #8805 (see [partial resolution](https://github.com/w3c/csswg-drafts/issues/8805#issuecomment-1640688426))
> [css-view-transitions-2] Apply resolutions from F2F

- css-transitions-2/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/8857
> [css-transitions-2] Add transition-behavior property

- css-backgrounds-4/Overview.bs
https://github.com/w3c/csswg-drafts/commit/2869346daa5f98a9e425888951a995c556138d39 introduced an issue in the display of the issue around adding `background-repeat: extend`.
This change fixes the formatting.
> [css-backgrounds-4] Fixed display of issue for `background-repeat: extend`

- css-view-transitions-1/Overview.bs
[css-view-transitions-1] Refactor VT old capture algorithm
We need to correctly set `captured in a view transition` before capturing the image, since the capture checks the boolean's value for descendant elements.
> [css-view-transitions-1] Refactor VT old capture algorithm

- css-regions-1/Overview.bs
Cf. https://github.com/w3c/fxtf-drafts/pull/523 for why it may be required.
> [css-regions-1] Add whitespaces around combinator

- css-borders-4/Overview.bs
I've added the definition for the `none` value of `box-shadow-offset` and corrected the computed value of that property to account for the `none` value now being part of the shadow list.
The `box-shadow` shorthand was adjusted accordingly.
Fixes #8567
Sebastian
> [css-borders-4] Fixed and added definitions for box-shadow-offset: none

- css-view-transitions-1/Overview.bs
And not e.g. squashed into it.
See https://github.com/w3c/csswg-drafts/pull/8819 for discussions
> [css-view-transitions-1] Clarify that ink overflow is outside the image content box #8819

- css-images-4/Overview.bs
It prevents switching positions of a color and its position in a gradient color stop.
This change was already applied in CSS Images 3 via #8021.
> [css-images-4] Apply #8021 to gradient definitions in CSS Images 4

- css-page-3/Overview.bs
There is no `border-short-style` in CSS 2.1. Replaced it with the `border-style` shorthand.
Fixes #3156
Sebastian
> [css-page-3][editorial] Replaced `border-short-style` by `border-style`

- css-scrollbars-1/Overview.bs
Fix two basic typos that I spotted while reading the spec.
> [css-scrollbars] Fix typos

- scroll-animations-1/Overview.bs
- web-animations-2/Overview.bs
[web-animations-2][scroll-animations-1] Fix bikeshed lint errors for broken / ambiguous links.  Also adds workaround for Chrome bug in list numbering.
> [web-animations-2][scroll-animations-1] Fix links

- web-animations-1/Overview.bs
Continuing from https://github.com/w3c/csswg-drafts/pull/8965 ... This refactors the Animation Effects section of the Web Animations model.
Have not yet worked through the progress calculation section (other than teasing out things which should go ahead of it), so haven't dealt with https://github.com/w3c/csswg-drafts/pull/8965#discussion_r1233105532, but it's almost 2am so submitting everything I've got for above it since it's a pretty coherent set of changes as-is. :)
> [web-animations-1] Restructure and Improve DFNs in Animation Effects section

- web-animations-1/Overview.bs
to match the updated terminology in css-easing.
> [web-animations-1][editorial] Rename ‘timing function’ to ‘easing function’

- css-anchor-position-1/Overview.bs
Per resolution https://github.com/w3c/csswg-drafts/issues/9195#issuecomment-1690141172
This PR allows more properties in a `@position-fallback` rule:
- All margin properties in [CSS-BOX-4](https://drafts.csswg.org/css-box-4/#margins):
- `margin-top`, `margin-bottom`, `margin-left`, `margin-right` and their logical equivalents
- `margin`, `margin-block`, `margin-inline` shorthands
- `margin-trim`, as it's also a margin property if I read the spec correctly
- All border properties in [CSS-BOX-4](https://drafts.csswg.org/css-box-4/#borders):
- border color, border style and border width properties, and related shorthands
- All padding properties in [CSS-BOX-4](https://drafts.csswg.org/css-box-4/#paddings):
- `padding-top`, `padding-bottom`, `padding-left`, `padding-right` and their logical …
> [css-anchor-position-1] Add more properties to position fallback

- css-fonts-4/Overview.bs
As resolved on 2023-08-16, https://github.com/w3c/csswg-drafts/issues/7441#issuecomment-1680918811
Proposed draft text to add this property to the spec; feel free to edit/fix as needed!
The WPT tests mentioned are being created in https://bugzilla.mozilla.org/show_bug.cgi?id=1849010.
> [css-fonts-4] Add font-synthesis-position (#7441)

- css-color-5/Overview.bs
With the current instructions in the spec for serializing `color-mix`, values of `50%` are incorrectly excluded from the serialization when the specified percentages don't add up to 100% and need normalization.
The proposed wording makes it more clear when to exclude these percentage values for both the first and the second color. The first percentage is excluded only if both are `50%`, and the second one only when normalization is not required and therefore the information from the first color is enough.
> [css-color-5] Serialization of color-mix edge case with not normalized values including 50% #8564

- css-borders-4/Overview.bs
Copied over the section from Level 3 about "Layering, Layout, and Other Details" of box shadows and defined the longhands as coordinating list property group with `box-shadow-offset` being the coordinating list base property.
This is meant to fix #8592 and supersedes #8613.
Sebastian
> [css-borders-4] Defined `box-shadow-*` as coordinating list property group

- css-text-4/Overview.bs
Recast `word-boundary-detection: auto()` as `word-break: auto-phrase`, as well as `word-boundary-detection: manual` as `word-break: manual`.
This allows retiring the `word-boundary-detection` property.
Also, the `word-boundary-expansion` property needed to gain its own `auto-phrase` value, since it could no longer depend on `word-boundary-detection: auto()`.
Since there's no longer a pair of `word-boundary-*` properties, there's no need to keep the two names related, and the original name was quite a mouthful. `word-space-transform` is simpler, and better show-cases the similarities with `text-transform`.
Supporting sections had to be reorganized as well to keep the whole thing coherent.
This addresses https://github.com/w3c/csswg-drafts/issues/7193 (and …
> [css-text-4] auto-phrase

- css-fonts-4/Overview.bs
A numeric range is missing for the `<integer>` in `<feature-tag-value>`:
> `<feature-tag-value> = <string> [ <integer> | on | off ]?`
>
> If present, a value indicates an index used for glyph selection. An `<integer>` value must be 0 or greater.
A numeric range is missing for the `<angle>` in `font-style` in `@font-face`:
> **Value:** `auto | normal | italic | oblique [ <angle>{1,2} ]?`
>
> The meaning of the values for these descriptors are the same as those for the corresponding font properties [...]. If specified values are out of range of the accepted values of the property of the same name, the descriptor is treated as a parse error.
> [css-fonts-4] Add missing numeric range annotations

- css-fonts-4/Overview.bs
- css-fonts-5/Overview.bs
This is the same fix as https://github.com/w3c/csswg-drafts/commit/e6148b9a897359117bf9082d6a48dd0ff75f8767 but applied to CSS Fonts 5 instead of CSS Fonts 4 (oversight).
It also fixes another oversight in CSS Fonts 4, by replacing a remaining occurrence of `<font-face-name>` with `<family-name>`.
> [css-fonts-5] Use local(<family-name>) #8187

- css-fonts-4/Overview.bs
Fixes Bikeshed warnings for *Multiple possible 'descriptor' local refs*.
> [css-fonts-4] Fix ambiguous descriptor auto-links

- css-text-4/Overview.bs
Some redundant text had appeared through parallel history in css-text-3 and css-text-4. This PR deduplicates them, and takes the opportunity for shuffling some paragraphs and sections around to try and make things a little more coherent.
> [css-text-4] Deduplication of normative text and editorial reorganization

- css-fonts-4/Overview.bs
This PR adds a `.prod` class name to the `<pre>` containing the production rule of `<family-name>`.
As [commented in its code](https://github.com/w3c/reffy/blob/bb48cea4635c8dfb33b1ea66f30630e756df0d96/src/browserlib/extract-cssdfn.mjs#L703-L708), `w3c/reffy` extracts a production rule if it is contained in a `<pre class=prod>` of if its left hand side is contained in a `<dfn>`:
```
<pre class=prod><foo> = bar</pre>
<pre><dfn><foo></dfn> = bar</pre>
```
> [css-fonts-4] Fix markup for the production rule of <family-name> 

- css-fonts-4/Overview.bs
This PR defines `<opentype-tag>` representing the `<string>` in `font-feature-settings` and `font-variation-settings`.
It allows to share a single implementation for parsing this `<string>` as a valid OpenType tag.
> [css-fonts-4] Define feature and variation names with <opentype-tag>

- css-fonts-5/Overview.bs
The range already exists in [CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/#propdef-font-size-adjust) and the [current prose](https://drafts.csswg.org/css-fonts-5/#valdef-font-size-adjust-number) in CSS Fonts 5 does not allow negative number as well:
> Negative values are invalid.
> [css-fonts-5] Set range for font-size-adjust number

- css-contain-2/Overview.bs
[css-contain-2] Update selection link to point to selection API instead of highlight pseudos.
Fixes #9277
> [css-contain-2] Update selection link to point to selection API instead of highlight pseudos.

- css-gcpm-3/Overview.bs
`<string()>` is defined with the same value definition in [CSS Content 3](https://drafts.csswg.org/css-content-3/#funcdef-string) and [CSS GCPM 3](https://drafts.csswg.org/css-gcpm-3/#funcdef-string).
This PR removes the definition in CSS GCPM 3.
> [css-gcpm-3] Remove duplicate definitions of <string()>

- css-gcpm-3/Overview.bs
This PR prefixes `nth()` with `:`, as required by Bikeshed:
> Does it start with a `:`? Then it’s a selector.
https://speced.github.io/bikeshed/#dfn-types
> The `nth()` page pseudo-class allows the selection of arbitrary document pages.
https://drafts.csswg.org/css-gcpm-3/#document-page-selectors
> [css-gcpm-3] Define :nth() as selector instead of function

- css-transforms-2/Overview.bs
The first (simpler) half of what was discussed in https://github.com/w3c/csswg-drafts/issues/918.
Will try write some new tentative tests for this too.
> [css-transforms-2] Make backface-visibility:hidden create a stacking context and containing block when participating in a 3D rendering context.

- css-overflow-4/Overview.bs
The first sentence of the description of `max-lines` included a double negative. I rephrased that sentence to avoid that double negative, so it's easier understandable.
Sebastian
> [css-overflow-4] Rephrased description of `max-lines` to avoid double negative

- css-fonts-4/Overview.bs
> ```json
>   {
>     "name": "<palette-mix()>",
>     "type": "type"
>   }
> ```
https://github.com/w3c/webref/blob/d898c413c384c43f38d20ebf34db2e8fac7e9ce8/ed/css/css-fonts.json#L997
> ```json
>   {
>     "name": "<palette-mix()>",
>     "type": "function",
>   }
> ```
https://github.com/w3c/webref/blob/d898c413c384c43f38d20ebf34db2e8fac7e9ce8/ed/css/css-fonts.json#L1414
> [css-fonts-4] Remove duplicate definition of `<palette-mix()>`

- css-namespaces-3/Overview.bs
The definition of the `@namespace` at-rule was not identified in the spec, preventing cross-references to it, and hiding it from spec crawlers.
> [css-namespaces-3] Wrap definition of `@namespace` in `<dfn>`

- css-fonts-4/Overview.bs
I think this was an oversight.
> [css-fonts-4] Add missing at-keword in production of @font-feature-values

- css-anchor-position-1/Overview.bs
For #9239 
Define whether there's a snapshotted scroll offset on each axis separately, and then revise the concept of snapshotted scroll snapshot and how it's used accordingly.
> [css-anchor-position-1] Make snapshotted scroll offset per-axis

- css-anchor-position-1/Overview.bs
`anchor-center` should be a subsection of Anchor-Based Positioning, not a top-level section.
This PR fixes it.
> [css-anchor-position-1] Fix anchor-center section number

- cssom-1/Overview.bs
Replaces `<alphavalue>` by `<alpha-value>`. I can only find occurrence of the latter in other specs (CSS Colors, CSS Shapes, Filter Effects).
> [cssom-1] Fix links to `<alpha-value>` and (pre-defined) keywords

- css-view-transitions-2/Overview.bs
As per [resolution at TPAC](https://github.com/w3c/csswg-drafts/issues/8960#issuecomment-1719695337), adding a concept of "active types" to a view transition, with an `active-view-transition` pseudo-class that matches the root element if it has an active view transition that matches the list of active types.
To set the active types, `startViewTransition` now accepts options, like `startViewTransition(update, types: ["slide", "reverse"]})`
Closes #8960
> [css-view-transitions-2] Add transition types

- css-view-transitions-2/Overview.bs
Rename based on TPAC conversation: auto-view-transition => view-transition (with `trigger: navigation` as the descriptor)
Also added CSSOM support for the new rule.
Close #8048 as per [TPAC discussion](https://github.com/w3c/csswg-drafts/issues/8048#issuecomment-1719751618).
Opened #9383 to continue bikeshedding discussion about the at-rule name. We can update the spec once that's finalized.
> [css-view-transitions-2] Apply renames based on TPAC discussion

- cssom-view-1/Overview.bs
`element.checkVisibility()` checks against CSS properties, which apply on the flat tree, not the shadow-including tree.
Fixes #9486
> [cssom-view] Use flat tree instead of shadow-including tree for element.checkVisibility()

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
[css-view-transitions] Make the startViewTransition non-nullable
Fixes #9460
> [css-view-transitions] Make the startViewTransition non-nullable

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
Removed and amended some wrong names and refs to css-view-transitions-1.
> [css-view-transitions-2] Fix build errors/warnings

- css-color-5/PDFium.html
> [css-color-5] Fix missing space between example title and counter

- css-view-transitions-2/Overview.bs
- Use the `@view-transition { navigation: auto | none; type: ... }` syntax as per the resolution
- `type: none` means that type is unspecified, needs a resolution
- reloads are ignored as per previous resolution
- Renamed the JS param "type" instead of "types"
- Currently types are resolved both at old and new document separately, this needs a resolution.
Closes #9383
See resolution: https://github.com/w3c/csswg-drafts/issues/9383#issuecomment-1779644377
> [css-view-transitions-2] Apply new @view-transition rule syntax

- css-view-transitions-2/Overview.bs
* Specify paint holding
* Fix missing |transition| var
* Allow an empty list in the type descriptor
Closes #8888
> [css-view-transitions-2] A few minor edits

- css-view-transitions-2/Overview.bs
As per the resolution, UAs may skip author view-transition if the UA provides its own transition or other navigation experience.
Closes #8953
> [css-view-transitions-2] Add note about UA transitions

- css-color-4/Overview.bs
The example LCH interpolation with premultiplied alpha at https://www.w3.org/TR/css-color-4/#ex-premultiplied-lch un-premultiplies the hue component, which I believe is wrong according to:
> To obtain a color value from a premultipled color value ... each component which had been premultiplied is divided by the interpolated alpha value.
> [css-color-4] Fix LCH alpha interpolation example

- css-counter-styles-3/Overview.bs
Odia is now the preferred name in English.
Ref:
* https://www.omniglot.com/writing/oriya.htm
* https://www.unicode.org/L2/L2012/12380-odia-naming.pdf
* https://en.wikipedia.org/wiki/Odia_language
> [css-counter-styles-3][editorial] Add the preferred name for Oriya

- css-grid-1/Overview.bs
- css-grid-2/Overview.bs
@fantasai and I did some editorial rearrangement, per #3418.
PR to ask for review from @Loirooriol and @mrego.
> [css-grid-1][editorial] Rearrange the grid layout algo a little for clarity, making a new top-level algo. #3418

- css-backgrounds-4/Overview.bs
- css-box-3/Overview.bs
- css-box-4/Overview.bs
- css-shapes-1/Overview.bs
Follow-up on https://github.com/w3c/csswg-drafts/commit/7dc439c83df8bd34885f74689f8cbc7dff77b5e0, fixing https://github.com/speced/bikeshed/issues/2679.
The commit [removed the `<box>` production](https://github.com/w3c/csswg-drafts/commit/7dc439c83df8bd34885f74689f8cbc7dff77b5e0#diff-529e03c120f8bdf7db93b9f4dd1007bce16c44b6f73a45c0da5c4366c4e567a0L678) (which became undefined) and replaced `<box>` references with `<visual-box>`, but some `<box>` references remained in other specs (including CSS Box, which defines `<visual-box>`).
> [css-box-4][css-backgrounds-4][css-shapes-1] Cleanup <*-box> definitions

- css-backgrounds-4/Overview.bs
This adds a `background-layer` property as a shorthand for everything related to background layers excluding `background-color`.
It follows the resolution of https://github.com/w3c/csswg-drafts/issues/8726#issuecomment-1611761835.
Note that I went with `background-layer` for now. The name might still change, which is discussed in #9083.
Fixes #8726
Sebastian
> [css-backgrounds-4] Added `background-layer` property

- css-values-5/Overview.bs
Fixes #8384.
- defines `toggle()` in a production rule
- removes the trailing semicolon in `random()` production
- replaces `<any-value> ; ...`/`<declaration-value> ; ...` with `<declaration-value>? ; ...` since `<any-value>` eats semicolons, and custom properties accept empty inputs
> [css-values-5] Minor syntax fixes

- css-view-transitions-2/Overview.bs
- `types: none` should resolve to having no types
- `navigation: none` should always skip transition.
Closes #9534
> [css-view-transitions-2] Tighten view-transition rule resolving

- css-view-transitions-2/Overview.bs
As per CSSWG resolution.
Closes #9155
> [css-view-transitions-2] UA may apply implementation-defined timeout o cross-document view transition

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
When starting a transition in an old page and there's a capture ongoing for a cross-document view transition, the programatically-created transition is automatically skipped, calling its callback and resolving the promises on the next task. The `ready` promise is rejected.
As per resolution.
Closes #9512
> [css-view-transitions-2] cross-document transition preceeds startViewTransition on outgoing page

- css-anchor-position-1/Overview.bs
Spotted a typo here: https://drafts.csswg.org/css-anchor-position-1/#valdef-inset-area-center
> [css-anchor-position-1] Fixing a typo

- css-images-4/Overview.bs
Editorial.
> Each `<image-set-option>` defines a possible image [...] composed of three parts:
>
> - An image reference (required) [...]
> - A `<resolution>` **(optional)** [...]
> - A `type( <string> )` function **(optional)** [...]
But currently optional parts are not optionals:
> `<image-set-option> = [ <image> | <string> ] [ <resolution> || type(<string>) ]`
> [css-images-4] Allow omitting resolution/type in image-set()

- css-position-3/Overview.bs
Editorial. 
`<'top'>` in source produces `<top>` (CSS type) instead of `<'top'>` (CSS property value range) in output, so it should be `<<'top'>>` in source.
> [css-position-3] Fix broken refs to property value ranges

- css-speech-1/Overview.bs
https://drafts.csswg.org/css-speech-1/#valdef-voice-pitch-frequency
> **`<frequency>`**: [...] Values are restricted to positive numbers when the `absolute` keyword is specified.
This PR adds the corresponding range.
> [css-speech] Enforce positive absolute frequency in `voice-pitch` and `voice-range`

- css-page-floats-3/Overview.bs
[css-page-floats-3] 
The page-floats-3 spec does not enumerate all possible clear values in the property summary. The description below the summary details the available properties `both-inline`, `both-block` and `both`, but these aren't in the summary.
> [css-page-floats-3]: editorial: add all clear values to summary

- cssom-1/Overview.bs
Removes the false assumption that *parse a CSS rule* only receives style rules, which is an oversight in this [commit](https://github.com/w3c/csswg-drafts/commit/19dabdbdcae66319b023e570ba587e951981a603#diff-d3a2dbe000640f0fa11122e261954d2d3eb276f97f2540b1e94afb883d050854L1741), I guess.
> [cssom-1] Fix typo

- css-view-transitions-2/Overview.bs
As per resolution, specificity is 1 pseudo-class (if *) or 2 pseudo-classes (if a type ident)
Closes #9546
> [css-view-transitions-2] Specificity of :active-view-transition()

- css-borders-4/Overview.bs
Some examples used `border-*-parts` and others a `repeat()` function which are currently not defined.
The examples for `border-*-clip` using a `repeat()` function will be added back once it's described how repetitions are meant to work.
Sebastian
> [css-borders-4] Fixed examples for `border-limit` and `border-*-clip` properties

- css-values-4/Overview.bs
As far as I know, all function names are case-insensitive, but there is no specification that requires it.
> [css-values-4] Define function names as case-insensitive

- css-backgrounds-3/Overview.bs
- css-easing-1/Overview.bs
- css-easing-2/Overview.bs
- css-shapes-1/Overview.bs
Eg. rewrite `[<foo>,]? <bar>` as `<foo>? , <bar>`.
In case there is any doubt for `[<bg-layer># ,]? <final-bg-layer>`.
> the `#` and `?` multipliers may be stacked as `#?`
https://drafts.csswg.org/css-values-4/#component-multipliers
---
**edit**
Hmm, actually there is currently a mismatch between...:
> `<step-easing-function> = step-start | step-end | steps(<integer>[, <step-position>]?)`
... and:
> **`steps(<integer>, <step-position>?)`:** The first parameter specifies the number of intervals [...]
This confuses `w3c/reffy`, which [extracts](https://github.com/w3c/webref/blob/4390fd492ed7ee4c100895c123ada1757f9568d9/ed/css/css-easing.json#L103) the latter whereas some contextual definitions like the latter may use an abstract syntax, eg. `pow(A, B)` instead of the formal syntax …
> [multi][editorial] Rewrite syntax with implicitly optional comma

- css-2023/Overview.bs
In [CSS 2023](https://www.w3.org/TR/css-2023/) sections 2.1, 2.2 and 2.3 the names of four specifications do not match with the name that appear in the specifications themselves. 
- CSS User Interface Module Level 3 -> CSS Basic User Interface Module Level 3 
- CSS Text Decoration Level 3 -> CSS Text Decoration Module Level 3 
- CSS Masking Level 1 -> CSS Masking Module Level 1
- CSS Transitions Level 1 -> CSS Transitions
> [css-2023] Possible errata in four specification names

- css-view-transitions-2/Overview.bs
The `pagereveal` event is now part of the HTML spec, so removing the older version here.
> [css-view-transitions-2] Remove pagereveal monkey-patches

- css-shapes-1/Overview.bs
Fixing up a few long-pending Shapes edits for #9053, #8695, #824, and a Guillaume complaint (about the basic shape grammar definitions not being in a prod) that I can't find the issue number for right now.
> Shapes edits

- css-shapes-1/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/5160
> [css-shapes-1] propdef fixes

- css-backgrounds-3/Overview.bs
- css-borders-4/Overview.bs
This corrects the description for where box shadows are applied.
Fixes #9286
> [css-backgrounds-3][css-borders-4] Fixed definition for where box shadows apply

- css-backgrounds-4/Overview.bs
Added the exclamation point to the syntaxes of `background-position-block` and `background-position-inline` like there is already for the physical longhands to make it clear that the combination of `start` or `end` keyword with a `<length-percentage>` must produce a value.
Sebastian
> [css-backgrounds-4] Fixed logical background-position-* longhands syntaxes

- css-anchor-position-1/Overview.bs
The syntax for `anchor-size()` got corrected to actually define `anchor-size()` instead of just `anchor()`.
Sebastian
> [css-anchor-position-1] Fixed anchor-size() syntax

- css-view-transitions-1/Overview.bs
Keeping `auto` as reserved for future purposes, so for now it is not a valid ident for `view-transition-name`.
Closes #9639
> [css-view-transitions-1] Treat `auto` as an invalid value for `view-transition-name`

- css-view-transitions-1/Overview.bs
Closes https://github.com/w3c/csswg-drafts/issues/9672.
> [css-view-transitions-1] Add note to explain paint order

- css-view-transitions-1/Overview.bs
> [css-view-transitions-1] Add a note to explain how the named elements are cleaned up

- css-view-transitions-2/Overview.bs
[css-view-transitions-2] Nit: use 'set' to update variable
Small fix to css-view-transitions-2 where we're using 'let' when updating the value of the `Document`'s `active view transition`.
> [css-view-transitions-2] Nit: use 'set' to update variable

- css-contain-3/Overview.bs
From [1]: "RESOLVED: No container is valid for unknown queries"
[1] https://github.com/w3c/csswg-drafts/issues/7551#issuecomment-1854385652
> [css-contain-3] No query container for unknown features (#7551)

- css-view-transitions-1/Overview.bs
Note: this change is not a behavior change, but rather a clarification of existing expected behavior.
- Instead of reacting to the update callback's promise in several places, we react to it once with fulfill/reject steps and continue based on the state, all inside the "call the update callback" algorithm.
- Clarify that in the successful case, `updateCallbackDone` is always resolved after the new state capture but before the `ready` promise. (This is current behavior, but not explicit in the current spec).
- Fix a bug where we were resolving a promise with the result of reacting to a different promise, which is wrong use of those operations.
- Use normative language for user-agent transition timeout
- Remove redundant early returns for `done` phase.
Closes #9762
> [css-view-transitions-1] Refactor timings of `updateCallbackDone` and related

- css-view-transitions-2/Overview.bs
As per [resolution](https://github.com/w3c/csswg-drafts/issues/8783#issuecomment-1885359766), `auto` would match any navigation, except:
- reloads (via script, browser UI, `<meta>`, anythg)..,
- A browser-UI push/replace (e.g. typing in the URL address bar, bookmarks, etc)
Closess #8783
> [css-view-transitions-2] Define the `navigation: auto` descriptor

- css-color-4/Overview.bs
And thus shouldn't match CanvasText, but Canvas.
> [css-color-4] ActiveCaption is a background.

- css-shapes-1/Overview.bs
`shape-image-threshold` is defined with `<alpha-value>` but its specified value must be clamped whereas there is interop for clamping the computed value, like for `opacity`.
I suggest to define `shape-image-threshold` with `<'opacity'>`.
Related: https://github.com/w3c/csswg-drafts/issues/8311
> [css-shapes-1] Replace `<alpha-value>` with `<'opacity'>`

- scroll-animations-1/Overview.bs
> [scroll-animations-1] Add `all` as a value for `timeline-scope`

- cssom-view-1/Overview.bs
[cssom-view-1] Add more checkVisibility dictionary properties
Fixes #9474
Fixes #9487
> [cssom-view-1] Add more checkVisibility dictionary properties

- css-scroll-snap-2/Overview.bs
snapChanged and snapChanging details are JavaScript events which are fired when a scroller's snap target changes.
This adds some interfaces to support the definition of these events:
- SnapEvent interface defines a shared event type for snapChanged and snapChanging.
- SnapTargetList interface defines an object that stores one array of snap targets per x/y axis.
- SnapTargetArray interface defines an object that stores a single array of snap targets.
> [css-scroll-snap-2] Add snapChanged and snapChanging details

- cssom-1/Overview.bs
Per https://github.com/w3c/csswg-drafts/issues/3103#issuecomment-421261334, this PR removes a reference to HTML's "script-blocking style sheet" concept from https://drafts.csswg.org/cssom/#requirements-on-user-agents-implementing-the-xml-stylesheet-processing-instruction.
PTAL @annevk. Btw do you have any opinions on what we should do about the same reference to the same term at the bottom of https://drafts.csswg.org/cssom/#requirements-on-user-agents-implementing-the-http-link-header? These days HTML defines the `Link` header processing model, and as per https://html.spec.whatwg.org/#table-link-relations we only support `preconnect` and `preload`, not what CSSOM-1 defines here (and this is noted by the section's "Note yet widely implemented" call-out). IMO it seems best to expand this PR …
> Remove duplicate script-blocking style sheet requirement

- css-scroll-snap-2/Overview.bs
This contribution replaces all occurrences of “the the” by “the”.
> [css-scroll-snap-2] Fix typo in CSS `scroll-snap` overview

- css-contain-4/scroll_state_explainer.md
Moved from https://lilles.github.io/explainers/state_container_queries.html with state() changed to scroll-state().
> [css-contain-4] Move Scroll State Container Queries explainer into repo #6402

- css-fonts-4/Overview.bs
The `font-stretch` property was not properly defined as a "property". This made links to it from the rest of the spec actually target the definition of the property in the /TR version of the spec.
> [css-fonts-4] Set dfn type for legacy "font-stretch" property dfn

- scroll-animations-1/Overview.bs
As suggested by @tantek in https://github.com/mozilla/standards-positions/pull/978#pullrequestreview-1852888403
> [scroll-animations] Abstract should say CSS properties instead of markup

- css-viewport/Overview.bs
> Negative values for [zoom](https://drafts.csswg.org/css-viewport-1/#propdef-zoom) are illegal.
This PR encodes this requirement in its value definition, following the [range notation syntax](https://drafts.csswg.org/css-values-4/#numeric-ranges).
> [css-viewport-1] Hardcode numeric range in syntax

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
A `view-transition-class` property allows specifying view-transition pseudo-elements that apply to multiple participating elements without having to replicate them.
In this PR:
- Specifying `view-transition-class`
- Extending the pseudo-element syntax to support `::view-transition-foo(name.class)`
- Extending the capture algorithms and data structure to capture the classes
- Added a simple example for using classes
Based on [this resolution](https://github.com/w3c/csswg-drafts/issues/8319#issuecomment-1876155920).
Closes #8319
> [css-view-transitions-2] Specify 'view-transition-class' and corresponding algorithms

- css-view-transitions-2/Overview.bs
The syntax used parentheses for grouping, instead of brackets, see: https://drafts.csswg.org/css-values-4/#component-combinators
(Buggy syntax introduced in #9773)
> [css-view-transitions-2] Fix "<pt-class-selector>" syntax

- css-view-transitions-2/Overview.bs
In prepartion for the HTML integration and the `pageconceal` event, the check for whether cross-document view transition should take place is to be called twice from the HTML spec:
- once when initiating the navigation, to check if a `pageconceal` event should be blocking
- once right before firing `pageconceal`.
So separating the algorithm and exporting the check.
> [css-view-transitions-2] Separte MPA transition start from check

- css-view-transitions-2/Overview.bs
In #9383, which introduced `@view-transitions`, I do not see examples with `@view-transitions` (or with the other rule names) containing nested rules, so I assume this is not planned in the future, and that the basic syntax of its block contents can be defined with `<declaration-list>` instead of `<declaration-rule-list>`.
https://drafts.csswg.org/css-view-transitions-2/#view-transition-grammar
> [css-view-transitions-2] Only accept declarations in `@view-transitions`

- css-fonts-5/Overview.bs
[css-fonts-5] font-size-adjust precedes font metrics overrides #8967
> [css-fonts-5] font-size-adjust precedes font metrics overrides #8967

- css-view-transitions-1/Overview.bs
Currently, below `view-transition-name`, defined with `none | auto | <custom-ident>`:
> `<custom-ident>`: [...] The value `none` is excluded from `<custom-ident>` here.
https://drafts.csswg.org/css-view-transitions-1/#valdef-view-transition-name-custom-ident
This PR adds `auto` as an excluded `<custom-ident>` value.
> [css-view-transitions-1] Exclude auto as custom ident for view-transition-name

- css-view-transitions-2/Overview.bs
Pseudo classes start with a single colon. Pseudo elements start with two.
> [css-view-transitions-2] Nit: remove extra leading colon before active-view-transition() pseudo class

- mediaqueries-5/Overview.bs
This CL adds the `picture-in-picture` display mode to mediaqueries-5 spec as discussed in https://github.com/w3c/csswg-drafts/issues/9260
> [mediaqueries-5] Add picture-in-picture display mode | issue #9260

- css-view-transitions-1/Overview.bs
Closes #9817
See [resolution](https://github.com/w3c/csswg-drafts/issues/9817#issuecomment-1933113926).
> [css-view-transitions-1] Inherit to the UA stylesheet rules for animation-delay in vt pseudo-elements

- css-fonts-4/Overview.bs
The map interface for [`@historical-forms`](https://drafts.csswg.org/css-fonts-4/#at-ruledef-font-feature-values-historical-forms) declaration values is missing in [`CSSFontFeatureValuesRule`](https://drafts.csswg.org/css-fonts-4/#cssfontfeaturevaluesrule).
> [css-fonts-4] Define CSSFontFeatureValuesRule.historicalForms

- css-view-transitions-1/Overview.bs
See [resolution](https://github.com/w3c/csswg-drafts/issues/9543#issuecomment-1939242246).
Note: this only covers [css-view-transitions-1], will follow up on cross-document view transitions.
> [css-view-transitions-1] Auto-skip a view-transition if document is hidden

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
- L2 redefines appropriate algorithms and additional fields instead of relying on L1
- moved `onReady` to correct place, and renamed `proceedWithNavigation`.
See #9886, based on [this resolution](https://github.com/w3c/csswg-drafts/issues/9850#issuecomment-1919627409).
> [css-view-transitions-2] Editorial: refactor L2 concerns out of L1

- css-view-transitions-2/Overview.bs
This handles the cases where
- A cross document transition starts from a hidden document
- A hidden document receives a cross-document transition
- A cross-document transition starts from a document that hasn't yet rendered
Closes #9822
See also #9543
Resolutions:
https://github.com/w3c/csswg-drafts/issues/9822#issuecomment-1939374784
https://github.com/w3c/csswg-drafts/issues/9543#issuecomment-1939242246
> [css-view-transitions-2] Skip cross-document view-transitions when hidden or not-yet-revealed

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
Together with https://github.com/whatwg/html/pull/10137
See #9543
> [css-view-transitions-1] Export an algorithm to skip a transition in a hidden document

- css-view-transitions-2/Overview.bs
See [this resolution](https://github.com/w3c/csswg-drafts/issues/9888#issuecomment-1939367607)
Closes #9888
> [css-view-transitions-2] Resolve outbound transition promises after document unloads

- CONTRIBUTING.md
This is merely a suggestion to improve the contribution best practices to reflect (what I think is) the actual status quo.
This is based on an attempt to figure out how we could have avoided some incidents that ruffled a few feathers, by being clearer about expectations;  I'd welcome feedback about whether this is useful or if it could be improved in some other way.
> [Contributing.md] Suggestion to improve the contribution best practices

- css-view-transitions-2/Overview.bs
Closes #9887
See [resolution](https://github.com/w3c/csswg-drafts/9887#issuecomment-1939286361)
> [css-view-transitions-2] Amend specificity of view-transition pseudos with a class

- css-color-4/Overview.bs
- css-color-5/Overview.bs
- css-color-6/Overview.bs
- cssom-1/Overview.bs
This PR rephrases `specified value` as `declared value`, where it involves CSSOM value serialization. Fixes #9993.
The fact that the CSS-wide keywords are kept as-is is already [covered in serialize-values tests](https://github.com/web-platform-tests/wpt/blob/f57f833daf407ab46840ec52c0a8de8ee02e319a/css/cssom/serialize-values.html#L369-L372).
> [cssom-1][css-color-4][css-color-5][css-color-6] Describe CSSOM serialization in terms of declared values rather than specified values, fix #9993

- web-animations-2/Overview.bs
This is to specify the [agreed upon](https://github.com/w3c/csswg-drafts/issues/8799#issuecomment-1561576205) animation.progress API.
> [web-animations-2] Specify Animation progress API

- css-view-transitions-2/Overview.bs
- Make types mutable using ViewTransition.typeList https://github.com/w3c/csswg-drafts/issues/9542#issuecomment-1994829341
- Separate `:active-view-transition` and `:active-view-transition-type` See https://github.com/w3c/csswg-drafts/issues/9972#issuecomment-1994889933
- Add notes about types being bound to one document See https://github.com/w3c/csswg-drafts/issues/9526#issuecomment-1994844676
Closes #9972
Closes #9542
Closes #9526
Closes #9626
> [css-view-transitions-2] Apply resolutions for view-transition types

- web-animations-1/Overview.bs
Sorry, but I didn’t open an issue for such a small typographic error.
> [web-animations-1] Fix typo `invaid` → `invalid`

- css-view-transitions-2/Overview.bs
Instead of relying on the source snapshot params in HTML, we update a flag every time something relevant changes, and HTML can read that flag.
> [css-view-transitions-2] Update the algorithm to check opt-in on outbound transition

- css-overflow-3/Overview.bs
This clarification was precipitated by an  [intersection observer issue](https://github.com/w3c/IntersectionObserver/issues/521) in order to avoid confusion over who can scroll the overflow area of a scroll container.
> [css-overflow-3] Clarify that scripts can also scroll a scroll container

- css-scroll-snap-2/Overview.bs
- cssom-view-1/Overview.bs
SnapEvent defines the interface of scroll-snap-related JavaScript events, snapchanged and snapchanging.
> [css-scroll-snap-2] Add SnapEvent definition

- css-animations-1/Overview.bs
- css-fonts-4/Overview.bs
- cssom-1/Overview.bs
This is intended to address #5649.
> [cssom] [css-fonts] [css-page] Sort out properties and descriptors.

- css-view-transitions-2/Overview.bs
- Divided the spec to have feature-based sections rather than by type of addition.
- Added overviews and examples, enhanced intro to introduce all new features.
- Applied resolutions regarding types:
* https://github.com/w3c/csswg-drafts/issues/10070#issuecomment-2009980134
* https://github.com/w3c/csswg-drafts/issues/10011#issuecomment-2009951924
* https://github.com/w3c/csswg-drafts/issues/10071#issuecomment-2005363808
Closes #10011 
Closes #10070
Closes #10071
> [css-view-transitions-2] Refactor based on topics

- css-view-transitions-2/Overview.bs
Based on resolution:
https://github.com/w3c/csswg-drafts/issues/9874#issuecomment-2023235242
Closes #9874
> [css-view-transitions-2] Allow pseudo-element with class and no *

- css-view-transitions-2/Overview.bs
Based on CSSWG resolution:
https://github.com/w3c/csswg-drafts/issues/10114#issuecomment-2023217450
Closes #10114
> [css-view-transitions-2] Use the right data types for `types`

- css-transforms-2/Overview.bs
It should've been "making elements [...] further away appear smaller", not "making elements [...] further away to appear smaller".
I have not opened an issue for this or discussed with anyone, given how minor of a change it is.
>  [css-transforms-2] Fix a typo.

- css-scrollbars-1/Overview.bs
While the example isn't inherently wrong, it's of little relevance to present-day authors, as Internet Explorer hasn't been supported for years, and barely has any usage anymore.
> [css-scrollbars] Remove example about IE

- css-view-transitions-1/Overview.bs
This doesn't change observable behavior, but makes the visibility reaction consistent with other similar reactions.
See https://github.com/whatwg/html/pull/10137
> [css-view-transitions-1] Perform the visibility change steps in own task

- css-view-transitions-2/Overview.bs
- Add [SameObject] to CSSOM
- Clarify that classes can't include white space
> [css-view-transitions-2] Make some syntax clarifications

- css-view-transitions-1/Overview.bs
This aligns with current behavior, but was overlooked in the spec.
Closes #10177
> [css-view-transitions-1] Use snapshot containing block for new root

- css-view-transitions-1/Overview.bs
[css-view-transitions-1] More precisely define snapshot containing block in subframes #9786
The intent of the current definition is that the snapshot containing block in a child frame should be a rect at the origin, the same size as the frame, including any scrollbars.
Initial containing block is misleading in 2 ways - it doesn't include scrollbars in its size and its position changes as the page scrolls so a strict reading would make the snapshot containing block's position dependent on the scroll offset.
I think [viewport](https://www.w3.org/TR/CSS22/visuren.html#viewport) is the better definition here but I believe that excludes scrollbars as well so we explicitly union it with [scrollbar gutters](https://drafts.csswg.org/css-overflow/#scrollbar-gutter-property).
Also, refer to [child …
> [css-view-transitions-1] More precisely define snapshot containing block in subframes #9786

- css-scroll-snap-1/Overview.bs
Implements the algorithm agreed upon in https://github.com/w3c/csswg-drafts/issues/9622#issuecomment-1843949800 to select a particular snap area in each axis. Fixes #9622.
> [css-scroll-snap-1] Define selected snap area amongst multiple aligned candidates

- cssom-1/Overview.bs
`CSSRuleList` is currently defined as *"a collection of CSS **style** rules"*.
`CSSRule` is currently defined as *"representing a CSS **style** rule"*.
I do not know if this is a remnant of an older version of the spec, or if this somewhat matches browser implementations. In the second case, I assume it is better to make the spec more abstract.
> [cssom-1] Fix false assumption that all rules are style rules

- css-fonts-3/Overview.html
- web-animations-1/Overview.bs
(Apologies, discovered these over a multi-repo search. Thought to just file a simple PR.)
> [css-?] Correct instances of “the these”

- css-contain-3/Overview.bs
> [css-contain-3] Fix a typo in the text of size container features

- css-syntax-3/Overview.bs
[*Consume a qualified rule*](https://drafts.csswg.org/css-syntax-3/#consume-qualified-rule) consumes two blocks in a row:
> Otherwise, consume a block from `input`, and assign the results to `rule`’s lists of declarations and child rules. 
> 
> Consume a block from `input`, and let `child rules` be the result.
I assume it is a typo from https://github.com/w3c/csswg-drafts/commit/e5547b96f5de6fb5a68d050f42d562c448b99d0b.
> [css-syntax-3] Do not consume a qualified rule block twice

- cssom-view-1/Overview.bs
Per https://github.com/w3c/csswg-drafts/issues/9932, add `shadowRoots` parameter to `caretPositionFromPoint` API.
Implementation bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1889503
https://issues.chromium.org/issues/332774620
https://bugs.webkit.org/show_bug.cgi?id=172137
WPT test coverage will be added subsequently.
> [cssom-view] add `shadowRoots` parameter to `caretPositionFromPoint` API.

- css-view-transitions-1/Overview.bs
The "update callback done" promise should always be resolved right after the update callback is called, even in failure cases. This is what certain WPTs expect, for instance: css/css-view-transitions/duplicate-tag-rejects-start.html
> [css-view-transitions-1] Fix timing of resolving "update callback done" promise

- css-view-transitions-1/Overview.bs
Applies resolution at https://github.com/w3c/csswg-drafts/issues/10145.
> [css-view-transitions-1] Ignore names from shadow DOM

- css-scroll-snap-2/Overview.bs
Add snap event handler attributes for Document and Element
This adds the onsnapchanged and onsnapchanging attributes to the css-scroll-snap-2 [specification](https://drafts.csswg.org/css-scroll-snap-2/#snap-events) for elements and Document objects.
Heavily influenced by css-animations' [extensions to GlobalInterfaceHandlers](https://drafts.csswg.org/css-animations/#interface-globaleventhandlers).
> [css-scroll-snap-2] Add snap event handler attributes for Document and Element

- css-scroll-snap-2/Overview.bs
- cssom-view-1/Overview.bs
This renames snapchanged to scrollsnapchange and snapchanging to scrollsnapchanging, per the CSSWG [resolution](https://github.com/w3c/csswg-drafts/issues/9697#issuecomment-2089278615)
> [css-scroll-snap-2] Rename snap events

- cssom-view-1/Overview.bs
Per #10230, `CaretPosition` backed by live range can cause issues. We should remove the `caret range` concept from `CaretPosition` interface.
This is also a long-standing issue. https://lists.w3.org/Archives/Public/www-style/2011May/0051.html
> [cssom-view] Remove `caret range` concept from `CaretPosition` interface.

- web-animations-2/Overview.bs
Fixes the various indentation errors when running bikeshed on the web-animations-2 spec.
> [web-animations-2] Fix bikeshed indentation errors

- css-text-4/Overview.bs
> [css-text-4] Add note about deviations from UAX-14

- css-animations-2/Overview.bs
In #8746 it was resolved to switch from `<custom-ident>` to `<dashed-ident>` for timeline names, and this was done in the grammar in 9f39808. However, further down in the spec, it still shows `<custom-ident>`
> [css-animations-2] Fix custom-ident to dashed-ident for animation-timeline

- css-gcpm-3/Overview.bs
The spec introduces the `element()` value, not a `value()` element.
It looks like this is a simple typo.
> [css-gcpm-3] Fix typo

- css-pseudo-4/Overview.bs
> Define "part-like pseudo-element", from #10083.

- css-pseudo-4/Overview.bs
This adds the ::details-content pseudo-element as resolved in:
1. https://github.com/w3c/csswg-drafts/issues/9879#issuecomment-1942785500
2. https://github.com/whatwg/html/issues/10200#issuecomment-1998676547 / https://github.com/w3c/csswg-drafts/issues/9951#issuecomment-1997916879
3. https://github.com/w3c/csswg-drafts/issues/9879#issuecomment-2121658036
and uses the definition added in #10083.
> [css-pseudo-4] Add ::details-content pseudo-element.

- cssom-view-1/Overview.bs
Per issue #10345, We should change the API signature from `document.caretPositionFromPoint(double x, double y, ShadowRoot... shadowRoots)` to `document.caretPositionFromPoint(double x, double y, optional CaretPositionFromPointOptions options = {})` where `CaretPositionFromPointOptions` is defined as:
```
dictionary CaretPositionFromPointOptions {
sequence<ShadowRoot> shadowRoots = [];
};
```
> [cssom-view] Change `document.caretPositionFromPoint`'s `shadowRoots` parameter from rest parameter to a dictionary with an array of shadow roots

- css-box-4/Overview.bs
This adds the change for the [resolution for allowing the combination of `block` and `inline` keywords in `margin-trim`](https://github.com/w3c/csswg-drafts/issues/7884#issuecomment-2160955876).
Fixes #7884.
Sebastian
> [css-box-4] Allowed combination of block and inline keywords in margin-trim

- css-color-4/hslToRgb.js
I propose to remove the `<hue>` normalization in range [0,360) from the HSL to RGB algorithm. I think this is supposed to already have been applied ~~at parse time~~ before, as defined in [4.3. Representing Cylindrical-coordinate Hues: the `<hue>` syntax](https://drafts.csswg.org/css-color-4/#hue-syntax):
> This number is normalized to the range [0,360).
Furthermore, this is not applied in other conversion algorithms (HWB to RGB, LCH to LAB, etc).
> [css-color-4] `<hue>` is already normalized

- css-color-5/Overview.bs
[`<color-interpolation-method>`](https://drafts.csswg.org/css-color-5/#color-interpolation-method) does not allow to specify `<hue-interpolation-method>` with `<rectangular-color-space>`, therefore I suggest to remove this from step 2 of [Calculating the Result of color-mix](https://drafts.csswg.org/css-color-5/#color-mix-result):
> 2. [...] If the specified color space is a rectangular-orthogonal-color space, then specifying a `<hue-interpolation-method>` is an error.
**Note:** in the sentence above (which is removed by this PR), *rectangular-orthogonal-color* is an autolink that has no target; maybe [`<rectangular-color-space>`](https://drafts.csswg.org/css-color-5/#typedef-rectangular-color-space) should have been used?
> [css-color-5] <hue-interpolation-method> error occurs at parse time

- css-color-4/Overview.bs
This sentence in [13.2. CSS Gamut Mapping to an RGB Destination](https://drafts.csswg.org/css-color-4/#css-gamut-mapping) suggests that CSS gamut mapping is applied to get used values:
> **TESTS**
>
> Used values of color are not exposed to script, making this hard to test in an automated manner.
From my understanding, used values of color are exposed by [`getComputedStyle()`](https://drafts.csswg.org/cssom-1/#resolved-values):
> - [...]
> - `color`
> - `outline-color`
> - A resolved value special case property like `color` defined in another specification
>
> The resolved value is the [used value](https://drafts.csswg.org/css-cascade-5/#used-value).
I guess the resolved value should not depend on the display device ([13.1. An Introduction to Gamut …
> [css-color-4] CSS gamut mapping applies on actual values

- css-pseudo-4/Overview.bs
1. By depending on the animation rules defined in https://drafts.csswg.org/css-contain-3/#content-visibility-animation the step-end and step-start values are not needed.
2. By depending on the change in 
https://github.com/whatwg/html/pull/10265#issuecomment-2145837051 
and
whatwg/html@fb3033a
the display: block is no longer needed.
> [css-pseudo-4] Simplified example of `::details-content`

- css-scroll-snap-2/Overview.bs
This specifies the resolution from
https://github.com/w3c/csswg-drafts/issues/10175 that when the targets of a snap event are pseudo elements, the snap event should the owning elements of the pseudo-elements as snap targets.
> [css-scroll-snap-2] Set pseudo snap Targets to their owning elements.

- cssom-1/Overview.bs
I found this was missing while implementing `CSSPageDescriptors` in Gecko.
`@page{ orientation: ... }` Is generally treated the same as `@page{ size: ... }` in this way and definitely is a descriptor on page-rules, so it should be included in `CSSPageDescriptors`.
> [cssom] [css-page] Add orientation to CSSPageDescriptors

- css-mixins-1/Overview.bs
To begin with, only `@function` is described.
#9350
> [css-mixins] Add CSS Functions and Mixins specification

- css-anchor-position-1/Overview.bs
> [css-anchor-position-1] Rename position-try-options to -fallbacks

- cssom-1/Overview.bs
The current text expects 'parse a CSS declaration block' to return a syntax error, which it never actually returns.
Follow-up to 7d8f87c8b8de9b7dd64719aeac18004ea76fdad0.
> [cssom] Throw on empty 'nested declarations rule' insertion

- css-view-transitions-1/Overview.bs
The previous fix for using the tree context made it inconsistent with how shadow DOM styling works for things like anchor positioning, and made it so that e.g. `::part` cannot set a `view-transition-name`.
Refactored to make the `view-transition-name` a tree-scoped name, rather than check the tree context of the element.
This aligns better with the [existing resolution](https://github.com/w3c/csswg-drafts/issues/10145#issuecomment-2100931679) and should not require a new resolution.
Closes #10145
> [css-view-transitions-1] Fix tree-scoping from element-based to name-based.

- css-viewport/Overview.bs
In preparation to add the segments property we need to make sure that the viewport property is properly specified. This patch already adds the zoom property to the viewport interface as it was already defined.
> [css-viewport] Define the viewport property in window

- css-scroll-snap-2/Overview.bs
Towards resolving [6985](https://github.com/w3c/csswg-drafts/issues/6985#issuecomment-2166073296) this patch removes scroll-start from the spec and notes that :snapped is being replaced.
> [css-scroll-snap-2] Drop scroll-start and add issue to :snapped

- css-viewport/Overview.bs
Reverts w3c/csswg-drafts#10548
Zoom is not a property on Window, but a CSS property.
> Revert "[css-viewport] Define the viewport property in window"

- css-fonts-4/Overview.bs
Following 69f7f7a, I think [`<generic-complete>`](https://drafts.csswg.org/css-fonts-4/#typedef-generic-complete) is missing `monospace`.
> [css-fonts-4] Restore monospace in generic family

- css-anchor-position-1/Overview.bs
The complicated wording indicates that you have to have exactly the same "leaf" skipped contents. IOW, anchors can't flow across an element that skips its contents to something outside, but two things in a skipped subtree without intervening skipped-causing elements can anchor to each other.
This change allows browsers to avoid layout of skipped content when starting to skip subtrees.
> [css-anchor-positioning-1] Clarify that an element can anchor to another within the same skipped contents

- css-align-3/Overview.bs
The link `#auto-safety-defaults` does not exist, the correct link is `#auto-safety-default`.
> [css-align-3] Fix broken link

- css-align-3/Overview.bs
In the first paragraph of the example and section heading, the order of the keywords `safe` and `unsafe`, but the figure for illustrates this keywords in the opposite order, which may cause confusion.
Changed the order of the images and the order of the image descriptions.
> [css-align-3] Example 3 changing the order of images to match the text

- css-nesting-1/Overview.bs
Follow up on https://github.com/w3c/csswg-drafts/commit/23459f3bc644814fb441ed5732b818fbf4d70ee4.
> The `@container` rule is a conditional group rule [...]
https://drafts.csswg.org/css-conditional-5/#container-rule
> [css-nesting-1][editorial] `@container` is now a conditional group rule

- css-scroll-snap-2/Overview.bs
This removes longhand references to scroll-start-target-* as these have been dropped.
> [css-scroll-snap-2] Remove scroll-start-target-* longhand vestiges

- css-view-transitions-2/Overview.bs
> [css-view-transitions-2] Stop extending CSSRule with obsolete pattern

- css-conditional-3/Overview.bs
Introduced by recent commit:
https://github.com/w3c/csswg-drafts/commit/3dab354901b4c9b2a716475efb98445317c65727
There's no `bool` type in Web IDL, only `boolean`.
> [css-conditional-3] Fix Web IDL, `bool` should have been `boolean`

- css-exclusions-1/Overview.bs
The command:
```shell
bikeshed spec css-exclusions-1\Overview.bs
```
Throws error when called locally:
```shell
LINE ~51: The biblio refs [[CSS2]] and [[CSS21]] are both aliases of the same base reference [[CSS21]]. Please choose one name and use it consistently.
```
A search through the repositories shows that the alias `[[!CSS2]]` is used three times more often than `[[!CSS21]]`, so I replaced all aliases with `[[!CSS2]]`.
> All future specifications should refer to CSS 2.2 when referring to CSS level 2;
[Sourse](https://drafts.csswg.org/css2/#about)
But did not find a list of preferred aliases, so relied on the frequency of alias usage in the project. If such a list exists somewhere, please let me know.
> [css-exclusions-1] Fix bikeshed errors

- css-exclusions-1/Overview.bs
The command:
```shell
bikeshed spec css-exclusions-1\Overview.bs
```
Throws errors when called locally:
```shell
LINE 206:5: Spurious / in <img>.
LINE 218:7: Spurious / in <img>.
...
```
> The spec command is the most common one you’ll use. It turns a Bikeshed source file into an output HTML file. The rest of this document mostly describes how to format a source file for use with this command.
[Source](https://speced.github.io/bikeshed/#cli-spec)
Could you please tell where the description how specifications are generated for the drafts.csswg.org domain can be found? Apparently, it's not done using the command `bikeshed spec`, otherwise the document can not be generated. Would like to have the ability to fully reproduce the process locally.
> [css-exclusions-1]  Fix spurious / in <img>

- css-color-hdr/Overview.bs
The +b needs to happen outside of the exp() call to be the reverse of the original HLG.
We found this while writing tests for GTK doing roundtrips to HLG and back. See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7493
> Fix reverse HLG transform

- css-view-transitions-1/Overview.bs
> [css-view-transitions-1] Add a rendering-characteristic note about out-of-viewport elements

- css-sizing-3/Overview.bs
- css-sizing-4/Overview.bs
This adds calc-size() support to the grammar productions for width/height and min/max-width/height, which also implies adding them to the productions for block/inline-size and min/max-block/inline-size and to flex-basis.
This is part of #626.
> [css-sizing] Add calc-size to productions for width/height and min/max-width/height.

- css-inline-3/Overview.bs
The command:
```
bikeshed spec css-inline-3\Overview.bs
```
Throws errors:
```
LINE 2571:27: Garbage after the tagname in </h4>.
```
> [css-inline-3] Fix broken tag

- css-highlight-api-1/Overview.bs
The command:
```
bikeshed spec css-highlight-api-1\Overview.bs
```
Throws errors:
```
LINE ~203: Couldn't find section '#es-set-add' in spec 'webidl':
[[webidl#es-set-add|the steps for a built-in setlike add function]]
LINE ~241: Couldn't find section '#es-map-set' in spec 'webidl':
[[webidl#es-map-set|the steps for a built-in maplike set function]]
```
> [css-highlight-api-1] Fix broken links

- css-line-grid-1/Overview.bs
The command:
```
bikeshed spec css-line-grid-1\Overview.bs
```
Throws errors:
```
LINE 82:3: Spurious / in <img>.
LINE 91:4: Spurious / in <img>.
LINE 128:3: Spurious / in <img>.
LINE 136:3: Spurious / in <img>.
LINE 382:4: Spurious / in <img>.
LINE 389:4: Spurious / in <img>.
LINE 410:4: Spurious / in <img>.
LINE 417:4: Spurious / in <img>.
LINE 650:4: Spurious / in <img>.
LINE 657:4: Spurious / in <img>.
LINE 673:4: Spurious / in <img>.
LINE 680:4: Spurious / in <img>.
LINE 703:4: Spurious / in <img>.
LINE 710:4: Spurious / in <img>.
```
> [css-line-grid-1] Spurious / in <img>

- css-ui-4/Overview.bs
- addresses https://github.com/w3c/csswg-drafts/issues/7700#issuecomment-1933183097
- addresses https://github.com/TalbotG/web-platform-tests/blob/3a2ba5940decbe028a26482b1c44243ba8d7338f/css/css-ui/parsing/canonical-order-outline-sub-properties-001.html#L132
The `outline` property needs to look consistent with the [`border`](https://drafts.csswg.org/css-backgrounds/#propdef-border) property. The rest of the document follows the `width style color` order from the first commit, so no change is required.
> [css-ui-4] update outline value syntax

- css-conditional-3/Overview.bs
> [css-conditional-3] supports() must return false for invalid custom property value

- css-nav-1/Overview.bs
The command:
```
bikeshed spec css-nav-1\Overview.bs
```
Throws errors:
```
LINE 137:5: Spurious / in <img>.
LINE 278:9: Spurious / in <img>.
LINE 279:9: Spurious / in <img>.
LINE 288:9: Spurious / in <img>.
LINE 289:9: Spurious / in <img>.
LINE 290:9: Spurious / in <img>.
LINE 291:9: Spurious / in <img>.
LINE 554:9: Spurious / in <img>.
LINE 785:9: Spurious / in <img>.
LINE 841:9: Spurious / in <img>.
LINE 1311:7: Spurious / in <img>.
LINE 1528:9: Spurious / in <img>.
LINE 1606:9: Spurious / in <img>.
```
> [css-nav-1] Fix spurious / in <img>

- css-overflow-5/Overview.bs
This changes the scroll marker primitive to be based on a regular <a> element within a focusgroup allowing multiple groups of markers to be created and leaning on the focusgroup proposal to establish the interaction behavior.
> [css-overflow-5] Create scroll markers from <a> elements.

- css-shapes-2/Overview.bs
- `using` instead of `via`
- allow any order in arcs/curves
Closes #5841
> [css-shapes-2]: apply minor comments to `shape()` syntax

- css-tables-3/Overview.bs
The closing tag in the source code:
```
</a boxes>
```
Fixed tag, moved "boxes" into the text.
> [css-tables-3] Fix misprint

- css-tables-3/Overview.bs
The command:
```
bikeshed spec css-tables-3\Overview.bs
```
Throws errors:
```
LINE 153:3: Spurious / in <img>.
LINE 635:4: Spurious / in <img>.
LINE 1803:4: Spurious / in <img>.
LINE 1996:6: Spurious / in <img>.
LINE 2657:5: Spurious / in <img>.
LINE 2867:4: Spurious / in <img>.
LINE 2879:4: Spurious / in <img>.
LINE 2915:4: Spurious / in <img>.
```
> [css-tables-3] Fix spurious / in <img>

- css-shapes-2/Overview.bs
The command:
```
bikeshed spec css-shapes-2\Overview.bs
```
Throws errors:
```
LINE 490:3: Spurious / in <img>.
LINE 567:3: Spurious / in <img>.
LINE 582:3: Spurious / in <img>.
LINE 585:3: Spurious / in <img>.
LINE 657:4: Spurious / in <img>.
```
> [css-shapes-2] Fix spurious / in <img>

- css-round-display-1/Overview.bs
The command:
```
bikeshed spec css-round-display-1\Overview.bs
```
Throws errors:
```
LINE 303:9: Spurious / in <img>.
LINE 324:9: Spurious / in <img>.
```
> [css-round-display-1] Fix spurious / in <img>

- css-font-loading-3/Overview.bs
It's not used anywhere since a4fdf3e4853af40542a6bb3a9cebc8b76dc760a8.
> [css-font-loading-3] Remove unused ForEachCallback

- css-conditional-5/Overview.bs
Per resolution in:
https://github.com/w3c/csswg-drafts/issues/5984#issuecomment-2112977366
> [css-conditional-5] Container queries use the flat tree #5984

- css-color-4/rgbToHwb.js
Tests related to out-of-gamut relative colors [css-color-5] already implicitly match this corrected behavior.
> [css-color-4] #10695 Fix rgbToHwb to use subset of rgbToHsl that only computes the hue

- css-view-transitions-2/Overview.bs
Resolution: https://github.com/w3c/csswg-drafts/issues/10529#issuecomment-2274241823
Closes #10529
> [css-view-transitions-2] `view-transition-class` is a tree-scoped name

- css-font-loading-3/Overview.bs
Rather than defining a custom BinaryData typedef, the FontSource interface should just use the BufferSource definition from WebIDL.
https://webidl.spec.whatwg.org/#BufferSource
I came across this implementing this API for the Ladybird Browser. Let me know if the issue is not as editorial as I think and needs an issue/meeting topic :).
> [css-font-loading-3][editorial] Reference WebIDL BufferSource

- css-grid-2/Overview.bs
Fixed a link to the section "Stretch 'auto' Tracks" by reusing the markup from CSS Grid 1.
The issue is that Bikeshed doesn't seem to allow markup within section link shortcuts.
Sebastian
> [css-grid-2] Fixed link to "Stretch 'auto' Tracks" section

- css-backgrounds-4/Overview.bs
Added the `background-repeat-x`, `background-repeat-y`, `background-repeat-block` and `background-repeat-inline` longhand properties as [resolved in #116](https://github.com/w3c/csswg-drafts/issues/116#issuecomment-1854430181).
I didn't add the logical values to the shorthand for now, because @Loirooriol expressed some valid concerns regarding that. I _did_ add logical versions of the longhands as counterparts for the physical ones, though.
Sebastian
> [css-backgrounds-4] Added background-repeat-* longhands

- css-viewport-1/Overview.bs
This property exposes in JavaScript what is already exposed to CSS via env() variables.
TAG review w3ctag/design-reviews#689.
CSSWG Approval: [here](https://github.com/w3c/csswg-drafts/issues/9237#issuecomment-2160730855)
Fixes #9237.
> [css-viewport] Add the segments property (#9237).

- css-view-transitions-2/Overview.bs
> [css-view-transitions-2] CSSViewTransitionRule.navigation returns an empty string for invalid/missing descriptor

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
The WebIDL namespace is global, it's a bit better if we call this something a bit more view-transitions-specific so that other specs don't rely on it, since UpdateCallback is otherwise very generic.
I don't think this would be a normative change since the name of a callback isn't exposed anywhere author visible.
> [css-view-transitions] Rename UpdateCallback to something more specific.

- selectors-4/Overview.bs
- Add link-defaults for two definitions
- Fix numerous "Ambiguous for-less link" warnings
- Convert spaces to tabs on line 1980
- Tag var 'argument' with 'ignore' where it's used in a Note
> [selectors-4] Fix bikeshed warnings

- css-highlight-api-1/Overview.bs
The command:
```
bikeshed spec css-highlight-api-1\Overview.bs
```
Throws errors:
```
LINE 629:11: Character " (at 629:17) is invalid in unquoted attribute values.
LINE 629:11: Garbage after class=.
LINE 629:1: Garbage at 629:5 in <h3>.
LINE 644:11: Character " (at 644:17) is invalid in unquoted attribute values.
LINE 644:11: Garbage after class=.
LINE 644:1: Garbage at 644:5 in <h3>.
LINE 673:11: Character " (at 673:17) is invalid in unquoted attribute values.
LINE 673:11: Garbage after class=.
LINE 673:1: Garbage at 673:5 in <h3>.
```
> [css-highlight-api-1] Fix unquoted attribute values

- css-fonts-4/Overview.bs
According to the CSS Values and Units specification [as stated](https://drafts.csswg.org/css-values-4/#component-types):
> If the property’s value grammar is a comma-separated repetition, the corresponding type does not include the top-level comma-separated list multiplier. (E.g. if a property named `pairing` is defined as `[ <custom-ident> <integer>? ]#`, then `<'pairing'>` is equivalent to `[ <custom-ident> <integer>? ]`, not `[ <custom-ident> <integer>? ]#`.)
The definition of `<'font-family'>` is `[ <family-name> | <generic-family> ]#`. When used in the context of `<'font'>` without the #-multiplier, this implies that only a single `<family-name>` or `<generic-family>` can be used as the `<'font-family'>` value. However, the `<'font'>` property allows a comma-separated list of family …
> [css-font-4][editorial] Fix <'font'> syntax, simplify <font-variant-css2> and <font-width-css3> syntaxes

- css-conditional-5/Overview.bs
Per resolution in [1], add scroll-state() as a query function to query sticky, snap, and overflow scroll states with a new container-type for scroll-state queries.
[1] https://github.com/w3c/csswg-drafts/issues/6402#issuecomment-1812973013
> [css-conditional-5] Draft spec for scroll-state() #6402

- css-view-transitions-1/Overview.bs
This fixes an issue where skipping the transition from within thet update callback would call the update callback twice.
Closes #10822
> [css-view-transitions-1] Swap the order between setting the phase and calling the update callback

- css-view-transitions-2/Overview.bs
When hiding the document, and inbound cross-document view transition should be skipped.
This is a missing piece of #9822 that wasn't edited in.
Closes web-platform-tests/wpt#47828
> [css-view-transitions-2] When hiding the document, and inbound cross-document view transition should be skipped.

- css-text-4/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/3473#issuecomment-1646267487
> [css-text] Introduce a text-wrap-style value focused on orphans

- css-values-5/Overview.bs
`<progress>` currently requires a timing function and allow omitting the progress numeric value. I think this is a typo.
> [css-values-5] Define the appropriate components as optional

- css-backgrounds-4/Overview.bs
Enclosing `<>` needed to be doubled. Also added a wrapping `<dfn>` to make the term linkable.
> [css-backgrounds-4] Fix definition of `<position-three>`

- mediaqueries-5/Overview.bs
Per resolution at https://github.com/w3c/csswg-drafts/issues/6517#issuecomment-2220975121 this migrates the [Web Preferences API](https://wicg.github.io/web-preferences-api/) to the Media Queries Level 5 spec.
> [mediaqueries-5] Migrate Web Preferences API proposal

- css-pseudo-4/Overview.bs
This was discussed here: https://github.com/w3c/csswg-drafts/issues/10440
> [css-pseudo-4] Define ::picker()

- css-ui-4/Overview.bs
This was discussed here: https://github.com/w3c/csswg-drafts/issues/5998
> [css-ui-4] Define appearance:base

- css-conditional-5/Overview.bs
Unintentionally left out in the original scroll-state() PR.
> [css-conditional-5] Add 'none'-keywords to scroll-state() features

- css-view-transitions-2/Overview.bs
The previous wording of this was somewhat handwavy, made it more rigorous.
- The timeout starts when the transition is created (before pageswap)
- If the timeout expires before the transition is resolved (pagereveal), the inbound transition params are cleared and the behavior is similar to having the transition skipped at pageswap.
- If the timeout expires while the navigation is active, it is skipped with a `TimeoutError`.
Closes #10800
> [css-view-transition-2] Clarify timeout behavior for inbound view transition

- css-scoping-1/Overview.bs
In #6867 we [resolved](https://github.com/w3c/csswg-drafts/issues/6867#issuecomment-1332344714) to add `:has-slotted`. This PR is a first pass to add this.
The reference to `assignedNodes()` reference doesn’t work, not sure why. 🤷🏽‍♀️
There is [another open PR](https://github.com/w3c/csswg-drafts/pull/10586) by @keithamus but it adds `:has-slotted()` instead, which is both considerably harder to implement, and not what the resolution is about. I did however include a note that this will be included in a future version.
> [css-scoping] First pass at adding `:has-slotted`

- cssom-1/Overview.bs
With CSSOM, it's possible to reach into a CSSNestedDeclarations rule and remove its declarations, causing it to serialize as the empty string. Such rules add "whitespace junk" when serializing the outer rule, which looks unattractive.
Fixed by ignoring rules that serialize to the empty string.
> [cssom] Don't serialize empty rules

- css-view-transitions-2/Overview.bs
- view-transition-group maintains the tree-scoping relationship
- nearest/custom-ident act like `contain` for their descendants
Closes #10780
Closes #10633
See resolutions in the above issues.
> [css-view-transitions-2] Clarify a few nesting details

- css-conditional-5/Overview.bs
Edit to clarify the resolution[1] in #10784 that scroll-state(snapped) matches the snap target for scrollsnapchanging, not scrollsnapchanged. That is, the snapped query changes evaluation during a scroll operation.
[1] https://github.com/w3c/csswg-drafts/issues/10784#issuecomment-2379901508
> [css-conditional-5] snapped matches scrollsnapchanging #10784

- css-pseudo-4/Overview.bs
- css-shadow-parts-1/Overview.bs
Fixes #10083.
@fantasai, could you review? I'm not an editor on the Pseudo spec. ^_^
> [css-shadow-parts][css-pseudo] Move various ::part() details to 'part-like pseudo-element'.

- cssom-view-1/Overview.bs
Add "run snapshot post-layout state steps" as resolved in issue #10796. Let other specifications specify what they snapshot on a feature-by-feature basis.
Resolution: https://github.com/w3c/csswg-drafts/issues/10796#issuecomment-2379885032
> [cssom-view-1] Add: run snapshot post-layout state steps #10796

- css-color-4/Overview.bs
Unless explicitly specified, I would use [parse a CSS `<color>` value](https://drafts.csswg.org/css-color-4/#parse-a-css-color-value) to parse a `<color>` appearing in a stylesheet or a CSSOM input. But I should not, which I suggest to make explicit.
> [css-color-4] Clarify intended use of the parse a CSS <color> algorithm

- css-ui-4/Overview.bs
I was reading through the css-ui-4 spec and noticed that the outline-color property was specified as `auto | [ <<color>> | <<image-1D>> ]`. This confuses me because I don't understand why these needed to be disambiguated using the group notation. There doesn't seem to be any ambiguity, so I removed the group notation and changed it to `auto | <<color>> | <<image-1D>>`.
If this is _not correct_, I'm happy to close this PR, but for my own edification I'd love to know why the group notation is considered important here.
> [css-ui-4] Editorial improvement; removes redundant group notation from outline-color property

- css-view-transitions-1/Overview.bs
> [css-view-transitions-1] Remove redundant declaration.

- web-animations-1/Overview.bs
[web-animations-1] Add pseudoElement to getAnimations options #9908
> [web-animations-1] Add pseudoElement to getAnimations options

- css-view-transitions-1/Overview.bs
> [css-view-transitions] Clear captured flag on error.

- css-view-transitions-1/Overview.bs
> [css-view-transitions] Specify with kind of exception gets used when skipping on resize.

- css-ui-4/Overview.bs
[css-ui-4] The "see how it renders in your browser" example for caret-animation had `caret-animation: none` which is neither auto nor `manual` as the text would suggest. Fix it.
> Fix the caret-animation example

- css-view-transitions-1/Overview.bs
Fixes https://github.com/w3c/csswg-drafts/issues/11071.
> [css-view-transitions-1] Fix for fragmented boxes in new DOM.

- css-shapes-2/Overview.bs
Match the first moveTo of the `path()` with the "from" of the `shape()`
This is guaranteed to work since `path()` always starts with an M or m.
See resolution: https://github.com/w3c/csswg-drafts/issues/10740#issuecomment-2379740446
Closes #10740
> [css-shapes-2] Clarify shape/path interpolation

- css-view-transitions-2/Overview.bs
This restriction only makes sense for the initial navigation, not for traversal.
Closes #11063
> [css-view-transitions-2] Allow transitions when traversing into a document that was created using cross-origin redirects

- css-color-hdr/Overview.bs
Update the definition of dynamic-range-limit-mix to facilitate interpolations of interpolations. Add explicit algorithm for the computed value when the specified value is dynamic-range-limit-mix.
> [css-color-hdr] Update dynamic-range-limit-mix to reflect #10271.

- css-namespaces-3/Overview.bs
This reverts commit 184eea92ec36d909eb03f48f8491dc2b1b2eeac6, which prevents CSS-wide keywords and `default` from being valid namespace prefixes, because they are invalid `<custom-ident>`s. Apologize for forgetting that.
There is no tests on WPT, but there is no reason for CSS-wide keywords and `default` to be invalid namespace prefixes, and they are valid in current version of Chrome and FF (at least).
There is no production representing an arbitrary case-sensitive identifier (which might help clarify how identifiers should be interpreted and serialized), so this PR simply revert this change.
> Revert "[css-namespaces-3] Define <namespace-prefix> with case-sensitive <custom-ident>"

- css-ui-4/Overview.bs
Similar to https://github.com/w3c/csswg-drafts/pull/11053, the css-ui-4 has a redundant group around the `outline` property value. It is currently specified as `[ <'outline-width'> || <'outline-style'> || <'outline-color'> ]`, but I think it could be better expressed without the `[]`, as `<'outline-width'> || <'outline-style'> || <'outline-color'>` instead. 
I'd like to point out that `caret` has similar shape, and is expressed as `<'caret-color'> || <'caret-animation'> || <'caret-shape'>`. So I think both should be have a consistent syntax.
> [css-ui-4] Editorial improvement; removes redundant group notation from outline property

- css-conditional-5/Overview.bs
- cssom-view-1/Overview.bs
scroll-state() snapshotting should happen as part of "run snapshot post- layout state steps".
Resolution: https://github.com/w3c/csswg-drafts/issues/10796#issuecomment-2379885032
> [css-conditional-5] Link scroll-state snapshotting to cssom-view #10796

- css-text-4/Overview.bs
The `whitespace` property includes `Inherited: individual properties`, but it seems to be the only instance of this value in all of the specs. Lots of other property uses `Inherited: see individual properties`. I presume `whitespace` should use this as well, so I've made this small editorial PR to correct this.
> [css-text-4] use "see individual properties" terminology for whitespace property

- css-color-hdr-1/Overview.bs
In the value definition (syntax) of [`dynamic-range-limit`](https://drafts.csswg.org/css-color-hdr-1/#propdef-dynamic-range-limit), `dynamic-range-limit-mix()` represents a [literal function](https://drafts.csswg.org/css-values-4/#component-types) taking no argument:
> Functional notations and their arguments. These may be written literally as defined in 2.6 Functional Notation Definitions, or referenced by a non-terminal using the function’s name, followed by an empty parentheses pair, between `<` and `>`, e.g. `<calc()>`, and references the correspondingly-named functional notation.
The Bikeshed linking mechanism is a bit wobbly, if I may say so (speced/bikeshed#2906), so this PR only changes references used in other syntaxes (there is only `dymaic-range-limit`).
> [css-color-hdr-1] Accept `dynamic-range-limit-mix()` as a type instead of a literal function

- css-overflow-4/Overview.bs
- css-page-floats-3/Overview.bs
Replaces the two remaining `<type> | <percentage>` with `<type-percentage>`.
> [css-overflow-4][css-page-floats-3][editorial] Syntax simplification

- css-view-transitions-2/Overview.bs
Describe how layered capture works, which CSS properties it targets and how it affects rendering. Based on [this resolution](https://github.com/w3c/csswg-drafts/issues/10585#issuecomment-2302433008).
This is a first pass, and still has open issues (will open separately):
1. Should there be a CSS property to decide on this? What should be the default?
2. How do we capture overflow/box-sizing?
3. (More capture questions if they come up)
Closes #10585
> [css-view-transitions-2] First pass at layered capture

- css-nesting-1/Overview.bs
> [css-nesting-1] Specificity of '&' is zero without a parent rule

- css-anchor-position-1/Overview.bs
- css-fonts-4/Overview.bs
- css-position-4/Overview.bs
Looking through all the `Animation type:` properties, there are three locations which say `(see prose)` and 1 location ([the `border-*-color` properties](https://github.com/w3c/csswg-drafts/blob/main/css-borders-4/Overview.bs#L57)) that use `see prose` (no parens). This PR makes them consistent, choosing to drop the parens from the three locations that have `(see prose)`, which although the more popular choice for `Animation type:` is overall a far less common stylistic choice.
This makes it more consistent with the other properties, such as `Percentages: see prose` (found in [css-box-3, height](https://github.com/w3c/csswg-drafts/blob/main/css-box-3/block-layout.bs#L1362) and [css-page-floats-3, float-offset](https://github.com/w3c/csswg-drafts/blob/main/css-page-floats-3/Overview.bs#L813 …
> [css-anchor-position-1]/[css-fonts-4]/[css-position-4] (editorial) make "see prose" value consistent (drop parens from outliers)

- css-cascade-6/Overview.bs
> [@scope] Allow declarations directly within @scope

- css-conditional-5/Overview.bs
Resolution:
https://github.com/w3c/csswg-drafts/issues/9192#issuecomment-1789850349
> [css-conditional-5] Make <container-query> optional #9192

- css-values-5/Overview.bs
The current wording is a tiny bit ambiguous; it could also be interpreted to mean that `interpolate-size: allow-keywords` only lets you interpolate between an intrinsic size and a length percentage, but not two length percentages.
I do realize how unlikely this interpretation is, but I had to do a double-take while reading so I thought I'd PR it.
> [css-values-5] Make it clear that `allow-keywords` can't just interpolate with intrinsic sizes.

- css-rhythm-1/Overview.bs
The `line-height-step` property in css-rythm-1 defines its initial value as `0px`. AIUI - it being a zero value means the `px` is redundant.
It seems to be more common to use `0` rather than `0px`. In fact here are all the places that have an initial of `0`:
- css-box (`margin*`, `padding*`)
- css-scroll-snap (`scroll-margin*`)
- css-inline (`baseline-shift`)
- css-shapes (`shape-margin`, `shape-padding`)
- css-text (`text-indent`, `line-padding`, `hyphenate-limit-zone`)
- css-text-decor (`text-decoration-trim`)
- css-ui (`outline-offset`)
- css-borders (`border-*-radius` & `border-radius`)
- css-logical (okay maybe an unfair comparison as it's mostly logical equivalents of box/borders)
And here are the places that have an initial of `0px`:
- css-rythm (`line-height-step` - that's this …
> [css-rythm-1] [editorial] remove redundant `px` dimension from `line-height-step` initial value

- css-view-transitions-2/Overview.bs
- Remove `type` from dfn
- Remove typo fixes from changelog
> [css-view-transitions-2] Editorial: fix a few nits for WD publishing

- css-multicol-2/Overview.bs
@frivoal @rachelandrew Hi y'all, just drafting the ::column pseudo per #10715. Feel free to review/merge. I can also move the new section elsewhere if desired (or, potentially, to the Pseudo spec instead, but I feel like this is the better spot for it).
> [css-multicol-2] Add ::column pseudo, per WG resolution. #10715

- css-view-transitions-2/Overview.bs
For now, not pursuing layered capture. The details are still in the [explainer](https://github.com/WICG/view-transitions/blob/main/nested-explainer.md#layered-capture), however the open issues make it so that there's currently no obvious way forward.
This reverts commit 02eb632efd9f2dfb361806b213c7650b01fc5995.
> [css-view-transitions-2] Revert "First pass at layered capture (#11045)"

- web-animations-2/Overview.bs
In line with the CSS working group's resolution[1] to change Animation.progress to Animation.overallProgress, this patch updates the relevant portions of the web-animations-2 spec.
[1] https://github.com/w3c/csswg-drafts/issues/8799#issuecomment-2461097047
> [web-animations-2] Change progress to overallProgress

- css-values-5/Overview.bs
This may have been the intended meaning of the spec text already, but I think we should clearly state the outcome of #5092: partial tainting of custom properties was proposed in that issue, discussed, objected to, and therefore *not* accepted.
This PR hopefully makes it clear that attr()-tainting applies to whole substitution values, for now.
> [css-values] Total attr()-tainting for substitution values

- css-overflow-5/Overview.bs
As resolved in #10917:
- removes the normative algorithm for determining the active marker and leaves it up to the UA,
- additionally defines an example algorithm that takes into account improvements mentioned in the issue for selecting the next marker when it is nearer to being in view.
The example algorithm also
- includes recursive marker selection within nested scroll containers as proposed in #11098, and
- uses the writing mode as the primary axis following the proposed primary axis algorithm in #11198.
> [css-overflow-5] Remove normative active marker algorithm.

- css-multicol-1/Overview.bs
Make the prose for `column-rule-style` consistent with the computed value definition for `column-rule-width` with regards to the effects of `none` and `hidden` values.
> [css-multicol-1] Clarify effect of `hidden` on `column-rule-width`. #11090

- css-conditional-5/Overview.bs
Just a typo, that's all.
( = I believe this to be non-substantive so probably won't need to make a W3C account)
> [css-conditional] Fix link to CSS-CONTAIN-3

- css-color-adjust-1/Overview.bs
The resolution was to close no change, but it was suggested to add an example illustrating the behavior.
> [css-color-adjust-1] Add example for `color-mix()` in Forced Colors Mode. #11097

- selectors-4/Overview.bs
This was resolved here: https://github.com/w3c/csswg-drafts/issues/11039#issuecomment-2491673891
> [selectors] Remove the :closed pseudo-class

- css-overflow-5/Overview.bs
Adds to the non-normative suggested compromise for selecting the active scroll marker the proposed compromise resolved on in  #11165 to ensure that scrolling from start to end scrolls through all of the markers in that scroller.
> [css-overflow-5] Allow scroll to target unreachable scroll marker targets

- css-shapes-2/Overview.bs
grammar changes:
- `<<position>>` can be used instead of an absolute point
- The relevant `<<position>>`'s dimension can be used for `hline`/`vline`
- Since keywords define the different components, order of components is flexible
- `with` is used for curve control points
- Two curve control points are separated by /
- Relative control points can be relative to segment-start/segment-end/reference-box, defaulting to segment start.
Resolution: https://github.com/w3c/csswg-drafts/issues/10649#issuecomment-2474354244
Closes #10649
Closes #10666
Copy the above line into the Title and replace with the relevant details. Fill in any additional details here. See …
> [css-shapes-2] Specify the grammar for `shape()`

- css-color-hdr-1/Overview.bs
Based on the parsing tests in WPT (https://github.com/web-platform-tests/wpt/blob/master/css/css-color-hdr/parsing.html) it seems as though commas are _required_ for each set of ident && <lengthpercentage> groups here, however the spec is using the `+` sigil which allows for "one or more" but doesn't specify commas. I think what might be desired here is to use `#` which is "one or more comma separated". This would satisfy the requirement for commas.
I think, in addition, we might want to specify something like `#{2,}` - considering all examples in the parse tests expect two or more values, and the spec talks about summing all values, I am unsure if it is redundant or not to specify just one value (e.g. `dynamic-range-limit-mix(high 10%)`).
This doesn't resolve the recursive affordances …
> [css-color-hdr-1] use one-or-more for `dynamic-range-limit-mix` grammar production

- css-backgrounds-3/Overview.bs
- css-box-3/block-layout.bs
- css-speech-1/Overview.bs
In css-backgrounds-3/css-box-3 the `Initial:` and `Computed value:` properties use `(see individual properties)` (note the parens). In css-speech-1 it uses `N/A (see individual properties)`. Both of these seem inconsistent with the overwhelming style of `see computed properties` (no `N/A`, no parens). This PR drops the parens around the term to make it more consistent. The `N/A` seems redundant in css-speech-1 as it's not "not applicable", it is applicable, the application being that the individual properties should be consulted. Of course I am happy to take guidance here if we feel as if `N/A (see individual properties)` should be kept, but it seems to be the only instance across all the specs is within css-speech-1.
> [css-backgrounds-3]/[css-box-3]/[css-speech-1] drop parens around "see individual properties"

- web-animations-2/Overview.bs
Due to faulty indentation, "Let effective start time be the animation’s start time if resolved, or zero otherwise." is step 1 and all other steps are sub steps.
> [web-animations-2] Fix numbering of steps for the computation of "at progress timeline boundary"

- css-values-5/Overview.bs
Otherwise we're making a non-backwards-compatible change against content:attr() from css-content-3 [1].
[1] https://drafts.csswg.org/css-content-3/#strings
> [css-values-5] Allow explicit null-namespace in attr-name

- scroll-animations-1/Overview.bs
It should be possible to explicitly set a `null` source when constructing a `ScrollTimeline`. This addresses https://github.com/w3c/csswg-drafts/issues/11340.
> [scroll-animations-1] allow explicitly setting `null` as a source when constructing a `ScrollTimeline`

- css-shapes-2/Overview.bs
The changed line says `<position>`  can be used with `by` but in the production list and a few lines below, the spec says `<position>` can only be used with `to`.
> [css-shapes-2][editorial] Fix minor syntax issue

- css-scroll-snap-2/Overview.bs
In line the CSS working group's resolution[1], this renames the "scroll-start-target" property to "scroll-initial-target" and replaces its keyword "auto" with "nearest."
[1] https://github.com/w3c/csswg-drafts/issues/11173#issuecomment-2536659205
> [css-scroll-snap-2] Rename scroll-start-target to scroll-initial-target

- css-2024/Overview.bs
This was resolved in https://github.com/w3c/csswg-drafts/issues/9793#issuecomment-2518138682.
Sebastian
> [css-2024] Added CSS Scroll Anchoring 1, CSSOM 1, CSS Color 5, and Selectors 4 to Rough Interoperability

- css-values-5/Overview.bs
This makes it match the prose that follows it.
> [css-values-5] Fix <progress> definition to use <percentage-token>

- css-align-3/Overview.bs
- css-overflow-3/Overview.bs
`scroll-start-target` was [renamed](https://github.com/w3c/csswg-drafts/commit/40b30fe918e1262c71386cd123e66a48ffaa65f5) `scroll-initial-target` in the scroll-snap-2 spec, resulting in some links in other specs breaking. This updates other specs that made mention of `scroll-start-target`.
> [css-scroll-snap-2] scroll-{start=>initial}-target rename cleanup

- selectors-4/Overview.bs
Also included a space here, since there's no example of the combination of whitespace and comment.
> [selectors-4] Fix unrendered comment in `:empty` example

- web-animations-1/Overview.bs
Fixes the numbering of the list items in this procedure: https://drafts.csswg.org/web-animations-1/#animation-silently-set-the-current-time
> [web-animations-1] Fix markup

- css-shapes-2/Overview.bs
This applies to arc/curve/smooth.
Also fixes a bug where the arc target point was using only coordinate-pair.
Resolution: https://github.com/w3c/csswg-drafts/issues/10666#issuecomment-2578298392
Closes #10666
> [css-shapes-2] by/to should always come before rest of parameters.

- css-shapes-2/Overview.bs
> [css-shapes-2] Match `shape()` main syntax with command-specific syntax

- css-grid-2/Overview.bs
This hyperlinks the terms "in-flow" & "out-of-flow" to their formal definitions for clarity.
Currently Bikeshed links it to https://drafts.csswg.org/css-display-4/#in-flow etc. If the CSS2 definition is preferred instead, just let me know.
----
Note to self:
```
To auto-select one of the following refs, insert one of these lines into a <pre class=link-defaults> block:
spec:css-display-4; type:dfn; text:in-flow
spec:css21; type:dfn; text:in-flow
```
> [css-grid-2] Gloss in-flow/out-of-flow jargon

- css-mixins-1/Overview.bs
This also makes the parameter list required.
A discussion could be had about 'using' as well, but since it looks like we're going to remove it, that problem will probably disappear on its own.
> [css-mixins-1] Do not allow whitespace before parameter list

- css-mixins-1/Overview.bs
The CSSNestedDeclarations rule does not quite work, since its style attribute returns a CSSStyleProperties object.
> [css-mixins-1] CSSFunctionDeclarations, not CSSNestedDeclarations

- css-mixins-1/Overview.bs
The previous attempt at defining this ("do var()/etc first") is pretty clumsy, and doesn't really work when there's another dashed-function in the argument list.
Also handle all arbitrary function substitution in "resolved local value", not just env() and attr().
> [css-mixins-1] Do arbitrary function substitution before evaluation

- selectors-4/Overview.bs
Since the list of elements almost includes all of the elements which :open is going to apply to, I figure that adding `<input>` to make it complete will reduce any potential confusion.
> [css-selectors-4] Add <input> to list of :open elements

- css-values-5/Overview.bs
This is not allowed in `<wq-name>`, and shouldn't be allowed in `<attr-name>` either.
> [css-values-5] Disallow whitespace in `<attr-name>`

- css-box-4/Overview.bs
This hyperlinks the term "in-flow" for clarity. No unlinked instances of "out-of-flow" were found in this spec.
> [css-box-4] Gloss in-flow jargon

- css-text-decor-4/Overview.bs
This hyperlinks the term "out-of-flow" for clarity. No unlinked instances of "in-flow" were found in this spec.
Didn't add a link on line 152 since it's only an example and currently contains zero links.
> [css-text-decor-4] Gloss out-of-flow jargon

- css-contain-2/Overview.bs
It is "then not ...", not "not then ...", and especially not "not them ...".
> [css-contain-2] Grammar improvements

- css-shapes-2/Overview.bs
- css-shapes-2/images/bubble-50.svg
- css-shapes-2/images/bubble.svg
This shows how to use `shape()` to build a responsive speech bubble `clip-path`, replacing SVG pixel values with percentage/pixel/calc/CSS variables.
> [css-shapes-2] Add a detailed example for `shape()`

- css-mixins-1/Overview.bs
This section was originally copied from css-nesting-1, and I must have forgotten to adjust this.
> [css-mixins-1] Fix anchor for CSSFunctionDeclarations

- css-scroll-snap-1/Overview.bs
As per #10914 when selecting a snap point as a result of a scroll by page operation we should always select a snap position that is less than a page away as long it still makes progress in the requested direction if one exists.
> [css-scroll-snap-1] Scroll by page should not skip over content.

- css-scoping-1/Overview.bs
This updates the `:has-slotted` specification to use the "flattened slottables" concept, per the resolution in https://github.com/w3c/csswg-drafts/issues/6867#issuecomment-2593536333.
> [css-scoping-1] update has-slotted to match flattened slottables

- css-shapes-2/Overview.bs
The example had an incorrect comment about limitations of `polygon()`, reworded.
> [css-shapes-2] Editorial: Reword example about polygon

- css-contain-2/Overview.bs
This just fixes a broken link, no actual behavior changes.
> [css-contain-2] Fix broken link to css-backgrounds-3 corner clipping

- css-highlight-api-1/Overview.bs
Add highlightsFromPoint() to CSS.highlights as discussed in #7513.
> [css-highlight-api-1] Add highlightsFromPoint() to CSS.highlights #7513

- css-shapes-2/Overview.bs
A "shape" is a set of commands to generate a path dynamically, rather than them being synonomous terms.
> [css-shapes-2] Refine use of the word "path" in the intro

- css-overflow-5/Overview.bs
This defines the focus related properties and pseudo-class matching as resolved in #11361.
> [css-overflow-5] Define activeElement and matching focus-related pseudo-classes for focused navigation pseudos.

- css-overflow-5/Overview.bs
In #10912 we resolved on the block directions wrapping the inline direction.
> [css-overflow-5] Editorial fix of button order.

- css-fonts-4/Overview.bs
https://drafts.csswg.org/css-fonts-4/#font-feature-variation-resolution looks strange currently, rendering as "either via the use of ‘font-variant’, ‘font-feature-settings’, ‘font’‘font-variation-settings’ in a style rule or within an @font-face rule".
I'm not totally sure of the intention, but I've made the most plausible fix to me.
> [css-fonts-4] Fix seeming typo in Font Feature and Variation Resolution

- css-borders-4/Overview.bs
This specifies the `corner-shape` group, including:
- general description and interaction with border-radius
- all the individual corners, side shorthands, and overall shorthand
- multiple keywords, and how they translate to a `superellipse()`
- The superellipse formula, and how it is rendered
- How the exponent of the superellipse interpolates
Open issues (will open separately):
- Add a few examples
- Resolve on "straight" vs "none" for the convex angle.
- Resolve on the exact interpolation formula
- Define restrictions for border rendering
This overwrites the existing `corner-shape` definition.
Closes #10993
Based on resolution https://github.com/w3c/csswg-drafts/issues/10993#issuecomment-2622578937
> [css-borders-4] Specify `corner-shape` based on superellipse

- css-highlight-api-1/Overview.bs
A recent update added a method to the `HighlightRegistry` interface through a `partial interface` definition. That's totally fine. However, the initial `interface` definition was also turned into a `partial interface` definition. That is incorrect, a `partial interface` definition always extends an interface that must be defined (without `partial`) somewhere.
This update drops `partial` from the core interface definition accordingly.
> [css-custom-highlight-1] Fix IDL definition of `HighlightRegistry`

- css-2020/Overview.bs
- css-2021/Overview.bs
- css-2022/Overview.bs
- css-2023/Overview.bs
- css-2024/Overview.bs
CSS Text Module Level 3 extends and supersedes everything in chapter 16 of CSS2, except text-decoration. text-decoration is defined in CSS2 section 16.3, not 16.2.
> [css-2024] Fix section number for text-decoration (#11598)

- css-color-4/Overview.bs
- css-color-5/Overview.bs
- css-easing-2/Overview.bs
- css-fonts-4/Overview.bs
- css-shapes-1/Overview.bs
`<pre>''keyword''</pre>` no longer links to `keyword` definition, which means `''keyword''` now generates `'keyword'`, which is inappropriate.
Related: https://github.com/speced/bikeshed/issues/3011
> [*][editorial] Drop autolinks to value in `<pre>`

- web-animations-1/Overview.bs
- **[web-animations-1] Fix markup errors**
- **[web-animations-1] Fix mistake in active time calculation**
- **[web-animations-1] Fix linking to end time term**
- **[web-animations-1] Fix link defaults**
- **[web-animations-1] Sort link defaults**
- **[web-animations-1] Drop unnecessary CompositeOperation dfn**
> Fix fill mode regression

- css-overflow-5/Overview.bs
Single quotes signal an autolink to a property or descriptor. Here, the single quotes are meant to appear literally, because `*` would be interpreted as a quantifier otherwise.
Update also fixes a markup error.
> [css-overflow-5] Escape single quote for '*'

- css-borders-4/Overview.bs
This is already specified in prose but missing in the production rule.
> The `superellipse( <number> | infinity )` function describes [...]
> `<corner-shape-value> = ... | superellipse(<number [0,∞]>)`
https://drafts.csswg.org/css-borders-4/#typedef-corner-shape-value
> [css-borders-4] Accept infinity keyword in superellipse()

- css-borders-4/Overview.bs
The grammar of [`corner-shape`](https://drafts.csswg.org/css-borders-4/#propdef-corner-shape) currently allows a trailing slash:
> `<corner-shape-value>{1,2} / [ <corner-shape-value>{1,2} ]?`
> [css-borders-4] Do not allow a trailing slash in `corner-shape`

- css-gaps-1/Overview.bs
There is a typo in the initial value of `column-rule-color`/`row-rule-color`.
> [css-gaps-1] Fix typo

- css-borders-4/Overview.bs
- css-color-4/Overview.bs
- css-color-5/Overview.bs
- css-easing-2/Overview.bs
- css-fonts-4/Overview.bs
- css-shapes-1/Overview.bs
Revert #11579 and replaces `''keyword''` with `<l>''keyword''</l>` in `<pre>`.
> [*][editorial] Fix autolinks to value in `<pre>`

- css-color-5/Overview.bs
At the f2f we agreed to drop the `max` argument and just always resolve to white/black for now, with the intention of resolving on additional functionality in the near future. (We just ran out of timebox for the topic.)
> [css-color-5] Simplify contrast-color(), per WG resolution. #11534

- css-borders-4/Overview.bs
`corner-shape` has only one value, there is no point in providing two values for each side, it was a copy-paste mistake from `border-radius`.
Closes #11650
> [css-borders-4] Remove the second value from the corner-*-shape variant

- css-borders-4/Overview.bs
Closes #6997
This defines the 'border-shape' property with a narrow set of details that we've resolved on, leaving room for discussing some details as we go along.
Specifically, this adds the two variants of 'border-shape' (single/double <basic-shape>).
Issues to be opened separately:
* interaction with border-{width|color|style}
* Clipping replaced elements
* Lots of examples
> [css-borders-4] Initial (somewhat scaffoldy) spec for 'border-shape'

- web-animations-2/Overview.bs
The values for "animation trigger state" and "animation trigger type" were defined with a `value` definition type. That type is reserved for CSS values: https://speced.github.io/bikeshed/#dfn-types
This makes tools that crawl specs to extract machine-readable information wrongly assume that the spec introduces new CSS values.
There is no specific definition type available for generic values. This update uses a regular `dfn` and updates references to these values accordingly.
> [web-animations-2] Use `dfn` type for animation trigger values

- css-overflow-5/Overview.bs
When activating a marker, as resolved in #11138 scrolling should be limited to the scrolling containers associated with the marker targets. This builds on the addition of container to the scroll into view algorithm in #11673.
> [css-overflow-5] Limit scrolling when activating a marker

- cssom-view-1/Overview.bs
Adds the container option to ScrollIntoViewOptions allowing scrolling only the nearest containing scrolling box as resolved in #9452. This also sets us the algorithm to scroll an element into view for scroll markers #11138.
> [cssom-view-1] Add container option to scrollIntoView options.

- css-grid-3/Overview.bs
Just  flipped all the related values in the text for `column`.
> Fix typo in description for column in item-track-direction

- css-mixins-1/Overview.bs
Replaces/removes links to `<function-name>` and `<function-parameter-list>`, which are no longer defined.
> [css-mixins-1] Fix markup

- css-2025/Overview.bs
This is meant to be the initial version of the CSS 2025 Group Note.
It's based on the latest version of the CSS 2024 Group Note (pending any possible last changes from #11696).
I kept everything as is including the authors and only updated the year.
@svgeesus As you helped a lot with the 2024 snapshot, I thought you're the right person to add as reviewer.
Sebastian
> [css-2025] Initial version based on last version of CSS 2024

- css-shapes-2/Overview.bs
> [css-shapes-2] Use <<position>> for `shape()` staring point

- css-color-hdr-1/Overview.bs
Fixes the grammar to match examples and text.
> [css-color-hdr] Clarification on the grammar / spec text for dynamic-range-limit-mix() #11672

- css-view-transitions-1/Overview.bs
> [css-view-transitions-1] Call pending update callbacks for skipped transitions before capturing the old state.

- css-values-5/Overview.bs
This change replaces a leftover of the old syntax for `attr()` in an example by the new one.
Sebastian
> [css-values-5] Tweaked attr() syntax, per WG resolution. #11034 #11035

- css-view-transitions-1/Overview.bs
- css-view-transitions-2/Overview.bs
`match-element` works the same as `auto`, except doesn't try to use the ID as the name.
It is excluded as a custom-ident in css-view-transitions-1.
Resolution: https://github.com/w3c/csswg-drafts/issues/10995#issuecomment-2551949161
> [css-view-transitions-1][css-view-transitions-2] Add view-transition-name: match-element     

- css-grid-3/Overview.bs
Fixes a typo in provided HTML example
This is non-substantial.
> [css-grid-3] Fix typo in html example

- cssom-view-1/Overview.bs
When determining the scroll into view position of an element, the UA should account for defined scroll snap positions. These are applied when scrolling due to https://www.w3.org/TR/css-scroll-snap-1/#choosing added in https://github.com/w3c/csswg-drafts/commit/8401d613596842b7ab337e1a3190a771601240aa however applying them here ensures that specs using the scroll into view position are snapping aware.
> [cssom-view-1] Apply scroll snap to scroll-into-view-position

- css-values-4/Overview.bs
Hopefully these are self-explanatory. I think they all count as editorial.
The numbering change is because it felt awkward to have non-numbered sequential steps in between an outer numbered list and an inner numbered list for Sum and Product nodes. But while I was at it, it made sense to also do that for Negate and Invert. Steps 2 and 3 feel simple enough that it's not necessary.
Closes #11781.
> [css-values-4] A small fix and some tweaks to calc serialization

- css-backgrounds-4/Overview.bs
Follow-up on https://github.com/w3c/csswg-drafts/issues/116#issuecomment-2295641610.
For example, flow-relative and physical `background-position-*` need to be in the same logical property group in order to maintain the appropriate order of declarations within a CSS declaration block, eg. with `style.cssText = 'background-repeat: repeat; background-repeat-block: no-repeat; background-repeat-y: repeat'`.
Cf. [serialize a CSS declaration block](https://drafts.csswg.org/cssom-1/#serialize-a-css-declaration-block)  and [set a CSS declaration](https://drafts.csswg.org/cssom-1/#set-a-css-declaration).
> [css-backgrounds-4] Define background-repeat|position longhands with a logical property group

- css-values-5/Overview.bs
As per #10489, the progress notation functions don't use `from` and `to` anymore and go with commas instead, but this progress-function() definition hasn't been changed in 5666cec, hence the fix.
> [css-values-5] Fix progress-function() definition to use commas #10489

- css-values-5/Overview.bs
Previous update introduced a definition of the `ident()` function in the prose. The definition in the production block needs to be dropped not to duplicate it.
> [css-values-5] Drop duplicate definition of ident()

- css-2025/Overview.bs
In sections 2.1 and 2.4 the names of several included recommendations do not match the names that appear in the recommendations. Now they are the same.
> [css-2025] sections 2.1 and 2.4: matching CSS recommendation names to real names

- css-pseudo-4/Overview.bs
Issue #11011 was resolved to take forced-colors and color-scheme from the originating element. Remove the note for the issue.
> [CSS Pseudo 4] Remove the comment for resolved Issue #11011 

- css-animations-2/Overview.bs
While most `animation-*` CSS properties should _not_ have an effect once a `CSSAnimation` object has had its `effect` property set via the bindings, the `animation-timeline` property, like the `animation-play-state` and `animation-name` properties, should not follow that pattern since it is relevant to the _animation_ and not the animation _effect_.
The relevant WPT test is updated in https://github.com/web-platform-tests/wpt/pull/51057.
> [css-animations-2] setting `effect` should not prevent the timeline to set set via `animation-timeline`

- css-highlight-api-1/Overview.bs
Add some clarifications to the algorithm for highlightsFromPoint so it includes StaticRanges too.
See issue https://github.com/w3c/csswg-drafts/issues/11745
> [css-highlight-api] highlightsFromPoint: add support for StaticRanges for #11745

- css-2024/Overview.bs
In sections 2.1 and 2.4 the names of several included recommendations do not match the names that appear in the recommendations. Now they are the same.
> [css-2024] Matching CSS recommendation names to real names

- css-view-transitions-1/Overview.bs
Fixes a formatting typo.
This is non-substantial.
> [css-view-transitions-1] Fix typo

- css-page-3/Overview.bs
- css-values-3/Overview.bs
- css-values-4/Overview.bs
- selectors-4/Overview.bs
This PR removes the quotes around `:` `/` `)` in value definitions.
Since eab6ac4, the related text of [CSS V&U](https://drafts.csswg.org/css-values-4/#component-types) is:
> 6. Delimiters, which represent their corresponding tokens. Slashes (`/`), commas (`,`), colons (`:`), semicolons (`;`), parentheses (`(` and `)`), and braces (`{` and `}`) are written literally. Other delimiters must be written enclosed in single quotes (such as `'+'`).
In this paragraph, whether they *can* be or they *must* be written literally is ambiguous.
None are tokenized as `<delim-token>` but as their own token, except `/`. They *are* delimiters, I think, and I guess these tokens only exist for convenience. But a "dumb" CSS value definition parser may interpret `')'` as a `<delim-token>` whose value is `)`, …
> [*][editorial] Unquote delimiters in value definitions

- css-mixins-1/Overview.bs
The default return type of [`@function`](https://drafts.csswg.org/css-mixins-1/#at-ruledef-function) is `*` but is not allowed by the grammar ([`<css-type>`](https://drafts.csswg.org/css-mixins-1/#typedef-css-type)).
This PR adds it as an alternative of `<css-type>`.
> [css-mixins-1] Typo: default return type is `type(*)`

- css-values-5/Overview.bs
There is no `<syntax>` argument to attr() anymore; refer to `<attr-type>` instead.
> [css-values-5] Refer to attr-type argument, not syntax

- css-mixins-1/Overview.bs
7efac5a8ab7204b6b34d1b1d41b9ecf56623e408 accidentally made local variables "inherit" any type specified by a shadowed parameter. This simply restores the old behavior of locals being untyped.
> [css-mixins-1] Make locals untyped again

- css-backgrounds-4/Overview.bs
The `background-position` longhands were already defined with `background-position` as a logical property group. #11139 duplicated the "Logical property group" line in the property definition table, leading to `background-position background-position` as logical property group in the rendered spec.
> [css-backgrounds-4] Drop duplicate `background-position` logical property group

- css-forms-1/Overview.bs
Previously `::file-selector-button` would be missing many of the styles associated with button-like UI.
> [css-forms-1] Add `::file-selector-button` to selectors for buttons

- css-forms-1/Overview.bs
This is implemented by Chromium for base appearance select, and by Firefox for auto appearance selects and other button-like elements.
> [css-forms-1] Add user-select: none to button-like stylesheet

- css-forms-1/Overview.bs
Fix ::checkmark styles to apply when input is checked
Also apply a border-radius to radio inputs.
With this you now end up with the below rendering:
> [css-forms-1] Fix ::checkmark styles to apply when input is checked

- css-forms-1/Overview.bs
This PR wraps [`<form-control-identifier>` ](https://drafts.csswg.org/css-forms-1/#selectordef-picker)in `<dfn>`.
https://github.com/w3c/webref/blob/main/ed/css/css-forms.json#L187-L191
> [css-forms-1] Fix markup

- css-forms-1/Overview.bs
Base select is always sized based on its content size rather than using the legacy fixed styling, so we set field-sizing to content !important.
See https://github.com/w3c/csswg-drafts/issues/11838#issuecomment-2708823023
> [css-forms-1] Add field-sizing to base select styles

- css-counter-styles-3/Overview.bs
Fixes #8185.
This PR allows all counter style names to be grouped under the same namespace in CSS tools like `w3c/webref`.
[`japanese-*`](https://drafts.csswg.org/css-counter-styles-3/#limited-japanese) are defined`for="<counter-style>"` whereas other predefined counter style names are defined `for="<counter-style-name>"`. [`<counter-style>`](https://drafts.csswg.org/css-counter-styles-3/#typedef-counter-style) produces `<counter-style-name>` and `<symbols()>`.
> [css-counter-styles-3] Fix markup

- css-counter-styles-3/Overview.bs
Fixes #9258. This PR removes this emphasized part:
> If a `@counter-style` uses the extends `system`, it must not contain a `symbols` or `additive-symbols` descriptor, **or else the `@counter-style` rule is invalid**.
It was reported in #5717 and should have been fixed in ba2a8cb.
They all follow the resolution in #1682.
---
ba2a8cb and this PR leave multiple requirements (*"must [not] contain"*) without explicitly saying what should happen when they are not met. In my opinion, *"otherwise, the `@counter-style` does not define a counter style (but is still a valid at-rule)"* should be added.
> [css-counter-styles-3] Extended @counter-style containing *-symbols are valid

- css-align-3/Overview.bs
- css-overflow-3/Overview.bs
See #4957.
Review questions:
* Should we collapse the concepts of "scroll origin position" and "initial scroll position" now that they coincide even in the presence of alignment? If so, which word should we use?
* I think we can close the two issues marked in https://drafts.csswg.org/css-overflow-3/#scrolling ?
* Having the[ "The scrollable overflow area is the union of:" list](https://drafts.csswg.org/css-overflow-3/#scrollable) before the [definition of key terms like “scroll position”](https://drafts.csswg.org/css-overflow-3/#scrolling) seems wrong. Should I pull it out into its own subsection? Where?
> [css-align-3][css-overflow-3] Content alignment on scroll containers extends scrollable area #4957

- css-values-5/Overview.bs
Per resolution in #9573, element-backed pseudo elements that refer to an element in an inner scope should not expose their tree order to tree counting functions. Spec text now says they instead resolve to 0, loosely based on the minutes[1].
Additionally, re-word the text for how tree counting functions resolve against pseudo elements. This is not backed by a resolution, but backed by the discussions in the meeting minutes[1].
[1] https://github.com/w3c/csswg-drafts/issues/9573#issuecomment-2622696411
> [css-values-5] Pseudo element and tree-scope for sibling functions #9573

- css-mixins-1/Overview.bs
CSSFunctionRule has so far ignored the existence of a prelude in the `@function` rule. This adds CSSOM support for the function name, return type, and parameters.
> [css-mixins-1] Flesh out CSSFunctionRule

- css-round-display-1/Overview.bs
The `@viewport` rule was removed[1] in favor of using viewport meta properties. This updates viewport-fit to follow this change.
[1] https://www.w3.org/TR/css-viewport-1/#since-the-29-march-2016-working-draft
> [css-round-display-1] Update viewport-fit to property of viewport meta element

- css-images-3/Overview.bs
- css-images-4/Overview.bs
Fixes #8346.
It explicitly allows declaring a conic/linear gradient rotation with `<zero>` in the grammar, which is already defined in prose.
It allows declaring an angular color stop/hint with `<zero>`, which matches the output in Chrome and Firefox but is currently undefined, so this change is substantive.
As noted in the issue, I believe that this change allows these lines to be removed from CSS V&U [3](https://github.com/w3c/csswg-drafts/blob/2e37f85c673df18fb79998c96124aab9d87e321f/css-values-3/Overview.bs#L1590-L1593) and [4](https://github.com/w3c/csswg-drafts/blob/2e37f85c673df18fb79998c96124aab9d87e321f/css-values-4/Overview.bs#L2635-L2638), because all uses `<angle>` with a bare `0` would now be explicitly allowed in the grammar:
> Note: For legacy reasons,
> some uses of …
> [css-images] Allow specifying any angle as a bare zero in gradients

- css-forms-1/Overview.bs
Add textarea to pseudo elements table
Also add placeholder pseudo to definitions
See https://github.com/w3c/csswg-drafts/issues/11844
> [css-forms-1] Add textarea to pseudo elements table

- css-values-5/Overview.bs
According to the definitions data model, `dfn-for` needs to a contain a "comma-separated list" of definitions. A recent commit used `|` to separate values definitions for `random()` and `<random-value-sharing>`. References back to the scoped definitions did not work as a result.
> [css-values-5] Editorial: fix scope of random() values

- css-view-transitions-1/Overview.bs
- Specify which documents is used for rendering supression
- Specify reason for skipping transition when capture fails
- Specify the correct document element in new capture
Closes #11721
Closes #11723
Closes #11725
> [css-view-transitions-1] Minor edits

- css-overflow-3/Overview.bs
fix the old URL remained after the default branch changed from master to main
> [css-overflow-3] fix link to commit history

- css-ui-4/Overview.bs
Resolves issue #10039.
Notes:
* Defines widgets to be replaced elements. This sets up their default layout behavior to be like other replaced elements, and implicitly disallows pseudo-elements unless otherwise specified.
* Removes the list of whitelisted properties that apply, since many more apply. Replaces it with a definition that:
* Requires all properties that affect outer layout results or apply visual effects outside of the box's internal rendering.
* Allows disregarding other properties when needed.
* This PR leaves open the possibility of spelling out particular additional properties which apply to certain widgets, though likely that text would go in the host language space like HTML, which is where widgets are enumerated.
I have tested the assertions in this spec PR against …
> [css-ui-4] Define appearance:auto box rendering and integration with CSS

- css-forms-1/Overview.bs
This matches recent change to HTML spec PR for select stylesheet. It's undesirable for authors to override the inertness of this button.
> [css-forms-1] Add !important to select buttons inertness

- css-view-transitions-2/Overview.bs
These names were intended to be unique.
> [css-view-transitions-2] Fix Typo in `view-transition-name: auto` example

- css-color-hdr-1/Overview.bs
CSS Color HDR redefines [`<colorspace-params>`](https://drafts.csswg.org/css-color-hdr-1/#typedef-colorspace-params) with the same value definition than in CSS Color 5.
This PR removes it from CSS Color HDR, because duplicate productions are problematic for the tools processing the data extracted from the specs.
> [css-color-hdr] Remove duplicate productions

- css-contain-2/Overview.bs
This prevents bikeshed from generating the spec locally.
> [css-contain-2] Fix typo in closing tag.

- css-overflow-5/carousel-explainer.md
This is an editorial change of the explainer only.
> [css-overflow-5] Add overflow-interactivity to alternatives considered.

- css-color-adjust-1/Overview.bs
- css-color-adjust-1/style.css
Forced Colors Mode is difficult to test via WPT because it is dependent on OS state (Window High Contrast) to trigger the feature to light up.
This change builds on a drafted [webdriver-bidi emulation command](https://www.w3.org/TR/webdriver-bidi/#module-emulation) (see https://github.com/w3c/webdriver-bidi/pull/905) to define a new forced colors emulation (https://alisonmaher.github.io/alisonmaher/css-color-adjust-1/Overview.html#emualte-forced-colors-mode) that keeps track of the current forced colors mode emulation state.
The change also updates the forced colors mode algorithm (https://alisonmaher.github.io/alisonmaher/css-color-adjust-1/Overview.html#forced) to inform the UA what to do when the forced colors mode emulation state is either `"light"` or `"dark"`.
CSSWG resolution for …
> Forced Colors Mode WebDriver Emulation

- css-values-5/Overview.bs
This is now specified more generally through "substitution contexts".
> [css-values-5] Remove chapter on attr() cycles

- css-values-5/Overview.bs
The current spec only remembers that we're in a cycle at the single point we're checking for cycles (step 1 of "substitute arbitrary substitution function"). This is not enough:
--x: var(--y, 1);
--y: var(--x, 2);
The current spec would produce computed values of --x:2 and --y:1, which doesn't make sense: if --x and --y indeed have non-invalid computed values, then the fallbacks should not have been taken in the first place.
I believe this is an unintended side effect of
f7a077668ea06a0509203c65d4d3cd5ef25ff458, therefore this PR restores the original behavior of making all properties in a cycle invalid.
> [css-values-5] All participants in a cycle become invalid

- css-values-4/Overview.bs
- css-values-5/Overview.bs
This matches existing implementation, and was a bug in the existing spec.
Closes #12073
> [css-values-4] Use "include" when fetching cross-origin CSS resources

- css-values-5/Overview.bs
Since there haven't been any discussions about *progress() for a long time, and both WebKit and Blink have implemented it, I suggest to move this warning to *mix() functions section that's currently under heavy discussion.
> [css-values-5] Move "exploratory draft" issue from *progress() to *mix()

- css-view-transitions-1/Overview.bs
Non-substantive contribution
There were actually two of these in the latest published version, but the first one was already fixed in 58350b3097b966d67d50f14d9de1a588d9c5690f
> [css-view-transitions-1] Fix typos in date in Changes Appendix

- css-viewport-1/Overview.bs
When the device is not folded (flat) or it's a regular device always return one segment (typically the size of the viewport). This is to follow developer feedback and consistency with the rest of the platform.
#11957
> [css-viewport-1] Make sure to always return one segment

- css-variables-1/Overview.bs
- css-variables-2/Overview.bs
The main part of the cycle behavior is now specified in css-values, so css-variables does not really need that much on that topic anymore.
This should mostly bring css-variables-1/2 up to date with #11500.
> [css-variables] Handle short-circuiting var(), argument grammars, etc

- css-mixins-1/Overview.bs
- css-values-5/Overview.bs
I couldn't make cycle detection work for custom functions by invoking "substitute arbitrary substitution functions", so I made that more explicit using "guarded" substitution contexts.
Resolves #11500.
> [css-mixins-1] Handle dynamic cycle detection, argument grammar

- css-color-adjust-1/Overview.bs
[css-color-adjust-1] This change fixes some auto-links that weren't working and adds exact locations for some links that were ambiguous. This cleans up all current bikeshed warnings for the color adjust spec, except for complaints about the "system color" definition not existing as an exportable definition, as this will require a change to the color spec.
> Fix bikeshed errors in color adjust spec

- css-color-adjust-1/Overview.bs
[css-color-adjust-1] This change makes the updates per resolutions taken in https://github.com/w3c/csswg-drafts/issues/11857.
More specifically, it moves the color properties that forced colors applies to within a note, mentions that this is the list at the time of writing and may not be exhaustive as other color properties are added over time, and notes that forced colors mode applies to any shorthand properties, as well.
It updates normative text referencing color properties to note that forced colors applies to the `<color>` components of all properties.
This change also updates `column-rule-color` to `rule-color` to ensure that full support exits for the new color properties added in the Gaps specification.
It adds `accent-color` to the list of color properties (it is mentioned lower …
> Update to color properties in Forced Colors Mode

- css-mixins-1/Overview.bs
- Two lines were not indented enough.
- "substitute arbitrary subsitution functions" was missing an "s".
> [css-mixins-1] Fix minor bikeshed errors

- css-values-5/Overview.bs
The spec defines functional notations in prose through `<dfn>`, then details the syntax of these notations. The syntaxes were incorrectly wrapped in another `<dfn>`, making Bikeshed think that these were new type definitions instead of references to the functional notation definitions.
In other words, this update gets things back to usual spec text, e.g., as in:
https://drafts.csswg.org/css-values-4/#ref-for-funcdef-abs%E2%91%A1
(which correctly links back to the definition in prose of `abs()`).
> [css-values-5] Fix syntax references for functions

- css-grid-1/Overview.bs
I think there's a typo going on here. "as" is written twice.
> [css-spec-grid-1] Fixes a small typo

- css-overflow-5/Overview.bs
Generating a ::scroll-marker-group for the root element should create a pseudo-element as a child of the root, which otherwise has all the usual scroll marker behaviors, as resolved in #11802.
> [css-overflow-5] Specify that root ::scroll-marker-group is a child.

- cssom-1/Overview.bs
I noticed the "that that" mistake while implementing this, then identified a couple of other small corrections. Not all of these are "wrong" exactly, they're just not worded the way the specs usually do.
> [cssom-1] Correct typos and grammar in "serialize a CSS declaration block"

- css-lists-3/Overview.bs
Non-substantive contribution.
Before:
- Markup for css-lists-3/Example 19 (nested lists) does not render the expected layout
- The body of the line item "Third second-level item, list start=3" indicates the intention of the authors
After:
- Minor correction to the markup matches likely author intent
> [css-lists-3] Correct markup for nested lists example

- css-animations-2/Overview.bs
- web-animations-2/Overview.bs
`Behavior` is a more accurate and intuitive term than `type`.
Also rewrites the explanations of `state`, `did trigger`, and `behavior` for clarity.
Also fixes some bikeshed linking syntax to point to IDL attributes where appropriate.
> [web-animations-2] s/animation-trigger-type/animation-trigger-behavior/

- css-color-adjust-1/Overview.bs
This change adds text to the Color Adjust spec per resolution in https://github.com/w3c/csswg-drafts/issues/8064. This change notes that UAs should force emojis to their monochrome variant depending on the value of `font-variant-emoji` and if a monochrome variant exists.
Updated spec text can be found hosted at https://alisonmaher.github.io/alisonmaher/css-color-adjust-1/Overview.html#forced-colors-properties
> [css-color-adjust-1] Emojis in forced colors mode

- css-anchor-position-1/anchored_container_query.md
First draft of an explainer for introducing container queries for querying applied position-try-fallbacks for anchor positioned elements.
> Add an explainer for anchored container queries

- css-view-transitions-2/Overview.bs
Resolution:
https://github.com/w3c/csswg-drafts/issues/12004#issuecomment-2910779457
Closes #12004
> [css-view-transitions-2] Generated strings start with -ua-

- css-color-hdr-1/Overview.bs
Issue #11954 noted that the spec does not really extend the definition of the `color()` function but rather extends the definition of one of the types that gets used in the definition of `color()`. A previous update dropped duplicated constructs accordingly, but the duplication of the definition itself remained.
Duplication is confusing for tools and readers because there's no longer any direct linnk between the definition of the `color()` function and its syntax.
This replaces the definition with a reference to the actual definition in `css-color-5`, allowing readers to access the actual function syntax. Note the "link default" should only be needed on a temporary basis (and it is needed precisely because the cross-references database currently contains more than one definition of the …
> [css-color-hdr-1] Use definition of `color()` from css-color-5

- css-borders-4/Overview.bs
- css-borders-4/images/corner-shape-adjusting.svg
- css-borders-4/images/corner-shape-border.svg
- css-borders-4/images/corner-shape-target-unit-vector-bevel.svg
- css-borders-4/images/corner-shape-target-unit-vector-round.svg
Based on [this resolution](https://github.com/w3c/csswg-drafts/issues/11610#issuecomment-2769797194)
- Borders are rendered perpendicular to the outer curve, clamped at corner-shape -1 or 1.
- Shadows are rendered like a scaled version of the original shape, converting the shadow spread to a scale.
Added detailed algorithms, explanation, and a chart.
Closes #11610 
Closes #11767
> [css-borders-4] Define border/shadow rendering for `corner-shape`

- css-borders-4/Overview.bs
If the hulls of opposite corners overlap, find a scale factor that would prevent the overlap, and apply to all radii.
Resolution: https://github.com/w3c/csswg-drafts/issues/12098#issuecomment-2898621830 Closes #12098
> [css-borders-4] Constrain radii for concave opposite corners

- css-overflow-4/Overview.bs
*Something* happens to the excess content (it overflows), so I find it more natural to say that the behavior is the same as the initial value, rather than to say there is no effect.
> [css-overflow-4][editorial] Minor phrasing tweak

- css-view-transitions-2/Overview.bs
This new pseudo is an ancestor to the other nested groups, and is positioned after the group's view-transition-image-pair which contains the group's contents.
Resolution:
https://github.com/w3c/csswg-drafts/issues/11926#issuecomment-2916977161
Closes #11926
> [css-view-transitions-2] Define the view-transition-group-children pseudo element

- css-forms-1/Overview.bs
> [css-forms-1] Fix double borders

- css-ui-4/Overview.bs
> [css-ui-4] Clarify the applicability of the caret-* properties

- cssom-view-1/Overview.bs
Addresses the concerns raised in #12260.
> [cssom-view-1] Editorial scrollIntoView container attribute fixes

- css-values-5/Overview.bs
The current syntax does not allow omitting stop options in color-interpolate(), which is an obvious oversight. (I am pretty sure this is the only one left.)
> [css-values-5] Allow omitting position options in color-interpolate()

- selectors-5/Overview.bs
This fixes #10296, #351, #1008 by specifying the `:heading` and `:heading(An+B)` pseudo classes, which will match against elements with a defined [heading level](https://html.spec.whatwg.org/multipage/sections.html#heading-level). As it stands, the current elements with a heading level are `h1`, `h2`, `h3`, `h4`, `h5`, and `h6`.
There is a proposal being actively prototyped to allow for more _dynamic_ heading levels that do not strictly adhere to their tagname (see https://github.com/whatwg/html/issues/5033 for more). This proposal (adding the `headingoffset`, `headingreset` attributes) will make it significantly more complex to unilaterally style elements with a heading level of, say, 1, raising the importance of the selectors proposed in this PR.
I've …
> [css-selectors-5] add `:heading`, `:heading(An+B)` pseudo classes

- selectors-5/Overview.bs
I merged #11836 a little hastily, as it does not reflect some of the resolutions we had in the WG meetings (https://github.com/w3c/csswg-drafts/issues/10296#issuecomment-2775988542), specifically:
- The spec needs to make note of the specificity of these selectors. It now does.
- `:heading()` can have comma separated An+B values, so needs to define a production that accommodates that. It now does.
> [selectors-5]: Update heading specs based on resolutions in #10296

- selectors-5/Overview.bs
This fixes a small typo from #12404
> [selectors-5] fix typo in :heading() syntax

- css-flexbox-1/Overview.bs
Per [sections 9.7(3) and 9.7(4)](https://drafts.csswg.org/css-flexbox-1/#resolve-flexible-lengths), the loop at 9.7(5) may begin with all flex items already frozen and with initial free space remaining that is not distributed.
Example:
```html
<!DOCTYPE html>
<style>
.flex {
display: flex;
flex-flow: row nowrap;
width: 100px;
background: red;    
}
.flex > div {    
flex: 0 1 auto;
}
</style>
<div class="flex">
<div style="background-color: orange">A</div>
<div style="background-color: blue">B</div>
<div style="background-color: green">C</div>
</div>
```
I am submitting the pull request under the [CC0](https://creativecommons.org/public-domain/cc0/) license
> Frozen items do not guarantee complete distribution of free space

- css-overflow-5/Overview.bs
As requested in Intent to Ship thread:
https://groups.google.com/a/chromium.org/g/blink-dev/c/R_VD_FkYrF8/m/XDzix9lbAwAJ adding an example to show how to use 'scroll-target-group' property to highlight the currently visible chapter within a table of contents.
> [css-overflow-5] Add an example for 'scroll-target-group' property

- cssom-view-1/Overview.bs
Adds an example of how scrollIntoView can be used for marker buttons on a carousel component without highjacking the page scroll.
> [cssom-view-1] Add scrollIntoView example demonstrating usage of container attribute

- css-fonts-4/Overview.bs
This was a little cramped, so I've added a space character between the `>` and `]`.
> [css-fonts-4] Add additional whitespace in font-variation-settings grammaer

- cssom-1/Overview.bs
Followup for #9686.
1. getComputedStyle already says it returns a CSSStyleProperties in step 6, and the IDL change fits that.
2. Copied the same change into ElementCSSInlineStyle.style. (fwiw, [WebKit has the same change](https://searchfox.org/wubkat/rev/3d577b31337b13acd2b569e59d863f8fd8505724/Source/WebCore/css/ElementCSSInlineStyle.idl#29).)
@emilio
> [cssom] Return CSSStyleProperties from `element.style` and getComputedStyle

- css-counter-styles-3/Overview.bs
This attempts to define extended CJK longhand counter styles with clear implementation separation as discussed in #12300.
Closes #12300.
This is mainly copy/pasted from an older version of the spec, which defined counter values outside this limited range and clearly separated required/optional implementations.
https://www.w3.org/TR/2013/WD-css-counter-styles-3-20130718/#extended-cjk
However, I made a slight change for the Korean range.
The former version of the spec [defines a range between 0 and 10^16](https://www.w3.org/TR/2013/WD-css-counter-styles-3-20130718/#extended-cjk:~:text=the%20Korean%20styles%20are%20defined%20for%20all%20non%2Dnegative%20numbers%20less%20than%201016.), yet the new version defines it down to a negative range because the current ED spec already defines the …
> [css-counter-styles] Define extended CJK longhand counter styles range

- css-content-3/Overview.bs
Explain how to set up a fallback when using counter in alt text in unsupported browsers.
Requested in I2S process:
https://groups.google.com/a/chromium.org/g/blink-dev/c/Ec36bxU5lok/m/5ljOQJS6BQAJ
> [css-content] Add an example explaining how to use counters in alt text

- css-pseudo-4/Overview.bs
As per resolution in #12159, Element.pseudo() returns CSSPseudoElement even when invoked on Element that can't generate the requested type.
> [css-pseudo-4] Add a note explaining Element.pseudo() behaviour #12159

- css-color-adjust-1/Overview.bs
Typo noticed while reviewing https://github.com/w3c/webdriver-bidi/pull/905
> [css-color-adjust-1][editorial] Fix typo in emualte-forced-colors-mode anchor

- css-color-adjust-1/Overview.bs
Add a summary of the following PRs to the Color Adjust changes section:
1. https://github.com/w3c/csswg-drafts/pull/11823
2. https://github.com/w3c/csswg-drafts/pull/12166
3. https://github.com/w3c/csswg-drafts/pull/12173
> [css-color-adjust-1] Add recent forced colors mode changes to color adjust changes section

- css-color-adjust-1/Overview.bs
As suggested by @fantasai, move the system color mappings for the forced colors mode emulation added in https://github.com/w3c/csswg-drafts/pull/11823 to a new subsection of the "Emulation" section to keep the main forced colors mode section simpler.
Checkout https://alisonmaher.github.io/alisonmaher/css-color-adjust-1/Overview.html#forced-color-palettes for a preview of the updates.
> [css-color-adjust-1] Create section for forced colors mode emulation color palettes

- css-gaps-1/Overview.bs
This PR updates the trailing gap decoration logic so that values are now assigned in forward order(i.e. from first to last). This ensures all decoration values apply left-to-right based on the resolution in #12527.
> [css-gaps-1] Update trailing gap decoration assignment to use values in forward order. Issue #12527 

- css-multicol-2/Overview.bs
There will be more to do here, and I want to add some images, but here's a first pass at the basics so we at least have lines and rows defined.
I haven't added the stuff about nested multicols here, not sure if it's the right place.
> [css-multicol-2] Initial pass at changes to the model section.

- css-align-3/Overview.bs
This is a follow-up fix on the old issue #764 for the incorrect/outdated "Applies to" lines related to `place-content` and `place-self`.
Sebastian
> [css-align-3][editorial] Fixed incorrect "Applies to" lines for place-* shorthands

- css-conditional-5/Overview.bs
Resolved in https://github.com/w3c/csswg-drafts/issues/6400#issuecomment-3200664309.
> [css-conditional-5] Define direction feature for scroll-state() queries

- css-counter-styles-3/Overview.bs
Fixed missing negative sign processing in CJK custom algorithms.
The Limited Chinese and Extended CJK algorithms defined negative signs but lacked explicit steps to handle negative values.
Closes #12714 
Added negative value processing steps to both custom algorithms(Limited Chinese& Extended CJK Algorithms).
- Added step to use absolute value when counter is negative
- Added step to prepend negative sign at the end
No WPT changes should be required. 
The existing WPT already implement this behavior, as the negative sign characters were defined in the specification tables. This change clarifies the algorithmic steps that were implicitly expected but not explicitly documented.
ref: https://github.com/web-platform-tests/wpt/pull/53312 & https://github.com/web-platform-tests/wpt/pull/54469 …
> [css-counter-styles-3] Add negative sign processing to CJK custom algorithms #12714

- css-overflow-5/Overview.bs
As resolved in https://github.com/w3c/csswg-drafts/issues/11600, `:target-before` and `:target-after` pseudo classes allow to select scroll markers before/after the `:target-current` one.
> [css-overflow-5] Add :target-before and :target-after pseudo classes #11600

- css-2025/Overview.bs
Those two specs were moved to Reliable CRs instead.
> [css-2025][editorial] Removed CSS Color Adjust 1 and CSS Conditional 4 from Rough Interop

- css-conditional-5/Overview.bs
Per resolution in:
https://github.com/w3c/csswg-drafts/issues/12090#issuecomment-3204775586
> [css-conditional-5] container-names are not tree-scoped #12090

- css-color-4/Overview.bs
These updates were resolved in both https://github.com/w3c/csswg-drafts/issues/5900 and https://github.com/w3c/csswg-drafts/issues/11332#issuecomment-3200774167
The change to system color text can be found hosted at https://alisonmaher.github.io/alisonmaher/css-color-4/Overview.html#css-system-colors (at the end of the section just before example 15).
For some reason, the second mention of "accent color" does not show as linked, even though it uses the same syntax as the first reference (perhaps a bikeshed issue?)
> [css-color-4] Updated `AccentColor` to take its value from `accent-color`, unless Forced Colors Mode is enabled

- css-backgrounds-4/Overview.bs
This adjusts the syntax of `background-clip` to accept a combination of `border-area` and `text`, as it was resolved on in https://github.com/w3c/csswg-drafts/issues/10696#issuecomment-2461103750.
Closes #10696
Sebastian
> [css-backgrounds-4] Allowed combining `border-area` and `text` in `background-clip`

- css-backgrounds-4/Overview.bs
In #12738 I missed to define what happens when both `border-area` and `text` are defined for `background-clip`, as @Loirooriol immediately [pointed out](https://github.com/w3c/csswg-drafts/pull/12738#discussion_r2324929980).
The [minutes of the call](https://github.com/w3c/csswg-drafts/issues/10696#issuecomment-2461103750) suggest the consensus was to do a union. So I added this note.
Sebastian
> [css-backgrounds-4] Defined interaction of `border-area` and `text` values for `background-clip`

- css-borders-4/Overview.bs
Fix oversights in f3d0da1. 
`corners` is basically renamed to `corner`:
> > Thanks. So I guess [`corners`](https://drafts.csswg.org/css-borders-4/#corners-shorthand) is now [`corner`](https://drafts.csswg.org/css-borders-4/#corner-shorthand). So is there any reason to keep _3.4. Corner Shaping Shorthand: the `corners` property_?
> 
> Oh I thought I removed the leftover. No there isn't.
https://github.com/w3c/csswg-drafts/issues/11623#issuecomment-3232601870
> [css-borders-4][editorial] Oversights

- css-overflow-4/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/8721
> [css-overflow] drop overflow columns and subsequent content with discard

- css-grid-3/Overview.bs
* Don't apply collapse tracks. #12485
* Use intrinsic sizing rules for percentage resolution. #12432
* Don't apply free space to stretch tracks. #12423
> [css-grid-3][masonry] Clarifications to intrinsic auto-repeats

- css-view-transitions-2/two-phase-transition-explainer.md
> [css-view-transitions-2] Create two-phase-transition-explainer.md

- css-gaps-1/Overview.bs
This PR aims to define the interpolation behavior for the `rule-width` and `rule-color` properties in CSSGapDecorations, based on the resolution in https://github.com/w3c/csswg-drafts/issues/12431.
Changes can be seen live in https://jav099.github.io/javier-intersections-draft.github.io/
> [css-gaps-1] Define Interpolation behavior for GapDecorations. Issue #12431

- css-overflow-4/Overview.bs
The sentence as it stood was unclear, but this seems to be the only reasonable thing it can mean.
> [css-overflow-4] Clarify (independent) formatting contexts and ellipsis insertion

- css-fonts-4/Overview.bs
> [css-fonts-4] Add notes for ui-* generic font family #12831

- css-anchor-position-2/Overview.bs
Per resolution:
https://github.com/w3c/csswg-drafts/issues/12610#issuecomment-3329830278
> [css-anchor-position-2] Add 'any' to position-area queries #12610

- css-2025/Overview.bs
CSS-CASCADE-5 specification is included in "2.2. Reliable Candidate Recommendations" section as "CSS Cascading and Inheritance Module Level 5", but also remains in "2.4. Modules with Rough Interoperability" section as "CSS Cascading and Inheritance Level 5" . Both references link to the same URL https://www.w3.org/TR/css-cascade-5/
I suppose this specification has been promoted from 2.4 section to 2.2 section, so it should be deleted from the 2.4 section.
> [css-2025] Delete CSS-CASCADE-5 reference in 2.4 section

- css-values-4/Overview.bs
This exports the "style resource base URL" definition so that it can be used in the definition of a urlpattern() function.
> [css-values-4] Export "style resource base URL" definition.

- css-conditional-5/Overview.bs
- css-conditional-5/scroll_state_explainer.md
Rename scroll-state `direction` feature to `scrolled`, as resolved in https://github.com/w3c/csswg-drafts/issues/12623#issuecomment-3275717227.
Updated scroll-state explainer with the new name for direction, specified it is only changed by relative scrolls and added semantic line breaks in the `scrolled` section.
> Rename direction to scrolled, updated explainer

- css-color-adjust-1/Overview.bs
The team in Chromium making the updates to forced colors mode emoji handling noted that it would be helpful to specify that `font-variant-emoji` gets overridden to `text` to ensure that the monochrome variant is chosen if available. This change adds more text to specify the exact details.
I wasn't sure if a new resolution was needed for this given the resolution in https://github.com/w3c/csswg-drafts/issues/8064#issuecomment-2163389692 but more than happy to file a new issue as needed.
> [css-color-adjust-1] Expand on how forced colors mode handles emojis

- css-forms-1/Overview.bs
Based on discussion within https://github.com/w3c/csswg-drafts/issues/12510
> [css-forms] Add select list box styles
